import { NextRequest, NextResponse } from "next/server";
import { getUserFromRequest, unauthorized } from "@/lib/api-auth";
import { getAccountingContext, AccountingContext } from "@/lib/accounting-context";
import { queryCodex } from "@/lib/codex-engine";
import { bootstrapAnswer, inferDomainFromQuestion } from "@/lib/llm-bootstrap";

// ── Live context → readable markdown summary ──────────────────────────────────
// Prepended to the answer so the response is grounded in the company's real data.
// Returns empty string when no context is available (all fields null).

function buildContextSummary(ctx: AccountingContext): string {
  const lines: string[] = [];

  if (ctx.trialBalance) {
    const tb = ctx.trialBalance;
    const s = tb.summary;
    const balanced = tb.isBalanced ? "✅ Balanced" : "⚠️ Out of balance";
    lines.push(
      `**Trial Balance (${tb.fromDate} → ${tb.toDate}):** ` +
        `${tb.accountCount} accounts | ${tb.journalCount} posted journals | ${balanced}`
    );
    lines.push(
      `  Income R${s.income.balance.toFixed(2)} | ` +
        `Expenses R${s.expense.balance.toFixed(2)} | ` +
        `Assets R${s.asset.balance.toFixed(2)} | ` +
        `Liabilities R${s.liability.balance.toFixed(2)}`
    );
  }

  if (ctx.unmatchedTransactions !== null) {
    const count = ctx.unmatchedTransactions.length;
    lines.push(
      `**Unmatched Bank Transactions (last 30 days):** ${count} transaction${count !== 1 ? "s" : ""} pending allocation`
    );
  }

  if (ctx.vatPeriodStatus) {
    const v = ctx.vatPeriodStatus;
    if (v.currentPeriodKey) {
      lines.push(
        `**VAT Period:** ${v.currentPeriodKey} — ${v.currentPeriodStatus ?? "open"} ` +
          `(${v.openCount} open period${v.openCount !== 1 ? "s" : ""})`
      );
    } else {
      lines.push(`**VAT Periods:** ${v.openCount} open period${v.openCount !== 1 ? "s" : ""}`);
    }
  }

  if (lines.length === 0) return "";

  return (
    `> 📊 **Live Accounting Data** *(as of ${new Date(ctx.fetchedAt).toLocaleString("en-ZA")})*\n` +
    lines.map((l) => `> ${l}`).join("\n") +
    "\n"
  );
}

// ── Route handler ─────────────────────────────────────────────────────────────

export async function POST(request: NextRequest) {
  try {
    // Auth — session cookie required, super-user only (same as all Sean routes)
    const user = await getUserFromRequest(request);
    if (!user) return unauthorized();

    // Parse body
    const body = await request.json().catch(() => null);
    if (!body || typeof body !== "object") {
      return NextResponse.json({ error: "Invalid request body" }, { status: 400 });
    }

    const { companyId, question, moduleContext } = body as {
      companyId?: string;
      question?: string;
      moduleContext?: string;
    };

    if (!companyId || typeof companyId !== "string" || companyId.trim() === "") {
      return NextResponse.json({ error: "companyId is required" }, { status: 400 });
    }
    if (!question || typeof question !== "string" || question.trim() === "") {
      return NextResponse.json({ error: "question is required" }, { status: 400 });
    }

    // Guard — bridge is inactive without ECO_BASE_URL
    const ecoBase = process.env.ECO_BASE_URL;
    if (!ecoBase) {
      return NextResponse.json(
        { error: "Accounting context unavailable — ECO_BASE_URL is not configured" },
        { status: 503 }
      );
    }

    // Infer domain; default to ACCOUNTING_GENERAL for this module (not "OTHER")
    const rawDomain = inferDomainFromQuestion(question);
    const domain = rawDomain === "OTHER" ? "ACCOUNTING_GENERAL" : rawDomain;

    // Fetch live context and query codex in parallel — neither blocks the other
    const [ctx, codexResult] = await Promise.all([
      getAccountingContext(companyId, ecoBase),
      queryCodex(question, domain),
    ]);

    // Build the answer
    let answer: string;
    const citationIds: string[] = [];

    if (codexResult.hasCodifiedKnowledge) {
      // Structured rules exist in the codex — use them directly
      answer = codexResult.formattedContext;
      citationIds.push(
        ...codexResult.taxRules.map((r) => r.citationId),
        ...codexResult.vatRules.map((r) => r.citationId),
        ...codexResult.decisionEngines.map((e) => e.citationId),
      );
    } else {
      // Fall back to KB search → LLM bootstrap
      const bootstrapResult = await bootstrapAnswer(question, domain, user.id);
      answer = bootstrapResult.answer;
      if (bootstrapResult.citationId) {
        citationIds.push(bootstrapResult.citationId);
        answer += `\n\n📚 *[${bootstrapResult.citationId}]*`;
      }
      if (bootstrapResult.source === "LLM" && bootstrapResult.provider) {
        answer +=
          `\n\n💡 *This answer was generated by ${bootstrapResult.provider} ` +
          `and saved to the knowledge base for future reference.*`;
      }
    }

    // Prepend live context summary when data is available
    const contextSummary = buildContextSummary(ctx);
    if (contextSummary) {
      answer = contextSummary + "\n" + answer;
    }

    return NextResponse.json({
      answer,
      context: ctx,
      module: "accounting",
      domain,
      moduleContext: moduleContext ?? null,
      citations: citationIds,
      hasCodifiedKnowledge: codexResult.hasCodifiedKnowledge,
    });
  } catch (error) {
    console.error("[AccountingQuery] Unhandled error:", error);
    return NextResponse.json(
      { error: "Internal server error" },
      { status: 500 }
    );
  }
}
