-- =============================================================================
-- Migration 062: Practice Management — Client Billing Preparation + WIP Management
-- =============================================================================
-- Run in Supabase SQL Editor AFTER migration 061.
--
-- Design rules:
--   - Only adds tables and columns — no drops, no modifies, safe re-run
--   - ADD COLUMN IF NOT EXISTS throughout
--   - CREATE TABLE IF NOT EXISTS throughout
--   - All business data DB-authoritative — no localStorage
--
-- What this migration does:
--   A. Extend practice_time_entries with billing pack linkage + write-off fields
--   B. Create practice_billing_packs table
--   C. Create practice_billing_pack_lines table
--   D. Add supporting indexes
-- =============================================================================

BEGIN;

-- ─────────────────────────────────────────────────────────────────────────────
-- A. Extend practice_time_entries
-- These columns link time entries to billing packs and track billing outcomes.
-- Added AFTER the billing_packs table is created so the FK is valid.
-- ─────────────────────────────────────────────────────────────────────────────

-- B and C are created first so A's FK resolves correctly.

-- ─────────────────────────────────────────────────────────────────────────────
-- B. Billing Packs
-- A billing pack is a partner-reviewed grouping of approved time entries
-- for a specific client, prepared for invoicing.
--
-- Lifecycle: draft → reviewed → approved → locked
--            draft/reviewed/approved → cancelled
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS practice_billing_packs (
    id                      INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    company_id              INTEGER NOT NULL,
    client_id               INTEGER NOT NULL,
    pack_number             TEXT,
    pack_name               TEXT NOT NULL,
    period_start            DATE,
    period_end              DATE,
    status                  TEXT NOT NULL DEFAULT 'draft',
    -- Hour totals (kept in sync by recalculate endpoint)
    total_hours             NUMERIC(12,2) NOT NULL DEFAULT 0,
    billable_hours          NUMERIC(12,2) NOT NULL DEFAULT 0,
    non_billable_hours      NUMERIC(12,2) NOT NULL DEFAULT 0,
    -- Value totals
    recoverable_value       NUMERIC(12,2) NOT NULL DEFAULT 0,
    writeoff_value          NUMERIC(12,2) NOT NULL DEFAULT 0,
    billable_value          NUMERIC(12,2) NOT NULL DEFAULT 0,
    -- Partner override: what will actually be invoiced (may differ from billable_value)
    proposed_invoice_value  NUMERIC(12,2),
    -- Notes
    notes                   TEXT,
    internal_notes          TEXT,
    -- Flexible settings blob for future use (fee cap, discount %, client ref, etc.)
    settings                JSONB NOT NULL DEFAULT '{}',
    -- Audit
    created_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by              INTEGER,
    updated_by              INTEGER
    -- Allowed status: draft | reviewed | approved | locked | cancelled
);

-- ─────────────────────────────────────────────────────────────────────────────
-- C. Billing Pack Lines
-- One line per time entry in a billing pack.
-- Line status controls what's billed vs written off vs excluded.
--
-- Allowed line_status: included | written_off | excluded
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS practice_billing_pack_lines (
    id                  INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    company_id          INTEGER NOT NULL,
    billing_pack_id     INTEGER NOT NULL REFERENCES practice_billing_packs(id) ON DELETE CASCADE,
    time_entry_id       INTEGER NOT NULL,
    client_id           INTEGER NOT NULL,
    task_id             INTEGER,
    workflow_run_id     BIGINT,
    -- Copied from time entry at pack creation time (snapshot for billing purposes)
    hours               NUMERIC(12,2) NOT NULL DEFAULT 0,
    recoverable_value   NUMERIC(12,2) NOT NULL DEFAULT 0,
    writeoff_value      NUMERIC(12,2) NOT NULL DEFAULT 0,
    billable_value      NUMERIC(12,2) NOT NULL DEFAULT 0,
    -- Line status
    line_status         TEXT NOT NULL DEFAULT 'included',
    -- Notes
    notes               TEXT,
    -- Audit
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now()
    -- Allowed line_status: included | written_off | excluded
);

-- ─────────────────────────────────────────────────────────────────────────────
-- A (continued). Extend practice_time_entries
-- Now that practice_billing_packs exists, the FK can be added.
-- ─────────────────────────────────────────────────────────────────────────────

ALTER TABLE practice_time_entries
    ADD COLUMN IF NOT EXISTS billing_pack_id
        INTEGER REFERENCES practice_billing_packs(id) ON DELETE SET NULL;

-- When the billing review on the pack occurred (pack approved/locked)
ALTER TABLE practice_time_entries
    ADD COLUMN IF NOT EXISTS billing_reviewed_at  TIMESTAMPTZ;

-- Who approved the billing pack that included this entry
ALTER TABLE practice_time_entries
    ADD COLUMN IF NOT EXISTS billing_reviewed_by  INTEGER;

-- Reason for write-off (separate from billing_notes which holds rejection reason)
ALTER TABLE practice_time_entries
    ADD COLUMN IF NOT EXISTS writeoff_reason  TEXT;

-- ─────────────────────────────────────────────────────────────────────────────
-- D. Indexes
-- ─────────────────────────────────────────────────────────────────────────────

-- Billing packs: lookup by company and client
CREATE INDEX IF NOT EXISTS idx_billing_packs_company
    ON practice_billing_packs(company_id);

CREATE INDEX IF NOT EXISTS idx_billing_packs_client
    ON practice_billing_packs(company_id, client_id);

CREATE INDEX IF NOT EXISTS idx_billing_packs_status
    ON practice_billing_packs(company_id, status)
    WHERE status NOT IN ('cancelled', 'locked');

-- Billing pack lines: lookup by pack and time entry
CREATE INDEX IF NOT EXISTS idx_billing_lines_pack
    ON practice_billing_pack_lines(billing_pack_id);

CREATE INDEX IF NOT EXISTS idx_billing_lines_time_entry
    ON practice_billing_pack_lines(time_entry_id);

CREATE INDEX IF NOT EXISTS idx_billing_lines_company
    ON practice_billing_pack_lines(company_id);

CREATE INDEX IF NOT EXISTS idx_billing_lines_status
    ON practice_billing_pack_lines(billing_pack_id, line_status);

-- practice_time_entries: lookup by billing pack
CREATE INDEX IF NOT EXISTS idx_pte_billing_pack_id
    ON practice_time_entries(billing_pack_id)
    WHERE billing_pack_id IS NOT NULL;

COMMIT;

-- ─── Verification ─────────────────────────────────────────────────────────────
-- Run after applying to confirm all structures exist.

SELECT 'practice_billing_packs' AS table_name,
       COUNT(*) AS column_count
FROM information_schema.columns
WHERE table_name = 'practice_billing_packs'

UNION ALL

SELECT 'practice_billing_pack_lines' AS table_name,
       COUNT(*) AS column_count
FROM information_schema.columns
WHERE table_name = 'practice_billing_pack_lines'

UNION ALL

SELECT 'practice_time_entries (new cols)' AS table_name,
       COUNT(*) AS column_count
FROM information_schema.columns
WHERE table_name = 'practice_time_entries'
  AND column_name IN ('billing_pack_id', 'billing_reviewed_at', 'billing_reviewed_by', 'writeoff_reason');
