-- =============================================================================
-- Migration 064: Practice Management — Billing Pack Controls + Events
-- =============================================================================
-- Run in Supabase SQL Editor AFTER migration 063.
--
-- What this migration does:
--   1. Adds governance columns to practice_billing_packs:
--        approved_at / approved_by    — who approved and when
--        locked_at   / locked_by      — who locked and when
--        cancelled_at / cancelled_by  — who cancelled and when
--        billing_period_key           — duplicate-pack detection key
--   2. Adds supporting indexes on practice_billing_packs
--   3. Creates practice_billing_pack_events — full pack history/audit log
--
-- Design rules:
--   - ADD COLUMN IF NOT EXISTS — safe re-run
--   - Only adds; never drops or modifies existing columns
--   - All new pack columns nullable (only populated on the relevant lifecycle event)
--   - billing_period_key: clientId_periodStart_periodEnd (app-generated)
-- =============================================================================

BEGIN;

-- ─── Extend practice_billing_packs ───────────────────────────────────────────

ALTER TABLE practice_billing_packs
    ADD COLUMN IF NOT EXISTS approved_at       TIMESTAMPTZ;

ALTER TABLE practice_billing_packs
    ADD COLUMN IF NOT EXISTS approved_by       INTEGER;

ALTER TABLE practice_billing_packs
    ADD COLUMN IF NOT EXISTS locked_at         TIMESTAMPTZ;

ALTER TABLE practice_billing_packs
    ADD COLUMN IF NOT EXISTS locked_by         INTEGER;

ALTER TABLE practice_billing_packs
    ADD COLUMN IF NOT EXISTS cancelled_at      TIMESTAMPTZ;

ALTER TABLE practice_billing_packs
    ADD COLUMN IF NOT EXISTS cancelled_by      INTEGER;

-- billing_period_key = "clientId_periodStart_periodEnd"
-- Used for duplicate active-pack detection within a company.
-- NULL when no period dates are supplied.
ALTER TABLE practice_billing_packs
    ADD COLUMN IF NOT EXISTS billing_period_key TEXT;

-- ─── Indexes on practice_billing_packs ───────────────────────────────────────

CREATE INDEX IF NOT EXISTS idx_billing_packs_pack_number
    ON practice_billing_packs(company_id, pack_number)
    WHERE pack_number IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_billing_packs_period_key
    ON practice_billing_packs(company_id, billing_period_key)
    WHERE billing_period_key IS NOT NULL;

-- ─── Create practice_billing_pack_events ─────────────────────────────────────

CREATE TABLE IF NOT EXISTS practice_billing_pack_events (
    id              INTEGER         PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    company_id      INTEGER         NOT NULL,
    billing_pack_id INTEGER         NOT NULL,
    event_type      TEXT            NOT NULL,
    old_status      TEXT,
    new_status      TEXT,
    actor_user_id   INTEGER,
    notes           TEXT,
    metadata        JSONB           NOT NULL DEFAULT '{}',
    created_at      TIMESTAMPTZ     NOT NULL DEFAULT now()
);

-- Allowed event_type values (enforced at app layer, documented here):
--   pack_created          — new pack inserted
--   pack_updated          — pack fields edited
--   pack_recalculated     — totals recalculated from lines
--   pack_approved         — partner approved pack
--   pack_locked           — pack locked; entries marked billed
--   pack_cancelled        — pack soft-cancelled
--   pack_number_assigned  — auto-generated pack_number assigned on create
--   pack_line_written_off — a line written off within this pack
--   pack_line_excluded    — a line excluded from this pack

-- ─── Indexes on practice_billing_pack_events ─────────────────────────────────

CREATE INDEX IF NOT EXISTS idx_bpe_company_id
    ON practice_billing_pack_events(company_id);

CREATE INDEX IF NOT EXISTS idx_bpe_billing_pack_id
    ON practice_billing_pack_events(billing_pack_id);

CREATE INDEX IF NOT EXISTS idx_bpe_event_type
    ON practice_billing_pack_events(event_type);

CREATE INDEX IF NOT EXISTS idx_bpe_created_at
    ON practice_billing_pack_events(created_at);

COMMIT;

-- ─── Verification ─────────────────────────────────────────────────────────────

-- 1. New columns on practice_billing_packs (expect 7 rows):
SELECT column_name, data_type, is_nullable
FROM information_schema.columns
WHERE table_name = 'practice_billing_packs'
  AND column_name IN (
    'approved_at', 'approved_by',
    'locked_at',   'locked_by',
    'cancelled_at','cancelled_by',
    'billing_period_key'
  )
ORDER BY column_name;

-- 2. practice_billing_pack_events table (expect 1 row):
SELECT table_name
FROM information_schema.tables
WHERE table_schema = 'public'
  AND table_name = 'practice_billing_pack_events';

-- 3. Indexes (expect 6 rows):
SELECT indexname FROM pg_indexes
WHERE tablename IN ('practice_billing_packs', 'practice_billing_pack_events')
  AND indexname LIKE '%billing%'
ORDER BY indexname;
