-- ============================================================================
-- Migration 067: Practice Engagement Recurrence Rules + Period Queue (Codebox 16)
-- Date: 2026-06-20
-- Purpose:
--   1. Extend practice_client_engagements with recurrence definition columns.
--   2. Create practice_engagement_periods — the manual period queue table.
--      Each row is one discrete service period for a recurring engagement.
--      Periods are created manually by the user; workflow generation is also
--      triggered manually per period. No cron. No auto-execution.
-- Safety:
--   - ADD COLUMN IF NOT EXISTS throughout — safe to re-run
--   - No table drops, no column drops, no type changes
--   - All new engagement columns are nullable
--   - CREATE TABLE IF NOT EXISTS
--   - Partial unique index enforces no duplicate active periods per engagement range
-- ============================================================================

BEGIN;

-- ─────────────────────────────────────────────────────────────────────────────
-- 1. Extend practice_client_engagements — recurrence definition
--
--    These fields define HOW the engagement recurs. They are used by the
--    server-side period preview/generate logic; they are NEVER used to
--    trigger automatic workflow generation.
--
--    recurrence_type:  monthly | quarterly | annual | once_off | ad_hoc
--    recurrence_start_date: first date of the first period (anchor)
--    recurrence_end_date:   last date the recurrence is valid
--    recurrence_day:   day-of-month the period starts (1–28; safe for all months)
--    recurrence_month: month of year for annual recurrences (1–12)
--    next_period_start / next_period_end / next_due_date:
--       Informational hint — updated after each period is generated.
--       NOT authoritative for workflow generation.
--    recurrence_notes: free-text explanation / override instructions
-- ─────────────────────────────────────────────────────────────────────────────

ALTER TABLE practice_client_engagements
  ADD COLUMN IF NOT EXISTS recurrence_type       TEXT,          -- monthly|quarterly|annual|once_off|ad_hoc
  ADD COLUMN IF NOT EXISTS recurrence_start_date DATE,          -- anchor for period generation
  ADD COLUMN IF NOT EXISTS recurrence_end_date   DATE,          -- hard stop date for period generation
  ADD COLUMN IF NOT EXISTS recurrence_day        INTEGER,       -- day of month (1–28) periods start on
  ADD COLUMN IF NOT EXISTS recurrence_month      INTEGER,       -- month (1–12) for annual recurrences
  ADD COLUMN IF NOT EXISTS next_period_start     DATE,          -- informational — last generated → next expected
  ADD COLUMN IF NOT EXISTS next_period_end       DATE,
  ADD COLUMN IF NOT EXISTS next_due_date         DATE,
  ADD COLUMN IF NOT EXISTS recurrence_notes      TEXT;

-- ─────────────────────────────────────────────────────────────────────────────
-- 2. Create practice_engagement_periods — manual period queue
--
--    One row = one discrete service period for an engagement.
--    Lifecycle:
--      queued   → ready → generated
--      queued/ready → skipped
--      any (except generated) → cancelled
--
--    workflow_run_id and deadline_id are populated only after
--    POST /api/practice/engagement-periods/:id/generate-workflow succeeds.
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS practice_engagement_periods (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id      INTEGER     NOT NULL,
    engagement_id   INTEGER     NOT NULL,     -- FK to practice_client_engagements
    client_id       INTEGER     NOT NULL,     -- denormalised for fast filtering
    service_id      INTEGER,                  -- FK to practice_service_catalog (optional)

    -- Period definition
    period_label    TEXT        NOT NULL,     -- human-readable e.g. "January 2026", "Q1 2026"
    period_start    DATE        NOT NULL,
    period_end      DATE        NOT NULL,
    due_date        DATE,                     -- compliance submission deadline (nullable)
    anchor_date     DATE,                     -- workflow task offset anchor

    -- Status
    -- queued | ready | generated | skipped | cancelled
    status          TEXT        NOT NULL DEFAULT 'queued',

    -- Generation traceability (populated after generate-workflow)
    workflow_run_id BIGINT,
    deadline_id     INTEGER,
    generated_at    TIMESTAMPTZ,
    generated_by    INTEGER,

    -- Skip traceability
    skipped_at      TIMESTAMPTZ,
    skipped_by      INTEGER,
    skip_reason     TEXT,

    -- Misc
    notes           TEXT,
    settings        JSONB       NOT NULL DEFAULT '{}',

    -- Audit
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_by      INTEGER,
    updated_by      INTEGER
);

-- ── Indexes ───────────────────────────────────────────────────────────────────

CREATE INDEX IF NOT EXISTS idx_ep_company
  ON practice_engagement_periods(company_id);

CREATE INDEX IF NOT EXISTS idx_ep_engagement
  ON practice_engagement_periods(company_id, engagement_id);

CREATE INDEX IF NOT EXISTS idx_ep_client
  ON practice_engagement_periods(company_id, client_id);

CREATE INDEX IF NOT EXISTS idx_ep_service
  ON practice_engagement_periods(company_id, service_id)
  WHERE service_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_ep_status
  ON practice_engagement_periods(company_id, status);

CREATE INDEX IF NOT EXISTS idx_ep_period_start
  ON practice_engagement_periods(company_id, period_start);

CREATE INDEX IF NOT EXISTS idx_ep_period_end
  ON practice_engagement_periods(company_id, period_end);

CREATE INDEX IF NOT EXISTS idx_ep_due_date
  ON practice_engagement_periods(company_id, due_date)
  WHERE due_date IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_ep_workflow_run
  ON practice_engagement_periods(workflow_run_id)
  WHERE workflow_run_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_ep_deadline
  ON practice_engagement_periods(deadline_id)
  WHERE deadline_id IS NOT NULL;

-- ── Partial unique guard ──────────────────────────────────────────────────────
-- Prevents two active (non-cancelled) rows for the same engagement and period range.
-- Cancelled rows are excluded so a period can be cancelled and re-queued.

CREATE UNIQUE INDEX IF NOT EXISTS idx_uq_ep_engagement_range
  ON practice_engagement_periods(company_id, engagement_id, period_start, period_end)
  WHERE status != 'cancelled';

COMMIT;


-- ─── Verification ─────────────────────────────────────────────────────────────
-- Run after migration to confirm all objects were created.
--
-- New engagement columns:
-- SELECT column_name, data_type, is_nullable
-- FROM information_schema.columns
-- WHERE table_name = 'practice_client_engagements'
--   AND column_name IN (
--     'recurrence_type','recurrence_start_date','recurrence_end_date',
--     'recurrence_day','recurrence_month',
--     'next_period_start','next_period_end','next_due_date','recurrence_notes'
--   )
-- ORDER BY column_name;
-- Expect: 9 rows
--
-- New table:
-- SELECT table_name FROM information_schema.tables
-- WHERE table_schema = 'public' AND table_name = 'practice_engagement_periods';
-- Expect: 1 row
--
-- Indexes:
-- SELECT indexname FROM pg_indexes
-- WHERE tablename = 'practice_engagement_periods'
-- ORDER BY indexname;
-- Expect: idx_ep_client, idx_ep_company, idx_ep_deadline, idx_ep_due_date,
--         idx_ep_engagement, idx_ep_period_end, idx_ep_period_start,
--         idx_ep_service, idx_ep_status, idx_ep_workflow_run,
--         idx_uq_ep_engagement_range,
--         practice_engagement_periods_pkey
-- (11 named + 1 pkey = 12 total)
