-- =============================================================================
-- Migration 069: Practice Client Health Scoring
-- =============================================================================
-- Run in Supabase SQL Editor.
--
-- Design rules:
--   - All DDL uses ADD COLUMN IF NOT EXISTS / CREATE TABLE IF NOT EXISTS
--   - No existing columns removed or modified
--   - Health fields on practice_clients are written ONLY by the
--     POST /api/practice/client-health/recalculate endpoint — never by
--     sanitizeClientBody() or user form submission
--
-- What this migration does:
--   A. Adds health score caching fields to practice_clients
--   B. Creates practice_client_health_snapshots (history table)
-- =============================================================================

BEGIN;

-- ─────────────────────────────────────────────────────────────────────────────
-- A. Cached health fields on practice_clients
-- These are written by the recalculate endpoint, not by user edits.
-- ─────────────────────────────────────────────────────────────────────────────

ALTER TABLE practice_clients
  ADD COLUMN IF NOT EXISTS health_score              INTEGER          NULL;

ALTER TABLE practice_clients
  ADD COLUMN IF NOT EXISTS health_status             TEXT             NULL;
  -- Allowed: good | watch | at_risk | critical | unknown

ALTER TABLE practice_clients
  ADD COLUMN IF NOT EXISTS health_last_calculated_at TIMESTAMPTZ      NULL;

ALTER TABLE practice_clients
  ADD COLUMN IF NOT EXISTS health_notes              TEXT             NULL;

-- Index for filtering/sorting by health status
CREATE INDEX IF NOT EXISTS idx_pc_health_status
  ON practice_clients(company_id, health_status)
  WHERE health_status IS NOT NULL;

-- ─────────────────────────────────────────────────────────────────────────────
-- B. Health snapshot history
-- One row per recalculation run per client. Lets the practice see
-- how a client's risk profile changed over time.
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS practice_client_health_snapshots (
    id              INTEGER         PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    company_id      INTEGER         NOT NULL,
    client_id       INTEGER         NOT NULL,
    health_score    INTEGER         NOT NULL,
    health_status   TEXT            NOT NULL,
    -- JSONB arrays for flexibility:
    --   risk_factors: [{ code, label, count?, value?, severity }]
    --   metrics:      { overdue_deadlines, pending_reviews, ... }
    risk_factors    JSONB           NOT NULL DEFAULT '[]',
    metrics         JSONB           NOT NULL DEFAULT '{}',
    calculated_at   TIMESTAMPTZ     NOT NULL DEFAULT now(),
    calculated_by   INTEGER         NULL     -- practice_team_members.id or null for system
);

CREATE INDEX IF NOT EXISTS idx_pchs_company
  ON practice_client_health_snapshots(company_id);

CREATE INDEX IF NOT EXISTS idx_pchs_client
  ON practice_client_health_snapshots(company_id, client_id);

CREATE INDEX IF NOT EXISTS idx_pchs_status
  ON practice_client_health_snapshots(company_id, health_status);

CREATE INDEX IF NOT EXISTS idx_pchs_calculated
  ON practice_client_health_snapshots(company_id, calculated_at DESC);

COMMIT;
