-- =============================================================================
-- Migration 070: Practice Client Health Actions
-- =============================================================================
-- Run in Supabase SQL Editor.
--
-- Design rules:
--   - All DDL uses CREATE TABLE IF NOT EXISTS
--   - No existing columns removed or modified
--   - Actions are created manually by users — no automation, no cron
--   - Linked records (tasks, deadlines, periods, packs) are reference-only;
--     no FK constraints to prevent orphan failures if linked records are deleted
--
-- What this migration does:
--   Creates practice_client_health_actions — operational follow-up tracking
--   per client risk factor.
-- =============================================================================

BEGIN;

CREATE TABLE IF NOT EXISTS practice_client_health_actions (
    id                          INTEGER         PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,

    -- Tenant + client scope
    company_id                  INTEGER         NOT NULL,
    client_id                   INTEGER         NOT NULL,

    -- Optional link to the snapshot that triggered this action
    health_snapshot_id          INTEGER         NULL,

    -- Action classification
    -- Allowed: create_task | assign_owner | open_deadline | generate_period |
    --          review_wip | fix_recurrence | fix_missing_owner | general_followup
    action_type                 TEXT            NOT NULL,
    action_title                TEXT            NOT NULL,

    -- Allowed: open | in_progress | completed | dismissed | cancelled
    action_status               TEXT            NOT NULL DEFAULT 'open',

    -- Source risk that prompted this action (from scoring engine)
    source_risk_code            TEXT            NULL,  -- e.g. 'overdue_deadlines'
    source_risk_label           TEXT            NULL,  -- human-readable label

    -- Optional links to records in other practice tables (no FK — reference only)
    linked_task_id              INTEGER         NULL,
    linked_deadline_id          INTEGER         NULL,
    linked_period_id            INTEGER         NULL,
    linked_billing_pack_id      INTEGER         NULL,

    -- Assignment + scheduling
    assigned_team_member_id     INTEGER         NULL,
    due_date                    DATE            NULL,

    -- Completion tracking
    completed_at                TIMESTAMPTZ     NULL,
    completed_by                INTEGER         NULL,

    -- Notes + flexible settings
    notes                       TEXT            NULL,
    settings                    JSONB           NOT NULL DEFAULT '{}',

    -- Audit timestamps + actors
    created_at                  TIMESTAMPTZ     NOT NULL DEFAULT now(),
    updated_at                  TIMESTAMPTZ     NOT NULL DEFAULT now(),
    created_by                  INTEGER         NULL,
    updated_by                  INTEGER         NULL
);

-- ─── Indexes ──────────────────────────────────────────────────────────────────

-- Tenant-level queries
CREATE INDEX IF NOT EXISTS idx_pcha_company
  ON practice_client_health_actions(company_id);

-- Per-client action list (most common query)
CREATE INDEX IF NOT EXISTS idx_pcha_client
  ON practice_client_health_actions(company_id, client_id);

-- Snapshot linkage
CREATE INDEX IF NOT EXISTS idx_pcha_snapshot
  ON practice_client_health_actions(health_snapshot_id)
  WHERE health_snapshot_id IS NOT NULL;

-- Dashboard: open action count
CREATE INDEX IF NOT EXISTS idx_pcha_status
  ON practice_client_health_actions(company_id, action_status);

-- Filter by type
CREATE INDEX IF NOT EXISTS idx_pcha_type
  ON practice_client_health_actions(company_id, action_type);

-- Team member workload view
CREATE INDEX IF NOT EXISTS idx_pcha_assignee
  ON practice_client_health_actions(company_id, assigned_team_member_id)
  WHERE assigned_team_member_id IS NOT NULL;

-- Overdue action detection
CREATE INDEX IF NOT EXISTS idx_pcha_due_date
  ON practice_client_health_actions(company_id, due_date)
  WHERE due_date IS NOT NULL AND action_status IN ('open', 'in_progress');

COMMIT;
