-- ============================================================
-- Codebox 21: Practice Reminder Center
-- Creates practice_reminders — in-app reminder and alert table.
-- No email/SMS/push. No cron. In-app only.
-- Run once in Supabase SQL Editor.
-- Expected result: "Success. No rows returned"
-- ============================================================

CREATE TABLE IF NOT EXISTS practice_reminders (
    id                       INTEGER      PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    company_id               INTEGER      NOT NULL,

    -- What kind of reminder
    reminder_type            TEXT         NOT NULL,  -- deadline_due | deadline_overdue | review_waiting | approval_waiting | billing_waiting | health_action | period_waiting | engagement_setup | capacity_warning | general

    -- Where this reminder came from (null = manual/general)
    source_type              TEXT         NOT NULL DEFAULT 'system',  -- deadline | task | billing_pack | health_action | engagement_period | engagement | team_member | client | system
    source_id                INTEGER      NULL,      -- FK-free reference; no FK to prevent orphan failures

    -- Context
    client_id                INTEGER      NULL,
    assigned_team_member_id  INTEGER      NULL,

    -- Content
    title                    TEXT         NOT NULL,
    message                  TEXT         NULL,
    severity                 TEXT         NOT NULL DEFAULT 'normal',  -- low | normal | high | urgent
    action_url               TEXT         NULL,     -- nav link to relevant module page
    metadata                 JSONB        NOT NULL DEFAULT '{}',

    -- Lifecycle
    status                   TEXT         NOT NULL DEFAULT 'open',    -- open | snoozed | completed | dismissed | cancelled
    due_date                 DATE         NULL,
    snoozed_until            TIMESTAMPTZ  NULL,
    dismissed_at             TIMESTAMPTZ  NULL,
    dismissed_by             INTEGER      NULL,
    completed_at             TIMESTAMPTZ  NULL,
    completed_by             INTEGER      NULL,

    -- Audit
    created_at               TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at               TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by               INTEGER      NULL
);

-- ── Indexes ────────────────────────────────────────────────────────────────────

-- Primary tenant filter (on every list query)
CREATE INDEX IF NOT EXISTS idx_pr_company
    ON practice_reminders(company_id);

-- Status filter (list view default excludes cancelled)
CREATE INDEX IF NOT EXISTS idx_pr_status
    ON practice_reminders(company_id, status)
    WHERE status NOT IN ('cancelled');

-- Type breakdown
CREATE INDEX IF NOT EXISTS idx_pr_type
    ON practice_reminders(company_id, reminder_type);

-- Source dedup check (compound: source_type + source_id + reminder_type)
CREATE INDEX IF NOT EXISTS idx_pr_source
    ON practice_reminders(company_id, source_type, source_id, reminder_type)
    WHERE status IN ('open', 'snoozed');

-- Client filter
CREATE INDEX IF NOT EXISTS idx_pr_client
    ON practice_reminders(company_id, client_id)
    WHERE client_id IS NOT NULL;

-- Assignee filter
CREATE INDEX IF NOT EXISTS idx_pr_assignee
    ON practice_reminders(company_id, assigned_team_member_id)
    WHERE assigned_team_member_id IS NOT NULL;

-- Due date sorting / overdue detection
CREATE INDEX IF NOT EXISTS idx_pr_due_date
    ON practice_reminders(company_id, due_date)
    WHERE due_date IS NOT NULL AND status IN ('open', 'snoozed');

-- Snooze expiry
CREATE INDEX IF NOT EXISTS idx_pr_snoozed_until
    ON practice_reminders(snoozed_until)
    WHERE status = 'snoozed' AND snoozed_until IS NOT NULL;

-- Severity urgency filter
CREATE INDEX IF NOT EXISTS idx_pr_severity
    ON practice_reminders(company_id, severity)
    WHERE severity IN ('high', 'urgent') AND status NOT IN ('cancelled', 'dismissed', 'completed');

-- Source-type breakdown
CREATE INDEX IF NOT EXISTS idx_pr_source_type
    ON practice_reminders(company_id, source_type);
