-- ============================================================
-- Codebox 22: Client Communication Log
-- Creates practice_client_communications — manual communication
-- history per client. No email sending. No integrations. In-app only.
-- Run once in Supabase SQL Editor.
-- Expected result: "Success. No rows returned"
-- ============================================================

CREATE TABLE IF NOT EXISTS practice_client_communications (
    id                       INTEGER      PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    company_id               INTEGER      NOT NULL,
    client_id                INTEGER      NOT NULL,

    -- What and how
    communication_type       TEXT         NOT NULL,   -- call | email_note | whatsapp_note | meeting | document_request | sars_followup | cipc_followup | billing_followup | general_note | internal_note
    direction                TEXT         NOT NULL DEFAULT 'outbound',  -- inbound | outbound | internal
    subject                  TEXT         NOT NULL,
    body                     TEXT         NULL,

    -- Contact details (free-text, no FK — contact may not be in system)
    contact_person_id        INTEGER      NULL,       -- reference-only, no FK
    contact_name             TEXT         NULL,
    contact_email            TEXT         NULL,
    contact_phone            TEXT         NULL,

    -- Optional links to related records (no FK constraints — reference only)
    related_task_id          INTEGER      NULL,
    related_deadline_id      INTEGER      NULL,
    related_engagement_id    INTEGER      NULL,
    related_reminder_id      INTEGER      NULL,
    related_health_action_id INTEGER      NULL,

    -- Response tracking
    response_required        BOOLEAN      NOT NULL DEFAULT false,
    response_due_date        DATE         NULL,
    response_status          TEXT         NOT NULL DEFAULT 'not_required',  -- not_required | waiting | received | overdue | cancelled
    responded_at             TIMESTAMPTZ  NULL,
    responded_by             INTEGER      NULL,

    -- Assignment and visibility
    assigned_team_member_id  INTEGER      NULL,
    communication_date       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    is_internal              BOOLEAN      NOT NULL DEFAULT false,
    visibility               TEXT         NOT NULL DEFAULT 'practice',  -- practice | manager_only | partner_only

    -- Notes and meta
    attachments_note         TEXT         NULL,
    tags                     JSONB        NOT NULL DEFAULT '[]',
    settings                 JSONB        NOT NULL DEFAULT '{}',

    -- Soft delete
    cancelled_at             TIMESTAMPTZ  NULL,

    -- Audit
    created_at               TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at               TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by               INTEGER      NULL,
    updated_by               INTEGER      NULL
);

-- ── Indexes ────────────────────────────────────────────────────────────────────

-- Primary tenant filter
CREATE INDEX IF NOT EXISTS idx_pcc_company
    ON practice_client_communications(company_id);

-- Per-client history (most common query)
CREATE INDEX IF NOT EXISTS idx_pcc_client
    ON practice_client_communications(company_id, client_id, communication_date DESC)
    WHERE cancelled_at IS NULL;

-- Type filter
CREATE INDEX IF NOT EXISTS idx_pcc_type
    ON practice_client_communications(company_id, communication_type)
    WHERE cancelled_at IS NULL;

-- Direction filter
CREATE INDEX IF NOT EXISTS idx_pcc_direction
    ON practice_client_communications(company_id, direction)
    WHERE cancelled_at IS NULL;

-- Response tracking: open responses
CREATE INDEX IF NOT EXISTS idx_pcc_response_required
    ON practice_client_communications(company_id, response_required)
    WHERE response_required = true AND cancelled_at IS NULL;

-- Response status filter
CREATE INDEX IF NOT EXISTS idx_pcc_response_status
    ON practice_client_communications(company_id, response_status)
    WHERE response_status NOT IN ('not_required', 'cancelled') AND cancelled_at IS NULL;

-- Response due date (overdue detection)
CREATE INDEX IF NOT EXISTS idx_pcc_response_due
    ON practice_client_communications(company_id, response_due_date)
    WHERE response_due_date IS NOT NULL AND response_status = 'waiting' AND cancelled_at IS NULL;

-- Assignee filter
CREATE INDEX IF NOT EXISTS idx_pcc_assignee
    ON practice_client_communications(company_id, assigned_team_member_id)
    WHERE assigned_team_member_id IS NOT NULL AND cancelled_at IS NULL;

-- Related records (for cross-linking queries)
CREATE INDEX IF NOT EXISTS idx_pcc_task
    ON practice_client_communications(related_task_id)
    WHERE related_task_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_pcc_deadline
    ON practice_client_communications(related_deadline_id)
    WHERE related_deadline_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_pcc_engagement
    ON practice_client_communications(related_engagement_id)
    WHERE related_engagement_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_pcc_reminder
    ON practice_client_communications(related_reminder_id)
    WHERE related_reminder_id IS NOT NULL;

-- Date ordering (default list view)
CREATE INDEX IF NOT EXISTS idx_pcc_date
    ON practice_client_communications(company_id, communication_date DESC)
    WHERE cancelled_at IS NULL;
