-- ============================================================
-- Codebox 23: Document Request Tracker + Client Document Checklist Foundation
-- Creates:
--   practice_document_requests       — tracked document requests per client
--   practice_document_checklists     — reusable request templates
--   practice_document_checklist_items — line items per template
--
-- NOT file storage. NOT OCR. NOT SharePoint integration.
-- Tracks: requested | reminder_sent | partially_received | received | waived | cancelled
-- Overdue detection is computed in-app — no cron, no stored overdue flag.
-- Run once in Supabase SQL Editor.
-- Expected result: "Success. No rows returned"
-- ============================================================

-- ── Table 1: Document Requests ─────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS practice_document_requests (
    id                       INTEGER      PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    company_id               INTEGER      NOT NULL,
    client_id                INTEGER      NOT NULL,

    -- What is being requested
    request_title            TEXT         NOT NULL,
    request_description      TEXT         NULL,
    document_category        TEXT         NOT NULL,
    -- identity | tax | vat | payroll | accounting | banking | cipc | trust
    -- | legal | compliance | financials | supporting_docs | custom
    document_type            TEXT         NULL,       -- free-text specific label (e.g. "VAT201 Return")

    -- Status
    request_status           TEXT         NOT NULL DEFAULT 'requested',
    -- requested | reminder_sent | partially_received | received | waived | cancelled

    -- Dates
    requested_at             TIMESTAMPTZ  NOT NULL DEFAULT now(),
    required_by_date         DATE         NULL,       -- client must provide by this date
    received_at              TIMESTAMPTZ  NULL,       -- stamped when status = 'received'

    -- Assignment
    assigned_team_member_id  INTEGER      NULL,

    -- Optional links (reference-only — no FK constraints — source records may be deleted)
    related_workflow_run_id  BIGINT       NULL,
    related_task_id          INTEGER      NULL,
    related_deadline_id      INTEGER      NULL,
    related_engagement_id    INTEGER      NULL,
    related_communication_id INTEGER      NULL,

    -- Reminder tracking
    reminder_count           INTEGER      NOT NULL DEFAULT 0,
    last_reminder_at         TIMESTAMPTZ  NULL,

    -- Notes
    notes                    TEXT         NULL,
    internal_notes           TEXT         NULL,

    -- Audit
    created_by               INTEGER      NULL,
    updated_by               INTEGER      NULL,
    created_at               TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at               TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- ── Table 2: Document Checklists ───────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS practice_document_checklists (
    id                       INTEGER      PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    company_id               INTEGER      NOT NULL,
    checklist_name           TEXT         NOT NULL,
    category                 TEXT         NOT NULL DEFAULT 'custom',
    -- vat | tax | payroll | financials | audit | onboarding | cipc | trust | custom
    description              TEXT         NULL,
    is_active                BOOLEAN      NOT NULL DEFAULT true,
    created_by               INTEGER      NULL,
    updated_by               INTEGER      NULL,
    created_at               TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at               TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- ── Table 3: Document Checklist Items ──────────────────────────────────────────

CREATE TABLE IF NOT EXISTS practice_document_checklist_items (
    id                       INTEGER      PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    checklist_id             INTEGER      NOT NULL,
    company_id               INTEGER      NOT NULL,   -- denormalized for fast company-scoped queries
    item_name                TEXT         NOT NULL,
    item_description         TEXT         NULL,
    document_category        TEXT         NOT NULL DEFAULT 'supporting_docs',
    document_type            TEXT         NULL,
    sort_order               INTEGER      NOT NULL DEFAULT 0,
    is_required              BOOLEAN      NOT NULL DEFAULT true,
    created_at               TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at               TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- ── Indexes: practice_document_requests ────────────────────────────────────────

-- Primary tenant filter
CREATE INDEX IF NOT EXISTS idx_pdr_company
    ON practice_document_requests(company_id);

-- Per-client request list (most common query — client detail page)
CREATE INDEX IF NOT EXISTS idx_pdr_client
    ON practice_document_requests(company_id, client_id, requested_at DESC)
    WHERE request_status != 'cancelled';

-- Status filter (summary + list filtering)
CREATE INDEX IF NOT EXISTS idx_pdr_status
    ON practice_document_requests(company_id, request_status)
    WHERE request_status != 'cancelled';

-- Overdue detection (outstanding + has due date)
CREATE INDEX IF NOT EXISTS idx_pdr_required_by
    ON practice_document_requests(company_id, required_by_date)
    WHERE required_by_date IS NOT NULL
      AND request_status IN ('requested', 'reminder_sent', 'partially_received');

-- Assignee filter
CREATE INDEX IF NOT EXISTS idx_pdr_assignee
    ON practice_document_requests(company_id, assigned_team_member_id)
    WHERE assigned_team_member_id IS NOT NULL AND request_status != 'cancelled';

-- Category filter
CREATE INDEX IF NOT EXISTS idx_pdr_category
    ON practice_document_requests(company_id, document_category)
    WHERE request_status != 'cancelled';

-- Default list sort
CREATE INDEX IF NOT EXISTS idx_pdr_requested_at
    ON practice_document_requests(company_id, requested_at DESC)
    WHERE request_status != 'cancelled';

-- Cross-link indexes (reference lookups)
CREATE INDEX IF NOT EXISTS idx_pdr_workflow
    ON practice_document_requests(related_workflow_run_id)
    WHERE related_workflow_run_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_pdr_task
    ON practice_document_requests(related_task_id)
    WHERE related_task_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_pdr_deadline
    ON practice_document_requests(related_deadline_id)
    WHERE related_deadline_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_pdr_engagement
    ON practice_document_requests(related_engagement_id)
    WHERE related_engagement_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_pdr_communication
    ON practice_document_requests(related_communication_id)
    WHERE related_communication_id IS NOT NULL;

-- ── Indexes: practice_document_checklists ─────────────────────────────────────

CREATE INDEX IF NOT EXISTS idx_pdc_company
    ON practice_document_checklists(company_id)
    WHERE is_active = true;

-- ── Indexes: practice_document_checklist_items ────────────────────────────────

CREATE INDEX IF NOT EXISTS idx_pdci_checklist
    ON practice_document_checklist_items(checklist_id, sort_order);

CREATE INDEX IF NOT EXISTS idx_pdci_company
    ON practice_document_checklist_items(company_id);
