-- ============================================================
-- Codebox 24: Annual Compliance Pack + Client Year-End Readiness Foundation
-- Creates:
--   practice_compliance_packs       — per-client compliance packs per period/type
--   practice_compliance_pack_items  — checklist items per pack
--   practice_compliance_pack_events — audit trail for pack status changes
--
-- NOT tax calculation. NOT financial statement generation. NOT SARS submission.
-- Tracks readiness/completeness only.
-- Readiness score is computed by the recalculate-readiness endpoint — no stored flags.
-- Run once in Supabase SQL Editor.
-- Expected result: "Success. No rows returned"
-- ============================================================

-- ── Table 1: Compliance Packs ─────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS practice_compliance_packs (
    id                       INTEGER      PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    company_id               INTEGER      NOT NULL,
    client_id                INTEGER      NOT NULL,

    -- Pack identity
    pack_type                TEXT         NOT NULL,
    -- annual_financials | company_tax | individual_tax | vat_period
    -- | payroll_annual | cipc_annual | custom
    pack_name                TEXT         NOT NULL,

    -- Period scope
    period_start             DATE         NULL,
    period_end               DATE         NULL,
    tax_year                 INTEGER      NULL,
    financial_year_end       DATE         NULL,

    -- Status lifecycle
    status                   TEXT         NOT NULL DEFAULT 'draft',
    -- draft | collecting_docs | ready_for_review | reviewed | completed | cancelled

    -- Readiness (computed on demand by recalculate-readiness — never a stored overdue flag)
    readiness_score          INTEGER      NULL,   -- 0–100; null = not yet calculated
    readiness_status         TEXT         NULL DEFAULT 'unknown',
    -- incomplete | partial | ready | blocked | unknown

    -- Assignment
    owner_team_member_id     INTEGER      NULL,
    reviewer_team_member_id  INTEGER      NULL,

    -- Optional cross-links (reference-only — no FK constraints, source records may be deleted)
    related_workflow_run_id  BIGINT       NULL,
    related_deadline_id      INTEGER      NULL,

    -- Metadata
    notes                    TEXT         NULL,
    internal_notes           TEXT         NULL,
    settings                 JSONB        NOT NULL DEFAULT '{}',

    -- Audit
    created_by               INTEGER      NULL,
    updated_by               INTEGER      NULL,
    created_at               TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at               TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- ── Table 2: Compliance Pack Items ────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS practice_compliance_pack_items (
    id                           INTEGER      PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    company_id                   INTEGER      NOT NULL,
    pack_id                      INTEGER      NOT NULL,

    -- Item identity
    item_type                    TEXT         NOT NULL DEFAULT 'document',
    -- document | task | deadline | checklist | review | custom
    item_name                    TEXT         NOT NULL,
    item_description             TEXT         NULL,

    -- Status
    status                       TEXT         NOT NULL DEFAULT 'required',
    -- required | requested | received | completed | waived | blocked | not_applicable
    required                     BOOLEAN      NOT NULL DEFAULT true,

    -- Optional cross-links (reference-only — no FK constraints)
    related_document_request_id  INTEGER      NULL,
    related_task_id              INTEGER      NULL,
    related_deadline_id          INTEGER      NULL,

    -- Ordering
    sort_order                   INTEGER      NOT NULL DEFAULT 0,

    -- Notes
    notes                        TEXT         NULL,

    -- Audit
    created_at                   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at                   TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- ── Table 3: Compliance Pack Events ───────────────────────────────────────────

CREATE TABLE IF NOT EXISTS practice_compliance_pack_events (
    id             INTEGER      PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    company_id     INTEGER      NOT NULL,
    pack_id        INTEGER      NOT NULL,
    event_type     TEXT         NOT NULL,
    old_status     TEXT         NULL,
    new_status     TEXT         NULL,
    actor_user_id  INTEGER      NULL,
    notes          TEXT         NULL,
    metadata       JSONB        NOT NULL DEFAULT '{}',
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- ── Indexes: practice_compliance_packs ────────────────────────────────────────

-- Primary tenant filter
CREATE INDEX IF NOT EXISTS idx_pcp_company
    ON practice_compliance_packs(company_id)
    WHERE status != 'cancelled';

-- Per-client pack list (most common query — client detail page)
CREATE INDEX IF NOT EXISTS idx_pcp_client
    ON practice_compliance_packs(company_id, client_id, created_at DESC)
    WHERE status != 'cancelled';

-- Pack type filter
CREATE INDEX IF NOT EXISTS idx_pcp_type
    ON practice_compliance_packs(company_id, pack_type)
    WHERE status != 'cancelled';

-- Status filter
CREATE INDEX IF NOT EXISTS idx_pcp_status
    ON practice_compliance_packs(company_id, status);

-- Readiness status filter (dashboard / command centre)
CREATE INDEX IF NOT EXISTS idx_pcp_readiness_status
    ON practice_compliance_packs(company_id, readiness_status)
    WHERE status != 'cancelled';

-- Period range filter
CREATE INDEX IF NOT EXISTS idx_pcp_period
    ON practice_compliance_packs(company_id, period_start, period_end)
    WHERE period_start IS NOT NULL;

-- Tax year filter
CREATE INDEX IF NOT EXISTS idx_pcp_tax_year
    ON practice_compliance_packs(company_id, tax_year)
    WHERE tax_year IS NOT NULL;

-- ── Indexes: practice_compliance_pack_items ───────────────────────────────────

-- Items per pack (primary access pattern)
CREATE INDEX IF NOT EXISTS idx_pcpi_pack
    ON practice_compliance_pack_items(pack_id, sort_order);

-- Company-scoped item queries
CREATE INDEX IF NOT EXISTS idx_pcpi_company
    ON practice_compliance_pack_items(company_id);

-- Cross-link: document request
CREATE INDEX IF NOT EXISTS idx_pcpi_doc_request
    ON practice_compliance_pack_items(related_document_request_id)
    WHERE related_document_request_id IS NOT NULL;

-- ── Indexes: practice_compliance_pack_events ──────────────────────────────────

-- Events per pack (chronological)
CREATE INDEX IF NOT EXISTS idx_pcpe_pack
    ON practice_compliance_pack_events(pack_id, created_at DESC);

-- Company-scoped event queries
CREATE INDEX IF NOT EXISTS idx_pcpe_company
    ON practice_compliance_pack_events(company_id);
