-- ============================================================
-- Codebox 25: Taxpayer Profile Foundation — Individual + Company Tax Readiness
-- Creates:
--   practice_taxpayer_profiles       — one profile per client (individual, company, trust, etc.)
--   practice_taxpayer_income_sources — income source declarations per profile
--   practice_taxpayer_deductions     — deduction declarations per profile
--   practice_taxpayer_readiness_items — readiness checklist items per profile
--
-- NOT tax calculation. NOT SARS submission. NOT eFiling integration.
-- Tracks taxpayer profile completeness and document readiness only.
-- Run once in Supabase SQL Editor.
-- Expected result: "Success. No rows returned"
-- ============================================================

-- ── Table 1: Taxpayer Profiles ────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS practice_taxpayer_profiles (
    id                       INTEGER      PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    company_id               INTEGER      NOT NULL,
    client_id                INTEGER      NOT NULL,

    -- Profile type (maps to client entity type)
    taxpayer_type            TEXT         NOT NULL,
    -- individual | company | trust | partnership | cc

    -- SARS registration
    income_tax_reference     TEXT         NULL,
    provisional_taxpayer     BOOLEAN      NOT NULL DEFAULT false,
    vat_registered           BOOLEAN      NOT NULL DEFAULT false,
    paye_registered          BOOLEAN      NOT NULL DEFAULT false,

    -- Individual-only fields
    id_number                TEXT         NULL,
    passport_number          TEXT         NULL,
    marital_status           TEXT         NULL,
    -- single | married | divorced | widowed

    -- Company / Trust / CC / Partnership fields
    registration_number      TEXT         NULL,
    financial_year_end       DATE         NULL,

    -- Profile lifecycle
    tax_status               TEXT         NOT NULL DEFAULT 'active',
    -- active | dormant | ceased

    -- Readiness (computed on demand — never a stored overdue flag)
    readiness_score          INTEGER      NULL,   -- 0–100; null = not yet calculated
    readiness_status         TEXT         NULL DEFAULT 'unknown',
    -- incomplete | partial | ready | blocked | unknown

    -- Assignment
    responsible_team_member_id  INTEGER   NULL,
    reviewer_team_member_id     INTEGER   NULL,

    -- Notes
    notes                    TEXT         NULL,
    internal_notes           TEXT         NULL,

    -- Audit
    created_by               INTEGER      NULL,
    updated_by               INTEGER      NULL,
    created_at               TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at               TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- ── Table 2: Income Sources ───────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS practice_taxpayer_income_sources (
    id             INTEGER      PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    company_id     INTEGER      NOT NULL,
    profile_id     INTEGER      NOT NULL,

    income_type    TEXT         NOT NULL,
    -- salary | business | rental | investment | interest | dividends
    -- | foreign_income | capital_gain | trust_distribution | pension | other

    description    TEXT         NULL,
    active         BOOLEAN      NOT NULL DEFAULT true,
    notes          TEXT         NULL,

    created_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- ── Table 3: Deductions ───────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS practice_taxpayer_deductions (
    id              INTEGER      PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    company_id      INTEGER      NOT NULL,
    profile_id      INTEGER      NOT NULL,

    deduction_type  TEXT         NOT NULL,
    -- retirement_annuity | medical | travel | home_office | donations
    -- | wear_and_tear | business_expenses | assessed_losses | other

    description     TEXT         NULL,
    active          BOOLEAN      NOT NULL DEFAULT true,

    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- ── Table 4: Readiness Items ──────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS practice_taxpayer_readiness_items (
    id                           INTEGER      PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    company_id                   INTEGER      NOT NULL,
    profile_id                   INTEGER      NOT NULL,

    item_name                    TEXT         NOT NULL,
    required                     BOOLEAN      NOT NULL DEFAULT true,

    status                       TEXT         NOT NULL DEFAULT 'required',
    -- required | received | completed | waived | blocked

    -- Optional cross-link (reference-only — no FK constraint)
    related_document_request_id  INTEGER      NULL,

    notes                        TEXT         NULL,

    created_at                   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at                   TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- ── Indexes: practice_taxpayer_profiles ───────────────────────────────────────

CREATE INDEX IF NOT EXISTS idx_ptp_company
    ON practice_taxpayer_profiles(company_id)
    WHERE tax_status != 'ceased';

CREATE INDEX IF NOT EXISTS idx_ptp_client
    ON practice_taxpayer_profiles(company_id, client_id);

CREATE INDEX IF NOT EXISTS idx_ptp_type
    ON practice_taxpayer_profiles(company_id, taxpayer_type)
    WHERE tax_status != 'ceased';

CREATE INDEX IF NOT EXISTS idx_ptp_tax_status
    ON practice_taxpayer_profiles(company_id, tax_status);

CREATE INDEX IF NOT EXISTS idx_ptp_readiness
    ON practice_taxpayer_profiles(company_id, readiness_status)
    WHERE tax_status = 'active';

-- ── Indexes: practice_taxpayer_income_sources ────────────────────────────────

CREATE INDEX IF NOT EXISTS idx_ptis_company
    ON practice_taxpayer_income_sources(company_id);

CREATE INDEX IF NOT EXISTS idx_ptis_profile
    ON practice_taxpayer_income_sources(profile_id)
    WHERE active = true;

CREATE INDEX IF NOT EXISTS idx_ptis_type
    ON practice_taxpayer_income_sources(company_id, income_type)
    WHERE active = true;

-- ── Indexes: practice_taxpayer_deductions ─────────────────────────────────────

CREATE INDEX IF NOT EXISTS idx_ptd_company
    ON practice_taxpayer_deductions(company_id);

CREATE INDEX IF NOT EXISTS idx_ptd_profile
    ON practice_taxpayer_deductions(profile_id)
    WHERE active = true;

CREATE INDEX IF NOT EXISTS idx_ptd_type
    ON practice_taxpayer_deductions(company_id, deduction_type)
    WHERE active = true;

-- ── Indexes: practice_taxpayer_readiness_items ────────────────────────────────

CREATE INDEX IF NOT EXISTS idx_ptri_company
    ON practice_taxpayer_readiness_items(company_id);

CREATE INDEX IF NOT EXISTS idx_ptri_profile
    ON practice_taxpayer_readiness_items(profile_id);

CREATE INDEX IF NOT EXISTS idx_ptri_status
    ON practice_taxpayer_readiness_items(profile_id, status);

CREATE INDEX IF NOT EXISTS idx_ptri_doc_request
    ON practice_taxpayer_readiness_items(related_document_request_id)
    WHERE related_document_request_id IS NOT NULL;
