-- ============================================================
-- Codebox 26: Provisional Tax Planning + Tax Calendar Foundation
-- Creates:
--   practice_provisional_tax_plans    — one plan per taxpayer profile per tax year
--   practice_provisional_tax_periods  — period 1 / period 2 / top-up tracking rows
--   practice_provisional_tax_events   — audit event log per plan
--
-- NOT tax calculation. NOT SARS submission. NOT eFiling.
-- Planning and readiness tracking only.
-- Due dates are editable planning defaults, not legal authority.
-- Run once in Supabase SQL Editor.
-- Expected result: "Success. No rows returned"
-- ============================================================

-- ── Table 1: Provisional Tax Plans ───────────────────────────────────────────

CREATE TABLE IF NOT EXISTS practice_provisional_tax_plans (
    id                              INTEGER      PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    company_id                      INTEGER      NOT NULL,
    client_id                       INTEGER      NOT NULL,
    taxpayer_profile_id             INTEGER      NOT NULL,

    -- Plan identity
    tax_year                        INTEGER      NOT NULL,
    plan_name                       TEXT         NOT NULL,

    -- Lifecycle
    status                          TEXT         NOT NULL DEFAULT 'draft',
    -- draft | collecting_info | ready_for_review | reviewed | submitted | completed | cancelled

    -- Taxpayer context (denormalised snapshot for display)
    taxpayer_type                   TEXT         NULL,
    provisional_taxpayer            BOOLEAN      NOT NULL DEFAULT true,

    -- Estimate fields — entered by practice, NOT calculated
    prior_year_taxable_income       NUMERIC(14,2) NULL,
    current_estimated_taxable_income NUMERIC(14,2) NULL,
    estimate_basis                  TEXT         NULL,
    risk_notes                      TEXT         NULL,

    -- Assignment
    responsible_team_member_id      INTEGER      NULL,
    reviewer_team_member_id         INTEGER      NULL,

    -- Review
    reviewed_at                     TIMESTAMPTZ  NULL,
    reviewed_by                     INTEGER      NULL,

    -- SA planning due date defaults (all editable — not legal authority)
    period_1_due_date               DATE         NULL,
    period_2_due_date               DATE         NULL,
    topup_due_date                  DATE         NULL,

    -- Cross-links (reference only — no FK constraints)
    related_compliance_pack_id      INTEGER      NULL,
    related_deadline_id             INTEGER      NULL,
    related_workflow_run_id         BIGINT       NULL,

    -- Metadata
    notes                           TEXT         NULL,
    internal_notes                  TEXT         NULL,
    settings                        JSONB        NOT NULL DEFAULT '{}',

    -- Audit
    created_by                      INTEGER      NULL,
    updated_by                      INTEGER      NULL,
    created_at                      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at                      TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- ── Table 2: Provisional Tax Periods ─────────────────────────────────────────

CREATE TABLE IF NOT EXISTS practice_provisional_tax_periods (
    id                      INTEGER      PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    company_id              INTEGER      NOT NULL,
    plan_id                 INTEGER      NOT NULL,

    period_type             TEXT         NOT NULL,
    -- period_1 | period_2 | topup

    due_date                DATE         NULL,

    status                  TEXT         NOT NULL DEFAULT 'not_started',
    -- not_started | collecting_info | ready | reviewed | submitted | paid | waived | cancelled

    -- Estimate fields — entered by practice
    estimated_taxable_income NUMERIC(14,2) NULL,
    estimated_tax_due        NUMERIC(14,2) NULL,

    -- Actuals — entered once submitted/paid
    amount_submitted        NUMERIC(14,2) NULL,
    amount_paid             NUMERIC(14,2) NULL,
    submitted_at            TIMESTAMPTZ  NULL,
    paid_at                 TIMESTAMPTZ  NULL,
    submission_reference    TEXT         NULL,
    payment_reference       TEXT         NULL,

    notes                   TEXT         NULL,

    created_at              TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at              TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- ── Table 3: Plan Events (audit log) ─────────────────────────────────────────

CREATE TABLE IF NOT EXISTS practice_provisional_tax_events (
    id              INTEGER      PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    company_id      INTEGER      NOT NULL,
    plan_id         INTEGER      NOT NULL,
    period_id       INTEGER      NULL,

    event_type      TEXT         NOT NULL,
    -- provisional_tax_plan_created | provisional_tax_plan_updated
    -- | provisional_tax_period_created | provisional_tax_period_updated
    -- | provisional_tax_status_changed | provisional_tax_reviewed

    old_status      TEXT         NULL,
    new_status      TEXT         NULL,
    actor_user_id   INTEGER      NULL,
    notes           TEXT         NULL,
    metadata        JSONB        NOT NULL DEFAULT '{}',

    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- ── Indexes: practice_provisional_tax_plans ───────────────────────────────────

CREATE INDEX IF NOT EXISTS idx_pptp_company
    ON practice_provisional_tax_plans(company_id)
    WHERE status != 'cancelled';

CREATE INDEX IF NOT EXISTS idx_pptp_client
    ON practice_provisional_tax_plans(company_id, client_id);

CREATE INDEX IF NOT EXISTS idx_pptp_profile
    ON practice_provisional_tax_plans(taxpayer_profile_id);

CREATE INDEX IF NOT EXISTS idx_pptp_tax_year
    ON practice_provisional_tax_plans(company_id, tax_year);

CREATE INDEX IF NOT EXISTS idx_pptp_status
    ON practice_provisional_tax_plans(company_id, status);

CREATE INDEX IF NOT EXISTS idx_pptp_p1_due
    ON practice_provisional_tax_plans(company_id, period_1_due_date)
    WHERE period_1_due_date IS NOT NULL AND status != 'cancelled';

CREATE INDEX IF NOT EXISTS idx_pptp_p2_due
    ON practice_provisional_tax_plans(company_id, period_2_due_date)
    WHERE period_2_due_date IS NOT NULL AND status != 'cancelled';

-- ── Indexes: practice_provisional_tax_periods ─────────────────────────────────

CREATE INDEX IF NOT EXISTS idx_pptper_company
    ON practice_provisional_tax_periods(company_id);

CREATE INDEX IF NOT EXISTS idx_pptper_plan
    ON practice_provisional_tax_periods(plan_id);

CREATE INDEX IF NOT EXISTS idx_pptper_type
    ON practice_provisional_tax_periods(plan_id, period_type);

CREATE INDEX IF NOT EXISTS idx_pptper_status
    ON practice_provisional_tax_periods(company_id, status);

CREATE INDEX IF NOT EXISTS idx_pptper_due
    ON practice_provisional_tax_periods(company_id, due_date)
    WHERE due_date IS NOT NULL AND status NOT IN ('paid', 'waived', 'cancelled');

-- ── Indexes: practice_provisional_tax_events ──────────────────────────────────

CREATE INDEX IF NOT EXISTS idx_ppte_company
    ON practice_provisional_tax_events(company_id);

CREATE INDEX IF NOT EXISTS idx_ppte_plan
    ON practice_provisional_tax_events(plan_id);

CREATE INDEX IF NOT EXISTS idx_ppte_period
    ON practice_provisional_tax_events(period_id)
    WHERE period_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_ppte_type
    ON practice_provisional_tax_events(plan_id, event_type);

CREATE INDEX IF NOT EXISTS idx_ppte_created
    ON practice_provisional_tax_events(plan_id, created_at DESC);
