-- ============================================================
-- Codebox 27: Individual Income Tax Data Capture Foundation
-- Creates:
--   practice_individual_tax_returns         — one return record per taxpayer per tax year
--   practice_individual_tax_items           — readiness checklist items per return
--   practice_individual_tax_income_entries  — income source entries per return
--   practice_individual_tax_deduction_entries — deduction entries per return
--   practice_individual_tax_events          — audit event log per return
--
-- NOT tax calculation. NOT SARS submission. NOT eFiling.
-- Structured data capture and readiness tracking only.
-- Run once in Supabase SQL Editor.
-- Expected result: "Success. No rows returned"
-- ============================================================

-- ── Table 1: Individual Tax Returns ──────────────────────────────────────────

CREATE TABLE IF NOT EXISTS practice_individual_tax_returns (
    id                              INTEGER      PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    company_id                      INTEGER      NOT NULL,
    client_id                       INTEGER      NOT NULL,
    taxpayer_profile_id             INTEGER      NOT NULL,

    -- Identity
    tax_year                        INTEGER      NOT NULL,
    return_name                     TEXT         NOT NULL,

    -- Lifecycle
    status                          TEXT         NOT NULL DEFAULT 'draft',
    -- draft | collecting_docs | data_captured | ready_for_review
    -- | reviewed | submitted | completed | cancelled

    -- Readiness (computed on demand — never auto-calculated)
    readiness_score                 INTEGER      NULL,   -- 0–100; null = not yet calculated
    readiness_status                TEXT         NULL DEFAULT 'unknown',
    -- incomplete | partial | ready | blocked | unknown

    -- Assignment + review
    responsible_team_member_id      INTEGER      NULL,
    reviewer_team_member_id         INTEGER      NULL,
    reviewed_at                     TIMESTAMPTZ  NULL,
    reviewed_by                     INTEGER      NULL,

    -- Cross-links (reference only — no FK constraints)
    related_taxpayer_profile_id     INTEGER      NULL,
    related_compliance_pack_id      INTEGER      NULL,
    related_deadline_id             INTEGER      NULL,
    related_workflow_run_id         BIGINT       NULL,
    related_provisional_tax_plan_id INTEGER      NULL,

    -- Metadata
    notes                           TEXT         NULL,
    internal_notes                  TEXT         NULL,
    settings                        JSONB        NOT NULL DEFAULT '{}',

    -- Audit
    created_by                      INTEGER      NULL,
    updated_by                      INTEGER      NULL,
    created_at                      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at                      TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- ── Table 2: Checklist Items ──────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS practice_individual_tax_items (
    id                              INTEGER      PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    company_id                      INTEGER      NOT NULL,
    tax_return_id                   INTEGER      NOT NULL,

    item_type                       TEXT         NOT NULL,
    -- irp5 | it3a | medical | retirement_annuity | travel | rental
    -- | investment | donations | capital_gain | business_income
    -- | foreign_income | document | custom

    item_label                      TEXT         NOT NULL,

    item_status                     TEXT         NOT NULL DEFAULT 'required',
    -- required | requested | received | captured | reviewed | waived | blocked | not_applicable

    -- Optional amount captured for this item
    amount                          NUMERIC(14,2) NULL,

    -- Cross-links
    source_reference                TEXT         NULL,
    related_document_request_id     INTEGER      NULL,

    notes                           TEXT         NULL,

    created_at                      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at                      TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- ── Table 3: Income Entries ───────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS practice_individual_tax_income_entries (
    id                  INTEGER      PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    company_id          INTEGER      NOT NULL,
    tax_return_id       INTEGER      NOT NULL,

    income_type         TEXT         NOT NULL,
    -- salary | pension | annuity | interest | dividends | rental
    -- | business | capital_gain | foreign_income | other

    description         TEXT         NULL,
    gross_amount        NUMERIC(14,2) NULL,
    tax_withheld        NUMERIC(14,2) NULL,
    source_reference    TEXT         NULL,
    notes               TEXT         NULL,

    created_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- ── Table 4: Deduction Entries ────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS practice_individual_tax_deduction_entries (
    id                  INTEGER      PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    company_id          INTEGER      NOT NULL,
    tax_return_id       INTEGER      NOT NULL,

    deduction_type      TEXT         NOT NULL,
    -- medical | retirement_annuity | travel | donations | home_office
    -- | wear_and_tear | business_expense | other

    description         TEXT         NULL,
    amount              NUMERIC(14,2) NULL,
    source_reference    TEXT         NULL,
    notes               TEXT         NULL,

    created_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- ── Table 5: Events (audit log) ───────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS practice_individual_tax_events (
    id              INTEGER      PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    company_id      INTEGER      NOT NULL,
    tax_return_id   INTEGER      NOT NULL,

    event_type      TEXT         NOT NULL,
    -- individual_tax_return_created | individual_tax_return_updated
    -- | individual_tax_items_generated | individual_tax_readiness_recalculated
    -- | individual_tax_income_added | individual_tax_deduction_added
    -- | individual_tax_status_changed | individual_tax_reviewed

    old_status      TEXT         NULL,
    new_status      TEXT         NULL,
    actor_user_id   INTEGER      NULL,
    notes           TEXT         NULL,
    metadata        JSONB        NOT NULL DEFAULT '{}',

    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- ── Indexes: practice_individual_tax_returns ──────────────────────────────────

CREATE INDEX IF NOT EXISTS idx_pitr_company
    ON practice_individual_tax_returns(company_id)
    WHERE status != 'cancelled';

CREATE INDEX IF NOT EXISTS idx_pitr_client
    ON practice_individual_tax_returns(company_id, client_id);

CREATE INDEX IF NOT EXISTS idx_pitr_profile
    ON practice_individual_tax_returns(taxpayer_profile_id);

CREATE INDEX IF NOT EXISTS idx_pitr_year
    ON practice_individual_tax_returns(company_id, tax_year);

CREATE INDEX IF NOT EXISTS idx_pitr_status
    ON practice_individual_tax_returns(company_id, status);

CREATE INDEX IF NOT EXISTS idx_pitr_readiness
    ON practice_individual_tax_returns(company_id, readiness_status)
    WHERE status NOT IN ('cancelled', 'completed');

-- ── Indexes: practice_individual_tax_items ────────────────────────────────────

CREATE INDEX IF NOT EXISTS idx_piti_company
    ON practice_individual_tax_items(company_id);

CREATE INDEX IF NOT EXISTS idx_piti_return
    ON practice_individual_tax_items(tax_return_id);

CREATE INDEX IF NOT EXISTS idx_piti_type
    ON practice_individual_tax_items(tax_return_id, item_type);

CREATE INDEX IF NOT EXISTS idx_piti_status
    ON practice_individual_tax_items(tax_return_id, item_status);

-- ── Indexes: practice_individual_tax_income_entries ───────────────────────────

CREATE INDEX IF NOT EXISTS idx_pitie_company
    ON practice_individual_tax_income_entries(company_id);

CREATE INDEX IF NOT EXISTS idx_pitie_return
    ON practice_individual_tax_income_entries(tax_return_id);

CREATE INDEX IF NOT EXISTS idx_pitie_type
    ON practice_individual_tax_income_entries(tax_return_id, income_type);

-- ── Indexes: practice_individual_tax_deduction_entries ───────────────────────

CREATE INDEX IF NOT EXISTS idx_pitde_company
    ON practice_individual_tax_deduction_entries(company_id);

CREATE INDEX IF NOT EXISTS idx_pitde_return
    ON practice_individual_tax_deduction_entries(tax_return_id);

CREATE INDEX IF NOT EXISTS idx_pitde_type
    ON practice_individual_tax_deduction_entries(tax_return_id, deduction_type);

-- ── Indexes: practice_individual_tax_events ───────────────────────────────────

CREATE INDEX IF NOT EXISTS idx_pitevt_company
    ON practice_individual_tax_events(company_id);

CREATE INDEX IF NOT EXISTS idx_pitevt_return
    ON practice_individual_tax_events(tax_return_id);

CREATE INDEX IF NOT EXISTS idx_pitevt_type
    ON practice_individual_tax_events(tax_return_id, event_type);

CREATE INDEX IF NOT EXISTS idx_pitevt_created
    ON practice_individual_tax_events(tax_return_id, created_at DESC);
