-- ============================================================
-- Codebox 28: Individual Income Tax Calculation Draft Engine Foundation
-- Creates:
--   practice_individual_tax_calculations       — one draft calculation per return
--   practice_individual_tax_calculation_events — audit event log per calculation
--
-- DRAFT / REVIEW ONLY. NOT SARS-final.
-- NOT eFiling submission. NOT tax advice.
-- All outputs must be reviewed by an accountant before use.
-- Run once in Supabase SQL Editor.
-- Expected result: "Success. No rows returned"
-- ============================================================

-- ── Table 1: Draft Calculations ────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS practice_individual_tax_calculations (
    id                          INTEGER      PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    company_id                  INTEGER      NOT NULL,
    tax_return_id               INTEGER      NOT NULL,
    client_id                   INTEGER      NOT NULL,
    taxpayer_profile_id         INTEGER      NOT NULL,
    tax_year                    INTEGER      NOT NULL,
    calculation_name            TEXT         NOT NULL,

    -- Lifecycle
    calculation_status          TEXT         NOT NULL DEFAULT 'draft',
    -- draft | ready_for_review | reviewed | approved | rejected | cancelled

    -- ── Input totals (always computed by backend from DB — never from frontend) ──
    gross_income_total          NUMERIC(14,2) NOT NULL DEFAULT 0,
    taxable_income_total        NUMERIC(14,2) NOT NULL DEFAULT 0,
    deduction_total             NUMERIC(14,2) NOT NULL DEFAULT 0,
    taxable_after_deductions    NUMERIC(14,2) NOT NULL DEFAULT 0,

    -- ── Tax components (null = not computed / not applicable) ──
    normal_tax_before_rebates   NUMERIC(14,2) NULL,
    primary_rebate              NUMERIC(14,2) NULL,
    secondary_rebate            NUMERIC(14,2) NULL,   -- age 65+
    tertiary_rebate             NUMERIC(14,2) NULL,   -- age 75+
    medical_tax_credit          NUMERIC(14,2) NULL,   -- foundation: null (no member count yet)
    additional_medical_credit   NUMERIC(14,2) NULL,
    tax_after_rebates           NUMERIC(14,2) NULL,
    paye_withheld               NUMERIC(14,2) NULL,   -- sum from income entries
    provisional_tax_paid        NUMERIC(14,2) NULL,   -- entered manually (future)
    estimated_tax_payable       NUMERIC(14,2) NULL,   -- positive = owe SARS
    estimated_refund            NUMERIC(14,2) NULL,   -- positive = refund due

    -- ── Versioning and transparency ──
    tax_table_version           TEXT         NULL,    -- e.g. '2026-v1'
    calculation_version         INTEGER      NOT NULL DEFAULT 1,

    -- JSON arrays stored for full audit transparency
    warning_flags               JSONB        NOT NULL DEFAULT '[]',
    -- e.g. ["DRAFT_TAX_TABLE_REQUIRES_REVIEW", "MISSING_IRP5", ...]

    calculation_lines           JSONB        NOT NULL DEFAULT '[]',
    -- e.g. [{"label":"Gross Income","amount":500000,"note":"..."}]

    assumptions                 JSONB        NOT NULL DEFAULT '[]',
    -- e.g. ["Primary rebate only applied","Medical credits not applied"]

    -- ── Review workflow ──
    reviewed_at                 TIMESTAMPTZ  NULL,
    reviewed_by                 INTEGER      NULL,
    approved_at                 TIMESTAMPTZ  NULL,
    approved_by                 INTEGER      NULL,
    rejection_reason            TEXT         NULL,

    -- ── Metadata ──
    notes                       TEXT         NULL,
    internal_notes              TEXT         NULL,

    -- ── Audit ──
    created_by                  INTEGER      NULL,
    updated_by                  INTEGER      NULL,
    created_at                  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at                  TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- ── Table 2: Calculation Events (audit log) ────────────────────────────────────

CREATE TABLE IF NOT EXISTS practice_individual_tax_calculation_events (
    id              INTEGER      PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    company_id      INTEGER      NOT NULL,
    calculation_id  INTEGER      NOT NULL,
    tax_return_id   INTEGER      NOT NULL,

    event_type      TEXT         NOT NULL,
    -- individual_tax_calculation_run
    -- | individual_tax_calculation_submitted_review
    -- | individual_tax_calculation_approved
    -- | individual_tax_calculation_rejected
    -- | individual_tax_calculation_updated
    -- | individual_tax_calculation_cancelled

    old_status      TEXT         NULL,
    new_status      TEXT         NULL,
    actor_user_id   INTEGER      NULL,
    notes           TEXT         NULL,
    metadata        JSONB        NOT NULL DEFAULT '{}',

    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- ── Indexes: practice_individual_tax_calculations ─────────────────────────────

CREATE INDEX IF NOT EXISTS idx_pitc_company
    ON practice_individual_tax_calculations(company_id)
    WHERE calculation_status != 'cancelled';

CREATE INDEX IF NOT EXISTS idx_pitc_return
    ON practice_individual_tax_calculations(tax_return_id);

CREATE INDEX IF NOT EXISTS idx_pitc_client
    ON practice_individual_tax_calculations(company_id, client_id);

CREATE INDEX IF NOT EXISTS idx_pitc_profile
    ON practice_individual_tax_calculations(taxpayer_profile_id);

CREATE INDEX IF NOT EXISTS idx_pitc_year
    ON practice_individual_tax_calculations(company_id, tax_year);

CREATE INDEX IF NOT EXISTS idx_pitc_status
    ON practice_individual_tax_calculations(company_id, calculation_status);

-- ── Indexes: practice_individual_tax_calculation_events ───────────────────────

CREATE INDEX IF NOT EXISTS idx_pitce_company
    ON practice_individual_tax_calculation_events(company_id);

CREATE INDEX IF NOT EXISTS idx_pitce_calc
    ON practice_individual_tax_calculation_events(calculation_id);

CREATE INDEX IF NOT EXISTS idx_pitce_return
    ON practice_individual_tax_calculation_events(tax_return_id);

CREATE INDEX IF NOT EXISTS idx_pitce_created
    ON practice_individual_tax_calculation_events(calculation_id, created_at DESC);
