-- ============================================================
-- Codebox 29: Tax Constant Tables + SARS Tax Year Configuration Foundation
-- Creates:
--   practice_tax_year_configs   — one config per tax year/country/scope
--   practice_tax_brackets       — one bracket row per bracket per config
--   practice_tax_config_events  — audit event log per config
--
-- DRAFT / REVIEW ONLY. Verify all values against SARS published rates.
-- company_id NULL = global/default config.
-- company_id SET  = practice-specific override (reserved for future use).
-- Run once in Supabase SQL Editor.
-- Expected result: "Success. No rows returned"
-- ============================================================

-- ── Table 1: Tax Year Configs ──────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS practice_tax_year_configs (
    id                              INTEGER      PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,

    -- NULL = global/default config; SET = practice-specific override
    company_id                      INTEGER      NULL,
    tax_year                        INTEGER      NOT NULL,
    config_name                     TEXT         NOT NULL,
    country_code                    TEXT         NOT NULL DEFAULT 'ZA',

    -- Lifecycle
    status                          TEXT         NOT NULL DEFAULT 'draft',
    -- draft | active | archived

    effective_from                  DATE         NULL,
    effective_to                    DATE         NULL,

    -- ── Thresholds (income below which no tax is payable) ──
    tax_threshold_under_65          NUMERIC(14,2) NULL,
    tax_threshold_65_to_74          NUMERIC(14,2) NULL,
    tax_threshold_75_plus           NUMERIC(14,2) NULL,

    -- ── Rebates ──
    primary_rebate                  NUMERIC(14,2) NULL,
    secondary_rebate                NUMERIC(14,2) NULL,   -- age 65+
    tertiary_rebate                 NUMERIC(14,2) NULL,   -- age 75+

    -- ── Medical tax credits (monthly per member) ──
    medical_credit_main_member      NUMERIC(14,2) NULL,
    medical_credit_first_dependent  NUMERIC(14,2) NULL,
    medical_credit_additional_dep   NUMERIC(14,2) NULL,

    -- ── Deduction limit placeholders ──
    -- RA: lower of 27.5% of taxable income OR R350,000 (example for 2024+)
    retirement_annuity_pct_limit    NUMERIC(8,4)  NULL,   -- e.g. 27.5000
    retirement_annuity_annual_cap   NUMERIC(14,2) NULL,   -- e.g. 350000.00

    -- s18A: up to 10% of taxable income
    donations_pct_limit             NUMERIC(8,4)  NULL,   -- e.g. 10.0000

    -- ── Metadata ──
    source_note                     TEXT         NULL,    -- e.g. "SARS Budget 2026"
    notes                           TEXT         NULL,
    settings                        JSONB        NOT NULL DEFAULT '{}',

    -- ── Review / lock trail ──
    reviewed_by                     INTEGER      NULL,
    reviewed_at                     TIMESTAMPTZ  NULL,
    locked_at                       TIMESTAMPTZ  NULL,
    locked_by                       INTEGER      NULL,

    -- ── Audit ──
    created_by                      INTEGER      NULL,
    updated_by                      INTEGER      NULL,
    created_at                      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at                      TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- ── Table 2: Tax Brackets ─────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS practice_tax_brackets (
    id              INTEGER      PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    company_id      INTEGER      NULL,
    config_id       INTEGER      NOT NULL,
    tax_year        INTEGER      NOT NULL,

    -- Order within this config: 1 = lowest bracket
    bracket_order   INTEGER      NOT NULL,

    -- Income range
    lower_bound     NUMERIC(14,2) NOT NULL,
    upper_bound     NUMERIC(14,2) NULL,          -- NULL = no upper limit (top bracket)

    -- Tax = base_tax + (income - lower_bound) * marginal_rate / 100
    base_tax        NUMERIC(14,2) NOT NULL DEFAULT 0,
    marginal_rate   NUMERIC(8,4)  NOT NULL,      -- stored as percentage, e.g. 18.0000

    notes           TEXT         NULL,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- ── Table 3: Config Events (audit log) ────────────────────────────────────────

CREATE TABLE IF NOT EXISTS practice_tax_config_events (
    id              INTEGER      PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    company_id      INTEGER      NULL,
    config_id       INTEGER      NOT NULL,

    event_type      TEXT         NOT NULL,
    -- config_created | config_updated | config_activated | config_archived
    -- | config_reviewed | config_locked | bracket_created | bracket_updated | bracket_deleted

    old_status      TEXT         NULL,
    new_status      TEXT         NULL,
    actor_user_id   INTEGER      NULL,
    notes           TEXT         NULL,
    metadata        JSONB        NOT NULL DEFAULT '{}',

    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- ── Indexes: practice_tax_year_configs ───────────────────────────────────────

CREATE INDEX IF NOT EXISTS idx_ptyc_company
    ON practice_tax_year_configs(company_id);

CREATE INDEX IF NOT EXISTS idx_ptyc_year
    ON practice_tax_year_configs(tax_year);

CREATE INDEX IF NOT EXISTS idx_ptyc_country
    ON practice_tax_year_configs(country_code);

CREATE INDEX IF NOT EXISTS idx_ptyc_status
    ON practice_tax_year_configs(status);

CREATE INDEX IF NOT EXISTS idx_ptyc_year_status
    ON practice_tax_year_configs(tax_year, status, country_code);

-- ── Indexes: practice_tax_brackets ───────────────────────────────────────────

CREATE INDEX IF NOT EXISTS idx_ptb_company
    ON practice_tax_brackets(company_id);

CREATE INDEX IF NOT EXISTS idx_ptb_config
    ON practice_tax_brackets(config_id);

CREATE INDEX IF NOT EXISTS idx_ptb_year
    ON practice_tax_brackets(tax_year);

CREATE INDEX IF NOT EXISTS idx_ptb_order
    ON practice_tax_brackets(config_id, bracket_order);

-- ── Indexes: practice_tax_config_events ──────────────────────────────────────

CREATE INDEX IF NOT EXISTS idx_ptce_config
    ON practice_tax_config_events(config_id);

CREATE INDEX IF NOT EXISTS idx_ptce_company
    ON practice_tax_config_events(company_id);

CREATE INDEX IF NOT EXISTS idx_ptce_created
    ON practice_tax_config_events(config_id, created_at DESC);
