-- ============================================================
-- Codebox 30: Individual Tax Review Pack + Draft Tax Report PDF
-- Creates:
--   practice_individual_tax_review_packs        — one pack per tax return / generation
--   practice_individual_tax_review_pack_events  — audit event log per pack
--
-- DRAFT / INTERNAL USE ONLY. Not SARS-final. Not eFiling.
-- All output requires accountant review before any use.
-- Run once in Supabase SQL Editor.
-- Expected result: "Success. No rows returned"
-- ============================================================

-- ── Table 1: Review Packs ─────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS practice_individual_tax_review_packs (
    id                          INTEGER      PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,

    -- Tenant + return context
    company_id                  INTEGER      NOT NULL,
    tax_return_id               INTEGER      NOT NULL,
    client_id                   INTEGER      NOT NULL,
    taxpayer_profile_id         INTEGER      NOT NULL,
    calculation_id              INTEGER      NULL,        -- nullable: pack may be generated before any calc

    tax_year                    INTEGER      NOT NULL,
    pack_name                   TEXT         NOT NULL,

    -- Lifecycle
    pack_status                 TEXT         NOT NULL DEFAULT 'draft',
    -- draft | generated | ready_for_review | reviewed | approved | rejected | cancelled

    -- Generation
    report_generated_at         TIMESTAMPTZ  NULL,
    report_generated_by         INTEGER      NULL,

    -- Review
    reviewer_team_member_id     INTEGER      NULL,
    reviewed_at                 TIMESTAMPTZ  NULL,
    reviewed_by                 INTEGER      NULL,
    approval_notes              TEXT         NULL,
    rejection_reason            TEXT         NULL,

    -- Data (immutable snapshot taken at generation time)
    warning_flags               JSONB        NOT NULL DEFAULT '[]',
    report_snapshot             JSONB        NOT NULL DEFAULT '{}',

    -- Audit
    created_at                  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at                  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by                  INTEGER      NULL,
    updated_by                  INTEGER      NULL
);

-- ── Table 2: Pack Events (audit log) ─────────────────────────────────────────

CREATE TABLE IF NOT EXISTS practice_individual_tax_review_pack_events (
    id                          INTEGER      PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,

    company_id                  INTEGER      NOT NULL,
    review_pack_id              INTEGER      NOT NULL,
    tax_return_id               INTEGER      NOT NULL,

    event_type                  TEXT         NOT NULL,
    -- individual_tax_review_pack_generated
    -- individual_tax_review_pack_report_viewed
    -- individual_tax_review_pack_submitted_review
    -- individual_tax_review_pack_approved
    -- individual_tax_review_pack_rejected
    -- individual_tax_review_pack_cancelled

    old_status                  TEXT         NULL,
    new_status                  TEXT         NULL,
    actor_user_id               INTEGER      NULL,
    notes                       TEXT         NULL,
    metadata                    JSONB        NOT NULL DEFAULT '{}',

    created_at                  TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- ── Indexes: practice_individual_tax_review_packs ─────────────────────────────

CREATE INDEX IF NOT EXISTS idx_pitrp_company
    ON practice_individual_tax_review_packs(company_id);

CREATE INDEX IF NOT EXISTS idx_pitrp_return
    ON practice_individual_tax_review_packs(tax_return_id);

CREATE INDEX IF NOT EXISTS idx_pitrp_client
    ON practice_individual_tax_review_packs(client_id);

CREATE INDEX IF NOT EXISTS idx_pitrp_profile
    ON practice_individual_tax_review_packs(taxpayer_profile_id);

CREATE INDEX IF NOT EXISTS idx_pitrp_calc
    ON practice_individual_tax_review_packs(calculation_id);

CREATE INDEX IF NOT EXISTS idx_pitrp_year
    ON practice_individual_tax_review_packs(tax_year);

CREATE INDEX IF NOT EXISTS idx_pitrp_status
    ON practice_individual_tax_review_packs(pack_status);

-- ── Indexes: practice_individual_tax_review_pack_events ──────────────────────

CREATE INDEX IF NOT EXISTS idx_pitrpe_pack
    ON practice_individual_tax_review_pack_events(review_pack_id);

CREATE INDEX IF NOT EXISTS idx_pitrpe_company
    ON practice_individual_tax_review_pack_events(company_id);

CREATE INDEX IF NOT EXISTS idx_pitrpe_created
    ON practice_individual_tax_review_pack_events(review_pack_id, created_at DESC);
