-- =============================================================================
-- 081_practice_company_tax_data.sql
-- Company Tax Data Capture Foundation (Codebox 31)
-- NOT company tax calculation. NOT ITR14 submission. NOT SARS integration.
-- Data capture + readiness only.
-- =============================================================================

-- ─── practice_company_tax_returns ────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS practice_company_tax_returns (
    id                              INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    company_id                      INTEGER NOT NULL,
    client_id                       INTEGER NOT NULL,
    taxpayer_profile_id             INTEGER NOT NULL,
    tax_year                        INTEGER NOT NULL,
    return_name                     TEXT    NOT NULL,
    financial_year_start            DATE    NULL,
    financial_year_end              DATE    NULL,
    status                          TEXT    NOT NULL DEFAULT 'draft',

    -- Readiness
    readiness_score                 INTEGER NULL,
    readiness_status                TEXT    NULL,

    -- AFS / accounting placeholders
    accounting_profit_loss          NUMERIC(14,2) NULL,
    turnover                        NUMERIC(14,2) NULL,
    cost_of_sales                   NUMERIC(14,2) NULL,
    gross_profit                    NUMERIC(14,2) NULL,
    operating_expenses              NUMERIC(14,2) NULL,
    finance_costs                   NUMERIC(14,2) NULL,
    other_income                    NUMERIC(14,2) NULL,

    -- Tax placeholders
    taxable_income_estimate         NUMERIC(14,2) NULL,
    assessed_loss_brought_forward   NUMERIC(14,2) NULL,
    assessed_loss_utilised          NUMERIC(14,2) NULL,
    assessed_loss_carried_forward   NUMERIC(14,2) NULL,

    -- Ownership
    responsible_team_member_id      INTEGER NULL,
    reviewer_team_member_id         INTEGER NULL,
    reviewed_at                     TIMESTAMPTZ NULL,
    reviewed_by                     INTEGER NULL,

    -- Links
    related_taxpayer_profile_id     INTEGER NULL,
    related_compliance_pack_id      INTEGER NULL,
    related_deadline_id             INTEGER NULL,
    related_workflow_run_id         BIGINT  NULL,
    related_provisional_tax_plan_id INTEGER NULL,

    -- Notes + settings
    notes                           TEXT    NULL,
    internal_notes                  TEXT    NULL,
    settings                        JSONB   NOT NULL DEFAULT '{}',

    -- Audit
    created_at                      TIMESTAMPTZ DEFAULT NOW(),
    updated_at                      TIMESTAMPTZ DEFAULT NOW(),
    created_by                      INTEGER NULL,
    updated_by                      INTEGER NULL,

    CONSTRAINT chk_pctr_status CHECK (status IN (
        'draft','collecting_docs','data_captured','ready_for_review',
        'reviewed','submitted','completed','cancelled'
    )),
    CONSTRAINT chk_pctr_readiness_status CHECK (readiness_status IS NULL OR readiness_status IN (
        'incomplete','partial','ready','blocked','unknown'
    ))
);

CREATE INDEX IF NOT EXISTS idx_pctr_company    ON practice_company_tax_returns(company_id);
CREATE INDEX IF NOT EXISTS idx_pctr_client     ON practice_company_tax_returns(client_id);
CREATE INDEX IF NOT EXISTS idx_pctr_profile    ON practice_company_tax_returns(taxpayer_profile_id);
CREATE INDEX IF NOT EXISTS idx_pctr_tax_year   ON practice_company_tax_returns(tax_year);
CREATE INDEX IF NOT EXISTS idx_pctr_status     ON practice_company_tax_returns(status);
CREATE INDEX IF NOT EXISTS idx_pctr_readiness  ON practice_company_tax_returns(readiness_status);
CREATE INDEX IF NOT EXISTS idx_pctr_fy_end     ON practice_company_tax_returns(financial_year_end);

-- ─── practice_company_tax_adjustments ────────────────────────────────────────
CREATE TABLE IF NOT EXISTS practice_company_tax_adjustments (
    id                              INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    company_id                      INTEGER NOT NULL,
    company_tax_return_id           INTEGER NOT NULL,
    adjustment_type                 TEXT    NOT NULL,
    adjustment_category             TEXT    NULL,
    description                     TEXT    NOT NULL,
    amount                          NUMERIC(14,2) NOT NULL DEFAULT 0,
    tax_effect                      TEXT    NULL,
    source_reference                TEXT    NULL,
    related_document_request_id     INTEGER NULL,
    notes                           TEXT    NULL,
    created_at                      TIMESTAMPTZ DEFAULT NOW(),
    updated_at                      TIMESTAMPTZ DEFAULT NOW(),

    CONSTRAINT chk_pcta_type CHECK (adjustment_type IN (
        'add_back','deduction','allowance','disallowance','assessed_loss',
        'capital_allowance','section_24c','doubtful_debt','donation','other'
    ))
);

CREATE INDEX IF NOT EXISTS idx_pcta_company    ON practice_company_tax_adjustments(company_id);
CREATE INDEX IF NOT EXISTS idx_pcta_return     ON practice_company_tax_adjustments(company_tax_return_id);
CREATE INDEX IF NOT EXISTS idx_pcta_type       ON practice_company_tax_adjustments(adjustment_type);

-- ─── practice_company_tax_readiness_items ────────────────────────────────────
CREATE TABLE IF NOT EXISTS practice_company_tax_readiness_items (
    id                              INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    company_id                      INTEGER NOT NULL,
    company_tax_return_id           INTEGER NOT NULL,
    item_type                       TEXT    NOT NULL,
    item_name                       TEXT    NOT NULL,
    status                          TEXT    NOT NULL DEFAULT 'required',
    required                        BOOLEAN NOT NULL DEFAULT TRUE,
    related_document_request_id     INTEGER NULL,
    notes                           TEXT    NULL,
    created_at                      TIMESTAMPTZ DEFAULT NOW(),
    updated_at                      TIMESTAMPTZ DEFAULT NOW(),

    CONSTRAINT chk_pctri_type CHECK (item_type IN (
        'afs','trial_balance','tax_computation','assessed_loss','provisional_tax',
        'sars_statement','fixed_assets','loan_accounts','supporting_document','review','custom'
    )),
    CONSTRAINT chk_pctri_status CHECK (status IN (
        'required','requested','received','captured','reviewed','waived','blocked','not_applicable'
    ))
);

CREATE INDEX IF NOT EXISTS idx_pctri_company   ON practice_company_tax_readiness_items(company_id);
CREATE INDEX IF NOT EXISTS idx_pctri_return    ON practice_company_tax_readiness_items(company_tax_return_id);
CREATE INDEX IF NOT EXISTS idx_pctri_type      ON practice_company_tax_readiness_items(item_type);
CREATE INDEX IF NOT EXISTS idx_pctri_status    ON practice_company_tax_readiness_items(status);

-- ─── practice_company_tax_events ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS practice_company_tax_events (
    id                              INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    company_id                      INTEGER NOT NULL,
    company_tax_return_id           INTEGER NOT NULL,
    event_type                      TEXT    NOT NULL,
    old_status                      TEXT    NULL,
    new_status                      TEXT    NULL,
    actor_user_id                   INTEGER NULL,
    notes                           TEXT    NULL,
    metadata                        JSONB   NOT NULL DEFAULT '{}',
    created_at                      TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_pcte_return     ON practice_company_tax_events(company_tax_return_id);
CREATE INDEX IF NOT EXISTS idx_pcte_company    ON practice_company_tax_events(company_id);
CREATE INDEX IF NOT EXISTS idx_pcte_created    ON practice_company_tax_events(created_at);
