-- =============================================================================
-- 082_practice_company_tax_calculations.sql
-- Company Tax Draft Calculation Engine Foundation (Codebox 32)
-- DRAFT/REVIEW ONLY. NOT SARS-final. NOT ITR14 submission. NOT eFiling.
-- All output requires accountant review before use.
-- Run once in Supabase SQL Editor.
-- Expected result: "Success. No rows returned"
-- =============================================================================

-- ─── practice_company_tax_calculations ───────────────────────────────────────
CREATE TABLE IF NOT EXISTS practice_company_tax_calculations (
    id                              INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    company_id                      INTEGER NOT NULL,
    company_tax_return_id           INTEGER NOT NULL,
    client_id                       INTEGER NOT NULL,
    taxpayer_profile_id             INTEGER NOT NULL,
    tax_year                        INTEGER NOT NULL,
    calculation_name                TEXT    NOT NULL,
    calculation_status              TEXT    NOT NULL DEFAULT 'draft',

    -- Input totals (all computed server-side from DB — never trust frontend totals)
    accounting_profit_loss          NUMERIC(14,2) NOT NULL DEFAULT 0,
    add_back_total                  NUMERIC(14,2) NOT NULL DEFAULT 0,
    deduction_total                 NUMERIC(14,2) NOT NULL DEFAULT 0,
    allowance_total                 NUMERIC(14,2) NOT NULL DEFAULT 0,
    disallowance_total              NUMERIC(14,2) NOT NULL DEFAULT 0,
    assessed_loss_brought_forward   NUMERIC(14,2) NOT NULL DEFAULT 0,
    assessed_loss_utilised          NUMERIC(14,2) NOT NULL DEFAULT 0,
    taxable_income_estimate         NUMERIC(14,2) NOT NULL DEFAULT 0,

    -- Tax components
    company_tax_rate                NUMERIC(8,4)  NULL,
    normal_tax_estimate             NUMERIC(14,2) NULL,
    provisional_tax_paid            NUMERIC(14,2) NULL,
    estimated_tax_payable           NUMERIC(14,2) NULL,
    estimated_refund                NUMERIC(14,2) NULL,

    -- Calculation metadata
    tax_config_source               TEXT    NULL,
    tax_config_version              TEXT    NULL,
    calculation_version             INTEGER NOT NULL DEFAULT 1,
    warning_flags                   JSONB   NOT NULL DEFAULT '[]',
    calculation_lines               JSONB   NOT NULL DEFAULT '[]',
    assumptions                     JSONB   NOT NULL DEFAULT '[]',

    -- Review / approval
    reviewed_at                     TIMESTAMPTZ NULL,
    reviewed_by                     INTEGER NULL,
    approved_at                     TIMESTAMPTZ NULL,
    approved_by                     INTEGER NULL,
    rejection_reason                TEXT    NULL,

    -- Notes
    notes                           TEXT    NULL,
    internal_notes                  TEXT    NULL,

    -- Audit
    created_at                      TIMESTAMPTZ DEFAULT NOW(),
    updated_at                      TIMESTAMPTZ DEFAULT NOW(),
    created_by                      INTEGER NULL,
    updated_by                      INTEGER NULL,

    CONSTRAINT chk_pctc_status CHECK (calculation_status IN (
        'draft','ready_for_review','reviewed','approved','rejected','cancelled'
    ))
);

CREATE INDEX IF NOT EXISTS idx_pctc_company    ON practice_company_tax_calculations(company_id);
CREATE INDEX IF NOT EXISTS idx_pctc_return     ON practice_company_tax_calculations(company_tax_return_id);
CREATE INDEX IF NOT EXISTS idx_pctc_client     ON practice_company_tax_calculations(client_id);
CREATE INDEX IF NOT EXISTS idx_pctc_profile    ON practice_company_tax_calculations(taxpayer_profile_id);
CREATE INDEX IF NOT EXISTS idx_pctc_tax_year   ON practice_company_tax_calculations(tax_year);
CREATE INDEX IF NOT EXISTS idx_pctc_status     ON practice_company_tax_calculations(calculation_status);

-- ─── practice_company_tax_calculation_events ─────────────────────────────────
CREATE TABLE IF NOT EXISTS practice_company_tax_calculation_events (
    id                              INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    company_id                      INTEGER NOT NULL,
    calculation_id                  INTEGER NOT NULL,
    company_tax_return_id           INTEGER NOT NULL,
    event_type                      TEXT    NOT NULL,
    old_status                      TEXT    NULL,
    new_status                      TEXT    NULL,
    actor_user_id                   INTEGER NULL,
    notes                           TEXT    NULL,
    metadata                        JSONB   NOT NULL DEFAULT '{}',
    created_at                      TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_pctce_calc      ON practice_company_tax_calculation_events(calculation_id);
CREATE INDEX IF NOT EXISTS idx_pctce_company   ON practice_company_tax_calculation_events(company_id);
CREATE INDEX IF NOT EXISTS idx_pctce_created   ON practice_company_tax_calculation_events(created_at);
