-- =============================================================================
-- 083_practice_company_tax_review_packs.sql
-- Company Tax Review Pack + Draft Report PDF (Codebox 33)
-- DRAFT/INTERNAL USE ONLY. NOT SARS-final. NOT ITR14 submission. NOT eFiling.
-- Stores immutable report snapshots. Source data changes do not affect packs.
-- Run once in Supabase SQL Editor.
-- Expected result: "Success. No rows returned"
-- =============================================================================

-- ─── practice_company_tax_review_packs ───────────────────────────────────────
CREATE TABLE IF NOT EXISTS practice_company_tax_review_packs (
    id                          INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    company_id                  INTEGER NOT NULL,
    company_tax_return_id       INTEGER NOT NULL,
    client_id                   INTEGER NOT NULL,
    taxpayer_profile_id         INTEGER NOT NULL,
    calculation_id              INTEGER NULL,
    tax_year                    INTEGER NOT NULL,
    pack_name                   TEXT    NOT NULL,
    pack_status                 TEXT    NOT NULL DEFAULT 'draft',

    -- Generation
    report_generated_at         TIMESTAMPTZ NULL,
    report_generated_by         INTEGER NULL,

    -- Review / approval
    reviewer_team_member_id     INTEGER NULL,
    reviewed_at                 TIMESTAMPTZ NULL,
    reviewed_by                 INTEGER NULL,
    approval_notes              TEXT    NULL,
    rejection_reason            TEXT    NULL,

    -- Report content (immutable snapshot — never changes after generation)
    warning_flags               JSONB   NOT NULL DEFAULT '[]',
    report_snapshot             JSONB   NOT NULL DEFAULT '{}',

    -- Audit
    created_at                  TIMESTAMPTZ DEFAULT NOW(),
    updated_at                  TIMESTAMPTZ DEFAULT NOW(),
    created_by                  INTEGER NULL,
    updated_by                  INTEGER NULL,

    CONSTRAINT chk_pctrp_status CHECK (pack_status IN (
        'draft', 'generated', 'ready_for_review', 'reviewed',
        'approved', 'rejected', 'cancelled'
    ))
);

CREATE INDEX IF NOT EXISTS idx_pctrp_company    ON practice_company_tax_review_packs(company_id);
CREATE INDEX IF NOT EXISTS idx_pctrp_return     ON practice_company_tax_review_packs(company_tax_return_id);
CREATE INDEX IF NOT EXISTS idx_pctrp_client     ON practice_company_tax_review_packs(client_id);
CREATE INDEX IF NOT EXISTS idx_pctrp_profile    ON practice_company_tax_review_packs(taxpayer_profile_id);
CREATE INDEX IF NOT EXISTS idx_pctrp_calc       ON practice_company_tax_review_packs(calculation_id);
CREATE INDEX IF NOT EXISTS idx_pctrp_tax_year   ON practice_company_tax_review_packs(tax_year);
CREATE INDEX IF NOT EXISTS idx_pctrp_status     ON practice_company_tax_review_packs(pack_status);

-- ─── practice_company_tax_review_pack_events ─────────────────────────────────
CREATE TABLE IF NOT EXISTS practice_company_tax_review_pack_events (
    id                          INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    company_id                  INTEGER NOT NULL,
    review_pack_id              INTEGER NOT NULL,
    company_tax_return_id       INTEGER NOT NULL,
    event_type                  TEXT    NOT NULL,
    old_status                  TEXT    NULL,
    new_status                  TEXT    NULL,
    actor_user_id               INTEGER NULL,
    notes                       TEXT    NULL,
    metadata                    JSONB   NOT NULL DEFAULT '{}',
    created_at                  TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_pctrpe_pack      ON practice_company_tax_review_pack_events(review_pack_id);
CREATE INDEX IF NOT EXISTS idx_pctrpe_company   ON practice_company_tax_review_pack_events(company_id);
CREATE INDEX IF NOT EXISTS idx_pctrpe_created   ON practice_company_tax_review_pack_events(created_at);
