-- ============================================================
-- Migration 084: Practice Tax Work Actions + Review Queue (Codebox 35)
-- Creates:
--   practice_tax_work_actions       — follow-up actions created from tax dashboard risks
--   practice_tax_work_action_events — append-only audit log for all action state changes
--
-- NOT tax calculation. NOT SARS. NOT automation. NOT Sean AI.
-- Tracks: open | in_progress | completed | dismissed | cancelled
-- Run once in Supabase SQL Editor.
-- Expected result: "Success. No rows returned"
-- ============================================================

-- ── Table 1: Tax Work Actions ─────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS practice_tax_work_actions (
    id                           INTEGER      PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    company_id                   INTEGER      NOT NULL,

    -- Source context (what tax item this action was created from)
    client_id                    INTEGER      NULL,
    source_type                  TEXT         NOT NULL,
    -- individual_return | company_return | provisional_plan
    -- individual_calculation | company_calculation
    -- individual_review_pack | company_review_pack
    -- compliance_deadline | document_request | tax_dashboard_risk
    source_id                    INTEGER      NOT NULL,

    -- Action definition
    action_type                  TEXT         NOT NULL,
    -- create_task | assign_owner | assign_reviewer | request_document
    -- generate_review_pack | run_calculation | submit_for_review | general_followup
    action_title                 TEXT         NOT NULL,

    -- Lifecycle
    action_status                TEXT         NOT NULL DEFAULT 'open',
    -- open | in_progress | completed | dismissed | cancelled

    -- Assignment
    assigned_team_member_id      INTEGER      NULL,
    due_date                     DATE         NULL,

    -- Linked output records (set once action is executed)
    linked_task_id               INTEGER      NULL,
    linked_document_request_id   INTEGER      NULL,
    linked_review_pack_id        INTEGER      NULL,

    -- Notes
    notes                        TEXT         NULL,

    -- Audit
    created_at                   TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at                   TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    created_by                   INTEGER      NULL,
    updated_by                   INTEGER      NULL,
    completed_at                 TIMESTAMPTZ  NULL,
    completed_by                 INTEGER      NULL,

    CONSTRAINT chk_ptwa_source_type CHECK (source_type IN (
        'individual_return', 'company_return', 'provisional_plan',
        'individual_calculation', 'company_calculation',
        'individual_review_pack', 'company_review_pack',
        'compliance_deadline', 'document_request', 'tax_dashboard_risk'
    )),
    CONSTRAINT chk_ptwa_action_type CHECK (action_type IN (
        'create_task', 'assign_owner', 'assign_reviewer', 'request_document',
        'generate_review_pack', 'run_calculation', 'submit_for_review', 'general_followup'
    )),
    CONSTRAINT chk_ptwa_action_status CHECK (action_status IN (
        'open', 'in_progress', 'completed', 'dismissed', 'cancelled'
    ))
);

-- ── Table 2: Tax Work Action Events (append-only audit log) ───────────────────

CREATE TABLE IF NOT EXISTS practice_tax_work_action_events (
    id              INTEGER      PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    company_id      INTEGER      NOT NULL,
    action_id       INTEGER      NULL,   -- nullable: preserves history if action is hard-deleted
    event_type      TEXT         NOT NULL,
    -- tax_action_created | tax_action_updated | tax_action_completed | tax_action_dismissed
    -- tax_action_cancelled | tax_action_task_created | tax_action_document_request_created
    -- tax_action_reviewer_assigned | tax_work_marked_ready_review
    old_status      TEXT         NULL,
    new_status      TEXT         NULL,
    actor_user_id   INTEGER      NULL,
    notes           TEXT         NULL,
    metadata        JSONB        NOT NULL DEFAULT '{}',
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

-- ── Indexes: practice_tax_work_actions ────────────────────────────────────────

CREATE INDEX IF NOT EXISTS idx_ptwa_company
    ON practice_tax_work_actions(company_id);

CREATE INDEX IF NOT EXISTS idx_ptwa_client
    ON practice_tax_work_actions(company_id, client_id)
    WHERE client_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_ptwa_source
    ON practice_tax_work_actions(company_id, source_type, source_id);

CREATE INDEX IF NOT EXISTS idx_ptwa_action_type
    ON practice_tax_work_actions(company_id, action_type);

CREATE INDEX IF NOT EXISTS idx_ptwa_action_status
    ON practice_tax_work_actions(company_id, action_status)
    WHERE action_status NOT IN ('cancelled', 'dismissed');

CREATE INDEX IF NOT EXISTS idx_ptwa_assignee
    ON practice_tax_work_actions(company_id, assigned_team_member_id)
    WHERE assigned_team_member_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_ptwa_due_date
    ON practice_tax_work_actions(company_id, due_date)
    WHERE due_date IS NOT NULL AND action_status = 'open';

-- ── Indexes: practice_tax_work_action_events ──────────────────────────────────

CREATE INDEX IF NOT EXISTS idx_ptwae_company
    ON practice_tax_work_action_events(company_id);

CREATE INDEX IF NOT EXISTS idx_ptwae_action
    ON practice_tax_work_action_events(action_id)
    WHERE action_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_ptwae_created_at
    ON practice_tax_work_action_events(company_id, created_at DESC);
