-- ============================================================
-- Migration 085: Practice Tax Checklist Templates (Codebox 36)
-- Creates:
--   practice_tax_checklist_templates       — reusable tax document checklist templates
--   practice_tax_checklist_template_items  — line items per template
--   practice_tax_checklist_template_events — append-only audit log
--
-- NOT document storage. NOT OCR. NOT SARS/eFiling. NOT AI.
-- Template-driven checklist generation only.
-- Run once in Supabase SQL Editor.
-- Expected result: "Success. No rows returned"
-- ============================================================

-- ── Table 1: Tax Checklist Templates ──────────────────────────────────────────

CREATE TABLE IF NOT EXISTS practice_tax_checklist_templates (
    id              INTEGER      PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    company_id      INTEGER      NOT NULL,

    template_name   TEXT         NOT NULL,
    template_type   TEXT         NOT NULL,
    -- individual_tax | company_tax | provisional_tax | annual_financials
    -- | vat_period | payroll_annual | cipc_annual | custom

    description     TEXT         NULL,

    -- Optional scope filters (null = applies to any)
    client_type     TEXT         NULL,
    -- individual | company | trust | close_corporation | partnership | sole_proprietor | other

    tax_year        INTEGER      NULL,   -- null = any year

    is_active       BOOLEAN      NOT NULL DEFAULT TRUE,
    is_default      BOOLEAN      NOT NULL DEFAULT FALSE, -- true for seeded defaults

    settings        JSONB        NOT NULL DEFAULT '{}',

    created_at      TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    created_by      INTEGER      NULL,
    updated_by      INTEGER      NULL,

    CONSTRAINT chk_ptct_template_type CHECK (template_type IN (
        'individual_tax', 'company_tax', 'provisional_tax', 'annual_financials',
        'vat_period', 'payroll_annual', 'cipc_annual', 'custom'
    )),
    CONSTRAINT chk_ptct_client_type CHECK (client_type IS NULL OR client_type IN (
        'individual', 'company', 'trust', 'close_corporation', 'partnership', 'sole_proprietor', 'other'
    ))
);

-- ── Table 2: Template Items ────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS practice_tax_checklist_template_items (
    id                      INTEGER      PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    company_id              INTEGER      NOT NULL,
    template_id             INTEGER      NOT NULL,

    item_name               TEXT         NOT NULL,
    item_description        TEXT         NULL,

    item_category           TEXT         NOT NULL DEFAULT 'document',
    -- document | tax_data | review | compliance | calculation | approval | custom

    target_type             TEXT         NOT NULL DEFAULT 'document_request',
    -- document_request | compliance_pack_item | individual_tax_item | company_tax_item

    required                BOOLEAN      NOT NULL DEFAULT TRUE,
    sort_order              INTEGER      NULL,
    default_due_offset_days INTEGER      NULL,  -- days from apply date → required_by_date

    -- Target-type-specific config stored in settings:
    --   document_request:   { document_category: 'tax'|'vat'|... }
    --   compliance_pack_item: { item_type: 'document'|'task'|'review'|... }
    --   individual_tax_item:  { item_type: 'irp5'|'document'|'custom'|... }
    --   company_tax_item:     { item_type: 'supporting_document'|'custom'|... }
    settings                JSONB        NOT NULL DEFAULT '{}',

    created_at              TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at              TIMESTAMPTZ  NOT NULL DEFAULT NOW(),

    CONSTRAINT chk_ptcti_item_category CHECK (item_category IN (
        'document', 'tax_data', 'review', 'compliance', 'calculation', 'approval', 'custom'
    )),
    CONSTRAINT chk_ptcti_target_type CHECK (target_type IN (
        'document_request', 'compliance_pack_item', 'individual_tax_item', 'company_tax_item'
    ))
);

-- ── Table 3: Template Events (append-only audit log) ──────────────────────────

CREATE TABLE IF NOT EXISTS practice_tax_checklist_template_events (
    id              INTEGER      PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    company_id      INTEGER      NOT NULL,
    template_id     INTEGER      NOT NULL,
    event_type      TEXT         NOT NULL,
    -- tax_checklist_template_created | tax_checklist_template_updated
    -- | tax_checklist_template_deactivated | tax_checklist_item_created
    -- | tax_checklist_item_updated | tax_checklist_applied
    -- | tax_checklist_defaults_seeded
    actor_user_id   INTEGER      NULL,
    notes           TEXT         NULL,
    metadata        JSONB        NOT NULL DEFAULT '{}',
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

-- ── Indexes: practice_tax_checklist_templates ─────────────────────────────────

CREATE INDEX IF NOT EXISTS idx_ptct_company
    ON practice_tax_checklist_templates(company_id);

CREATE INDEX IF NOT EXISTS idx_ptct_template_type
    ON practice_tax_checklist_templates(company_id, template_type)
    WHERE is_active = TRUE;

CREATE INDEX IF NOT EXISTS idx_ptct_client_type
    ON practice_tax_checklist_templates(company_id, client_type)
    WHERE client_type IS NOT NULL AND is_active = TRUE;

CREATE INDEX IF NOT EXISTS idx_ptct_is_active
    ON practice_tax_checklist_templates(company_id, is_active);

-- ── Indexes: practice_tax_checklist_template_items ────────────────────────────

CREATE INDEX IF NOT EXISTS idx_ptcti_template
    ON practice_tax_checklist_template_items(template_id);

CREATE INDEX IF NOT EXISTS idx_ptcti_company
    ON practice_tax_checklist_template_items(company_id);

CREATE INDEX IF NOT EXISTS idx_ptcti_target_type
    ON practice_tax_checklist_template_items(company_id, target_type);

-- ── Indexes: practice_tax_checklist_template_events ───────────────────────────

CREATE INDEX IF NOT EXISTS idx_ptcte_company
    ON practice_tax_checklist_template_events(company_id);

CREATE INDEX IF NOT EXISTS idx_ptcte_template
    ON practice_tax_checklist_template_events(template_id);

CREATE INDEX IF NOT EXISTS idx_ptcte_created_at
    ON practice_tax_checklist_template_events(company_id, created_at DESC);
