-- ============================================================
-- Migration 086: Practice Tax Bulk Operations Foundation (Codebox 37)
-- Creates:
--   practice_tax_bulk_operations       — operation definitions and results
--   practice_tax_bulk_operation_items  — per-client item results
--   practice_tax_bulk_operation_events — append-only audit log
--
-- NOT cron automation. NOT background execution. NOT SARS/eFiling.
-- User-triggered bulk preparation only.
-- Run once in Supabase SQL Editor.
-- Expected result: "Success. No rows returned"
-- ============================================================

-- ── Table 1: Bulk Operations ──────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS practice_tax_bulk_operations (
    id                  INTEGER      PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    company_id          INTEGER      NOT NULL,

    operation_name      TEXT         NOT NULL,
    operation_type      TEXT         NOT NULL,
    -- create_compliance_packs | apply_tax_checklist | create_document_requests
    -- | assign_tax_owners | assign_reviewers | create_tax_actions | mixed_tax_season_setup

    operation_status    TEXT         NOT NULL DEFAULT 'draft',
    -- draft | previewed | running | completed | completed_with_warnings | failed | cancelled

    tax_year            INTEGER      NULL,

    source_filter       JSONB        NOT NULL DEFAULT '{}',
    -- { client_type, responsible_team_member_id, provisional_taxpayer, has_active_engagement, missing_compliance_pack }

    options             JSONB        NOT NULL DEFAULT '{}',
    -- { compliance_pack_type, checklist_template_id, due_date, assign_responsible_team_member_id,
    --   assign_reviewer_team_member_id, override_existing, pack_period_start, pack_period_end,
    --   action_title, action_type }

    preview_snapshot    JSONB        NOT NULL DEFAULT '{}',
    -- { clients: [...], warnings: [...], estimated_outputs: {...}, client_count: N }

    result_summary      JSONB        NOT NULL DEFAULT '{}',
    -- { total, created, skipped, warnings, failed }

    started_at          TIMESTAMPTZ  NULL,
    completed_at        TIMESTAMPTZ  NULL,
    cancelled_at        TIMESTAMPTZ  NULL,

    created_by          INTEGER      NULL,
    updated_by          INTEGER      NULL,
    created_at          TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ  NOT NULL DEFAULT NOW(),

    CONSTRAINT chk_ptbo_operation_type CHECK (operation_type IN (
        'create_compliance_packs', 'apply_tax_checklist', 'create_document_requests',
        'assign_tax_owners', 'assign_reviewers', 'create_tax_actions', 'mixed_tax_season_setup'
    )),
    CONSTRAINT chk_ptbo_operation_status CHECK (operation_status IN (
        'draft', 'previewed', 'running', 'completed', 'completed_with_warnings', 'failed', 'cancelled'
    ))
);

-- ── Table 2: Per-Client Operation Items ────────────────────────────────────────

CREATE TABLE IF NOT EXISTS practice_tax_bulk_operation_items (
    id               INTEGER      PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    company_id       INTEGER      NOT NULL,
    operation_id     INTEGER      NOT NULL,
    client_id        INTEGER      NOT NULL,

    source_type      TEXT         NULL,
    source_id        INTEGER      NULL,

    item_status      TEXT         NOT NULL DEFAULT 'pending',
    -- pending | skipped | success | warning | failed

    message          TEXT         NULL,
    created_records  JSONB        NOT NULL DEFAULT '{}',
    error_detail     TEXT         NULL,

    created_at       TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at       TIMESTAMPTZ  NOT NULL DEFAULT NOW(),

    CONSTRAINT chk_ptboi_item_status CHECK (item_status IN (
        'pending', 'skipped', 'success', 'warning', 'failed'
    ))
);

-- ── Table 3: Bulk Operation Events (append-only audit log) ────────────────────

CREATE TABLE IF NOT EXISTS practice_tax_bulk_operation_events (
    id              INTEGER      PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    company_id      INTEGER      NOT NULL,
    operation_id    INTEGER      NOT NULL,
    event_type      TEXT         NOT NULL,
    actor_user_id   INTEGER      NULL,
    notes           TEXT         NULL,
    metadata        JSONB        NOT NULL DEFAULT '{}',
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

-- ── Indexes: practice_tax_bulk_operations ─────────────────────────────────────

CREATE INDEX IF NOT EXISTS idx_ptbo_company
    ON practice_tax_bulk_operations(company_id);

CREATE INDEX IF NOT EXISTS idx_ptbo_operation_type
    ON practice_tax_bulk_operations(company_id, operation_type);

CREATE INDEX IF NOT EXISTS idx_ptbo_operation_status
    ON practice_tax_bulk_operations(company_id, operation_status);

CREATE INDEX IF NOT EXISTS idx_ptbo_tax_year
    ON practice_tax_bulk_operations(company_id, tax_year)
    WHERE tax_year IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_ptbo_created_at
    ON practice_tax_bulk_operations(company_id, created_at DESC);

-- ── Indexes: practice_tax_bulk_operation_items ────────────────────────────────

CREATE INDEX IF NOT EXISTS idx_ptboi_operation
    ON practice_tax_bulk_operation_items(operation_id);

CREATE INDEX IF NOT EXISTS idx_ptboi_company
    ON practice_tax_bulk_operation_items(company_id);

CREATE INDEX IF NOT EXISTS idx_ptboi_client
    ON practice_tax_bulk_operation_items(company_id, client_id);

CREATE INDEX IF NOT EXISTS idx_ptboi_item_status
    ON practice_tax_bulk_operation_items(operation_id, item_status);

-- ── Indexes: practice_tax_bulk_operation_events ───────────────────────────────

CREATE INDEX IF NOT EXISTS idx_ptboe_company
    ON practice_tax_bulk_operation_events(company_id);

CREATE INDEX IF NOT EXISTS idx_ptboe_operation
    ON practice_tax_bulk_operation_events(operation_id);

CREATE INDEX IF NOT EXISTS idx_ptboe_created_at
    ON practice_tax_bulk_operation_events(company_id, created_at DESC);
