-- ============================================================
-- Migration 087: Practice Tax Reporting Snapshots (Codebox 38)
-- Creates:
--   practice_tax_reporting_snapshots — saved report snapshots for history/comparison
--
-- Optional table. Tax Reports work without it.
-- Only needed if POST /api/practice/tax-reports/snapshots is used.
-- Run once in Supabase SQL Editor.
-- Expected result: "Success. No rows returned"
-- ============================================================

CREATE TABLE IF NOT EXISTS practice_tax_reporting_snapshots (
    id              INTEGER      PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    company_id      INTEGER      NOT NULL,

    report_name     TEXT         NOT NULL,
    report_type     TEXT         NOT NULL,
    -- tax_season_progress | partner_summary | document_outstanding
    -- | review_bottleneck | bulk_operation_summary | risk_summary

    tax_year        INTEGER      NULL,
    filters         JSONB        NOT NULL DEFAULT '{}',
    report_data     JSONB        NOT NULL DEFAULT '{}',

    generated_at    TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    generated_by    INTEGER      NULL,
    notes           TEXT         NULL,

    CONSTRAINT chk_ptrs_report_type CHECK (report_type IN (
        'tax_season_progress', 'partner_summary', 'document_outstanding',
        'review_bottleneck', 'bulk_operation_summary', 'risk_summary'
    ))
);

CREATE INDEX IF NOT EXISTS idx_ptrs_company
    ON practice_tax_reporting_snapshots(company_id);

CREATE INDEX IF NOT EXISTS idx_ptrs_report_type
    ON practice_tax_reporting_snapshots(company_id, report_type);

CREATE INDEX IF NOT EXISTS idx_ptrs_generated_at
    ON practice_tax_reporting_snapshots(company_id, generated_at DESC);
