-- ============================================================
-- Migration 088: Practice Tax Filing Pipeline (Codebox 40)
-- Creates:
--   practice_tax_pipeline_events — append-only stage change audit log
-- Alters:
--   practice_individual_tax_returns  — adds filing_stage columns
--   practice_company_tax_returns     — adds filing_stage columns
--   practice_provisional_tax_plans   — adds filing_stage columns
--
-- Safe to run multiple times (IF NOT EXISTS / IF NOT ALREADY EXISTS).
-- Run once in Supabase SQL Editor.
-- Expected result: "Success. No rows returned"
-- ============================================================

-- ── 1. Pipeline Events table ──────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS practice_tax_pipeline_events (
    id              INTEGER      PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    company_id      INTEGER      NOT NULL,

    source_type     TEXT         NOT NULL,
    -- individual_tax_return | company_tax_return | provisional_tax_plan

    source_id       INTEGER      NOT NULL,

    old_stage       TEXT         NULL,
    new_stage       TEXT         NOT NULL,

    actor_user_id   INTEGER      NULL,
    notes           TEXT         NULL,
    metadata        JSONB        NOT NULL DEFAULT '{}',

    created_at      TIMESTAMPTZ  NOT NULL DEFAULT NOW(),

    CONSTRAINT chk_ptpe_source_type CHECK (source_type IN (
        'individual_tax_return',
        'company_tax_return',
        'provisional_tax_plan'
    )),
    CONSTRAINT chk_ptpe_new_stage CHECK (new_stage IN (
        'not_started', 'docs_requested', 'docs_received', 'data_captured',
        'calculation_completed', 'review_pack_generated', 'under_review',
        'ready_to_submit', 'submitted', 'completed', 'cancelled'
    ))
);

CREATE INDEX IF NOT EXISTS idx_ptpe_company
    ON practice_tax_pipeline_events(company_id);

CREATE INDEX IF NOT EXISTS idx_ptpe_source_type
    ON practice_tax_pipeline_events(company_id, source_type);

CREATE INDEX IF NOT EXISTS idx_ptpe_source_id
    ON practice_tax_pipeline_events(source_id, source_type);

CREATE INDEX IF NOT EXISTS idx_ptpe_new_stage
    ON practice_tax_pipeline_events(company_id, new_stage);

CREATE INDEX IF NOT EXISTS idx_ptpe_created_at
    ON practice_tax_pipeline_events(company_id, created_at DESC);

-- ── 2. Add filing_stage to individual tax returns ─────────────────────────────

ALTER TABLE practice_individual_tax_returns
    ADD COLUMN IF NOT EXISTS filing_stage            TEXT         NOT NULL DEFAULT 'not_started',
    ADD COLUMN IF NOT EXISTS filing_stage_updated_at TIMESTAMPTZ  NULL,
    ADD COLUMN IF NOT EXISTS filing_stage_updated_by INTEGER      NULL;

-- Add CHECK constraint for individual returns (safe: only adds if not already defined)
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.table_constraints
        WHERE table_name = 'practice_individual_tax_returns'
          AND constraint_name = 'chk_pitr_filing_stage'
    ) THEN
        ALTER TABLE practice_individual_tax_returns
            ADD CONSTRAINT chk_pitr_filing_stage CHECK (filing_stage IN (
                'not_started', 'docs_requested', 'docs_received', 'data_captured',
                'calculation_completed', 'review_pack_generated', 'under_review',
                'ready_to_submit', 'submitted', 'completed', 'cancelled'
            ));
    END IF;
END$$;

CREATE INDEX IF NOT EXISTS idx_pitr_filing_stage
    ON practice_individual_tax_returns(company_id, filing_stage)
    WHERE filing_stage NOT IN ('completed', 'cancelled');

-- ── 3. Add filing_stage to company tax returns ────────────────────────────────

ALTER TABLE practice_company_tax_returns
    ADD COLUMN IF NOT EXISTS filing_stage            TEXT         NOT NULL DEFAULT 'not_started',
    ADD COLUMN IF NOT EXISTS filing_stage_updated_at TIMESTAMPTZ  NULL,
    ADD COLUMN IF NOT EXISTS filing_stage_updated_by INTEGER      NULL;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.table_constraints
        WHERE table_name = 'practice_company_tax_returns'
          AND constraint_name = 'chk_pctr_filing_stage'
    ) THEN
        ALTER TABLE practice_company_tax_returns
            ADD CONSTRAINT chk_pctr_filing_stage CHECK (filing_stage IN (
                'not_started', 'docs_requested', 'docs_received', 'data_captured',
                'calculation_completed', 'review_pack_generated', 'under_review',
                'ready_to_submit', 'submitted', 'completed', 'cancelled'
            ));
    END IF;
END$$;

CREATE INDEX IF NOT EXISTS idx_pctr_filing_stage
    ON practice_company_tax_returns(company_id, filing_stage)
    WHERE filing_stage NOT IN ('completed', 'cancelled');

-- ── 4. Add filing_stage to provisional tax plans ──────────────────────────────

ALTER TABLE practice_provisional_tax_plans
    ADD COLUMN IF NOT EXISTS filing_stage            TEXT         NOT NULL DEFAULT 'not_started',
    ADD COLUMN IF NOT EXISTS filing_stage_updated_at TIMESTAMPTZ  NULL,
    ADD COLUMN IF NOT EXISTS filing_stage_updated_by INTEGER      NULL;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.table_constraints
        WHERE table_name = 'practice_provisional_tax_plans'
          AND constraint_name = 'chk_pptp_filing_stage'
    ) THEN
        ALTER TABLE practice_provisional_tax_plans
            ADD CONSTRAINT chk_pptp_filing_stage CHECK (filing_stage IN (
                'not_started', 'docs_requested', 'docs_received', 'data_captured',
                'calculation_completed', 'review_pack_generated', 'under_review',
                'ready_to_submit', 'submitted', 'completed', 'cancelled'
            ));
    END IF;
END$$;

CREATE INDEX IF NOT EXISTS idx_pptp_filing_stage
    ON practice_provisional_tax_plans(company_id, filing_stage)
    WHERE filing_stage NOT IN ('completed', 'cancelled');
