-- ============================================================
-- Migration 089: Tax Submission Register + Evidence Tracking (Codebox 41)
-- Creates:
--   practice_tax_submissions          — submission register (main table)
--   practice_tax_submission_evidence  — evidence records per submission
--   practice_tax_submission_events    — append-only audit log
--
-- Safe to run multiple times (IF NOT EXISTS guards throughout).
-- Run once in Supabase SQL Editor.
-- Expected result: "Success. No rows returned"
-- ============================================================

-- ── 1. Main Submission Register ───────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS practice_tax_submissions (
    id                              INTEGER      PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    company_id                      INTEGER      NOT NULL,
    client_id                       INTEGER      NOT NULL,

    -- Source entity
    source_type                     TEXT         NOT NULL,
    -- individual_tax_return | company_tax_return | provisional_tax_plan
    source_id                       INTEGER      NOT NULL,

    -- Tax context
    tax_year                        INTEGER      NULL,
    submission_type                 TEXT         NOT NULL,
    -- itr12 | itr14 | irp6_p1 | irp6_p2 | irp6_topup | emp501 | custom

    -- Lifecycle
    submission_status               TEXT         NOT NULL DEFAULT 'draft',
    -- draft | submitted | acknowledged | assessed | correction_required
    -- | objection_required | completed | cancelled

    -- Submission details
    submitted_at                    TIMESTAMPTZ  NULL,
    submitted_by_team_member_id     INTEGER      NULL,
    submission_method               TEXT         NULL,
    -- efiling | branch | email | manual | other
    submission_reference            TEXT         NULL,

    -- Acknowledgement
    acknowledgement_reference       TEXT         NULL,
    acknowledgement_received_at     TIMESTAMPTZ  NULL,

    -- Assessment
    assessment_received_at          TIMESTAMPTZ  NULL,
    assessment_reference            TEXT         NULL,
    assessment_outcome              TEXT         NULL,
    -- accepted | changed | additional_tax | refund | nil | disputed | unknown
    assessed_amount                 NUMERIC(14,2) NULL,
    refund_amount                   NUMERIC(14,2) NULL,
    amount_payable                  NUMERIC(14,2) NULL,
    payment_due_date                DATE         NULL,

    -- Cross-links (reference only — no FK constraints; cross-table)
    related_deadline_id             INTEGER      NULL,
    related_compliance_pack_id      INTEGER      NULL,
    related_workflow_run_id         BIGINT       NULL,
    related_review_pack_id          INTEGER      NULL,
    related_calculation_id          INTEGER      NULL,

    -- Evidence notes (free text — no file storage)
    evidence_summary                TEXT         NULL,
    acknowledgement_file_note       TEXT         NULL,
    assessment_file_note            TEXT         NULL,
    supporting_document_notes       TEXT         NULL,

    -- Follow-up
    follow_up_required              BOOLEAN      NOT NULL DEFAULT false,
    follow_up_due_date              DATE         NULL,
    follow_up_notes                 TEXT         NULL,
    responsible_team_member_id      INTEGER      NULL,

    -- Notes
    notes                           TEXT         NULL,
    internal_notes                  TEXT         NULL,
    settings                        JSONB        NOT NULL DEFAULT '{}',

    -- System
    created_at                      TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at                      TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    created_by                      INTEGER      NULL,
    updated_by                      INTEGER      NULL,

    CONSTRAINT chk_pts_source_type CHECK (source_type IN (
        'individual_tax_return', 'company_tax_return', 'provisional_tax_plan'
    )),
    CONSTRAINT chk_pts_submission_type CHECK (submission_type IN (
        'itr12', 'itr14', 'irp6_p1', 'irp6_p2', 'irp6_topup', 'emp501', 'custom'
    )),
    CONSTRAINT chk_pts_submission_status CHECK (submission_status IN (
        'draft', 'submitted', 'acknowledged', 'assessed',
        'correction_required', 'objection_required', 'completed', 'cancelled'
    )),
    CONSTRAINT chk_pts_submission_method CHECK (submission_method IS NULL OR submission_method IN (
        'efiling', 'branch', 'email', 'manual', 'other'
    )),
    CONSTRAINT chk_pts_assessment_outcome CHECK (assessment_outcome IS NULL OR assessment_outcome IN (
        'accepted', 'changed', 'additional_tax', 'refund', 'nil', 'disputed', 'unknown'
    ))
);

CREATE INDEX IF NOT EXISTS idx_pts_company        ON practice_tax_submissions(company_id);
CREATE INDEX IF NOT EXISTS idx_pts_client         ON practice_tax_submissions(company_id, client_id);
CREATE INDEX IF NOT EXISTS idx_pts_source_type    ON practice_tax_submissions(company_id, source_type);
CREATE INDEX IF NOT EXISTS idx_pts_source_id      ON practice_tax_submissions(source_id, source_type);
CREATE INDEX IF NOT EXISTS idx_pts_tax_year       ON practice_tax_submissions(company_id, tax_year);
CREATE INDEX IF NOT EXISTS idx_pts_sub_type       ON practice_tax_submissions(company_id, submission_type);
CREATE INDEX IF NOT EXISTS idx_pts_status         ON practice_tax_submissions(company_id, submission_status);
CREATE INDEX IF NOT EXISTS idx_pts_submitted_at   ON practice_tax_submissions(company_id, submitted_at);
CREATE INDEX IF NOT EXISTS idx_pts_payment_due    ON practice_tax_submissions(company_id, payment_due_date)
    WHERE payment_due_date IS NOT NULL AND submission_status NOT IN ('cancelled', 'completed');
CREATE INDEX IF NOT EXISTS idx_pts_responsible    ON practice_tax_submissions(company_id, responsible_team_member_id)
    WHERE responsible_team_member_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_pts_follow_up      ON practice_tax_submissions(company_id, follow_up_due_date)
    WHERE follow_up_required = true AND submission_status NOT IN ('cancelled', 'completed');

-- Auto-update updated_at on row change
CREATE OR REPLACE FUNCTION fn_pts_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS tg_pts_updated_at ON practice_tax_submissions;
CREATE TRIGGER tg_pts_updated_at
    BEFORE UPDATE ON practice_tax_submissions
    FOR EACH ROW EXECUTE FUNCTION fn_pts_updated_at();

-- ── 2. Evidence Records ───────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS practice_tax_submission_evidence (
    id                              INTEGER      PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    company_id                      INTEGER      NOT NULL,
    submission_id                   INTEGER      NOT NULL,

    evidence_type                   TEXT         NOT NULL,
    -- submission_confirmation | acknowledgement | assessment | payment_proof
    -- | supporting_document | correspondence | other

    evidence_title                  TEXT         NOT NULL,
    evidence_note                   TEXT         NULL,
    external_reference              TEXT         NULL,
    related_document_request_id     INTEGER      NULL,

    -- File metadata (no storage — notes/link only)
    uploaded_file_url               TEXT         NULL,
    file_name                       TEXT         NULL,
    file_mime_type                  TEXT         NULL,
    file_size_bytes                 INTEGER      NULL,

    -- Verification
    is_verified                     BOOLEAN      NOT NULL DEFAULT false,
    verified_at                     TIMESTAMPTZ  NULL,
    verified_by                     INTEGER      NULL,

    -- Soft delete
    is_deleted                      BOOLEAN      NOT NULL DEFAULT false,
    deleted_at                      TIMESTAMPTZ  NULL,
    deleted_by                      INTEGER      NULL,

    -- System
    created_at                      TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    created_by                      INTEGER      NULL,

    CONSTRAINT chk_ptse_evidence_type CHECK (evidence_type IN (
        'submission_confirmation', 'acknowledgement', 'assessment',
        'payment_proof', 'supporting_document', 'correspondence', 'other'
    ))
);

CREATE INDEX IF NOT EXISTS idx_ptse_company       ON practice_tax_submission_evidence(company_id);
CREATE INDEX IF NOT EXISTS idx_ptse_submission    ON practice_tax_submission_evidence(submission_id);
CREATE INDEX IF NOT EXISTS idx_ptse_type          ON practice_tax_submission_evidence(submission_id, evidence_type);
CREATE INDEX IF NOT EXISTS idx_ptse_verified      ON practice_tax_submission_evidence(submission_id, is_verified);
CREATE INDEX IF NOT EXISTS idx_ptse_doc_request   ON practice_tax_submission_evidence(related_document_request_id)
    WHERE related_document_request_id IS NOT NULL;

-- ── 3. Submission Events (audit log) ─────────────────────────────────────────

CREATE TABLE IF NOT EXISTS practice_tax_submission_events (
    id              INTEGER      PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    company_id      INTEGER      NOT NULL,
    submission_id   INTEGER      NOT NULL,
    event_type      TEXT         NOT NULL,
    -- submission_created | submission_updated | submission_marked_submitted
    -- | acknowledgement_recorded | assessment_recorded | evidence_added
    -- | evidence_verified | follow_up_set | submission_cancelled
    old_status      TEXT         NULL,
    new_status      TEXT         NULL,
    actor_user_id   INTEGER      NULL,
    notes           TEXT         NULL,
    metadata        JSONB        NOT NULL DEFAULT '{}',
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_ptcev_company      ON practice_tax_submission_events(company_id);
CREATE INDEX IF NOT EXISTS idx_ptcev_submission   ON practice_tax_submission_events(submission_id);
CREATE INDEX IF NOT EXISTS idx_ptcev_type         ON practice_tax_submission_events(submission_id, event_type);
CREATE INDEX IF NOT EXISTS idx_ptcev_created      ON practice_tax_submission_events(submission_id, created_at DESC);
