-- ============================================================
-- Migration 100: Tax Payment Tracking (Codebox 42)
-- Manual payment register linked to Tax Submissions.
-- NOT SARS integration. NOT bank reconciliation. NOT auto-import.
-- Everything here is manually entered by practice staff.
--
-- Creates:
--   practice_tax_payments         — one payment case per submission obligation
--   practice_tax_payment_events   — append-only log of every payment/refund/
--                                    interest/penalty movement against a case
--
-- Safe to run multiple times (IF NOT EXISTS guards throughout).
-- ============================================================

-- ── 1. Payment Cases ────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS practice_tax_payments (
    id                      INTEGER      PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    company_id              INTEGER      NOT NULL,
    client_id               INTEGER      NOT NULL,

    -- Link to the submission this payment case originates from (no FK — cross-table, matches 089 convention)
    submission_id           INTEGER      NOT NULL,
    tax_year                INTEGER      NULL,

    -- Direction: does the client owe SARS, or does SARS owe the client?
    direction               TEXT         NOT NULL,
    -- payable | refundable

    -- Running ledger (manually maintained via events, never recalculated from external sources)
    original_amount         NUMERIC(14,2) NOT NULL DEFAULT 0,
    interest_accrued        NUMERIC(14,2) NOT NULL DEFAULT 0,
    penalty_accrued         NUMERIC(14,2) NOT NULL DEFAULT 0,
    amount_settled          NUMERIC(14,2) NOT NULL DEFAULT 0,
    -- amount_settled = cumulative payments made (if payable) or cumulative refund received (if refundable)
    balance_outstanding     NUMERIC(14,2) NOT NULL DEFAULT 0,
    -- maintained by the application on every event:
    --   payable:    original_amount + interest_accrued + penalty_accrued - amount_settled
    --   refundable: original_amount - amount_settled

    status                  TEXT         NOT NULL DEFAULT 'outstanding',
    -- outstanding | partially_paid | paid_in_full | overpaid
    -- | refund_pending | refund_received | cancelled

    due_date                DATE         NULL,
    notes                   TEXT         NULL,
    internal_notes          TEXT         NULL,

    created_at              TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at              TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    created_by              INTEGER      NULL,
    updated_by              INTEGER      NULL,

    CONSTRAINT chk_ptp_direction CHECK (direction IN ('payable', 'refundable')),
    CONSTRAINT chk_ptp_status CHECK (status IN (
        'outstanding', 'partially_paid', 'paid_in_full', 'overpaid',
        'refund_pending', 'refund_received', 'cancelled'
    ))
);

CREATE INDEX IF NOT EXISTS idx_ptp_company      ON practice_tax_payments(company_id);
CREATE INDEX IF NOT EXISTS idx_ptp_client       ON practice_tax_payments(company_id, client_id);
CREATE INDEX IF NOT EXISTS idx_ptp_submission   ON practice_tax_payments(submission_id);
CREATE INDEX IF NOT EXISTS idx_ptp_status       ON practice_tax_payments(company_id, status);
CREATE INDEX IF NOT EXISTS idx_ptp_due_date     ON practice_tax_payments(company_id, due_date)
    WHERE due_date IS NOT NULL AND status NOT IN ('cancelled', 'paid_in_full', 'refund_received');

CREATE OR REPLACE FUNCTION fn_ptp_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS tg_ptp_updated_at ON practice_tax_payments;
CREATE TRIGGER tg_ptp_updated_at
    BEFORE UPDATE ON practice_tax_payments
    FOR EACH ROW EXECUTE FUNCTION fn_ptp_updated_at();

-- ── 2. Payment Events (append-only audit log) ──────────────────────────────

CREATE TABLE IF NOT EXISTS practice_tax_payment_events (
    id              INTEGER      PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    company_id      INTEGER      NOT NULL,
    payment_id      INTEGER      NOT NULL,

    event_type      TEXT         NOT NULL,
    -- payment_created | payment_recorded | refund_recorded
    -- | interest_added | penalty_added | payment_cancelled

    amount          NUMERIC(14,2) NULL,
    payment_date    DATE         NULL,
    payment_method  TEXT         NULL,
    -- eft | debit_order | cash | cheque | sars_efiling | other
    reference       TEXT         NULL,

    balance_before  NUMERIC(14,2) NULL,
    balance_after   NUMERIC(14,2) NULL,

    actor_user_id   INTEGER      NULL,
    notes           TEXT         NULL,
    metadata        JSONB        NOT NULL DEFAULT '{}',
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT NOW(),

    CONSTRAINT chk_ptpe_event_type CHECK (event_type IN (
        'payment_created', 'payment_recorded', 'refund_recorded',
        'interest_added', 'penalty_added', 'payment_cancelled'
    )),
    CONSTRAINT chk_ptpe_payment_method CHECK (payment_method IS NULL OR payment_method IN (
        'eft', 'debit_order', 'cash', 'cheque', 'sars_efiling', 'other'
    ))
);

CREATE INDEX IF NOT EXISTS idx_ptpe_company    ON practice_tax_payment_events(company_id);
CREATE INDEX IF NOT EXISTS idx_ptpe_payment    ON practice_tax_payment_events(payment_id);
CREATE INDEX IF NOT EXISTS idx_ptpe_type       ON practice_tax_payment_events(payment_id, event_type);
CREATE INDEX IF NOT EXISTS idx_ptpe_created    ON practice_tax_payment_events(payment_id, created_at DESC);

COMMENT ON TABLE practice_tax_payments IS
  'Manual tax payment register. One row per payable/refundable obligation linked to a practice_tax_submissions record. No SARS API, no bank integration — all entries are manually captured by practice staff.';
COMMENT ON TABLE practice_tax_payment_events IS
  'Append-only ledger of every payment, refund, interest, and penalty movement against a practice_tax_payments case. Never updated or deleted — full audit trail per SARS 7-year retention requirement.';
