-- ============================================================
-- Migration 101: SARS Statement Reconciliation (Codebox 43)
-- Manual statement-line capture and reconciliation against the
-- practice's own tax payment ledger (Codebox 42).
--
-- NOT SARS API.
-- NOT bank feed integration.
-- NOT automatic statement import.
-- Everything is manually entered by practice staff.
--
-- Creates:
--   practice_sars_statement_lines               — one row per SARS statement line
--   practice_sars_statement_reconciliation_events — append-only audit log of all
--                                                   status changes and match actions
--
-- Safe to run multiple times (IF NOT EXISTS guards throughout).
-- ============================================================

-- ── 1. SARS Statement Lines ─────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS practice_sars_statement_lines (
    id                      INTEGER      PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    company_id              INTEGER      NOT NULL,
    client_id               INTEGER      NOT NULL,

    -- Optional links to the submission and payment case this line relates to.
    -- Plain INTEGER — no FK constraint, matches the cross-table convention from
    -- migrations 089 and 100. Ownership is verified in application code.
    submission_id           INTEGER      NULL,
    payment_id              INTEGER      NULL,

    -- Statement line details (manually entered from SARS correspondence or eFiling)
    statement_date          DATE         NOT NULL,
    tax_type                TEXT         NOT NULL,
    -- itr12 | itr14 | irp6 | emp201 | emp501 | vat201 | other

    tax_year                INTEGER      NULL,
    period_label            TEXT         NULL,  -- e.g. "2025/03" or "2025 Feb"

    transaction_type        TEXT         NOT NULL,
    -- assessment | payment | refund | interest | penalty | adjustment | balance | other

    description             TEXT         NULL,
    reference_number        TEXT         NULL,

    -- Amounts: SARS uses a single-direction convention depending on transaction_type.
    -- We store debit and credit separately to mirror the actual SARS statement layout.
    -- For most transaction types only one of the two will be non-zero.
    debit_amount            NUMERIC(14,2) NOT NULL DEFAULT 0,
    credit_amount           NUMERIC(14,2) NOT NULL DEFAULT 0,

    -- Running balance as shown on the SARS statement (nil if not available).
    -- Negative = client owes SARS. Positive = SARS owes client.
    running_balance         NUMERIC(14,2) NULL,

    -- Reconciliation state
    reconciliation_status   TEXT         NOT NULL DEFAULT 'unmatched',
    -- unmatched | matched | partially_matched | disputed | ignored | cancelled

    -- Link to the practice_tax_payment_events row this line has been matched against.
    matched_payment_event_id INTEGER     NULL,
    matched_at              TIMESTAMPTZ  NULL,
    matched_by              INTEGER      NULL,

    notes                   TEXT         NULL,
    internal_notes          TEXT         NULL,

    created_at              TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at              TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    created_by              INTEGER      NULL,
    updated_by              INTEGER      NULL,

    CONSTRAINT chk_pssl_tax_type CHECK (tax_type IN (
        'itr12', 'itr14', 'irp6', 'emp201', 'emp501', 'vat201', 'other'
    )),
    CONSTRAINT chk_pssl_transaction_type CHECK (transaction_type IN (
        'assessment', 'payment', 'refund', 'interest', 'penalty',
        'adjustment', 'balance', 'other'
    )),
    CONSTRAINT chk_pssl_recon_status CHECK (reconciliation_status IN (
        'unmatched', 'matched', 'partially_matched', 'disputed', 'ignored', 'cancelled'
    )),
    CONSTRAINT chk_pssl_amounts_non_negative CHECK (
        debit_amount  >= 0 AND
        credit_amount >= 0
    )
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_pssl_company          ON practice_sars_statement_lines(company_id);
CREATE INDEX IF NOT EXISTS idx_pssl_client           ON practice_sars_statement_lines(company_id, client_id);
CREATE INDEX IF NOT EXISTS idx_pssl_submission       ON practice_sars_statement_lines(submission_id) WHERE submission_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_pssl_payment          ON practice_sars_statement_lines(payment_id) WHERE payment_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_pssl_date             ON practice_sars_statement_lines(company_id, statement_date DESC);
CREATE INDEX IF NOT EXISTS idx_pssl_tax_type         ON practice_sars_statement_lines(company_id, tax_type);
CREATE INDEX IF NOT EXISTS idx_pssl_transaction_type ON practice_sars_statement_lines(company_id, transaction_type);
CREATE INDEX IF NOT EXISTS idx_pssl_recon_status     ON practice_sars_statement_lines(company_id, reconciliation_status);
CREATE INDEX IF NOT EXISTS idx_pssl_reference        ON practice_sars_statement_lines(company_id, reference_number) WHERE reference_number IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_pssl_matched_event    ON practice_sars_statement_lines(matched_payment_event_id) WHERE matched_payment_event_id IS NOT NULL;

CREATE OR REPLACE FUNCTION fn_pssl_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS tg_pssl_updated_at ON practice_sars_statement_lines;
CREATE TRIGGER tg_pssl_updated_at
    BEFORE UPDATE ON practice_sars_statement_lines
    FOR EACH ROW EXECUTE FUNCTION fn_pssl_updated_at();

-- ── 2. Reconciliation Events (append-only audit log) ──────────────────────

CREATE TABLE IF NOT EXISTS practice_sars_statement_reconciliation_events (
    id                  INTEGER      PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    company_id          INTEGER      NOT NULL,
    statement_line_id   INTEGER      NOT NULL,

    event_type          TEXT         NOT NULL,
    -- sars_statement_line_created | sars_statement_line_updated
    -- | sars_statement_line_matched | sars_statement_line_unmatched
    -- | sars_statement_line_disputed | sars_statement_line_ignored
    -- | sars_statement_line_cancelled

    old_status          TEXT         NULL,
    new_status          TEXT         NULL,
    actor_user_id       INTEGER      NULL,
    notes               TEXT         NULL,
    metadata            JSONB        NOT NULL DEFAULT '{}',
    created_at          TIMESTAMPTZ  NOT NULL DEFAULT NOW(),

    CONSTRAINT chk_pssre_event_type CHECK (event_type IN (
        'sars_statement_line_created',
        'sars_statement_line_updated',
        'sars_statement_line_matched',
        'sars_statement_line_unmatched',
        'sars_statement_line_disputed',
        'sars_statement_line_ignored',
        'sars_statement_line_cancelled'
    ))
);

CREATE INDEX IF NOT EXISTS idx_pssre_company  ON practice_sars_statement_reconciliation_events(company_id);
CREATE INDEX IF NOT EXISTS idx_pssre_line     ON practice_sars_statement_reconciliation_events(statement_line_id);
CREATE INDEX IF NOT EXISTS idx_pssre_created  ON practice_sars_statement_reconciliation_events(statement_line_id, created_at DESC);

COMMENT ON TABLE practice_sars_statement_lines IS
  'Manual SARS statement register. One row per statement line as it appears on a SARS eFiling account statement or correspondence. Not connected to SARS API — all data is manually entered. Reconciled against practice_tax_payment_events rows from migration 100.';
COMMENT ON TABLE practice_sars_statement_reconciliation_events IS
  'Append-only audit log of all reconciliation actions (match, unmatch, dispute, ignore, cancel) against a practice_sars_statement_lines row. Never updated or deleted.';
