-- Migration 104: Practice Knowledge Base + Technical Opinion Library
-- Codebox 46 — Lorenco Practice Management
--
-- NOT AI-generated advice. NOT Sean AI. NOT automatic tax interpretation.
-- This is a HUMAN-CONTROLLED KNOWLEDGE LIBRARY.
--
-- Tables created (all IF NOT EXISTS — safe to re-run):
--   practice_knowledge_articles
--   practice_knowledge_links
--   practice_knowledge_events

-- ─────────────────────────────────────────────────────────────────────────────
-- TABLE: practice_knowledge_articles
-- One row per knowledge article — technical opinions, SARS interpretations,
-- internal policies, SOPs, working paper notes, client positions, etc.
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS practice_knowledge_articles (
    id                   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id           INTEGER NOT NULL,

    title                TEXT NOT NULL,

    category             TEXT NOT NULL CHECK (category IN (
                             'income_tax', 'company_tax', 'provisional_tax', 'vat', 'paye',
                             'payroll', 'cipc', 'coida', 'accounting', 'audit',
                             'secretarial', 'internal_policy', 'workflow', 'other'
                         )),

    article_type         TEXT NOT NULL CHECK (article_type IN (
                             'technical_opinion', 'sars_interpretation', 'internal_policy', 'sop',
                             'working_paper_note', 'client_position', 'checklist_note',
                             'template_note', 'general_note'
                         )),

    status                TEXT NOT NULL DEFAULT 'draft' CHECK (status IN (
                             'draft', 'under_review', 'approved', 'archived'
                         )),

    summary               TEXT,
    content               TEXT NOT NULL,
    tags                  JSONB NOT NULL DEFAULT '[]',

    effective_from        DATE,
    effective_to          DATE,

    reviewed_at           TIMESTAMPTZ,
    reviewed_by           INTEGER,
    approved_at           TIMESTAMPTZ,
    approved_by           INTEGER,

    version               INTEGER NOT NULL DEFAULT 1,

    source_reference      TEXT,
    internal_notes        TEXT,

    settings              JSONB NOT NULL DEFAULT '{}',

    created_at            TIMESTAMPTZ DEFAULT NOW(),
    updated_at            TIMESTAMPTZ DEFAULT NOW(),
    created_by            INTEGER,
    updated_by            INTEGER
);

CREATE INDEX IF NOT EXISTS idx_pka_company_id
    ON practice_knowledge_articles (company_id);

CREATE INDEX IF NOT EXISTS idx_pka_category
    ON practice_knowledge_articles (company_id, category);

CREATE INDEX IF NOT EXISTS idx_pka_article_type
    ON practice_knowledge_articles (company_id, article_type);

CREATE INDEX IF NOT EXISTS idx_pka_status
    ON practice_knowledge_articles (company_id, status);

CREATE INDEX IF NOT EXISTS idx_pka_title
    ON practice_knowledge_articles (company_id, title);

-- Auto-update updated_at
CREATE OR REPLACE FUNCTION fn_pka_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS tg_pka_updated_at ON practice_knowledge_articles;
CREATE TRIGGER tg_pka_updated_at
    BEFORE UPDATE ON practice_knowledge_articles
    FOR EACH ROW EXECUTE FUNCTION fn_pka_updated_at();

COMMENT ON TABLE practice_knowledge_articles IS
    'Codebox 46 — Human-authored practice knowledge base: technical opinions, SARS interpretations, internal policies, SOPs, working paper notes, client positions. NOT AI-generated. NOT Sean AI.';

-- ─────────────────────────────────────────────────────────────────────────────
-- TABLE: practice_knowledge_links
-- Links a knowledge article to a client, tax record, workflow, task, etc.
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS practice_knowledge_links (
    id                   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id           INTEGER NOT NULL,
    article_id           INTEGER NOT NULL,       -- plain integer, no FK (Codebox 41 convention)

    linked_type          TEXT NOT NULL CHECK (linked_type IN (
                             'client', 'taxpayer_profile', 'individual_tax_return', 'company_tax_return',
                             'provisional_tax_plan', 'tax_submission', 'sars_statement_line',
                             'tax_dispute', 'tax_completion_pack', 'workflow_run', 'task',
                             'document_request', 'compliance_pack'
                         )),
    linked_id            INTEGER NOT NULL,

    notes                TEXT,
    created_at           TIMESTAMPTZ DEFAULT NOW(),
    created_by           INTEGER,

    -- Prevent the same article being linked twice to the same record.
    CONSTRAINT uq_pkl_article_link UNIQUE (article_id, linked_type, linked_id)
);

CREATE INDEX IF NOT EXISTS idx_pkl_article_id
    ON practice_knowledge_links (article_id);

CREATE INDEX IF NOT EXISTS idx_pkl_linked_type
    ON practice_knowledge_links (company_id, linked_type);

CREATE INDEX IF NOT EXISTS idx_pkl_linked_id
    ON practice_knowledge_links (company_id, linked_type, linked_id);

COMMENT ON TABLE practice_knowledge_links IS
    'Codebox 46 — Links between knowledge articles and clients/tax records/workflows/tasks. One article can link to many records; a record can have many articles.';

-- ─────────────────────────────────────────────────────────────────────────────
-- TABLE: practice_knowledge_events  (append-only audit log)
-- Never updated. Never deleted.
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS practice_knowledge_events (
    id                   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id           INTEGER NOT NULL,
    article_id           INTEGER NOT NULL,       -- plain integer, no FK (Codebox 41 convention)

    event_type           TEXT NOT NULL,
    old_status           TEXT,
    new_status           TEXT,
    actor_user_id        INTEGER,
    notes                TEXT,
    metadata              JSONB NOT NULL DEFAULT '{}',
    created_at           TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_pke_article_id
    ON practice_knowledge_events (article_id);

CREATE INDEX IF NOT EXISTS idx_pke_company_article
    ON practice_knowledge_events (company_id, article_id);

CREATE INDEX IF NOT EXISTS idx_pke_created_desc
    ON practice_knowledge_events (created_at DESC);

COMMENT ON TABLE practice_knowledge_events IS
    'Codebox 46 — Append-only audit log for knowledge article lifecycle events (created, updated, submitted for review, approved, archived, linked, unlinked). Never updated or deleted.';
