-- Migration 105: Practice SOP Templates + Workflow Instruction Library
-- Codebox 47 — Lorenco Practice Management
--
-- NOT AI. NOT document management. NOT workflow execution.
-- This is the practice's operational instruction manual — HOW work must be performed.
--
-- Tables created (all IF NOT EXISTS — safe to re-run):
--   practice_sop_templates
--   practice_sop_links
--   practice_sop_events

-- ─────────────────────────────────────────────────────────────────────────────
-- TABLE: practice_sop_templates
-- One row per SOP — reusable instructions that attach to workflow templates,
-- workflow steps, tasks, review tasks, compliance packs, completion packs.
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS practice_sop_templates (
    id                   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id           INTEGER NOT NULL,

    title                TEXT NOT NULL,
    category             TEXT,                  -- free text — not enum-constrained (practice-defined groupings)

    status               TEXT NOT NULL DEFAULT 'draft' CHECK (status IN (
                             'draft', 'under_review', 'approved', 'archived'
                         )),

    summary              TEXT,
    instruction_body     TEXT NOT NULL,

    estimated_minutes    INTEGER,

    difficulty           TEXT CHECK (difficulty IS NULL OR difficulty IN (
                             'beginner', 'intermediate', 'advanced'
                         )),

    requires_review      BOOLEAN NOT NULL DEFAULT TRUE,

    version              INTEGER NOT NULL DEFAULT 1,

    effective_from       DATE,
    effective_to         DATE,

    reviewed_at          TIMESTAMPTZ,
    reviewed_by          INTEGER,
    approved_at          TIMESTAMPTZ,
    approved_by          INTEGER,

    internal_notes       TEXT,

    settings             JSONB NOT NULL DEFAULT '{}',

    created_at           TIMESTAMPTZ DEFAULT NOW(),
    updated_at           TIMESTAMPTZ DEFAULT NOW(),
    created_by           INTEGER,
    updated_by           INTEGER
);

CREATE INDEX IF NOT EXISTS idx_pst_company_id
    ON practice_sop_templates (company_id);

CREATE INDEX IF NOT EXISTS idx_pst_category
    ON practice_sop_templates (company_id, category);

CREATE INDEX IF NOT EXISTS idx_pst_status
    ON practice_sop_templates (company_id, status);

CREATE INDEX IF NOT EXISTS idx_pst_title
    ON practice_sop_templates (company_id, title);

-- Auto-update updated_at
CREATE OR REPLACE FUNCTION fn_pst_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS tg_pst_updated_at ON practice_sop_templates;
CREATE TRIGGER tg_pst_updated_at
    BEFORE UPDATE ON practice_sop_templates
    FOR EACH ROW EXECUTE FUNCTION fn_pst_updated_at();

COMMENT ON TABLE practice_sop_templates IS
    'Codebox 47 — Practice operational instruction manual: reusable SOP templates describing HOW work must be performed. NOT AI. NOT document management. NOT workflow execution.';

-- ─────────────────────────────────────────────────────────────────────────────
-- TABLE: practice_sop_links
-- Attaches an SOP to a workflow template, workflow step, task, review task,
-- compliance pack, completion pack, or knowledge article.
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS practice_sop_links (
    id                   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id           INTEGER NOT NULL,
    sop_id               INTEGER NOT NULL,       -- plain integer, no FK (Codebox 41 convention)

    linked_type          TEXT NOT NULL CHECK (linked_type IN (
                             'workflow_template', 'workflow_step', 'task', 'review_task',
                             'compliance_pack', 'completion_pack', 'knowledge_article'
                         )),
    linked_id            INTEGER NOT NULL,

    sort_order           INTEGER NOT NULL DEFAULT 0,
    notes                TEXT,
    created_at           TIMESTAMPTZ DEFAULT NOW(),
    created_by           INTEGER,

    -- Prevent the same SOP being linked twice to the same record.
    CONSTRAINT uq_psl_sop_link UNIQUE (sop_id, linked_type, linked_id)
);

CREATE INDEX IF NOT EXISTS idx_psl_sop_id
    ON practice_sop_links (sop_id);

CREATE INDEX IF NOT EXISTS idx_psl_linked_type
    ON practice_sop_links (company_id, linked_type);

CREATE INDEX IF NOT EXISTS idx_psl_linked_id
    ON practice_sop_links (company_id, linked_type, linked_id);

COMMENT ON TABLE practice_sop_links IS
    'Codebox 47 — Links between SOP templates and workflow templates/steps/tasks/review tasks/compliance packs/completion packs/knowledge articles. One SOP can attach to many records; a record can have many SOPs (ordered by sort_order).';

-- ─────────────────────────────────────────────────────────────────────────────
-- TABLE: practice_sop_events  (append-only audit log)
-- Never updated. Never deleted.
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS practice_sop_events (
    id                   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id           INTEGER NOT NULL,
    sop_id               INTEGER NOT NULL,       -- plain integer, no FK (Codebox 41 convention)

    event_type           TEXT NOT NULL,
    old_status           TEXT,
    new_status           TEXT,
    actor_user_id        INTEGER,
    notes                TEXT,
    metadata             JSONB NOT NULL DEFAULT '{}',
    created_at           TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_pse_sop_id
    ON practice_sop_events (sop_id);

CREATE INDEX IF NOT EXISTS idx_pse_company_sop
    ON practice_sop_events (company_id, sop_id);

CREATE INDEX IF NOT EXISTS idx_pse_created_desc
    ON practice_sop_events (created_at DESC);

COMMENT ON TABLE practice_sop_events IS
    'Codebox 47 — Append-only audit log for SOP lifecycle events (created, updated, submitted, approved, archived, linked, unlinked). Never updated or deleted.';
