-- Migration 106: Practice Quality Management System (QMS) Foundation
-- Codebox 48 — Lorenco Practice Management
--
-- NOT AI. NOT a disciplinary workflow. NOT Sean AI.
-- This is practice quality control — reviews, non-conformance findings, CAPA.
--
-- Tables created (all IF NOT EXISTS — safe to re-run):
--   practice_quality_reviews
--   practice_quality_findings
--   practice_quality_events

-- ─────────────────────────────────────────────────────────────────────────────
-- TABLE: practice_quality_reviews
-- One row per quality review — a task review, workflow review, tax review,
-- completion pack review, SOP compliance review, internal inspection, or
-- client file review.
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS practice_quality_reviews (
    id                            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id                    INTEGER NOT NULL,

    review_title                  TEXT NOT NULL,

    review_type                   TEXT NOT NULL CHECK (review_type IN (
                                      'task_review', 'workflow_review', 'tax_review',
                                      'completion_pack_review', 'sop_compliance_review',
                                      'internal_inspection', 'client_file_review', 'custom'
                                  )),

    -- Source record this review was generated from (optional — reviews may be
    -- manual/ad-hoc with no linked source, e.g. internal_inspection, custom).
    linked_type                   TEXT CHECK (linked_type IS NULL OR linked_type IN (
                                      'task', 'workflow', 'completion_pack', 'sop'
                                  )),
    linked_id                     INTEGER,          -- plain integer, no FK (Codebox 41 convention)

    client_id                     INTEGER,          -- plain integer, no FK — practice_clients

    assigned_reviewer_team_member_id INTEGER,       -- plain integer, no FK — practice_team_members

    status                        TEXT NOT NULL DEFAULT 'draft' CHECK (status IN (
                                      'draft', 'in_review', 'passed', 'failed',
                                      'needs_correction', 'completed', 'cancelled'
                                  )),

    quality_score                 INTEGER CHECK (quality_score IS NULL OR quality_score BETWEEN 0 AND 100),

    review_notes                  TEXT,

    reviewed_at                   TIMESTAMPTZ,
    reviewed_by                   INTEGER,

    created_at                    TIMESTAMPTZ DEFAULT NOW(),
    updated_at                    TIMESTAMPTZ DEFAULT NOW(),
    created_by                    INTEGER,
    updated_by                    INTEGER
);

CREATE INDEX IF NOT EXISTS idx_pqr_company_id
    ON practice_quality_reviews (company_id);

CREATE INDEX IF NOT EXISTS idx_pqr_review_type
    ON practice_quality_reviews (company_id, review_type);

CREATE INDEX IF NOT EXISTS idx_pqr_status
    ON practice_quality_reviews (company_id, status);

CREATE INDEX IF NOT EXISTS idx_pqr_linked
    ON practice_quality_reviews (company_id, linked_type, linked_id);

CREATE INDEX IF NOT EXISTS idx_pqr_client_id
    ON practice_quality_reviews (company_id, client_id);

-- Defense-in-depth duplicate guard: only one ACTIVE (non-terminal) review per
-- linked record. The application layer also checks this to return a friendly
-- 409 with the existing review id — this index guarantees it can never be
-- bypassed by a race condition.
CREATE UNIQUE INDEX IF NOT EXISTS uq_pqr_active_linked_review
    ON practice_quality_reviews (company_id, linked_type, linked_id)
    WHERE linked_type IS NOT NULL AND status NOT IN ('completed', 'cancelled');

-- Auto-update updated_at
CREATE OR REPLACE FUNCTION fn_pqr_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS tg_pqr_updated_at ON practice_quality_reviews;
CREATE TRIGGER tg_pqr_updated_at
    BEFORE UPDATE ON practice_quality_reviews
    FOR EACH ROW EXECUTE FUNCTION fn_pqr_updated_at();

COMMENT ON TABLE practice_quality_reviews IS
    'Codebox 48 — Practice quality reviews: task/workflow/tax/completion-pack/SOP-compliance reviews, internal inspections, client file reviews. NOT AI. NOT disciplinary workflow.';

-- ─────────────────────────────────────────────────────────────────────────────
-- TABLE: practice_quality_findings
-- Findings logged against a quality review — non-conformances, observations,
-- improvements, risks — with CAPA (corrective/preventive action) fields.
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS practice_quality_findings (
    id                        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id                INTEGER NOT NULL,
    review_id                 INTEGER NOT NULL,       -- plain integer, no FK (Codebox 41 convention)

    finding_type              TEXT NOT NULL CHECK (finding_type IN (
                                 'non_conformance', 'observation', 'improvement', 'risk',
                                 'missing_evidence', 'sop_not_followed', 'review_note', 'custom'
                             )),

    severity                  TEXT NOT NULL CHECK (severity IN (
                                 'low', 'medium', 'high', 'critical'
                             )),

    finding_title             TEXT NOT NULL,
    finding_description       TEXT,
    root_cause                TEXT,
    corrective_action         TEXT,
    preventive_action         TEXT,

    status                    TEXT NOT NULL DEFAULT 'open' CHECK (status IN (
                                 'open', 'in_progress', 'resolved', 'verified', 'dismissed', 'cancelled'
                             )),

    due_date                  DATE,
    responsible_team_member_id INTEGER,               -- plain integer, no FK — practice_team_members

    completed_at              TIMESTAMPTZ,
    completed_by              INTEGER,

    created_at                TIMESTAMPTZ DEFAULT NOW(),
    updated_at                TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_pqf_review_id
    ON practice_quality_findings (review_id);

CREATE INDEX IF NOT EXISTS idx_pqf_company_review
    ON practice_quality_findings (company_id, review_id);

CREATE INDEX IF NOT EXISTS idx_pqf_status
    ON practice_quality_findings (company_id, status);

CREATE INDEX IF NOT EXISTS idx_pqf_severity
    ON practice_quality_findings (company_id, severity);

-- Auto-update updated_at
CREATE OR REPLACE FUNCTION fn_pqf_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS tg_pqf_updated_at ON practice_quality_findings;
CREATE TRIGGER tg_pqf_updated_at
    BEFORE UPDATE ON practice_quality_findings
    FOR EACH ROW EXECUTE FUNCTION fn_pqf_updated_at();

COMMENT ON TABLE practice_quality_findings IS
    'Codebox 48 — Findings logged against a quality review, with CAPA (corrective_action / preventive_action) fields. NOT disciplinary — quality control only.';

-- ─────────────────────────────────────────────────────────────────────────────
-- TABLE: practice_quality_events  (append-only audit log)
-- Never updated. Never deleted.
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS practice_quality_events (
    id                   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id           INTEGER NOT NULL,
    review_id            INTEGER NOT NULL,       -- plain integer, no FK (Codebox 41 convention)
    finding_id           INTEGER,                -- plain integer, no FK — null for review-level events

    event_type           TEXT NOT NULL,
    old_status           TEXT,
    new_status           TEXT,
    actor_user_id         INTEGER,
    notes                 TEXT,
    metadata              JSONB NOT NULL DEFAULT '{}',
    created_at            TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_pqe_review_id
    ON practice_quality_events (review_id);

CREATE INDEX IF NOT EXISTS idx_pqe_finding_id
    ON practice_quality_events (finding_id)
    WHERE finding_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_pqe_company_review
    ON practice_quality_events (company_id, review_id);

CREATE INDEX IF NOT EXISTS idx_pqe_created_desc
    ON practice_quality_events (created_at DESC);

COMMENT ON TABLE practice_quality_events IS
    'Codebox 48 — Append-only audit log for quality review and finding lifecycle events. Never updated or deleted.';
