-- Migration 107: Practice Risk Register + Internal Control Matrix
-- Codebox 49 — Lorenco Practice Management
--
-- NOT enterprise risk software. This is internal practice governance.
--
-- Tables created (all IF NOT EXISTS — safe to re-run):
--   practice_risks
--   practice_risk_controls
--   practice_risk_reviews
--   practice_risk_events

-- ─────────────────────────────────────────────────────────────────────────────
-- TABLE: practice_risks
-- One row per identified risk — practice, client-service, operational,
-- compliance, infosec, fraud, or business continuity risk.
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS practice_risks (
    id                       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id               INTEGER NOT NULL,

    title                    TEXT NOT NULL,

    category                 TEXT NOT NULL CHECK (category IN (
                                 'operational', 'compliance', 'tax', 'payroll', 'finance',
                                 'cyber', 'privacy', 'fraud', 'business_continuity',
                                 'client_service', 'strategic', 'other'
                             )),

    status                   TEXT NOT NULL DEFAULT 'open' CHECK (status IN (
                                 'open', 'monitoring', 'mitigated', 'accepted', 'closed', 'cancelled'
                             )),

    owner_team_member_id     INTEGER,           -- plain integer, no FK — practice_team_members
    linked_client_id         INTEGER,           -- plain integer, no FK — practice_clients (optional)

    likelihood               INTEGER NOT NULL CHECK (likelihood BETWEEN 1 AND 5),
    impact                   INTEGER NOT NULL CHECK (impact BETWEEN 1 AND 5),

    -- Overall rating — always server-calculated as likelihood * impact (1-25).
    -- Never accepted from the client; recomputed on every likelihood/impact change.
    inherent_risk            INTEGER NOT NULL CHECK (inherent_risk BETWEEN 1 AND 25),

    -- Residual risk after controls are applied — manually assessed by staff
    -- (no automatic control-effectiveness discount formula at this stage).
    residual_risk            INTEGER CHECK (residual_risk IS NULL OR residual_risk BETWEEN 1 AND 25),

    review_frequency         TEXT NOT NULL DEFAULT 'annual' CHECK (review_frequency IN (
                                 'monthly', 'quarterly', 'biannual', 'annual', 'ad_hoc'
                             )),
    next_review_date         DATE,

    mitigation_plan          TEXT,
    contingency_plan         TEXT,
    monitoring_notes         TEXT,

    -- Provenance — set only when the risk was created from another module's
    -- record (Quality Finding, Knowledge Article, Tax Dispute, Completion Pack).
    -- A risk originates from at most ONE source, so this is a direct pair of
    -- columns rather than a separate many-to-many link table (contrast with
    -- Codebox 46/47's links tables, which attach ONE article/SOP to MANY records).
    source_type              TEXT CHECK (source_type IS NULL OR source_type IN (
                                 'quality_finding', 'knowledge_article', 'tax_dispute', 'completion_pack'
                             )),
    source_id                INTEGER,

    created_at               TIMESTAMPTZ DEFAULT NOW(),
    updated_at               TIMESTAMPTZ DEFAULT NOW(),
    created_by               INTEGER,
    updated_by               INTEGER
);

CREATE INDEX IF NOT EXISTS idx_prisk_company_id
    ON practice_risks (company_id);

CREATE INDEX IF NOT EXISTS idx_prisk_category
    ON practice_risks (company_id, category);

CREATE INDEX IF NOT EXISTS idx_prisk_status
    ON practice_risks (company_id, status);

CREATE INDEX IF NOT EXISTS idx_prisk_client
    ON practice_risks (company_id, linked_client_id);

CREATE INDEX IF NOT EXISTS idx_prisk_next_review
    ON practice_risks (company_id, next_review_date)
    WHERE next_review_date IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_prisk_source
    ON practice_risks (company_id, source_type, source_id)
    WHERE source_type IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_prisk_heatmap
    ON practice_risks (company_id, likelihood, impact);

-- Duplicate guard: no duplicate ACTIVE risk with the same (case-insensitive)
-- title + linked client. COALESCE sentinel (-1) makes NULL linked_client_id
-- values comparable so "no client" duplicates are also caught.
CREATE UNIQUE INDEX IF NOT EXISTS uq_prisk_active_title_client
    ON practice_risks (company_id, lower(title), COALESCE(linked_client_id, -1))
    WHERE status NOT IN ('closed', 'cancelled');

-- Auto-update updated_at
CREATE OR REPLACE FUNCTION fn_prisk_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS tg_prisk_updated_at ON practice_risks;
CREATE TRIGGER tg_prisk_updated_at
    BEFORE UPDATE ON practice_risks
    FOR EACH ROW EXECUTE FUNCTION fn_prisk_updated_at();

COMMENT ON TABLE practice_risks IS
    'Codebox 49 — Practice risk register: practice/client-service/operational/compliance/infosec/fraud/business-continuity risks. NOT enterprise risk software — internal practice governance.';

-- ─────────────────────────────────────────────────────────────────────────────
-- TABLE: practice_risk_controls
-- Internal Control Matrix — one or more controls per risk.
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS practice_risk_controls (
    id                    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id            INTEGER NOT NULL,
    risk_id               INTEGER NOT NULL,       -- plain integer, no FK (Codebox 41 convention)

    control_title         TEXT NOT NULL,
    control_type          TEXT,                   -- free text — e.g. preventive/detective/corrective/directive (practice-defined, not enum-constrained)
    owner_team_member_id  INTEGER,                -- plain integer, no FK — practice_team_members

    effectiveness         TEXT CHECK (effectiveness IS NULL OR effectiveness IN (
                              'ineffective', 'partially_effective', 'effective'
                          )),

    review_date           DATE,
    evidence_notes        TEXT,

    is_active             BOOLEAN NOT NULL DEFAULT TRUE,

    created_at            TIMESTAMPTZ DEFAULT NOW(),
    updated_at            TIMESTAMPTZ DEFAULT NOW(),
    created_by            INTEGER,
    updated_by            INTEGER
);

CREATE INDEX IF NOT EXISTS idx_prc_risk_id
    ON practice_risk_controls (risk_id);

CREATE INDEX IF NOT EXISTS idx_prc_company_risk
    ON practice_risk_controls (company_id, risk_id);

CREATE INDEX IF NOT EXISTS idx_prc_effectiveness
    ON practice_risk_controls (company_id, effectiveness);

-- Auto-update updated_at
CREATE OR REPLACE FUNCTION fn_prc_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS tg_prc_updated_at ON practice_risk_controls;
CREATE TRIGGER tg_prc_updated_at
    BEFORE UPDATE ON practice_risk_controls
    FOR EACH ROW EXECUTE FUNCTION fn_prc_updated_at();

COMMENT ON TABLE practice_risk_controls IS
    'Codebox 49 — Internal Control Matrix: controls mitigating a practice risk, with effectiveness assessment and evidence notes.';

-- ─────────────────────────────────────────────────────────────────────────────
-- TABLE: practice_risk_reviews
-- Review history — periodic re-assessment of a risk. Two-step: create (draft,
-- scheduled) then complete (assessment snapshot recorded).
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS practice_risk_reviews (
    id                        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id                INTEGER NOT NULL,
    risk_id                   INTEGER NOT NULL,       -- plain integer, no FK (Codebox 41 convention)

    review_status             TEXT NOT NULL DEFAULT 'draft' CHECK (review_status IN (
                                  'draft', 'completed', 'cancelled'
                              )),

    -- Snapshot of the assessment AT the time this review was completed —
    -- never modified after completion, so history is preserved even if the
    -- parent risk's current likelihood/impact/residual_risk change later.
    likelihood_at_review      INTEGER CHECK (likelihood_at_review IS NULL OR likelihood_at_review BETWEEN 1 AND 5),
    impact_at_review          INTEGER CHECK (impact_at_review     IS NULL OR impact_at_review     BETWEEN 1 AND 5),
    residual_risk_at_review   INTEGER CHECK (residual_risk_at_review IS NULL OR residual_risk_at_review BETWEEN 1 AND 25),

    review_notes              TEXT,
    next_review_date          DATE,

    reviewed_at               TIMESTAMPTZ,
    reviewed_by               INTEGER,

    created_at                TIMESTAMPTZ DEFAULT NOW(),
    updated_at                TIMESTAMPTZ DEFAULT NOW(),
    created_by                INTEGER
);

CREATE INDEX IF NOT EXISTS idx_prr_risk_id
    ON practice_risk_reviews (risk_id);

CREATE INDEX IF NOT EXISTS idx_prr_company_risk
    ON practice_risk_reviews (company_id, risk_id);

CREATE INDEX IF NOT EXISTS idx_prr_status
    ON practice_risk_reviews (company_id, review_status);

-- Auto-update updated_at
CREATE OR REPLACE FUNCTION fn_prr_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS tg_prr_updated_at ON practice_risk_reviews;
CREATE TRIGGER tg_prr_updated_at
    BEFORE UPDATE ON practice_risk_reviews
    FOR EACH ROW EXECUTE FUNCTION fn_prr_updated_at();

COMMENT ON TABLE practice_risk_reviews IS
    'Codebox 49 — Risk review history. Each row is a periodic re-assessment; snapshot fields are frozen once review_status = completed.';

-- ─────────────────────────────────────────────────────────────────────────────
-- TABLE: practice_risk_events  (append-only audit log)
-- Never updated. Never deleted.
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS practice_risk_events (
    id                   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id           INTEGER NOT NULL,
    risk_id              INTEGER NOT NULL,       -- plain integer, no FK (Codebox 41 convention)
    control_id           INTEGER,                -- plain integer, no FK — null for risk-level events
    review_id            INTEGER,                -- plain integer, no FK — null unless review-related

    event_type           TEXT NOT NULL,
    old_status           TEXT,
    new_status           TEXT,
    actor_user_id        INTEGER,
    notes                TEXT,
    metadata             JSONB NOT NULL DEFAULT '{}',
    created_at           TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_pre_risk_id
    ON practice_risk_events (risk_id);

CREATE INDEX IF NOT EXISTS idx_pre_company_risk
    ON practice_risk_events (company_id, risk_id);

CREATE INDEX IF NOT EXISTS idx_pre_created_desc
    ON practice_risk_events (created_at DESC);

COMMENT ON TABLE practice_risk_events IS
    'Codebox 49 — Append-only audit log for risk, control, and review lifecycle events. Never updated or deleted.';
