-- Migration 108: Practice KPI Engine + Historical Trend Analytics
-- Codebox 51 — Lorenco Practice Management
--
-- NOT AI. NOT forecasting. NOT predictive analytics.
-- This is deterministic KPI history only — snapshots of the Management
-- Dashboard (Codebox 50) captured over time so partners can see trends.
--
-- Tables created (all IF NOT EXISTS — safe to re-run):
--   practice_kpi_snapshots
--   practice_kpi_snapshot_events

-- ─────────────────────────────────────────────────────────────────────────────
-- TABLE: practice_kpi_snapshots
-- One row per captured KPI snapshot — a frozen copy of the Management
-- Dashboard's summary/alerts/partner-review/practice-score at a point in time.
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS practice_kpi_snapshots (
    id                   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id           INTEGER NOT NULL,

    snapshot_name        TEXT NOT NULL,

    snapshot_type        TEXT NOT NULL CHECK (snapshot_type IN (
                             'daily', 'weekly', 'monthly', 'quarterly', 'annual', 'manual'
                         )),

    period_start         DATE,
    period_end           DATE,
    period_key           TEXT,          -- e.g. '2026-07', '2026-Q3' — caller-defined, used for the duplicate guard

    source_dashboard     TEXT NOT NULL DEFAULT 'management_dashboard',

    -- Frozen copies of the four Management Dashboard payloads at capture time.
    -- Never recalculated after capture — that would defeat the purpose of a
    -- historical record. See kpi-history.js for the exact shape of each.
    kpi_data             JSONB NOT NULL DEFAULT '{}',    -- computeSummary() output
    score_data           JSONB NOT NULL DEFAULT '{}',    -- computePracticeScore() output
    alert_data           JSONB NOT NULL DEFAULT '{}',    -- computeAlerts() output
    partner_queue_data   JSONB NOT NULL DEFAULT '{}',    -- computePartnerReview() output

    generated_at         TIMESTAMPTZ DEFAULT NOW(),
    generated_by         INTEGER,

    -- Deviation from the literal spec (documented in the completion report):
    -- 'status' was added so DELETE can archive instead of hard-deleting, per
    -- the spec's own stated preference ("Preferred: Add status field ... and
    -- archive instead of hard delete"). Also required for force-recapture:
    -- the unique guard below only applies to 'active' rows, so archiving a
    -- superseded snapshot frees its period_key for a fresh capture without
    -- ever losing the old snapshot's historical data.
    status               TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'archived')),

    notes                TEXT,
    settings             JSONB NOT NULL DEFAULT '{}',

    created_at           TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_pks_company_id
    ON practice_kpi_snapshots (company_id);

CREATE INDEX IF NOT EXISTS idx_pks_snapshot_type
    ON practice_kpi_snapshots (company_id, snapshot_type);

CREATE INDEX IF NOT EXISTS idx_pks_period_key
    ON practice_kpi_snapshots (company_id, period_key)
    WHERE period_key IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_pks_generated_at
    ON practice_kpi_snapshots (company_id, generated_at DESC);

CREATE INDEX IF NOT EXISTS idx_pks_source_dashboard
    ON practice_kpi_snapshots (company_id, source_dashboard);

CREATE INDEX IF NOT EXISTS idx_pks_status
    ON practice_kpi_snapshots (company_id, status);

-- Unique guard (spec: company_id + source_dashboard + snapshot_type + period_key,
-- where period_key is not null). Scoped to status = 'active' so an archived
-- (superseded) snapshot never blocks a fresh capture for the same period —
-- see the 'status' comment above for why this was necessary.
CREATE UNIQUE INDEX IF NOT EXISTS uq_pks_active_period
    ON practice_kpi_snapshots (company_id, source_dashboard, snapshot_type, period_key)
    WHERE period_key IS NOT NULL AND status = 'active';

COMMENT ON TABLE practice_kpi_snapshots IS
    'Codebox 51 — Deterministic KPI history: frozen snapshots of the Management Dashboard (Codebox 50) captured over time. NOT AI. NOT forecasting.';

-- ─────────────────────────────────────────────────────────────────────────────
-- TABLE: practice_kpi_snapshot_events  (append-only audit log)
-- Never updated. Never deleted.
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS practice_kpi_snapshot_events (
    id                   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id           INTEGER NOT NULL,
    snapshot_id          INTEGER NOT NULL,       -- plain integer, no FK (Codebox 41 convention)

    event_type           TEXT NOT NULL,
    actor_user_id        INTEGER,
    notes                TEXT,
    metadata             JSONB NOT NULL DEFAULT '{}',
    created_at           TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_pkse_snapshot_id
    ON practice_kpi_snapshot_events (snapshot_id);

CREATE INDEX IF NOT EXISTS idx_pkse_company_snapshot
    ON practice_kpi_snapshot_events (company_id, snapshot_id);

CREATE INDEX IF NOT EXISTS idx_pkse_created_desc
    ON practice_kpi_snapshot_events (created_at DESC);

COMMENT ON TABLE practice_kpi_snapshot_events IS
    'Codebox 51 — Append-only audit log for KPI snapshot lifecycle events (captured, archived, compared, trend viewed). Never updated or deleted.';
