-- Migration 109: Practice Partner Monthly Review Pack
-- Codebox 52 — Lorenco Practice Management
--
-- NOT AI. NOT forecasting. NOT automated email reporting.
-- Deterministic management reporting and partner sign-off only.
--
-- Tables created (all IF NOT EXISTS — safe to re-run):
--   practice_partner_review_packs
--   practice_partner_review_pack_events

-- ─────────────────────────────────────────────────────────────────────────────
-- TABLE: practice_partner_review_packs
-- One row per generated monthly (or ad-hoc) partner review pack — a frozen
-- report built from the Management Dashboard (Codebox 50) and KPI History
-- (Codebox 51), carried through a partner sign-off workflow.
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS practice_partner_review_packs (
    id                    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id            INTEGER NOT NULL,

    pack_name             TEXT NOT NULL,

    pack_status           TEXT NOT NULL DEFAULT 'draft' CHECK (pack_status IN (
                              'draft', 'generated', 'under_review', 'approved',
                              'rejected', 'archived', 'cancelled'
                          )),

    review_period_start   DATE NOT NULL,
    review_period_end     DATE NOT NULL,
    period_key            TEXT,          -- e.g. '2026-07' — caller-defined, used for the duplicate guard

    snapshot_start_id     INTEGER,       -- plain integer, no FK — practice_kpi_snapshots
    snapshot_end_id       INTEGER,       -- plain integer, no FK — practice_kpi_snapshots

    -- Frozen report content, built once at generation time and never
    -- recalculated — see partner-review-packs.js for the exact shape.
    -- This is what makes the pack a stable historical record even if the
    -- underlying KPI/risk/tax/etc. data changes afterwards.
    report_snapshot       JSONB NOT NULL DEFAULT '{}',

    executive_summary     TEXT,
    partner_notes         TEXT,

    prepared_by           INTEGER,
    prepared_at           TIMESTAMPTZ,
    reviewed_by           INTEGER,
    reviewed_at           TIMESTAMPTZ,
    approved_by           INTEGER,
    approved_at           TIMESTAMPTZ,
    rejection_reason      TEXT,

    settings              JSONB NOT NULL DEFAULT '{}',

    created_at            TIMESTAMPTZ DEFAULT NOW(),
    updated_at            TIMESTAMPTZ DEFAULT NOW(),
    created_by            INTEGER,
    updated_by            INTEGER
);

CREATE INDEX IF NOT EXISTS idx_pprp_company_id
    ON practice_partner_review_packs (company_id);

CREATE INDEX IF NOT EXISTS idx_pprp_pack_status
    ON practice_partner_review_packs (company_id, pack_status);

CREATE INDEX IF NOT EXISTS idx_pprp_period_key
    ON practice_partner_review_packs (company_id, period_key)
    WHERE period_key IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_pprp_review_period_start
    ON practice_partner_review_packs (company_id, review_period_start);

CREATE INDEX IF NOT EXISTS idx_pprp_review_period_end
    ON practice_partner_review_packs (company_id, review_period_end);

CREATE INDEX IF NOT EXISTS idx_pprp_snapshot_start_id
    ON practice_partner_review_packs (snapshot_start_id)
    WHERE snapshot_start_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_pprp_snapshot_end_id
    ON practice_partner_review_packs (snapshot_end_id)
    WHERE snapshot_end_id IS NOT NULL;

-- Duplicate guard (not explicitly requested as a named index in the spec,
-- but required to implement the spec's own rule: "duplicate active pack for
-- same period_key should return 409 unless force=true"). Scoped to the
-- non-terminal statuses so a cancelled/archived pack never blocks a fresh
-- generation for the same period — see partner-review-packs.js for how
-- force=true supersedes (cancels) rather than overwrites the old pack.
CREATE UNIQUE INDEX IF NOT EXISTS uq_pprp_active_period
    ON practice_partner_review_packs (company_id, period_key)
    WHERE period_key IS NOT NULL AND pack_status NOT IN ('cancelled', 'archived');

-- Auto-update updated_at
CREATE OR REPLACE FUNCTION fn_pprp_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS tg_pprp_updated_at ON practice_partner_review_packs;
CREATE TRIGGER tg_pprp_updated_at
    BEFORE UPDATE ON practice_partner_review_packs
    FOR EACH ROW EXECUTE FUNCTION fn_pprp_updated_at();

COMMENT ON TABLE practice_partner_review_packs IS
    'Codebox 52 — Monthly partner review packs: frozen management reports built from the Management Dashboard and KPI History, carried through a partner sign-off workflow. NOT AI. NOT forecasting. NOT automated email reporting.';

-- ─────────────────────────────────────────────────────────────────────────────
-- TABLE: practice_partner_review_pack_events  (append-only audit log)
-- Never updated. Never deleted.
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS practice_partner_review_pack_events (
    id                   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id           INTEGER NOT NULL,
    pack_id              INTEGER NOT NULL,       -- plain integer, no FK (Codebox 41 convention)

    event_type           TEXT NOT NULL,
    old_status           TEXT,
    new_status           TEXT,
    actor_user_id        INTEGER,
    notes                TEXT,
    metadata             JSONB NOT NULL DEFAULT '{}',
    created_at           TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_pprpe_pack_id
    ON practice_partner_review_pack_events (pack_id);

CREATE INDEX IF NOT EXISTS idx_pprpe_company_pack
    ON practice_partner_review_pack_events (company_id, pack_id);

CREATE INDEX IF NOT EXISTS idx_pprpe_created_desc
    ON practice_partner_review_pack_events (created_at DESC);

COMMENT ON TABLE practice_partner_review_pack_events IS
    'Codebox 52 — Append-only audit log for partner review pack lifecycle events (generated, updated, submitted, approved, rejected, cancelled, report viewed, PDF downloaded). Never updated or deleted.';
