-- Migration 110: Practice Alert Rules Engine
-- Codebox 53 — Lorenco Practice Management
--
-- NOT AI. NOT automatic threshold tuning. NOT machine learning.
-- Deterministic, database-driven alert thresholds only.
--
-- Tables created (all IF NOT EXISTS — safe to re-run):
--   practice_alert_rule_groups
--   practice_alert_rules
--   practice_alert_rule_events

-- ─────────────────────────────────────────────────────────────────────────────
-- TABLE: practice_alert_rule_groups
-- Organizational categories for rules (Risk, Tax, Capacity, QMS, ...).
-- Per-company (not global) so each practice's group list/ordering is its own —
-- consistent with the rest of the schema's multi-tenant convention and avoids
-- a shared cross-tenant config table.
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS practice_alert_rule_groups (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id    INTEGER NOT NULL,

    group_key     TEXT NOT NULL,        -- e.g. 'risk', 'tax', 'capacity'
    display_name  TEXT NOT NULL,
    description   TEXT,
    sort_order    INTEGER NOT NULL DEFAULT 0,

    created_at    TIMESTAMPTZ DEFAULT NOW(),
    updated_at    TIMESTAMPTZ DEFAULT NOW(),
    created_by    INTEGER,
    updated_by    INTEGER
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_pargp_company_key
    ON practice_alert_rule_groups (company_id, group_key);

CREATE INDEX IF NOT EXISTS idx_pargp_company_id
    ON practice_alert_rule_groups (company_id);

COMMENT ON TABLE practice_alert_rule_groups IS
    'Codebox 53 — Organizational categories for alert rules (Risk, Tax, Capacity, QMS, Client Health, Compliance, Documents, Reminders, Communications, Knowledge, SOP, Billing). Per-company.';

-- ─────────────────────────────────────────────────────────────────────────────
-- TABLE: practice_alert_rules
-- One row per configurable threshold. This is the single source of truth
-- consulted by getRule()/getRules() — see alert-rules.js.
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS practice_alert_rules (
    id                    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id            INTEGER NOT NULL,
    group_id              INTEGER,       -- plain integer, no FK — practice_alert_rule_groups (Codebox 41 convention)

    rule_key              TEXT NOT NULL,
    category              TEXT NOT NULL,  -- denormalized copy of the owning group's group_key — avoids a join for the common "get by key" lookup

    display_name          TEXT NOT NULL,
    description            TEXT,

    comparison_operator   TEXT NOT NULL CHECK (comparison_operator IN (
                              '>', '>=', '<', '<=', '=', '!=', 'between', 'contains'
                          )),

    threshold_value       NUMERIC,        -- primary numeric threshold (used by >,>=,<,<=,between-low)
    warning_value         NUMERIC,        -- secondary/lower threshold for a pre-warning band (e.g. high vs critical); also used as between-high

    threshold_text        TEXT,           -- used only by the 'contains'/'=' operators when the match target is a status/enum string, not a number

    severity              TEXT NOT NULL CHECK (severity IN ('info', 'low', 'medium', 'high', 'critical')),

    enabled               BOOLEAN NOT NULL DEFAULT true,
    editable              BOOLEAN NOT NULL DEFAULT true,
    system_rule           BOOLEAN NOT NULL DEFAULT false,   -- system rules cannot be deleted (may still be edited/reset if editable=true)

    default_value         NUMERIC,        -- original seed threshold_value — used to restore on Reset Rule
    default_warning_value NUMERIC,        -- original seed warning_value
    default_threshold_text TEXT,          -- original seed threshold_text
    default_severity      TEXT,           -- original seed severity
    default_enabled        BOOLEAN,       -- original seed enabled flag

    sort_order            INTEGER NOT NULL DEFAULT 0,
    settings               JSONB NOT NULL DEFAULT '{}',   -- unit ('points'|'percent'|'days'|'ratio'), min_value, max_value, maps_to (doc-only pointer to consuming code)

    version                INTEGER NOT NULL DEFAULT 1,     -- incremented on every edit/reset — success criterion "Rules versioned"

    created_at            TIMESTAMPTZ DEFAULT NOW(),
    updated_at            TIMESTAMPTZ DEFAULT NOW(),
    created_by            INTEGER,
    updated_by            INTEGER
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_par_company_rule_key
    ON practice_alert_rules (company_id, rule_key);

CREATE INDEX IF NOT EXISTS idx_par_company_id
    ON practice_alert_rules (company_id);

CREATE INDEX IF NOT EXISTS idx_par_category
    ON practice_alert_rules (company_id, category);

CREATE INDEX IF NOT EXISTS idx_par_group_id
    ON practice_alert_rules (group_id)
    WHERE group_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_par_enabled
    ON practice_alert_rules (company_id, enabled);

-- Auto-update updated_at (does not touch version — version is bumped
-- explicitly in application code only on meaningful field changes, not on
-- every UPDATE, e.g. not on a no-op save).
CREATE OR REPLACE FUNCTION fn_par_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS tg_par_updated_at ON practice_alert_rules;
CREATE TRIGGER tg_par_updated_at
    BEFORE UPDATE ON practice_alert_rules
    FOR EACH ROW EXECUTE FUNCTION fn_par_updated_at();

COMMENT ON TABLE practice_alert_rules IS
    'Codebox 53 — Configurable alert thresholds consulted via getRule()/getRules() in alert-rules.js. Default seeded values exactly match the previously hardcoded behaviour in management-dashboard.js, risk-register.js, capacity.js, client-health.js, compliance-packs.js, reminders.js, document-requests.js, and communications.js.';

-- ─────────────────────────────────────────────────────────────────────────────
-- TABLE: practice_alert_rule_events  (append-only audit log)
-- Never updated. Never deleted.
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS practice_alert_rule_events (
    id                   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id           INTEGER NOT NULL,
    rule_id              INTEGER,        -- plain integer, no FK (Codebox 41 convention) — nullable for group-level/bulk events
    rule_key             TEXT,           -- denormalized so the audit trail survives rule deletion

    event_type           TEXT NOT NULL,  -- rule_created | rule_updated | rule_reset | rule_deleted | group_reset | rules_seeded | rules_exported | rules_imported
    old_value             JSONB,
    new_value             JSONB,

    actor_user_id        INTEGER,
    notes                TEXT,
    metadata              JSONB NOT NULL DEFAULT '{}',
    created_at            TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_pare_rule_id
    ON practice_alert_rule_events (rule_id)
    WHERE rule_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_pare_company_rule
    ON practice_alert_rule_events (company_id, rule_id);

CREATE INDEX IF NOT EXISTS idx_pare_created_desc
    ON practice_alert_rule_events (created_at DESC);

COMMENT ON TABLE practice_alert_rule_events IS
    'Codebox 53 — Append-only audit log for alert rule lifecycle events (created, updated, reset, deleted, seeded, exported, imported). Never updated or deleted.';
