-- Migration 111: Practice Notification Centre + Internal Notification Routing
-- Codebox 54 — Lorenco Practice Management
--
-- NOT email. NOT SMS. NOT push notifications. NOT Teams. NOT Sean AI.
-- Internal notification centre inside Practice Management only.
--
-- Tables created (all IF NOT EXISTS — safe to re-run):
--   practice_notifications
--   practice_notification_events

-- ─────────────────────────────────────────────────────────────────────────────
-- TABLE: practice_notifications
-- One row per actionable internal notification, assigned to a team member.
-- Created directly (POST /) or via the reusable notify() helper exported
-- from notifications.js — see that file for routing/dedup logic. No other
-- module writes to this table automatically yet (Codebox 54 ships the
-- helper only — see docs for why automatic conversion is out of scope).
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS practice_notifications (
    id                      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id              INTEGER NOT NULL,

    notification_key        TEXT,          -- caller-defined dedup key, e.g. 'risk_high_42' — see uq_pnot_active_key below

    title                   TEXT NOT NULL,
    message                 TEXT,

    category                TEXT NOT NULL CHECK (category IN (
                                'risk', 'tax', 'billing', 'workflow', 'capacity', 'client',
                                'documents', 'compliance', 'qms', 'knowledge', 'sop',
                                'communication', 'system'
                            )),
    severity                TEXT NOT NULL CHECK (severity IN ('info', 'low', 'medium', 'high', 'critical')),

    source_module           TEXT,          -- e.g. 'risk-register', 'alert-rules' — documentation/filtering only, no FK
    source_type             TEXT,          -- e.g. 'practice_risk' — the source entity's conceptual type
    source_id               INTEGER,       -- plain integer, no FK (Codebox 41 convention) — the source entity's id

    assigned_team_member_id INTEGER,       -- plain integer, no FK — practice_team_members. NULL only if routing found no team member at all (see notify() fallback chain).
    created_by               INTEGER,       -- plain integer, no FK — users.id; NULL for system-generated notifications

    notification_status     TEXT NOT NULL DEFAULT 'new' CHECK (notification_status IN (
                                'new', 'read', 'snoozed', 'completed', 'archived', 'cancelled'
                            )),

    read_at                 TIMESTAMPTZ,
    snoozed_until            TIMESTAMPTZ,
    completed_at             TIMESTAMPTZ,   -- not explicitly listed in the spec's field list, added for symmetry with read_at/archived_at given the dedicated PUT /:id/complete endpoint and 'completed' status
    archived_at              TIMESTAMPTZ,
    cancelled_at             TIMESTAMPTZ,   -- same reasoning as completed_at — DELETE (cancel only) needs a timestamp like every other terminal transition

    due_date                 DATE,

    metadata                 JSONB NOT NULL DEFAULT '{}',

    created_at               TIMESTAMPTZ DEFAULT NOW(),
    updated_at               TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_pnot_company_id
    ON practice_notifications (company_id);

CREATE INDEX IF NOT EXISTS idx_pnot_assigned_team_member_id
    ON practice_notifications (assigned_team_member_id)
    WHERE assigned_team_member_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_pnot_status
    ON practice_notifications (company_id, notification_status);

CREATE INDEX IF NOT EXISTS idx_pnot_severity
    ON practice_notifications (company_id, severity);

CREATE INDEX IF NOT EXISTS idx_pnot_category
    ON practice_notifications (company_id, category);

CREATE INDEX IF NOT EXISTS idx_pnot_created_at
    ON practice_notifications (created_at DESC);

CREATE INDEX IF NOT EXISTS idx_pnot_due_date
    ON practice_notifications (company_id, due_date)
    WHERE due_date IS NOT NULL;

-- Duplicate guard — the DB-level half of notify()'s deduplication. While an
-- assignee already has an active (non-terminal) notification for the same
-- notification_key, a second one for the same assignee cannot be created.
-- Once the existing one reaches a terminal status, the key frees up again —
-- so the same alert condition recurring after resolution creates a fresh
-- notification rather than being silently blocked forever.
CREATE UNIQUE INDEX IF NOT EXISTS uq_pnot_active_key
    ON practice_notifications (company_id, notification_key, assigned_team_member_id)
    WHERE notification_key IS NOT NULL
      AND notification_status NOT IN ('completed', 'archived', 'cancelled');

CREATE OR REPLACE FUNCTION fn_pnot_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS tg_pnot_updated_at ON practice_notifications;
CREATE TRIGGER tg_pnot_updated_at
    BEFORE UPDATE ON practice_notifications
    FOR EACH ROW EXECUTE FUNCTION fn_pnot_updated_at();

COMMENT ON TABLE practice_notifications IS
    'Codebox 54 — Internal notification centre. NOT email/SMS/push/Teams/Sean AI. Assigned, actionable notifications routed to team members via notify() — see notifications.js.';

-- ─────────────────────────────────────────────────────────────────────────────
-- TABLE: practice_notification_events  (append-only audit log)
-- Never updated. Never deleted.
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS practice_notification_events (
    id                    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id            INTEGER NOT NULL,
    notification_id       INTEGER NOT NULL,   -- plain integer, no FK (Codebox 41 convention)

    event_type            TEXT NOT NULL,      -- notification_created | notification_read | notification_unread | notification_snoozed | notification_completed | notification_archived | notification_cancelled
    old_status             TEXT,
    new_status             TEXT,

    actor_user_id         INTEGER,
    notes                  TEXT,
    metadata                JSONB NOT NULL DEFAULT '{}',
    created_at              TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_pnote_notification_id
    ON practice_notification_events (notification_id);

CREATE INDEX IF NOT EXISTS idx_pnote_company_notification
    ON practice_notification_events (company_id, notification_id);

CREATE INDEX IF NOT EXISTS idx_pnote_created_desc
    ON practice_notification_events (created_at DESC);

COMMENT ON TABLE practice_notification_events IS
    'Codebox 54 — Append-only audit log for notification lifecycle events (created, read, unread, snoozed, completed, archived, cancelled). Never updated or deleted.';
