-- Migration 112: Practice Work Queue + Personal Work Hub
-- Codebox 55 — Lorenco Practice Management
--
-- NOT AI. NOT automatic workload balancing. NOT auto-assignment.
-- No work items are stored here — the queue is always computed live by
-- aggregating existing source tables (tasks, deadlines, reminders, risks,
-- QMS reviews/findings, compliance packs, document requests, communications,
-- tax returns, notifications). This migration only adds per-user display
-- preferences and an append-only interaction log.
--
-- Tables created (all IF NOT EXISTS — safe to re-run):
--   practice_work_queue_preferences
--   practice_work_queue_events

-- ─────────────────────────────────────────────────────────────────────────────
-- TABLE: practice_work_queue_preferences
-- One row per team member — how they like their Work Hub laid out. Never
-- used to compute WHAT appears in the queue (that's always live-aggregated),
-- only HOW it's displayed (view/sort/section visibility).
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS practice_work_queue_preferences (
    id                   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id           INTEGER NOT NULL,
    team_member_id       INTEGER NOT NULL,   -- plain integer, no FK — practice_team_members (Codebox 41 convention)

    default_view         TEXT NOT NULL DEFAULT 'my_work' CHECK (default_view IN (
                             'my_work', 'today', 'overdue', 'upcoming', 'waiting_on_me', 'waiting_on_others', 'completed'
                         )),
    show_completed       BOOLEAN NOT NULL DEFAULT false,
    show_notifications   BOOLEAN NOT NULL DEFAULT true,
    show_overdue_first   BOOLEAN NOT NULL DEFAULT true,
    collapsed_sections   JSONB NOT NULL DEFAULT '[]',   -- array of section keys the user has manually collapsed

    metadata             JSONB NOT NULL DEFAULT '{}',

    created_at           TIMESTAMPTZ DEFAULT NOW(),
    updated_at           TIMESTAMPTZ DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_pwqp_company_member
    ON practice_work_queue_preferences (company_id, team_member_id);

CREATE INDEX IF NOT EXISTS idx_pwqp_company_id
    ON practice_work_queue_preferences (company_id);

CREATE OR REPLACE FUNCTION fn_pwqp_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS tg_pwqp_updated_at ON practice_work_queue_preferences;
CREATE TRIGGER tg_pwqp_updated_at
    BEFORE UPDATE ON practice_work_queue_preferences
    FOR EACH ROW EXECUTE FUNCTION fn_pwqp_updated_at();

COMMENT ON TABLE practice_work_queue_preferences IS
    'Codebox 55 — Per-team-member Work Hub display preferences only. Never used to compute queue contents — the queue is always live-aggregated from source modules. See work-queue.js.';

-- ─────────────────────────────────────────────────────────────────────────────
-- TABLE: practice_work_queue_events  (append-only interaction log)
-- Never updated. Never deleted. Records how staff use the Work Hub itself —
-- distinct from each source module's own audit trail (a task being
-- completed is still logged by tasks' own event log; this table additionally
-- records that the completion happened FROM the Work Hub, for UX analysis).
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS practice_work_queue_events (
    id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id         INTEGER NOT NULL,
    team_member_id     INTEGER,             -- plain integer, no FK — practice_team_members; whose queue this happened in

    event_type         TEXT NOT NULL CHECK (event_type IN (
                           'page_opened', 'item_opened', 'item_completed', 'item_snoozed',
                           'item_delegated', 'queue_filtered'
                       )),

    source_module      TEXT,                -- e.g. 'tasks', 'risk-register' — which aggregated source the item came from (null for page_opened/queue_filtered)
    source_type        TEXT,                -- e.g. 'practice_task'
    source_id          INTEGER,             -- plain integer, no FK — the source entity's id

    actor_user_id      INTEGER,
    notes              TEXT,
    metadata           JSONB NOT NULL DEFAULT '{}',
    created_at         TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_pwqe_company_id
    ON practice_work_queue_events (company_id);

CREATE INDEX IF NOT EXISTS idx_pwqe_team_member_id
    ON practice_work_queue_events (team_member_id)
    WHERE team_member_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_pwqe_created_desc
    ON practice_work_queue_events (created_at DESC);

COMMENT ON TABLE practice_work_queue_events IS
    'Codebox 55 — Append-only log of Work Hub interactions (page opened, item opened/completed/snoozed/delegated, queue filtered). Never updated or deleted. Separate from each source module''s own event log.';
