-- Migration 113: Practice Planning Board + Weekly Planning Centre
-- Codebox 56 — Lorenco Practice Management
--
-- NOT AI scheduling. NOT automatic task movement. NOT calendar sync.
-- NOT automatic workload balancing. Deterministic aggregation + manager
-- planning notes only.
--
-- Tables created (all IF NOT EXISTS — safe to re-run):
--   practice_planning_notes
--   practice_planning_events
--
-- No work items are stored here — same principle as Codebox 55's Work
-- Queue. The Planning Board's team/week/deadline/capacity views are all
-- computed live by reusing capacity.js's buildTeamCapacity() and
-- work-queue.js's buildActiveQueue() in-process. The only new persisted
-- data is manager-authored planning notes.

-- ─────────────────────────────────────────────────────────────────────────────
-- TABLE: practice_planning_notes
-- Free-form manager notes pinned to a planning week, optionally scoped to a
-- team member and/or client — "Anton is out Wed-Thu", "Follow up with ABC
-- Traders before Friday", etc. Never read by any other module — purely
-- informational context for the Monday planning meeting.
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS practice_planning_notes (
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id       INTEGER NOT NULL,

    week_start       DATE NOT NULL,          -- Monday of the planning week this note belongs to

    team_member_id   INTEGER,                -- plain integer, no FK — practice_team_members (Codebox 41 convention). Nullable — a note can be team-wide.
    client_id        INTEGER,                -- plain integer, no FK — practice_clients. Nullable — a note can be client-agnostic.

    title            TEXT NOT NULL,
    notes            TEXT,

    status           TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'in_progress', 'done', 'archived')),

    metadata         JSONB NOT NULL DEFAULT '{}',

    created_by       INTEGER,                -- plain integer, no FK — users.id
    created_at       TIMESTAMPTZ DEFAULT NOW(),
    updated_at       TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_ppn_company_week
    ON practice_planning_notes (company_id, week_start);

CREATE INDEX IF NOT EXISTS idx_ppn_team_member_id
    ON practice_planning_notes (team_member_id)
    WHERE team_member_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_ppn_client_id
    ON practice_planning_notes (client_id)
    WHERE client_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_ppn_status
    ON practice_planning_notes (company_id, status);

CREATE OR REPLACE FUNCTION fn_ppn_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS tg_ppn_updated_at ON practice_planning_notes;
CREATE TRIGGER tg_ppn_updated_at
    BEFORE UPDATE ON practice_planning_notes
    FOR EACH ROW EXECUTE FUNCTION fn_ppn_updated_at();

COMMENT ON TABLE practice_planning_notes IS
    'Codebox 56 — Manager planning notes pinned to a week, optionally scoped to a team member and/or client. Purely informational — never read by any other module. Soft-delete via status=archived, never hard-deleted.';

-- ─────────────────────────────────────────────────────────────────────────────
-- TABLE: practice_planning_events  (append-only audit log)
-- Never updated. Never deleted.
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS practice_planning_events (
    id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id         INTEGER NOT NULL,
    note_id            INTEGER,             -- plain integer, no FK — practice_planning_notes; nullable for board-level events (board_opened, filter_changed, week_changed)

    event_type         TEXT NOT NULL CHECK (event_type IN (
                           'board_opened', 'note_created', 'note_updated', 'note_archived',
                           'filter_changed', 'week_changed'
                       )),

    actor_user_id      INTEGER,
    notes              TEXT,
    metadata           JSONB NOT NULL DEFAULT '{}',
    created_at         TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_ppe_company_id
    ON practice_planning_events (company_id);

CREATE INDEX IF NOT EXISTS idx_ppe_note_id
    ON practice_planning_events (note_id)
    WHERE note_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_ppe_created_desc
    ON practice_planning_events (created_at DESC);

COMMENT ON TABLE practice_planning_events IS
    'Codebox 56 — Append-only log of Planning Board interactions (board opened, note created/updated/archived, filter changed, week changed). Never updated or deleted.';
