-- Migration 114: Practice Resource Forecasting + Future Capacity Planning
-- Codebox 57 — Lorenco Practice Management
--
-- NOT AI. NOT automatic scheduling. NOT calendar sync. NOT leave management.
-- NOT hiring recommendations. Deterministic, explainable forward-looking
-- capacity projection only.
--
-- Tables created (all IF NOT EXISTS — safe to re-run):
--   practice_resource_forecast_snapshots
--   practice_resource_forecast_events
--
-- No forecast is computed and stored automatically. The live forecast (via
-- GET /forecast, /team, /clients, /deadlines) is always computed on demand
-- by reusing planning-board.js's buildTeamItemPool() and capacity.js's
-- buildTeamCapacity() in-process — the only persisted data here is a
-- manager's deliberate "save this forecast for the record" snapshot.

-- ─────────────────────────────────────────────────────────────────────────────
-- TABLE: practice_resource_forecast_snapshots
-- A frozen copy of a computed forecast, taken at a point in time. Same
-- "frozen JSONB, never recalculated on read" pattern as Codebox 51's KPI
-- snapshots and Codebox 52's partner review packs — this is what makes a
-- saved forecast a stable historical record even if the underlying
-- tasks/deadlines/capacity change afterwards.
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS practice_resource_forecast_snapshots (
    id                   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id           INTEGER NOT NULL,

    snapshot_name        TEXT NOT NULL,

    forecast_start_date  DATE NOT NULL,
    forecast_end_date    DATE NOT NULL,
    forecast_weeks       INTEGER NOT NULL CHECK (forecast_weeks IN (4, 6, 8, 12)),

    -- Frozen computed output — weekly buckets, team forecast, client
    -- forecast, deadline forecast. Never recalculated on read; see
    -- resource-forecasting.js's _buildForecast() for the exact shape.
    forecast_data        JSONB NOT NULL DEFAULT '{}',
    summary_data         JSONB NOT NULL DEFAULT '{}',

    status               TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'archived')),

    notes                TEXT,

    created_by           INTEGER,     -- plain integer, no FK — users.id
    created_at           TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_prfs_company_id
    ON practice_resource_forecast_snapshots (company_id);

CREATE INDEX IF NOT EXISTS idx_prfs_forecast_start_date
    ON practice_resource_forecast_snapshots (company_id, forecast_start_date);

CREATE INDEX IF NOT EXISTS idx_prfs_forecast_end_date
    ON practice_resource_forecast_snapshots (company_id, forecast_end_date);

CREATE INDEX IF NOT EXISTS idx_prfs_created_at
    ON practice_resource_forecast_snapshots (created_at DESC);

COMMENT ON TABLE practice_resource_forecast_snapshots IS
    'Codebox 57 — Frozen resource forecast snapshots. Deterministic, explainable, no AI. Never recalculated on read. Soft-archived via status=archived, never hard-deleted.';

-- ─────────────────────────────────────────────────────────────────────────────
-- TABLE: practice_resource_forecast_events  (append-only audit log)
-- Never updated. Never deleted.
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS practice_resource_forecast_events (
    id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id         INTEGER NOT NULL,
    snapshot_id        INTEGER,     -- plain integer, no FK (Codebox 41 convention) — nullable for forecast_viewed events with no saved snapshot

    event_type         TEXT NOT NULL CHECK (event_type IN (
                           'forecast_snapshot_created', 'forecast_snapshot_archived', 'forecast_viewed'
                       )),

    actor_user_id      INTEGER,
    notes              TEXT,
    metadata           JSONB NOT NULL DEFAULT '{}',
    created_at         TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_prfe_company_id
    ON practice_resource_forecast_events (company_id);

CREATE INDEX IF NOT EXISTS idx_prfe_snapshot_id
    ON practice_resource_forecast_events (snapshot_id)
    WHERE snapshot_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_prfe_created_desc
    ON practice_resource_forecast_events (created_at DESC);

COMMENT ON TABLE practice_resource_forecast_events IS
    'Codebox 57 — Append-only log of resource forecast interactions (snapshot created/archived, forecast viewed). Never updated or deleted.';
