-- Migration 115: Practice Delegation + Work Reassignment Controls
-- Codebox 58 — Lorenco Practice Management
--
-- NOT AI delegation. NOT automatic reassignment. NOT approval workflows.
-- NOT skill matching. NOT workload optimisation. Manager-controlled,
-- fully auditable, fully reversible ownership transfer only.
--
-- Tables created (all IF NOT EXISTS — safe to re-run):
--   practice_work_delegations
--   practice_work_delegation_events
--
-- This module does not own task/deadline/review/etc. data — it changes the
-- existing owner column on the source table (via delegation.js's
-- changeOwnership() helper) and keeps a full audit record of that change.
-- Source modules remain owners of their own tables.

-- ─────────────────────────────────────────────────────────────────────────────
-- TABLE: practice_work_delegations
-- One row per reassignment. Never deleted — even a cancelled/declined
-- delegation stays as a permanent record of what was attempted and why.
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS practice_work_delegations (
    id                    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id            INTEGER NOT NULL,

    source_module         TEXT NOT NULL,     -- e.g. 'tasks', 'deadlines' — see delegation.js SOURCE_REGISTRY
    source_type           TEXT NOT NULL,     -- e.g. 'practice_task' — descriptive, matches work-queue.js's source_type convention
    source_id             INTEGER NOT NULL,  -- plain integer, no FK (Codebox 41 convention) — the source entity's id

    -- Which ownership slot on the source record this delegation targets.
    -- Not in the spec's literal field list, but structurally required —
    -- e.g. practice_tasks alone has 4 independent owner columns
    -- (assignee/preparer/reviewer/approver). Defaults are documented per
    -- source_module in delegation.js's SOURCE_REGISTRY.
    ownership_role        TEXT NOT NULL,

    previous_owner_id     INTEGER,           -- plain integer, no FK — practice_team_members. Nullable: a previously-unowned item can be delegated too.
    new_owner_id          INTEGER NOT NULL,  -- plain integer, no FK — practice_team_members

    delegated_by          INTEGER,           -- plain integer, no FK — practice_team_members (who performed the delegation)

    delegation_reason     TEXT NOT NULL,
    delegation_notes      TEXT,

    delegation_status     TEXT NOT NULL DEFAULT 'delegated' CHECK (delegation_status IN (
                              'draft', 'delegated', 'accepted', 'declined', 'cancelled', 'completed'
                          )),

    effective_date        DATE,
    completed_at           TIMESTAMPTZ,

    metadata               JSONB NOT NULL DEFAULT '{}',

    created_by             INTEGER,          -- plain integer, no FK — users.id
    created_at              TIMESTAMPTZ DEFAULT NOW(),
    updated_at              TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_pwd_company_id
    ON practice_work_delegations (company_id);

CREATE INDEX IF NOT EXISTS idx_pwd_source_type
    ON practice_work_delegations (company_id, source_type);

CREATE INDEX IF NOT EXISTS idx_pwd_source_id
    ON practice_work_delegations (source_module, source_id);

CREATE INDEX IF NOT EXISTS idx_pwd_previous_owner_id
    ON practice_work_delegations (previous_owner_id)
    WHERE previous_owner_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_pwd_new_owner_id
    ON practice_work_delegations (new_owner_id);

CREATE INDEX IF NOT EXISTS idx_pwd_status
    ON practice_work_delegations (company_id, delegation_status);

CREATE OR REPLACE FUNCTION fn_pwd_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS tg_pwd_updated_at ON practice_work_delegations;
CREATE TRIGGER tg_pwd_updated_at
    BEFORE UPDATE ON practice_work_delegations
    FOR EACH ROW EXECUTE FUNCTION fn_pwd_updated_at();

COMMENT ON TABLE practice_work_delegations IS
    'Codebox 58 — Auditable work reassignment records. Ownership changes on the source table happen immediately via changeOwnership(); accept/decline/cancel are post-hoc acknowledgement/reversal actions. Never hard-deleted.';

-- ─────────────────────────────────────────────────────────────────────────────
-- TABLE: practice_work_delegation_events  (append-only audit log)
-- Never updated. Never deleted. No ownership change may occur without a
-- corresponding event row here — enforced by delegation.js's
-- changeOwnership() helper always writing one in the same operation.
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS practice_work_delegation_events (
    id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id         INTEGER NOT NULL,
    delegation_id      INTEGER NOT NULL,   -- plain integer, no FK (Codebox 41 convention)

    event_type         TEXT NOT NULL CHECK (event_type IN (
                           'delegation_created', 'delegation_accepted', 'delegation_declined',
                           'delegation_cancelled', 'delegation_completed', 'ownership_changed'
                       )),

    old_owner_id        INTEGER,
    new_owner_id         INTEGER,

    actor_user_id       INTEGER,
    notes               TEXT,
    metadata            JSONB NOT NULL DEFAULT '{}',
    created_at           TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_pwde_company_id
    ON practice_work_delegation_events (company_id);

CREATE INDEX IF NOT EXISTS idx_pwde_delegation_id
    ON practice_work_delegation_events (delegation_id);

CREATE INDEX IF NOT EXISTS idx_pwde_created_desc
    ON practice_work_delegation_events (created_at DESC);

COMMENT ON TABLE practice_work_delegation_events IS
    'Codebox 58 — Append-only log of delegation lifecycle events (created, accepted, declined, cancelled, completed, ownership_changed). Never updated or deleted. Every ownership change on a source table has a matching ownership_changed row here.';
