-- Migration 116: Practice Skills Matrix + Competency Framework
-- Codebox 59 — Lorenco Practice Management
--
-- NOT AI recommendations. NOT auto-delegation. NOT an HR module. NOT
-- payroll integration. NOT performance reviews. NOT training automation.
-- This module ADVISES managers — it never assigns work, never blocks
-- delegation, and never overrides a manager's decision. Fully manager
-- controlled: no self-service editing of one's own competency data.
--
-- Tables created (all IF NOT EXISTS — safe to re-run):
--   practice_skill_categories
--   practice_skills
--   practice_team_skills
--   practice_certifications
--   practice_team_certifications
--   practice_skill_events

-- ─────────────────────────────────────────────────────────────────────────────
-- TABLE: practice_skill_categories
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS practice_skill_categories (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id    INTEGER NOT NULL,

    category_key  TEXT NOT NULL,        -- e.g. 'tax', 'accounting', 'payroll'
    display_name  TEXT NOT NULL,
    description   TEXT,
    sort_order    INTEGER NOT NULL DEFAULT 0,
    is_active     BOOLEAN NOT NULL DEFAULT true,

    created_at    TIMESTAMPTZ DEFAULT NOW(),
    updated_at    TIMESTAMPTZ DEFAULT NOW(),
    created_by    INTEGER,
    updated_by    INTEGER
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_psc_company_key
    ON practice_skill_categories (company_id, category_key);

CREATE INDEX IF NOT EXISTS idx_psc_company_id
    ON practice_skill_categories (company_id);

COMMENT ON TABLE practice_skill_categories IS
    'Codebox 59 — Skill categories (Tax, Accounting, Payroll, Compliance, Secretarial, QMS, Risk, Advisory, Administration, Client Service, Software, Leadership). Per-company, manager-extensible.';

-- ─────────────────────────────────────────────────────────────────────────────
-- TABLE: practice_skills
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS practice_skills (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id    INTEGER NOT NULL,
    category_id   INTEGER,     -- plain integer, no FK — practice_skill_categories (Codebox 41 convention)

    skill_key     TEXT NOT NULL,        -- e.g. 'prepare_vat_return'
    display_name  TEXT NOT NULL,
    description   TEXT,
    sort_order    INTEGER NOT NULL DEFAULT 0,
    is_active     BOOLEAN NOT NULL DEFAULT true,

    metadata      JSONB NOT NULL DEFAULT '{}',   -- e.g. { maps_to_source_module: 'tax-individual' } — see skills-matrix.js MODULE_SKILL_MAP

    created_at    TIMESTAMPTZ DEFAULT NOW(),
    updated_at    TIMESTAMPTZ DEFAULT NOW(),
    created_by    INTEGER,
    updated_by    INTEGER
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_ps_company_key
    ON practice_skills (company_id, skill_key);

CREATE INDEX IF NOT EXISTS idx_ps_company_id
    ON practice_skills (company_id);

CREATE INDEX IF NOT EXISTS idx_ps_category_id
    ON practice_skills (category_id)
    WHERE category_id IS NOT NULL;

COMMENT ON TABLE practice_skills IS
    'Codebox 59 — Individual skills within a category (e.g. Prepare VAT Return, Payroll Review, Xero). Per-company, manager-extensible.';

-- ─────────────────────────────────────────────────────────────────────────────
-- TABLE: practice_team_skills
-- One row per (team member, skill) — the actual competency record.
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS practice_team_skills (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id          INTEGER NOT NULL,
    team_member_id      INTEGER NOT NULL,   -- plain integer, no FK — practice_team_members
    skill_id            INTEGER NOT NULL,   -- plain integer, no FK — practice_skills

    current_level       INTEGER NOT NULL DEFAULT 0 CHECK (current_level BETWEEN 0 AND 5),
    target_level         INTEGER CHECK (target_level BETWEEN 0 AND 5),

    is_preferred          BOOLEAN NOT NULL DEFAULT false,   -- this team member prefers/enjoys this kind of work
    is_restricted          BOOLEAN NOT NULL DEFAULT false,   -- manager has explicitly restricted this member from this work

    last_reviewed_date    DATE,
    review_notes          TEXT,

    metadata               JSONB NOT NULL DEFAULT '{}',

    created_at              TIMESTAMPTZ DEFAULT NOW(),
    updated_at              TIMESTAMPTZ DEFAULT NOW(),
    created_by              INTEGER,
    updated_by              INTEGER
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_pts_member_skill
    ON practice_team_skills (company_id, team_member_id, skill_id);

CREATE INDEX IF NOT EXISTS idx_pts_company_id
    ON practice_team_skills (company_id);

CREATE INDEX IF NOT EXISTS idx_pts_team_member_id
    ON practice_team_skills (team_member_id);

CREATE INDEX IF NOT EXISTS idx_pts_skill_id
    ON practice_team_skills (skill_id);

CREATE OR REPLACE FUNCTION fn_pts_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS tg_pts_updated_at ON practice_team_skills;
CREATE TRIGGER tg_pts_updated_at
    BEFORE UPDATE ON practice_team_skills
    FOR EACH ROW EXECUTE FUNCTION fn_pts_updated_at();

COMMENT ON TABLE practice_team_skills IS
    'Codebox 59 — Per-team-member competency record for one skill (0=No Exposure .. 5=Expert). Fully manager controlled — no self-service editing.';

-- ─────────────────────────────────────────────────────────────────────────────
-- TABLE: practice_certifications
-- Catalog of certification types the practice tracks (e.g. SAICA CA(SA)).
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS practice_certifications (
    id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id         INTEGER NOT NULL,

    certification_name  TEXT NOT NULL,
    issuer              TEXT,
    category_id          INTEGER,   -- plain integer, no FK — practice_skill_categories (optional link)
    description           TEXT,
    is_active              BOOLEAN NOT NULL DEFAULT true,

    created_at              TIMESTAMPTZ DEFAULT NOW(),
    updated_at              TIMESTAMPTZ DEFAULT NOW(),
    created_by              INTEGER,
    updated_by              INTEGER
);

CREATE INDEX IF NOT EXISTS idx_pc_company_id
    ON practice_certifications (company_id);

COMMENT ON TABLE practice_certifications IS
    'Codebox 59 — Catalog of certification types the practice tracks (e.g. SAICA CA(SA), SAIT Tax Practitioner). Not seeded by default — practice-specific.';

-- ─────────────────────────────────────────────────────────────────────────────
-- TABLE: practice_team_certifications
-- One row per (team member, certification) actually held.
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS practice_team_certifications (
    id                    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id            INTEGER NOT NULL,
    team_member_id        INTEGER NOT NULL,   -- plain integer, no FK — practice_team_members
    certification_id      INTEGER NOT NULL,   -- plain integer, no FK — practice_certifications

    issue_date             DATE,
    expiry_date             DATE,
    status                  TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'expired', 'pending', 'revoked')),
    certificate_number       TEXT,
    notes                    TEXT,
    is_active                BOOLEAN NOT NULL DEFAULT true,   -- distinct from `status`: this is the soft-delete/archive flag for a mistaken or duplicate entry, independent of the certification's own real-world lifecycle (active/expired/pending/revoked)

    metadata                  JSONB NOT NULL DEFAULT '{}',

    created_at                TIMESTAMPTZ DEFAULT NOW(),
    updated_at                TIMESTAMPTZ DEFAULT NOW(),
    created_by                INTEGER,
    updated_by                INTEGER
);

CREATE INDEX IF NOT EXISTS idx_ptc_company_id
    ON practice_team_certifications (company_id);

CREATE INDEX IF NOT EXISTS idx_ptc_team_member_id
    ON practice_team_certifications (team_member_id);

CREATE INDEX IF NOT EXISTS idx_ptc_certification_id
    ON practice_team_certifications (certification_id);

CREATE INDEX IF NOT EXISTS idx_ptc_expiry_date
    ON practice_team_certifications (company_id, expiry_date)
    WHERE expiry_date IS NOT NULL;

CREATE OR REPLACE FUNCTION fn_ptc_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS tg_ptc_updated_at ON practice_team_certifications;
CREATE TRIGGER tg_ptc_updated_at
    BEFORE UPDATE ON practice_team_certifications
    FOR EACH ROW EXECUTE FUNCTION fn_ptc_updated_at();

COMMENT ON TABLE practice_team_certifications IS
    'Codebox 59 — Certifications actually held by a team member. expiry_date indexed to support future expiry-reminder codeboxes (not built here — see spec "Allow expiry reminders later").';

-- ─────────────────────────────────────────────────────────────────────────────
-- TABLE: practice_skill_events  (append-only audit log)
-- Never updated. Never deleted.
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS practice_skill_events (
    id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id         INTEGER NOT NULL,

    event_type         TEXT NOT NULL CHECK (event_type IN (
                           'category_created', 'category_updated', 'category_archived',
                           'skill_created', 'skill_updated', 'skill_archived',
                           'team_skill_updated', 'team_skill_archived',
                           'certification_created', 'certification_updated', 'certification_archived',
                           'team_certification_added', 'team_certification_updated', 'team_certification_archived',
                           'skills_seeded'
                       )),
    entity_type         TEXT,        -- 'category' | 'skill' | 'team_skill' | 'certification' | 'team_certification'
    entity_id            INTEGER,    -- plain integer, no FK (Codebox 41 convention)

    actor_user_id       INTEGER,
    notes                TEXT,
    metadata              JSONB NOT NULL DEFAULT '{}',
    created_at             TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_pse_company_id
    ON practice_skill_events (company_id);

CREATE INDEX IF NOT EXISTS idx_pse_entity
    ON practice_skill_events (entity_type, entity_id)
    WHERE entity_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_pse_created_desc
    ON practice_skill_events (created_at DESC);

COMMENT ON TABLE practice_skill_events IS
    'Codebox 59 — Append-only log of Skills Matrix changes. Never updated or deleted.';
