-- Migration 117: Practice Learning, Development & Training Centre
-- Codebox 60 — Lorenco Practice Management
--
-- NOT AI coaching. NOT automatic development plans. NOT an LMS. NOT
-- external learning provider integration. NOT employee performance
-- reviews. Complements the Skills Matrix (Codebox 59) — fully manager
-- controlled, deterministic, explainable.
--
-- Tables created (all IF NOT EXISTS — safe to re-run):
--   practice_learning_plans
--   practice_learning_goals
--   practice_learning_activities
--   practice_learning_progress
--   practice_cpd_records
--   practice_learning_events

-- ─────────────────────────────────────────────────────────────────────────────
-- TABLE: practice_learning_plans
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS practice_learning_plans (
    id                        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id                INTEGER NOT NULL,
    team_member_id            INTEGER NOT NULL,   -- plain integer, no FK — practice_team_members (Codebox 41 convention)

    plan_name                 TEXT NOT NULL,
    description                TEXT,

    start_date                 DATE,
    target_completion_date      DATE,

    status                      TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'active', 'on_hold', 'completed', 'cancelled')),

    mentor_team_member_id       INTEGER,   -- plain integer, no FK — practice_team_members. Nullable — not every plan has a formal mentor.

    -- Cached snapshot of the live progress calculation — recomputed and
    -- rewritten by calculateLearningProgress() on every goal/activity write
    -- that touches this plan, never edited directly. See learning-centre.js.
    overall_progress             NUMERIC NOT NULL DEFAULT 0 CHECK (overall_progress BETWEEN 0 AND 100),

    notes                        TEXT,
    metadata                     JSONB NOT NULL DEFAULT '{}',

    created_by                   INTEGER,   -- plain integer, no FK — users.id
    created_at                    TIMESTAMPTZ DEFAULT NOW(),
    updated_at                    TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_plp_company_id
    ON practice_learning_plans (company_id);

CREATE INDEX IF NOT EXISTS idx_plp_team_member_id
    ON practice_learning_plans (team_member_id);

CREATE INDEX IF NOT EXISTS idx_plp_mentor_id
    ON practice_learning_plans (mentor_team_member_id)
    WHERE mentor_team_member_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_plp_status
    ON practice_learning_plans (company_id, status);

CREATE OR REPLACE FUNCTION fn_plp_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS tg_plp_updated_at ON practice_learning_plans;
CREATE TRIGGER tg_plp_updated_at
    BEFORE UPDATE ON practice_learning_plans
    FOR EACH ROW EXECUTE FUNCTION fn_plp_updated_at();

COMMENT ON TABLE practice_learning_plans IS
    'Codebox 60 — Manager-created development plans for a team member, optionally with a mentor. Fully manager controlled — no self-service editing, no automatic plan creation.';

-- ─────────────────────────────────────────────────────────────────────────────
-- TABLE: practice_learning_goals
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS practice_learning_goals (
    id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id          INTEGER NOT NULL,
    learning_plan_id     INTEGER NOT NULL,   -- plain integer, no FK — practice_learning_plans
    skill_id             INTEGER,             -- plain integer, no FK — practice_skills (Codebox 59). Nullable — a goal need not map to a catalog skill.

    goal_title           TEXT NOT NULL,
    goal_description      TEXT,

    priority              TEXT NOT NULL DEFAULT 'medium' CHECK (priority IN ('low', 'medium', 'high', 'critical')),

    target_level           INTEGER CHECK (target_level BETWEEN 0 AND 5),    -- same 0-5 scale as practice_team_skills, for goals linked to a skill
    current_level           INTEGER CHECK (current_level BETWEEN 0 AND 5),

    status                   TEXT NOT NULL DEFAULT 'not_started' CHECK (status IN ('not_started', 'in_progress', 'completed', 'on_hold', 'cancelled')),

    target_date               DATE,
    completed_date             DATE,

    metadata                   JSONB NOT NULL DEFAULT '{}',

    created_by                 INTEGER,
    created_at                  TIMESTAMPTZ DEFAULT NOW(),
    updated_at                  TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_plg_company_id
    ON practice_learning_goals (company_id);

CREATE INDEX IF NOT EXISTS idx_plg_plan_id
    ON practice_learning_goals (learning_plan_id);

CREATE INDEX IF NOT EXISTS idx_plg_skill_id
    ON practice_learning_goals (skill_id)
    WHERE skill_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_plg_status
    ON practice_learning_goals (company_id, status);

CREATE OR REPLACE FUNCTION fn_plg_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS tg_plg_updated_at ON practice_learning_goals;
CREATE TRIGGER tg_plg_updated_at
    BEFORE UPDATE ON practice_learning_goals
    FOR EACH ROW EXECUTE FUNCTION fn_plg_updated_at();

COMMENT ON TABLE practice_learning_goals IS
    'Codebox 60 — Individual goals within a learning plan, optionally linked to a Skills Matrix skill. Never auto-created — a manager may create one from a Skills Matrix suggestion, but the action is always deliberate.';

-- ─────────────────────────────────────────────────────────────────────────────
-- TABLE: practice_learning_activities
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS practice_learning_activities (
    id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id          INTEGER NOT NULL,
    goal_id              INTEGER NOT NULL,   -- plain integer, no FK — practice_learning_goals

    activity_type         TEXT NOT NULL CHECK (activity_type IN (
                              'internal_training', 'external_course', 'workshop', 'reading', 'case_study',
                              'mentoring_session', 'shadowing', 'client_meeting_observation', 'research', 'other'
                          )),
    title                  TEXT NOT NULL,
    description             TEXT,

    planned_hours            NUMERIC,
    completed_hours           NUMERIC,

    status                    TEXT NOT NULL DEFAULT 'planned' CHECK (status IN ('planned', 'in_progress', 'completed', 'cancelled')),
    completion_date            DATE,
    evidence_notes              TEXT,

    metadata                    JSONB NOT NULL DEFAULT '{}',

    created_by                  INTEGER,
    created_at                    TIMESTAMPTZ DEFAULT NOW(),
    updated_at                    TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_pla_company_id
    ON practice_learning_activities (company_id);

CREATE INDEX IF NOT EXISTS idx_pla_goal_id
    ON practice_learning_activities (goal_id);

CREATE INDEX IF NOT EXISTS idx_pla_status
    ON practice_learning_activities (company_id, status);

CREATE OR REPLACE FUNCTION fn_pla_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS tg_pla_updated_at ON practice_learning_activities;
CREATE TRIGGER tg_pla_updated_at
    BEFORE UPDATE ON practice_learning_activities
    FOR EACH ROW EXECUTE FUNCTION fn_pla_updated_at();

COMMENT ON TABLE practice_learning_activities IS
    'Codebox 60 — Concrete learning activities under a goal (internal training, external course, workshop, reading, case study, mentoring session, shadowing, client meeting observation, research, other).';

-- ─────────────────────────────────────────────────────────────────────────────
-- TABLE: practice_learning_progress
-- Point-in-time progress snapshots — a history/trend record, distinct from
-- practice_learning_plans.overall_progress (which always holds only the
-- latest computed value). Written whenever a manager explicitly captures a
-- progress snapshot, and whenever a plan is marked completed/cancelled.
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS practice_learning_progress (
    id                     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id              INTEGER NOT NULL,
    learning_plan_id         INTEGER NOT NULL,   -- plain integer, no FK — practice_learning_plans

    snapshot_date              DATE NOT NULL DEFAULT CURRENT_DATE,
    overall_progress             NUMERIC NOT NULL CHECK (overall_progress BETWEEN 0 AND 100),
    goals_total                   INTEGER NOT NULL DEFAULT 0,
    goals_completed                INTEGER NOT NULL DEFAULT 0,
    hours_planned                   NUMERIC NOT NULL DEFAULT 0,
    hours_completed                  NUMERIC NOT NULL DEFAULT 0,

    notes                             TEXT,
    metadata                           JSONB NOT NULL DEFAULT '{}',

    created_by                         INTEGER,
    created_at                          TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_plpr_company_id
    ON practice_learning_progress (company_id);

CREATE INDEX IF NOT EXISTS idx_plpr_plan_id
    ON practice_learning_progress (learning_plan_id, snapshot_date DESC);

COMMENT ON TABLE practice_learning_progress IS
    'Codebox 60 — Point-in-time progress snapshots for a learning plan (trend history). Distinct from practice_learning_plans.overall_progress, which always holds only the current computed value.';

-- ─────────────────────────────────────────────────────────────────────────────
-- TABLE: practice_cpd_records
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS practice_cpd_records (
    id                     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id              INTEGER NOT NULL,
    team_member_id           INTEGER NOT NULL,   -- plain integer, no FK — practice_team_members

    provider                  TEXT,
    course_name                TEXT NOT NULL,
    hours                        NUMERIC NOT NULL DEFAULT 0,
    category                     TEXT,           -- free text — CPD categories are typically defined by an external professional body (SAICA/SAIT/etc.), a different taxonomy from internal Skills Matrix categories, so deliberately not linked to practice_skill_categories

    certificate_number             TEXT,
    issue_date                      DATE,
    expiry_date                      DATE,
    evidence                          TEXT,        -- free-text reference/URL — no file upload system exists in this codebase

    status                             TEXT NOT NULL DEFAULT 'recorded' CHECK (status IN ('recorded', 'verified', 'expired')),
    is_active                           BOOLEAN NOT NULL DEFAULT true,   -- soft-delete flag, independent of `status` (same reasoning as practice_team_certifications.is_active in Codebox 59)

    notes                                 TEXT,
    metadata                               JSONB NOT NULL DEFAULT '{}',

    created_by                             INTEGER,
    created_at                              TIMESTAMPTZ DEFAULT NOW(),
    updated_at                              TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_pcpd_company_id
    ON practice_cpd_records (company_id);

CREATE INDEX IF NOT EXISTS idx_pcpd_team_member_id
    ON practice_cpd_records (team_member_id);

CREATE INDEX IF NOT EXISTS idx_pcpd_expiry_date
    ON practice_cpd_records (company_id, expiry_date)
    WHERE expiry_date IS NOT NULL;

CREATE OR REPLACE FUNCTION fn_pcpd_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS tg_pcpd_updated_at ON practice_cpd_records;
CREATE TRIGGER tg_pcpd_updated_at
    BEFORE UPDATE ON practice_cpd_records
    FOR EACH ROW EXECUTE FUNCTION fn_pcpd_updated_at();

COMMENT ON TABLE practice_cpd_records IS
    'Codebox 60 — CPD (Continuing Professional Development) records per team member. No external provider integrations.';

-- ─────────────────────────────────────────────────────────────────────────────
-- TABLE: practice_learning_events  (append-only audit log)
-- Never updated. Never deleted.
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS practice_learning_events (
    id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id          INTEGER NOT NULL,

    event_type            TEXT NOT NULL CHECK (event_type IN (
                              'plan_created', 'plan_updated', 'plan_archived',
                              'goal_created', 'goal_updated', 'goal_completed', 'goal_archived',
                              'activity_created', 'activity_updated', 'activity_completed', 'activity_archived',
                              'cpd_recorded', 'cpd_updated', 'cpd_archived',
                              'progress_snapshot_created'
                          )),
    entity_type              TEXT,    -- 'plan' | 'goal' | 'activity' | 'cpd_record' | 'progress_snapshot'
    entity_id                 INTEGER,  -- plain integer, no FK (Codebox 41 convention)

    actor_user_id             INTEGER,
    notes                      TEXT,
    metadata                    JSONB NOT NULL DEFAULT '{}',
    created_at                   TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_ple_company_id
    ON practice_learning_events (company_id);

CREATE INDEX IF NOT EXISTS idx_ple_entity
    ON practice_learning_events (entity_type, entity_id)
    WHERE entity_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_ple_created_desc
    ON practice_learning_events (created_at DESC);

COMMENT ON TABLE practice_learning_events IS
    'Codebox 60 — Append-only log of Learning Centre changes. Never updated or deleted.';
