-- Migration 118: Practice Client Success & Relationship Management
-- Codebox 61 — Lorenco Practice Management
--
-- NOT a CRM. NOT a sales pipeline. NOT marketing/email marketing. NOT lead
-- management. NOT client master data (that stays in practice_clients).
-- Fully manager-controlled, deterministic, explainable. No AI, no scoring
-- black boxes, no forecasting.
--
-- AUDIT FINDING (RULE A1/A4 — see docs/new-app/61_client_success.md,
-- Architect Freedom #1): practice_client_contacts ALREADY EXISTS as a live,
-- working feature (CRUD routes in modules/practice/index.js, lines ~988-1092)
-- but has NO prior migration file anywhere in this repo. To avoid both (a)
-- blindly creating a possibly-conflicting duplicate table and (b) silently
-- skipping the spec's explicit request for new contact fields, this migration
-- uses CREATE TABLE IF NOT EXISTS with the FULL existing column set (so a
-- fresh/reset database gets a complete, working table in one shot) followed
-- by explicit ALTER TABLE ... ADD COLUMN IF NOT EXISTS statements for the new
-- Codebox 61 fields (so an already-live table — the expected case in the
-- current Supabase instance — is safely extended without any risk of the
-- CREATE TABLE IF NOT EXISTS silently no-op'ing past the new columns).
--
-- Tables created (all IF NOT EXISTS — safe to re-run):
--   practice_client_success              (new)
--   practice_client_contacts             (pre-existing — extended, not replaced)
--   practice_client_success_activities   (new)
--   practice_client_opportunities        (new)
--   practice_client_meetings             (new)
--   practice_client_success_events       (new, append-only)

-- ─────────────────────────────────────────────────────────────────────────────
-- TABLE: practice_client_success
-- One current row per client. Holds the manager-facing relationship health
-- state (distinct from practice_clients.health_score/health_status, which is
-- the pre-existing OPERATIONAL risk score computed by client-health.js from
-- overdue deadlines/tasks/periods/WIP — see client-success.js's
-- calculateClientHealth(), which composes that operational score with
-- communication cadence rather than recomputing overdue-item logic itself).
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS practice_client_success (
    id                          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id                   INTEGER NOT NULL,
    client_id                     INTEGER NOT NULL,   -- plain integer, no FK — practice_clients (Codebox 41 convention)

    -- Relationship health — deliberately named relationship_* (not health_*)
    -- to avoid any confusion with practice_clients.health_status, which is a
    -- different, pre-existing, purely operational concept.
    relationship_status            TEXT NOT NULL DEFAULT 'unknown' CHECK (relationship_status IN ('healthy', 'watch', 'at_risk', 'critical', 'unknown')),
    relationship_score              NUMERIC CHECK (relationship_score BETWEEN 0 AND 100),
    relationship_last_calculated_at  TIMESTAMPTZ,

    -- Manager override — when set, calculateClientHealth() never overwrites
    -- relationship_status/relationship_score until the override is cleared.
    is_manager_override               BOOLEAN NOT NULL DEFAULT false,
    override_reason                    TEXT,
    override_by                         INTEGER,   -- plain integer, no FK — users.id
    override_at                          TIMESTAMPTZ,

    trend                                 TEXT NOT NULL DEFAULT 'unknown' CHECK (trend IN ('improving', 'stable', 'declining', 'unknown')),

    -- Communication cadence (native to this codebox — no email integration,
    -- these are manager/team-logged dates)
    last_meaningful_contact_date            DATE,
    next_planned_contact_date                DATE,

    -- Relationship review cycle
    last_review_date                          DATE,
    next_review_date                           DATE,

    relationship_owner_team_member_id           INTEGER,   -- plain integer, no FK — practice_team_members. Nullable — falls back to practice_clients.responsible_team_member_id for display if unset.

    notes                                         TEXT,
    metadata                                       JSONB NOT NULL DEFAULT '{}',

    created_by                                     INTEGER,
    created_at                                       TIMESTAMPTZ DEFAULT NOW(),
    updated_at                                       TIMESTAMPTZ DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_pcs_company_client
    ON practice_client_success (company_id, client_id);

CREATE INDEX IF NOT EXISTS idx_pcs_company_id
    ON practice_client_success (company_id);

CREATE INDEX IF NOT EXISTS idx_pcs_relationship_status
    ON practice_client_success (company_id, relationship_status);

CREATE INDEX IF NOT EXISTS idx_pcs_next_review
    ON practice_client_success (company_id, next_review_date)
    WHERE next_review_date IS NOT NULL;

CREATE OR REPLACE FUNCTION fn_pcs_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS tg_pcs_updated_at ON practice_client_success;
CREATE TRIGGER tg_pcs_updated_at
    BEFORE UPDATE ON practice_client_success
    FOR EACH ROW EXECUTE FUNCTION fn_pcs_updated_at();

COMMENT ON TABLE practice_client_success IS
    'Codebox 61 — Manager-facing relationship health record per client. relationship_status/score are computed by client-success.js calculateClientHealth(), which composes the pre-existing operational health score (client-health.js) with communication cadence. Manager override always wins.';

-- ─────────────────────────────────────────────────────────────────────────────
-- TABLE: practice_client_contacts  (PRE-EXISTING — see audit note at top of file)
-- Reproduces the exact live column set already used by modules/practice/index.js
-- for the IF-NOT-EXISTS (fresh-database) path, then extends it via ALTER for
-- the already-exists (current Supabase) path. Both paths converge on the same
-- final shape.
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS practice_client_contacts (
    id                              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id                       INTEGER NOT NULL,
    client_id                         INTEGER NOT NULL,   -- plain integer, no FK — practice_clients

    contact_name                       TEXT NOT NULL,
    role                                 TEXT,
    email                                 TEXT,
    phone                                  TEXT,
    mobile                                  TEXT,

    is_primary                               BOOLEAN NOT NULL DEFAULT false,
    receives_tax_correspondence               BOOLEAN NOT NULL DEFAULT false,
    receives_billing                           BOOLEAN NOT NULL DEFAULT false,
    receives_payroll                            BOOLEAN NOT NULL DEFAULT false,
    receives_cipc                                BOOLEAN NOT NULL DEFAULT false,

    -- Codebox 61 additions (also applied via ALTER below for already-live tables)
    is_decision_maker                             BOOLEAN NOT NULL DEFAULT false,
    is_financial_contact                           BOOLEAN NOT NULL DEFAULT false,
    is_operational_contact                          BOOLEAN NOT NULL DEFAULT false,
    birthday                                         DATE,

    notes                                              TEXT,
    is_active                                           BOOLEAN NOT NULL DEFAULT true,

    created_by                                           INTEGER,
    updated_by                                            INTEGER,
    created_at                                             TIMESTAMPTZ DEFAULT NOW(),
    updated_at                                              TIMESTAMPTZ DEFAULT NOW()
);

-- Idempotent extension path for the case where the table already exists live
-- (the expected case in the current Supabase instance — see audit note above).
ALTER TABLE practice_client_contacts ADD COLUMN IF NOT EXISTS is_decision_maker      BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE practice_client_contacts ADD COLUMN IF NOT EXISTS is_financial_contact    BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE practice_client_contacts ADD COLUMN IF NOT EXISTS is_operational_contact  BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE practice_client_contacts ADD COLUMN IF NOT EXISTS birthday                DATE;

CREATE INDEX IF NOT EXISTS idx_pcc_company_id
    ON practice_client_contacts (company_id);

CREATE INDEX IF NOT EXISTS idx_pcc_client_id
    ON practice_client_contacts (client_id);

COMMENT ON TABLE practice_client_contacts IS
    'Pre-existing table (CRUD in modules/practice/index.js) — Codebox 61 adds is_decision_maker, is_financial_contact, is_operational_contact, birthday. is_primary is reused as "preferred contact" per Architect Freedom — no redundant new column added.';

-- ─────────────────────────────────────────────────────────────────────────────
-- TABLE: practice_client_success_activities
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS practice_client_success_activities (
    id                     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id              INTEGER NOT NULL,
    client_id                INTEGER NOT NULL,   -- plain integer, no FK — practice_clients

    activity_type              TEXT NOT NULL CHECK (activity_type IN (
                                   'quarterly_review', 'annual_planning', 'tax_planning', 'business_review',
                                   'health_check', 'follow_up', 'training', 'onboarding', 'other'
                               )),
    title                        TEXT NOT NULL,
    description                   TEXT,

    scheduled_date                 DATE,
    completed_date                  DATE,

    status                           TEXT NOT NULL DEFAULT 'planned' CHECK (status IN ('planned', 'completed', 'cancelled')),

    owner_team_member_id               INTEGER,   -- plain integer, no FK — practice_team_members

    notes                                TEXT,
    metadata                              JSONB NOT NULL DEFAULT '{}',

    created_by                            INTEGER,
    created_at                              TIMESTAMPTZ DEFAULT NOW(),
    updated_at                               TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_pcsa_company_id
    ON practice_client_success_activities (company_id);

CREATE INDEX IF NOT EXISTS idx_pcsa_client_id
    ON practice_client_success_activities (client_id);

CREATE INDEX IF NOT EXISTS idx_pcsa_status
    ON practice_client_success_activities (company_id, status);

CREATE INDEX IF NOT EXISTS idx_pcsa_scheduled_date
    ON practice_client_success_activities (company_id, scheduled_date)
    WHERE scheduled_date IS NOT NULL;

CREATE OR REPLACE FUNCTION fn_pcsa_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS tg_pcsa_updated_at ON practice_client_success_activities;
CREATE TRIGGER tg_pcsa_updated_at
    BEFORE UPDATE ON practice_client_success_activities
    FOR EACH ROW EXECUTE FUNCTION fn_pcsa_updated_at();

COMMENT ON TABLE practice_client_success_activities IS
    'Codebox 61 — Planned/completed relationship activities per client (quarterly reviews, business reviews, health checks, etc.). Distinct from practice_tasks — these are relationship-management activities, not compliance work items.';

-- ─────────────────────────────────────────────────────────────────────────────
-- TABLE: practice_client_opportunities
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS practice_client_opportunities (
    id                     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id              INTEGER NOT NULL,
    client_id                INTEGER NOT NULL,   -- plain integer, no FK — practice_clients

    opportunity_type            TEXT NOT NULL CHECK (opportunity_type IN (
                                    'accounting', 'payroll', 'pos', 'inventory', 'sean_ai',
                                    'secretarial', 'advisory', 'training', 'other'
                                )),
    title                         TEXT NOT NULL,
    description                    TEXT,

    status                          TEXT NOT NULL DEFAULT 'identified' CHECK (status IN ('identified', 'discussed', 'proposal', 'won', 'lost', 'deferred')),
    status_reason                    TEXT,   -- why won/lost/deferred

    estimated_value                    NUMERIC,
    expected_date                       DATE,

    owner_team_member_id                  INTEGER,   -- plain integer, no FK — practice_team_members

    notes                                    TEXT,
    metadata                                  JSONB NOT NULL DEFAULT '{}',

    created_by                                INTEGER,
    created_at                                  TIMESTAMPTZ DEFAULT NOW(),
    updated_at                                   TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_pco_company_id
    ON practice_client_opportunities (company_id);

CREATE INDEX IF NOT EXISTS idx_pco_client_id
    ON practice_client_opportunities (client_id);

CREATE INDEX IF NOT EXISTS idx_pco_status
    ON practice_client_opportunities (company_id, status);

CREATE OR REPLACE FUNCTION fn_pco_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS tg_pco_updated_at ON practice_client_opportunities;
CREATE TRIGGER tg_pco_updated_at
    BEFORE UPDATE ON practice_client_opportunities
    FOR EACH ROW EXECUTE FUNCTION fn_pco_updated_at();

COMMENT ON TABLE practice_client_opportunities IS
    'Codebox 61 — Manually logged strategic opportunities per client (cross-sell/upsell candidates). NOT a sales pipeline — no stages/forecasting/quota tracking, just a manager-maintained log.';

-- ─────────────────────────────────────────────────────────────────────────────
-- TABLE: practice_client_meetings
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS practice_client_meetings (
    id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id          INTEGER NOT NULL,
    client_id            INTEGER NOT NULL,   -- plain integer, no FK — practice_clients

    meeting_date           DATE NOT NULL,
    purpose                  TEXT,
    attendees                  JSONB NOT NULL DEFAULT '[]',   -- array of free-text attendee names/roles — no attendee-linking system exists

    summary                     TEXT,
    decisions                    TEXT,
    follow_ups                    TEXT,
    next_meeting_date               DATE,

    linked_document_notes             TEXT,   -- free-text reference — no file storage/upload system exists in this codebase

    owner_team_member_id                INTEGER,   -- plain integer, no FK — practice_team_members

    metadata                              JSONB NOT NULL DEFAULT '{}',

    created_by                             INTEGER,
    created_at                               TIMESTAMPTZ DEFAULT NOW(),
    updated_at                                TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_pcm_company_id
    ON practice_client_meetings (company_id);

CREATE INDEX IF NOT EXISTS idx_pcm_client_id
    ON practice_client_meetings (client_id, meeting_date DESC);

CREATE OR REPLACE FUNCTION fn_pcm_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS tg_pcm_updated_at ON practice_client_meetings;
CREATE TRIGGER tg_pcm_updated_at
    BEFORE UPDATE ON practice_client_meetings
    FOR EACH ROW EXECUTE FUNCTION fn_pcm_updated_at();

COMMENT ON TABLE practice_client_meetings IS
    'Codebox 61 — Meeting history per client. meeting_date also feeds practice_client_success.last_meaningful_contact_date via client-success.js when a meeting is logged.';

-- ─────────────────────────────────────────────────────────────────────────────
-- TABLE: practice_client_success_events  (append-only audit log)
-- Never updated. Never deleted.
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS practice_client_success_events (
    id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id          INTEGER NOT NULL,

    event_type            TEXT NOT NULL CHECK (event_type IN (
                              'health_assessed', 'health_overridden', 'health_override_cleared',
                              'activity_created', 'activity_updated', 'activity_completed', 'activity_cancelled',
                              'meeting_logged', 'meeting_updated',
                              'opportunity_created', 'opportunity_updated', 'opportunity_won', 'opportunity_lost',
                              'contact_added', 'contact_updated', 'contact_archived',
                              'review_scheduled', 'review_completed'
                          )),
    entity_type              TEXT,    -- 'client_success' | 'activity' | 'meeting' | 'opportunity' | 'contact'
    entity_id                 INTEGER,  -- plain integer, no FK (Codebox 41 convention)
    client_id                  INTEGER,  -- plain integer, no FK — practice_clients (denormalized for fast per-client history queries)

    actor_user_id                INTEGER,
    notes                          TEXT,
    metadata                        JSONB NOT NULL DEFAULT '{}',
    created_at                       TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_pcse_company_id
    ON practice_client_success_events (company_id);

CREATE INDEX IF NOT EXISTS idx_pcse_client_id
    ON practice_client_success_events (client_id)
    WHERE client_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_pcse_created_desc
    ON practice_client_success_events (created_at DESC);

COMMENT ON TABLE practice_client_success_events IS
    'Codebox 61 — Append-only log of Client Success changes. Never updated or deleted.';
