-- Migration 119: Practice Secretarial Foundation
-- Codebox 62 — Lorenco Practice Management
--
-- NOT accounting. NOT tax. NOT payroll. NOT a client CRM. NOT document
-- management. NOT a CIPC API integration, NOT automatic submissions, NOT
-- e-signatures, NOT document generation, NOT trust accounting, NOT estate
-- planning. Fully manager-controlled, deterministic, explainable — a
-- foundation for the statutory-change WORKFLOWS that arrive in Codebox 63.
--
-- AUDIT FINDING (RULE A1/A2 — see docs/new-app/62_secretarial_foundation.md
-- Architect Freedom #1): several fields the spec lists for the Secretarial
-- Profile already exist elsewhere and are reused, NOT duplicated here:
--   practice_clients.registration_number      -- CIPC registration number
--   practice_clients.vat_number                -- VAT number
--   practice_clients.coida_registration_number  -- COIDA number
--   practice_taxpayer_profiles.income_tax_reference  -- Income tax number
--   practice_taxpayer_profiles.financial_year_end    -- Financial year-end (proper DATE, per client)
-- getCorporateProfile() in secretarial.js cross-references these live rather
-- than copying their values onto a new table. PAYE/SDL/UIF registration
-- NUMBERS were confirmed absent everywhere (only a paye_registered BOOLEAN
-- flag exists on practice_taxpayer_profiles) — those three are genuinely new
-- fields here. Company type, registration date, registered/postal address,
-- company status, CIPC status, auditor, company secretary, and financial
-- officer are also genuinely new — none exist anywhere else in the schema.
--
-- Tables created (all IF NOT EXISTS — safe to re-run):
--   practice_secretarial_profiles
--   practice_company_directors
--   practice_company_shareholders
--   practice_annual_returns
--   practice_secretarial_events

-- ─────────────────────────────────────────────────────────────────────────────
-- TABLE: practice_secretarial_profiles
-- One row per client. Fields already owned by practice_clients or
-- practice_taxpayer_profiles are deliberately NOT repeated here — see the
-- audit note above.
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS practice_secretarial_profiles (
    id                      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id               INTEGER NOT NULL,
    client_id                 INTEGER NOT NULL,   -- plain integer, no FK — practice_clients (Codebox 41 convention)

    company_type                TEXT CHECK (company_type IN ('pty_ltd', 'cc', 'npc', 'trust', 'partnership', 'sole_proprietor', 'other')),
    registration_date             DATE,

    registered_address              TEXT,
    postal_address                    TEXT,

    -- Internal, app-reasoned lifecycle state (CHECK-constrained — this app
    -- decides what these mean and drives UI off them).
    company_status                      TEXT NOT NULL DEFAULT 'active' CHECK (company_status IN ('active', 'dormant', 'deregistration_process', 'deregistered', 'in_liquidation', 'other')),
    -- Externally-defined CIPC status text (CIPC's own vocabulary — "In
    -- Business", "Business Rescue", "Final Deregistration", etc. — free text
    -- rather than CHECK-constrained, same reasoning as CPD category in
    -- Codebox 60: an external taxonomy shouldn't be hard-coded into ours).
    cipc_status                          TEXT,

    -- Registration numbers genuinely absent elsewhere in the schema (see
    -- audit note — income tax/VAT/COIDA/registration number are reused, not
    -- duplicated, from practice_clients / practice_taxpayer_profiles).
    paye_number                            TEXT,
    sdl_number                              TEXT,
    uif_number                               TEXT,

    auditor                                   TEXT,
    company_secretary                          TEXT,
    financial_officer                           TEXT,

    notes                                        TEXT,
    metadata                                      JSONB NOT NULL DEFAULT '{}',

    created_by                                    INTEGER,
    created_at                                     TIMESTAMPTZ DEFAULT NOW(),
    updated_at                                      TIMESTAMPTZ DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_psp_company_client
    ON practice_secretarial_profiles (company_id, client_id);

CREATE INDEX IF NOT EXISTS idx_psp_company_id
    ON practice_secretarial_profiles (company_id);

CREATE OR REPLACE FUNCTION fn_psp_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS tg_psp_updated_at ON practice_secretarial_profiles;
CREATE TRIGGER tg_psp_updated_at
    BEFORE UPDATE ON practice_secretarial_profiles
    FOR EACH ROW EXECUTE FUNCTION fn_psp_updated_at();

COMMENT ON TABLE practice_secretarial_profiles IS
    'Codebox 62 — Per-client CIPC/statutory profile. Registration number, VAT number, COIDA number, income tax number, and financial year-end are intentionally NOT stored here — reused live from practice_clients / practice_taxpayer_profiles by getCorporateProfile(). See migration header.';

-- ─────────────────────────────────────────────────────────────────────────────
-- TABLE: practice_company_directors
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS practice_company_directors (
    id                     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id              INTEGER NOT NULL,
    client_id                 INTEGER NOT NULL,   -- plain integer, no FK — practice_clients

    director_name               TEXT NOT NULL,
    id_or_passport_number        TEXT,   -- free text — no separate person/contact catalog exists to link to

    role                           TEXT NOT NULL DEFAULT 'executive' CHECK (role IN ('executive', 'non_executive', 'alternate')),
    appointment_date                DATE,
    resignation_date                  DATE,
    status                              TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'resigned')),

    -- Spec lists shareholding_pct as its own director field, separate from
    -- practice_company_shareholders — kept as specified even though it can
    -- drift from a matching shareholder row (a director need not be a
    -- formally registered shareholder entity). See Architect Freedom #4.
    shareholding_pct                     NUMERIC CHECK (shareholding_pct BETWEEN 0 AND 100),
    signing_authority                     BOOLEAN NOT NULL DEFAULT false,

    notes                                   TEXT,
    metadata                                 JSONB NOT NULL DEFAULT '{}',

    created_by                               INTEGER,
    created_at                                TIMESTAMPTZ DEFAULT NOW(),
    updated_at                                 TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_pcd_company_id
    ON practice_company_directors (company_id);

CREATE INDEX IF NOT EXISTS idx_pcd_client_id
    ON practice_company_directors (client_id);

CREATE INDEX IF NOT EXISTS idx_pcd_status
    ON practice_company_directors (company_id, status);

CREATE OR REPLACE FUNCTION fn_pcd_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS tg_pcd_updated_at ON practice_company_directors;
CREATE TRIGGER tg_pcd_updated_at
    BEFORE UPDATE ON practice_company_directors
    FOR EACH ROW EXECUTE FUNCTION fn_pcd_updated_at();

COMMENT ON TABLE practice_company_directors IS
    'Codebox 62 — Director register per client. Appointment/resignation events auto-record to practice_secretarial_events. Change WORKFLOWS (approvals, checklists, CIPC filing) arrive in Codebox 63 — this table is the record, not the process.';

-- ─────────────────────────────────────────────────────────────────────────────
-- TABLE: practice_company_shareholders
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS practice_company_shareholders (
    id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id          INTEGER NOT NULL,
    client_id             INTEGER NOT NULL,   -- plain integer, no FK — practice_clients

    shareholder_name        TEXT NOT NULL,
    shareholder_type          TEXT NOT NULL CHECK (shareholder_type IN ('individual', 'company', 'trust')),

    shares                      NUMERIC,
    percentage                   NUMERIC CHECK (percentage BETWEEN 0 AND 100),

    issue_date                    DATE,
    transfer_date                  DATE,
    status                          TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'transferred', 'cancelled')),

    notes                             TEXT,
    metadata                           JSONB NOT NULL DEFAULT '{}',

    created_by                         INTEGER,
    created_at                          TIMESTAMPTZ DEFAULT NOW(),
    updated_at                           TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_pcs_company_id
    ON practice_company_shareholders (company_id);

CREATE INDEX IF NOT EXISTS idx_pcs_client_id
    ON practice_company_shareholders (client_id);

CREATE INDEX IF NOT EXISTS idx_pcs_status
    ON practice_company_shareholders (company_id, status);

CREATE OR REPLACE FUNCTION fn_pcsh_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS tg_pcsh_updated_at ON practice_company_shareholders;
CREATE TRIGGER tg_pcsh_updated_at
    BEFORE UPDATE ON practice_company_shareholders
    FOR EACH ROW EXECUTE FUNCTION fn_pcsh_updated_at();

COMMENT ON TABLE practice_company_shareholders IS
    'Codebox 62 — Shareholder register per client. Share transfers auto-record to practice_secretarial_events.';

-- ─────────────────────────────────────────────────────────────────────────────
-- TABLE: practice_annual_returns
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS practice_annual_returns (
    id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id          INTEGER NOT NULL,
    client_id             INTEGER NOT NULL,   -- plain integer, no FK — practice_clients

    return_year             INTEGER NOT NULL,
    due_date                  DATE,
    submission_date            DATE,
    status                       TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'submitted', 'overdue', 'exempted')),
    reference                     TEXT,
    reminder_date                  DATE,

    notes                            TEXT,
    metadata                          JSONB NOT NULL DEFAULT '{}',

    created_by                         INTEGER,
    created_at                          TIMESTAMPTZ DEFAULT NOW(),
    updated_at                           TIMESTAMPTZ DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_par_client_year
    ON practice_annual_returns (company_id, client_id, return_year);

CREATE INDEX IF NOT EXISTS idx_par_company_id
    ON practice_annual_returns (company_id);

CREATE INDEX IF NOT EXISTS idx_par_due_date
    ON practice_annual_returns (company_id, due_date)
    WHERE status IN ('pending', 'overdue');

CREATE OR REPLACE FUNCTION fn_par_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS tg_par_updated_at ON practice_annual_returns;
CREATE TRIGGER tg_par_updated_at
    BEFORE UPDATE ON practice_annual_returns
    FOR EACH ROW EXECUTE FUNCTION fn_par_updated_at();

COMMENT ON TABLE practice_annual_returns IS
    'Codebox 62 — CIPC annual return tracking per client per year. One row per (client, year) — see uq_par_client_year.';

-- ─────────────────────────────────────────────────────────────────────────────
-- TABLE: practice_secretarial_events  (append-only audit log + Timeline source)
-- Never updated. Never deleted. GET /timeline reads directly from this table.
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS practice_secretarial_events (
    id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id          INTEGER NOT NULL,
    client_id             INTEGER NOT NULL,   -- plain integer, no FK — practice_clients (every event is client-scoped, unlike other modules' events tables)

    event_type              TEXT NOT NULL CHECK (event_type IN (
                                'profile_created', 'profile_updated',
                                'director_appointed', 'director_resigned', 'director_updated',
                                'shareholder_added', 'shareholder_updated', 'share_transferred',
                                'annual_return_created', 'annual_return_submitted', 'annual_return_updated',
                                'company_detail_changed', 'manager_note'
                             )),
    entity_type                TEXT,    -- 'profile' | 'director' | 'shareholder' | 'annual_return'
    entity_id                    INTEGER,  -- plain integer, no FK (Codebox 41 convention)

    actor_user_id                  INTEGER,
    notes                            TEXT,
    metadata                          JSONB NOT NULL DEFAULT '{}',
    created_at                         TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_pse_company_id
    ON practice_secretarial_events (company_id);

CREATE INDEX IF NOT EXISTS idx_pse_client_id
    ON practice_secretarial_events (client_id, created_at DESC);

COMMENT ON TABLE practice_secretarial_events IS
    'Codebox 62 — Append-only log of Secretarial changes per client. Never updated or deleted. Doubles as the Timeline data source (GET /timeline reads this directly — no separate timeline table).';
