-- Migration 120: Practice Secretarial Workflows + Statutory Change Management
-- Codebox 63 — Lorenco Practice Management
--
-- NOT CIPC API. NOT automatic CIPC filing. NOT document generation. NOT
-- e-signatures. A manual internal workflow foundation — future CIPC
-- integration must plug into this workflow, not replace it.
--
-- Turns Secretarial (Codebox 62) from registers into controlled statutory
-- change management: every director appointment/resignation, share transfer,
-- address change, etc. becomes a case with a checklist, an approval step,
-- an effective date, and an append-only audit trail — never a direct,
-- uncontrolled edit to the Codebox 62 registers.
--
-- AUDIT (RULE A1 — see docs/new-app/63_secretarial_workflows.md Architect
-- Freedom #1-#3): confirmed practice_secretarial_profiles (migration 119)
-- has registered_address, postal_address, company_secretary, auditor,
-- company_status — all safe register-update targets for the matching
-- change_types below. It has NO field for "accounting officer" (only the
-- distinct "financial_officer") and NO field for "public officer" at all —
-- accounting_officer_change and public_officer_change are therefore NOT
-- auto-implemented (secretarial-workflows.js blocks these with 422 rather
-- than guess-mapping onto a field that may mean something legally
-- different). Company NAME lives on practice_clients.name (client master
-- data, out of this module's bounds) and financial_year_end lives on
-- practice_taxpayer_profiles (a different module's table) — company_name_change
-- and financial_year_end_change are likewise blocked with 422. See the
-- router's IMPLEMENTATION_RULES map for the definitive, single source of
-- truth on which change_types are auto-implemented vs. always manual.
--
-- Tables created (all IF NOT EXISTS — safe to re-run):
--   practice_secretarial_change_cases
--   practice_secretarial_change_checklist_items
--   practice_secretarial_change_events

-- ─────────────────────────────────────────────────────────────────────────────
-- TABLE: practice_secretarial_change_cases
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS practice_secretarial_change_cases (
    id                      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id               INTEGER NOT NULL,
    client_id                  INTEGER NOT NULL,   -- plain integer, no FK — practice_clients (Codebox 41 convention)

    change_type                  TEXT NOT NULL CHECK (change_type IN (
                                     'director_appointment', 'director_resignation',
                                     'share_transfer', 'share_issue', 'share_cancellation',
                                     'registered_address_change', 'postal_address_change',
                                     'company_name_change', 'financial_year_end_change',
                                     'company_secretary_change', 'auditor_change',
                                     'accounting_officer_change', 'public_officer_change',
                                     'company_status_change', 'annual_return', 'custom'
                                 )),

    case_status                    TEXT NOT NULL DEFAULT 'draft' CHECK (case_status IN (
                                       'draft', 'preparing', 'awaiting_documents', 'ready_for_review',
                                       'approved', 'implemented', 'completed', 'rejected', 'cancelled'
                                   )),

    change_title                      TEXT NOT NULL,
    change_summary                     TEXT,

    requested_by_name                    TEXT,
    requested_date                         DATE,
    effective_date                           DATE,

    approved_by                                INTEGER,   -- plain integer, no FK — users.id
    approved_at                                  TIMESTAMPTZ,
    implemented_by                                 INTEGER,
    implemented_at                                   TIMESTAMPTZ,
    completed_by                                       INTEGER,
    completed_at                                         TIMESTAMPTZ,

    rejection_reason                                       TEXT,
    notes                                                     TEXT,
    internal_notes                                             TEXT,

    -- Structured, change_type-specific data. Deliberately schemaless — 16
    -- change types with wildly different field needs (a director's ID number
    -- vs. a new registered address vs. a share transfer's parties) would
    -- otherwise need 16 sets of nullable columns. payload is the case's
    -- working data; before/after_snapshot capture register state at the
    -- moment of implementation for audit purposes (see events table).
    payload                                                       JSONB NOT NULL DEFAULT '{}',
    before_snapshot                                                JSONB,
    after_snapshot                                                  JSONB,
    settings                                                         JSONB NOT NULL DEFAULT '{}',

    created_by                                                       INTEGER,
    updated_by                                                         INTEGER,
    created_at                                                          TIMESTAMPTZ DEFAULT NOW(),
    updated_at                                                           TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_pscc_company_id     ON practice_secretarial_change_cases (company_id);
CREATE INDEX IF NOT EXISTS idx_pscc_client_id       ON practice_secretarial_change_cases (client_id);
CREATE INDEX IF NOT EXISTS idx_pscc_change_type     ON practice_secretarial_change_cases (company_id, change_type);
CREATE INDEX IF NOT EXISTS idx_pscc_case_status     ON practice_secretarial_change_cases (company_id, case_status);
CREATE INDEX IF NOT EXISTS idx_pscc_effective_date  ON practice_secretarial_change_cases (company_id, effective_date) WHERE effective_date IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_pscc_created_at      ON practice_secretarial_change_cases (created_at DESC);

CREATE OR REPLACE FUNCTION fn_pscc_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS tg_pscc_updated_at ON practice_secretarial_change_cases;
CREATE TRIGGER tg_pscc_updated_at
    BEFORE UPDATE ON practice_secretarial_change_cases
    FOR EACH ROW EXECUTE FUNCTION fn_pscc_updated_at();

COMMENT ON TABLE practice_secretarial_change_cases IS
    'Codebox 63 — Statutory change case register. The control point for every director/shareholder/profile mutation — Codebox 62''s registers are never edited directly through this workflow except via POST /:id/implement, which is itself gated on case_status = approved.';

-- ─────────────────────────────────────────────────────────────────────────────
-- TABLE: practice_secretarial_change_checklist_items
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS practice_secretarial_change_checklist_items (
    id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id          INTEGER NOT NULL,
    change_case_id        INTEGER NOT NULL,   -- plain integer, no FK — practice_secretarial_change_cases

    item_name               TEXT NOT NULL,
    item_type                 TEXT NOT NULL CHECK (item_type IN (
                                 'document', 'approval', 'register_update', 'cipc_step',
                                 'client_confirmation', 'internal_review', 'resolution', 'minute', 'custom'
                             )),

    required                   BOOLEAN NOT NULL DEFAULT true,
    completed                    BOOLEAN NOT NULL DEFAULT false,
    completed_at                   TIMESTAMPTZ,
    completed_by                     INTEGER,

    notes                               TEXT,
    sort_order                           INTEGER NOT NULL DEFAULT 0,

    created_at                             TIMESTAMPTZ DEFAULT NOW(),
    updated_at                               TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_pscci_company_id ON practice_secretarial_change_checklist_items (company_id);
CREATE INDEX IF NOT EXISTS idx_pscci_case_id     ON practice_secretarial_change_checklist_items (change_case_id, sort_order);

CREATE OR REPLACE FUNCTION fn_pscci_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS tg_pscci_updated_at ON practice_secretarial_change_checklist_items;
CREATE TRIGGER tg_pscci_updated_at
    BEFORE UPDATE ON practice_secretarial_change_checklist_items
    FOR EACH ROW EXECUTE FUNCTION fn_pscci_updated_at();

COMMENT ON TABLE practice_secretarial_change_checklist_items IS
    'Codebox 63 — Per-case checklist. Generated from CHECKLIST_DEFAULTS per change_type (see secretarial-workflows.js) or added manually. required items gate approval unless a manager override reason is recorded on the case.';

-- ─────────────────────────────────────────────────────────────────────────────
-- TABLE: practice_secretarial_change_events  (append-only audit log)
-- Never updated. Never deleted. No workflow status change happens without
-- a matching event row — enforced entirely at the application layer in
-- secretarial-workflows.js (every status-changing route writes its event
-- inside the same handler, before responding).
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS practice_secretarial_change_events (
    id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id          INTEGER NOT NULL,
    change_case_id        INTEGER NOT NULL,   -- plain integer, no FK — practice_secretarial_change_cases

    event_type              TEXT NOT NULL CHECK (event_type IN (
                                'change_case_created', 'change_case_updated',
                                'checklist_generated', 'checklist_item_updated',
                                'submitted_for_review', 'change_approved', 'change_rejected',
                                'change_implemented', 'change_completed', 'change_cancelled',
                                'register_updated', 'timeline_event_created'
                             )),
    old_status                TEXT,
    new_status                  TEXT,

    actor_user_id                 INTEGER,
    notes                           TEXT,
    metadata                         JSONB NOT NULL DEFAULT '{}',
    created_at                        TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_pscce_company_id ON practice_secretarial_change_events (company_id);
CREATE INDEX IF NOT EXISTS idx_pscce_case_id     ON practice_secretarial_change_events (change_case_id, created_at DESC);

COMMENT ON TABLE practice_secretarial_change_events IS
    'Codebox 63 — Append-only log of statutory change case activity. Never updated or deleted.';
