-- Migration 121: Secretarial Resolutions + Minutes Register Foundation
-- Codebox 64 — Lorenco Practice Management
--
-- NOT PDF generation. NOT e-signature. NOT CIPC submission. NOT document
-- storage. Structured governance record keeping only — future PDF/
-- e-signature must plug into these records, not replace them.
--
-- Codebox 63 controls the statutory CHANGE workflow (director appointments,
-- address changes, etc.). This codebox creates the governance DECISION
-- register behind those changes: who approved what, when, under which
-- authority, and which resolution/meeting supports it.
--
-- AUDIT (RULE A1 — see docs/new-app/64_secretarial_governance_register.md
-- Architect Freedom #1): confirmed no pre-existing tables with these names.
-- Note: practice_client_meetings (Codebox 61, Client Success) already exists
-- but is a DIFFERENT concept — relationship/communication meetings (quarterly
-- reviews, business reviews). practice_secretarial_meetings here is STATUTORY
-- governance meetings (directors meetings, AGMs) with attendees, minutes, and
-- resolutions — the two are never confused or merged; see docs Architect
-- Freedom #1 for the full distinction.
--
-- Tables created (all IF NOT EXISTS — safe to re-run):
--   practice_secretarial_resolutions
--   practice_secretarial_meetings
--   practice_secretarial_meeting_attendees
--   practice_secretarial_decisions
--   practice_secretarial_governance_events

-- ─────────────────────────────────────────────────────────────────────────────
-- TABLE: practice_secretarial_resolutions
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS practice_secretarial_resolutions (
    id                      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id               INTEGER NOT NULL,
    client_id                  INTEGER NOT NULL,   -- plain integer, no FK — practice_clients (Codebox 41 convention)
    change_case_id               INTEGER,            -- plain integer, no FK — practice_secretarial_change_cases (Codebox 63). Nullable — not every resolution supports a statutory change.

    resolution_type                 TEXT NOT NULL CHECK (resolution_type IN (
                                        'directors_resolution', 'shareholders_resolution', 'written_resolution',
                                        'ordinary_resolution', 'special_resolution', 'trustee_resolution',
                                        'member_resolution', 'custom'
                                    )),
    resolution_status                 TEXT NOT NULL DEFAULT 'draft' CHECK (resolution_status IN (
                                          'draft', 'prepared', 'approved', 'signed', 'implemented', 'archived', 'cancelled'
                                      )),

    resolution_title                     TEXT NOT NULL,
    resolution_summary                     TEXT,
    resolution_date                          DATE,
    effective_date                             DATE,

    prepared_by                                  TEXT,   -- free text (person's name) — no separate person catalog exists, same convention as practice_company_directors.director_name
    approved_by                                    INTEGER,   -- plain integer — users.id (the staff member who actioned the approval in-app)
    approved_at                                      TIMESTAMPTZ,
    signed_at                                          TIMESTAMPTZ,
    implemented_at                                       TIMESTAMPTZ,

    reference_number                                       TEXT,
    notes                                                     TEXT,
    internal_notes                                             TEXT,

    -- A point-in-time copy of the resolution's key fields at signing — NOT a
    -- generated document (no PDF/e-signature here), just an auditable
    -- structured snapshot so later edits to notes/summary can never quietly
    -- rewrite what was actually signed off.
    content_snapshot                                             JSONB,
    settings                                                       JSONB NOT NULL DEFAULT '{}',

    created_by                                                     INTEGER,
    updated_by                                                       INTEGER,
    created_at                                                        TIMESTAMPTZ DEFAULT NOW(),
    updated_at                                                          TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_psr_company_id        ON practice_secretarial_resolutions (company_id);
CREATE INDEX IF NOT EXISTS idx_psr_client_id          ON practice_secretarial_resolutions (client_id);
CREATE INDEX IF NOT EXISTS idx_psr_change_case_id     ON practice_secretarial_resolutions (change_case_id) WHERE change_case_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_psr_resolution_type    ON practice_secretarial_resolutions (company_id, resolution_type);
CREATE INDEX IF NOT EXISTS idx_psr_resolution_status  ON practice_secretarial_resolutions (company_id, resolution_status);
CREATE INDEX IF NOT EXISTS idx_psr_resolution_date    ON practice_secretarial_resolutions (company_id, resolution_date);

CREATE OR REPLACE FUNCTION fn_psr_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS tg_psr_updated_at ON practice_secretarial_resolutions;
CREATE TRIGGER tg_psr_updated_at
    BEFORE UPDATE ON practice_secretarial_resolutions
    FOR EACH ROW EXECUTE FUNCTION fn_psr_updated_at();

COMMENT ON TABLE practice_secretarial_resolutions IS
    'Codebox 64 — Resolutions register. Optionally linked to a Codebox 63 statutory change case. NOT PDF generation, NOT e-signature — content_snapshot is a structured audit copy, not a generated/signed document.';

-- ─────────────────────────────────────────────────────────────────────────────
-- TABLE: practice_secretarial_meetings
-- Distinct from practice_client_meetings (Codebox 61) — see migration header.
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS practice_secretarial_meetings (
    id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id          INTEGER NOT NULL,
    client_id             INTEGER NOT NULL,   -- plain integer, no FK — practice_clients
    change_case_id          INTEGER,            -- plain integer, no FK — practice_secretarial_change_cases. Nullable.

    meeting_type               TEXT NOT NULL CHECK (meeting_type IN (
                                  'directors_meeting', 'shareholders_meeting', 'annual_general_meeting',
                                  'special_general_meeting', 'trustees_meeting', 'members_meeting', 'custom'
                              )),
    meeting_status               TEXT NOT NULL DEFAULT 'planned' CHECK (meeting_status IN (
                                     'planned', 'held', 'minutes_draft', 'minutes_approved', 'completed', 'cancelled'
                                 )),

    meeting_title                  TEXT NOT NULL,
    meeting_date                     DATE,
    meeting_location                   TEXT,
    chairperson_name                     TEXT,
    minute_taker_name                      TEXT,

    agenda_summary                           TEXT,
    minutes_summary                            TEXT,
    decisions_summary                            TEXT,
    next_meeting_date                              DATE,

    notes                                            TEXT,
    internal_notes                                     TEXT,
    settings                                             JSONB NOT NULL DEFAULT '{}',

    created_by                                             INTEGER,
    updated_by                                               INTEGER,
    created_at                                                TIMESTAMPTZ DEFAULT NOW(),
    updated_at                                                  TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_psm_company_id     ON practice_secretarial_meetings (company_id);
CREATE INDEX IF NOT EXISTS idx_psm_client_id       ON practice_secretarial_meetings (client_id);
CREATE INDEX IF NOT EXISTS idx_psm_change_case_id  ON practice_secretarial_meetings (change_case_id) WHERE change_case_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_psm_meeting_type    ON practice_secretarial_meetings (company_id, meeting_type);
CREATE INDEX IF NOT EXISTS idx_psm_meeting_status  ON practice_secretarial_meetings (company_id, meeting_status);
CREATE INDEX IF NOT EXISTS idx_psm_meeting_date    ON practice_secretarial_meetings (company_id, meeting_date);

CREATE OR REPLACE FUNCTION fn_psm_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS tg_psm_updated_at ON practice_secretarial_meetings;
CREATE TRIGGER tg_psm_updated_at
    BEFORE UPDATE ON practice_secretarial_meetings
    FOR EACH ROW EXECUTE FUNCTION fn_psm_updated_at();

COMMENT ON TABLE practice_secretarial_meetings IS
    'Codebox 64 — Statutory governance meetings (directors/shareholders/AGM/trustees/members), distinct from practice_client_meetings (Codebox 61, relationship meetings). Optionally linked to a Codebox 63 statutory change case.';

-- ─────────────────────────────────────────────────────────────────────────────
-- TABLE: practice_secretarial_meeting_attendees
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS practice_secretarial_meeting_attendees (
    id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id          INTEGER NOT NULL,
    meeting_id            INTEGER NOT NULL,   -- plain integer, no FK — practice_secretarial_meetings

    attendee_name           TEXT NOT NULL,
    attendee_role             TEXT,
    attendee_type               TEXT NOT NULL CHECK (attendee_type IN ('director', 'shareholder', 'trustee', 'member', 'advisor', 'staff', 'other')),

    attendance_status             TEXT NOT NULL DEFAULT 'invited' CHECK (attendance_status IN ('invited', 'present', 'absent', 'proxy', 'apology')),

    email                            TEXT,
    notes                              TEXT,

    created_at                          TIMESTAMPTZ DEFAULT NOW(),
    updated_at                            TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_psma_company_id ON practice_secretarial_meeting_attendees (company_id);
CREATE INDEX IF NOT EXISTS idx_psma_meeting_id  ON practice_secretarial_meeting_attendees (meeting_id);

CREATE OR REPLACE FUNCTION fn_psma_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS tg_psma_updated_at ON practice_secretarial_meeting_attendees;
CREATE TRIGGER tg_psma_updated_at
    BEFORE UPDATE ON practice_secretarial_meeting_attendees
    FOR EACH ROW EXECUTE FUNCTION fn_psma_updated_at();

COMMENT ON TABLE practice_secretarial_meeting_attendees IS
    'Codebox 64 — Attendee/attendance record per governance meeting.';

-- ─────────────────────────────────────────────────────────────────────────────
-- TABLE: practice_secretarial_decisions
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS practice_secretarial_decisions (
    id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id          INTEGER NOT NULL,
    client_id             INTEGER NOT NULL,   -- plain integer, no FK — practice_clients
    meeting_id              INTEGER,            -- plain integer, no FK — practice_secretarial_meetings. Nullable.
    resolution_id             INTEGER,            -- plain integer, no FK — practice_secretarial_resolutions. Nullable.
    change_case_id              INTEGER,            -- plain integer, no FK — practice_secretarial_change_cases. Nullable.

    decision_type                  TEXT NOT NULL CHECK (decision_type IN (
                                       'approval', 'rejection', 'instruction', 'noting', 'delegation',
                                       'statutory_change', 'financial', 'governance', 'custom'
                                   )),
    decision_status                  TEXT NOT NULL DEFAULT 'draft' CHECK (decision_status IN ('draft', 'approved', 'implemented', 'cancelled')),

    decision_title                     TEXT NOT NULL,
    decision_summary                     TEXT,
    decision_date                          DATE,
    effective_date                           DATE,

    responsible_team_member_id                 INTEGER,   -- plain integer, no FK — practice_team_members. Nullable.
    follow_up_required                           BOOLEAN NOT NULL DEFAULT false,
    follow_up_due_date                             DATE,

    notes                                            TEXT,
    internal_notes                                     TEXT,
    metadata                                             JSONB NOT NULL DEFAULT '{}',

    created_by                                             INTEGER,
    updated_by                                               INTEGER,
    created_at                                                TIMESTAMPTZ DEFAULT NOW(),
    updated_at                                                  TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_psd_company_id     ON practice_secretarial_decisions (company_id);
CREATE INDEX IF NOT EXISTS idx_psd_client_id       ON practice_secretarial_decisions (client_id);
CREATE INDEX IF NOT EXISTS idx_psd_meeting_id      ON practice_secretarial_decisions (meeting_id) WHERE meeting_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_psd_resolution_id   ON practice_secretarial_decisions (resolution_id) WHERE resolution_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_psd_change_case_id  ON practice_secretarial_decisions (change_case_id) WHERE change_case_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_psd_decision_status ON practice_secretarial_decisions (company_id, decision_status);
CREATE INDEX IF NOT EXISTS idx_psd_decision_date   ON practice_secretarial_decisions (company_id, decision_date);

CREATE OR REPLACE FUNCTION fn_psd_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS tg_psd_updated_at ON practice_secretarial_decisions;
CREATE TRIGGER tg_psd_updated_at
    BEFORE UPDATE ON practice_secretarial_decisions
    FOR EACH ROW EXECUTE FUNCTION fn_psd_updated_at();

COMMENT ON TABLE practice_secretarial_decisions IS
    'Codebox 64 — Written decision records. Optionally linked to a meeting, a resolution, and/or a Codebox 63 statutory change case — all three links are independent and optional.';

-- ─────────────────────────────────────────────────────────────────────────────
-- TABLE: practice_secretarial_governance_events  (append-only audit log)
-- Never updated. Never deleted. No workflow status change without an event —
-- enforced at the application layer in secretarial-governance.js.
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS practice_secretarial_governance_events (
    id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id          INTEGER NOT NULL,

    source_type           TEXT NOT NULL CHECK (source_type IN ('resolution', 'meeting', 'attendee', 'decision')),
    source_id               INTEGER NOT NULL,   -- plain integer, no FK (Codebox 41 convention) — points into the table matching source_type
    client_id                 INTEGER,            -- plain integer, no FK — practice_clients (denormalized for fast per-client history queries, same pattern as practice_client_success_events)

    event_type                  TEXT NOT NULL CHECK (event_type IN (
                                    'resolution_created', 'resolution_updated', 'resolution_approved', 'resolution_signed',
                                    'resolution_implemented', 'resolution_cancelled',
                                    'meeting_created', 'meeting_updated', 'meeting_held', 'minutes_approved', 'meeting_cancelled',
                                    'attendee_added', 'attendee_updated',
                                    'decision_created', 'decision_updated', 'decision_approved', 'decision_implemented', 'decision_cancelled'
                                )),
    old_status                    TEXT,
    new_status                      TEXT,

    actor_user_id                     INTEGER,
    notes                               TEXT,
    metadata                             JSONB NOT NULL DEFAULT '{}',
    created_at                            TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_psge_company_id  ON practice_secretarial_governance_events (company_id);
CREATE INDEX IF NOT EXISTS idx_psge_source       ON practice_secretarial_governance_events (source_type, source_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_psge_client_id    ON practice_secretarial_governance_events (client_id) WHERE client_id IS NOT NULL;

COMMENT ON TABLE practice_secretarial_governance_events IS
    'Codebox 64 — Append-only log of resolution/meeting/attendee/decision activity. Never updated or deleted. Governance-significant events are ALSO pushed into practice_secretarial_events (Codebox 62''s Timeline) via secretarial.js''s writeSecretarialEvent() export — this table is not a second timeline, it is this module''s own detailed audit trail.';
