-- Migration 122: Secretarial Beneficial Ownership + Ownership Chain Foundation
-- Codebox 65 — Lorenco Practice Management
--
-- NOT CIPC API. NOT automatic filing. NOT legal advice. NOT document
-- generation. Structured BO recordkeeping and readiness tracking only —
-- future CIPC filing must plug into this foundation, not replace it.
--
-- AUDIT (RULE A1 — see docs/new-app/65_beneficial_ownership.md Architect
-- Freedom #1): confirmed no pre-existing beneficial-ownership tables.
-- 'beneficial_ownership' already appears as a plain TASK_TYPE/DEADLINE_TYPE
-- enum value (migration 011, index.js compliance suggestions) — a lightweight
-- tag on unrelated tables (practice_tasks/practice_deadlines), not a
-- recordkeeping system. No collision; both are left untouched.
--
-- This module explicitly does NOT duplicate practice_company_shareholders
-- (Codebox 62) — getBeneficialOwnershipProfile() reads it live. Beneficial
-- owners and ownership chains are a separate, ADDITIONAL layer answering
-- "who is ultimately behind the shareholder," not a replacement for the
-- shareholder register itself.
--
-- Tables created (all IF NOT EXISTS — safe to re-run):
--   practice_beneficial_owners
--   practice_ownership_chains
--   practice_bo_readiness_items
--   practice_beneficial_ownership_events

-- ─────────────────────────────────────────────────────────────────────────────
-- TABLE: practice_beneficial_owners
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS practice_beneficial_owners (
    id                      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id               INTEGER NOT NULL,
    client_id                  INTEGER NOT NULL,   -- plain integer, no FK — practice_clients (Codebox 41 convention)

    owner_type                   TEXT NOT NULL CHECK (owner_type IN ('natural_person', 'company', 'trust', 'partnership', 'nominee', 'other')),

    owner_name                     TEXT NOT NULL,
    id_number                        TEXT,   -- natural persons
    registration_number                TEXT,   -- companies/partnerships
    trust_number                         TEXT,   -- trusts
    tax_number                             TEXT,
    nationality                              TEXT,
    country_of_residence                       TEXT,

    control_type                                 TEXT NOT NULL CHECK (control_type IN (
                                                     'shareholding', 'voting_rights', 'board_control', 'trustee_control',
                                                     'beneficiary_control', 'nominee_control', 'agreement_control', 'other_control'
                                                 )),

    -- See migration header + secretarial docs for the full percentage
    -- calculation rules (never guessed — null + confidence=unknown when
    -- data is insufficient).
    direct_percentage                              NUMERIC CHECK (direct_percentage BETWEEN 0 AND 100),
    indirect_percentage                              NUMERIC CHECK (indirect_percentage BETWEEN 0 AND 100),
    effective_percentage                               NUMERIC CHECK (effective_percentage BETWEEN 0 AND 100),

    is_natural_person                                    BOOLEAN NOT NULL DEFAULT false,
    is_reportable                                          BOOLEAN NOT NULL DEFAULT false,
    reporting_threshold_met                                  BOOLEAN,   -- null = unknown (insufficient data), not false

    status                                                     TEXT NOT NULL DEFAULT 'draft' CHECK (status IN (
                                                                   'draft', 'active', 'incomplete', 'verified', 'not_reportable', 'archived'
                                                               )),
    verification_status                                          TEXT NOT NULL DEFAULT 'not_started' CHECK (verification_status IN (
                                                                       'not_started', 'requested', 'documents_received', 'verified', 'rejected', 'expired'
                                                                   )),

    source_note                                                    TEXT,   -- where this owner's info came from (e.g. "client-provided org chart", "trust deed clause 4")
    verification_notes                                               TEXT,
    notes                                                              TEXT,
    internal_notes                                                       TEXT,
    settings                                                               JSONB NOT NULL DEFAULT '{}',

    created_by                                                             INTEGER,
    updated_by                                                               INTEGER,
    created_at                                                                TIMESTAMPTZ DEFAULT NOW(),
    updated_at                                                                  TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_pbo_company_id           ON practice_beneficial_owners (company_id);
CREATE INDEX IF NOT EXISTS idx_pbo_client_id             ON practice_beneficial_owners (client_id);
CREATE INDEX IF NOT EXISTS idx_pbo_owner_type            ON practice_beneficial_owners (company_id, owner_type);
CREATE INDEX IF NOT EXISTS idx_pbo_status                ON practice_beneficial_owners (company_id, status);
CREATE INDEX IF NOT EXISTS idx_pbo_verification_status   ON practice_beneficial_owners (company_id, verification_status);
CREATE INDEX IF NOT EXISTS idx_pbo_is_reportable         ON practice_beneficial_owners (company_id, is_reportable);

CREATE OR REPLACE FUNCTION fn_pbo_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS tg_pbo_updated_at ON practice_beneficial_owners;
CREATE TRIGGER tg_pbo_updated_at
    BEFORE UPDATE ON practice_beneficial_owners
    FOR EACH ROW EXECUTE FUNCTION fn_pbo_updated_at();

COMMENT ON TABLE practice_beneficial_owners IS
    'Codebox 65 — Beneficial owner register per client. An ADDITIONAL layer on top of practice_company_shareholders (Codebox 62), not a replacement — a beneficial owner may or may not be a direct shareholder (e.g. a natural person behind a corporate/trust shareholder).';

-- ─────────────────────────────────────────────────────────────────────────────
-- TABLE: practice_ownership_chains
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS practice_ownership_chains (
    id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id          INTEGER NOT NULL,
    client_id             INTEGER NOT NULL,   -- plain integer, no FK — practice_clients

    chain_name               TEXT NOT NULL,
    chain_status                TEXT NOT NULL DEFAULT 'draft' CHECK (chain_status IN ('draft', 'active', 'verified', 'incomplete', 'archived')),

    root_holder_type              TEXT NOT NULL CHECK (root_holder_type IN ('shareholder', 'company', 'trust', 'natural_person', 'nominee', 'other')),
    root_holder_name                TEXT NOT NULL,
    root_holder_reference_id          INTEGER,   -- plain integer, no FK — practice_company_shareholders.id when root_holder_type = 'shareholder'. Nullable.

    ultimate_owner_id                   INTEGER,   -- plain integer, no FK — practice_beneficial_owners.id. Nullable — a chain can exist before its ultimate owner is confirmed.

    -- Ordered array of intermediate holding steps, e.g.
    -- [{"holder_name": "ABC Trust", "holder_type": "trust", "percentage": 60}, ...]
    -- Structured text/JSON only, per spec — never rendered as a graph here.
    chain_path                            JSONB NOT NULL DEFAULT '[]',

    direct_percentage                       NUMERIC CHECK (direct_percentage BETWEEN 0 AND 100),
    indirect_percentage                       NUMERIC CHECK (indirect_percentage BETWEEN 0 AND 100),
    effective_percentage                        NUMERIC CHECK (effective_percentage BETWEEN 0 AND 100),

    calculation_method                            TEXT NOT NULL DEFAULT 'unknown' CHECK (calculation_method IN ('direct', 'multiplied_chain', 'manual_override', 'unknown')),
    confidence                                      TEXT NOT NULL DEFAULT 'unknown' CHECK (confidence IN ('high', 'medium', 'low', 'unknown')),

    missing_information                               TEXT,
    notes                                               TEXT,
    internal_notes                                        TEXT,
    settings                                                JSONB NOT NULL DEFAULT '{}',

    created_by                                                INTEGER,
    updated_by                                                  INTEGER,
    created_at                                                   TIMESTAMPTZ DEFAULT NOW(),
    updated_at                                                     TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_poc_company_id        ON practice_ownership_chains (company_id);
CREATE INDEX IF NOT EXISTS idx_poc_client_id          ON practice_ownership_chains (client_id);
CREATE INDEX IF NOT EXISTS idx_poc_chain_status       ON practice_ownership_chains (company_id, chain_status);
CREATE INDEX IF NOT EXISTS idx_poc_ultimate_owner_id  ON practice_ownership_chains (ultimate_owner_id) WHERE ultimate_owner_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_poc_confidence         ON practice_ownership_chains (company_id, confidence);

CREATE OR REPLACE FUNCTION fn_poc_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS tg_poc_updated_at ON practice_ownership_chains;
CREATE TRIGGER tg_poc_updated_at
    BEFORE UPDATE ON practice_ownership_chains
    FOR EACH ROW EXECUTE FUNCTION fn_poc_updated_at();

COMMENT ON TABLE practice_ownership_chains IS
    'Codebox 65 — Traces a path from a direct holder (often a practice_company_shareholders row) down to an ultimate beneficial owner. chain_path is structured JSON, never a generated graph/visualisation.';

-- ─────────────────────────────────────────────────────────────────────────────
-- TABLE: practice_bo_readiness_items
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS practice_bo_readiness_items (
    id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id          INTEGER NOT NULL,
    client_id             INTEGER NOT NULL,   -- plain integer, no FK — practice_clients
    beneficial_owner_id     INTEGER,             -- plain integer, no FK — practice_beneficial_owners. Nullable — some items are client-level, not owner-specific.
    ownership_chain_id        INTEGER,             -- plain integer, no FK — practice_ownership_chains. Nullable.

    item_type                    TEXT NOT NULL CHECK (item_type IN (
                                     'owner_identity', 'owner_address', 'ownership_percentage', 'chain_support',
                                     'trust_deed', 'company_register', 'nominee_declaration', 'resolution',
                                     'cipc_form', 'review', 'custom'
                                 )),
    item_name                      TEXT NOT NULL,
    status                           TEXT NOT NULL DEFAULT 'required' CHECK (status IN (
                                         'required', 'requested', 'received', 'verified', 'waived', 'blocked', 'not_applicable'
                                     )),
    required                          BOOLEAN NOT NULL DEFAULT true,
    due_date                            DATE,

    notes                                  TEXT,

    created_by                              INTEGER,
    updated_by                                INTEGER,
    created_at                                 TIMESTAMPTZ DEFAULT NOW(),
    updated_at                                   TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_pbri_company_id           ON practice_bo_readiness_items (company_id);
CREATE INDEX IF NOT EXISTS idx_pbri_client_id             ON practice_bo_readiness_items (client_id);
CREATE INDEX IF NOT EXISTS idx_pbri_beneficial_owner_id   ON practice_bo_readiness_items (beneficial_owner_id) WHERE beneficial_owner_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_pbri_ownership_chain_id    ON practice_bo_readiness_items (ownership_chain_id) WHERE ownership_chain_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_pbri_status                ON practice_bo_readiness_items (company_id, status);
CREATE INDEX IF NOT EXISTS idx_pbri_item_type             ON practice_bo_readiness_items (company_id, item_type);

CREATE OR REPLACE FUNCTION fn_pbri_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS tg_pbri_updated_at ON practice_bo_readiness_items;
CREATE TRIGGER tg_pbri_updated_at
    BEFORE UPDATE ON practice_bo_readiness_items
    FOR EACH ROW EXECUTE FUNCTION fn_pbri_updated_at();

COMMENT ON TABLE practice_bo_readiness_items IS
    'Codebox 65 — Per-client BO readiness checklist. Generated deterministically from owner/chain characteristics (see beneficial-ownership.js generateReadinessItems()) or added manually.';

-- ─────────────────────────────────────────────────────────────────────────────
-- TABLE: practice_beneficial_ownership_events  (append-only audit log)
-- Never updated. Never deleted. No owner/chain verification and no readiness
-- recalculation without a matching event — enforced at the application layer.
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS practice_beneficial_ownership_events (
    id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id          INTEGER NOT NULL,
    client_id             INTEGER,   -- plain integer, no FK — practice_clients (denormalized for fast per-client history queries)

    source_type             TEXT NOT NULL CHECK (source_type IN ('beneficial_owner', 'ownership_chain', 'readiness_item')),
    source_id                  INTEGER NOT NULL,   -- plain integer, no FK (Codebox 41 convention) — points into the table matching source_type

    event_type                    TEXT NOT NULL CHECK (event_type IN (
                                      'bo_owner_created', 'bo_owner_updated', 'bo_owner_verified', 'bo_owner_archived',
                                      'ownership_chain_created', 'ownership_chain_updated', 'ownership_chain_verified', 'ownership_chain_archived',
                                      'readiness_item_created', 'readiness_item_updated', 'bo_readiness_recalculated'
                                  )),
    old_status                      TEXT,
    new_status                        TEXT,

    actor_user_id                       INTEGER,
    notes                                  TEXT,
    metadata                                JSONB NOT NULL DEFAULT '{}',
    created_at                                TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_pboe_company_id  ON practice_beneficial_ownership_events (company_id);
CREATE INDEX IF NOT EXISTS idx_pboe_source       ON practice_beneficial_ownership_events (source_type, source_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_pboe_client_id    ON practice_beneficial_ownership_events (client_id) WHERE client_id IS NOT NULL;

COMMENT ON TABLE practice_beneficial_ownership_events IS
    'Codebox 65 — Append-only log of beneficial owner/ownership chain/readiness item activity. Never updated or deleted.';
