-- Migration 123: Secretarial Statutory Calendar + Compliance Scheduler
-- Codebox 67 — Lorenco Practice Management
--
-- NOT another Deadlines module. Practice Deadlines (practice_deadlines,
-- migrations 007/011/058) remains the master task/deadline system — this
-- module defines statutory OBLIGATIONS (what's due, how often, under what
-- rule) and synchronises them with practice_deadlines by LINKING to an
-- existing/created deadline row, never duplicating deadline management.
--
-- NOT CIPC API. NOT automatic submissions. NOT cron jobs. NOT calendar sync
-- (Google/Outlook). NOT email/SMS/push reminders.
--
-- AUDIT (RULE A1 — see docs/new-app/67_secretarial_calendar.md Architect
-- Freedom #1): confirmed practice_deadlines (migration 007, extended by
-- 011/058) already has compliance_area, deadline_type, due_date, status,
-- reminder_date, responsible_team_member_id, is_active, settings — this is
-- the reuse target. This module never re-implements deadline CRUD; it only
-- reads/creates rows in practice_deadlines via a resolve-or-create helper
-- and stores the resulting id as practice_statutory_schedule.linked_deadline_id.
--
-- Tables created (all IF NOT EXISTS — safe to re-run):
--   practice_statutory_obligations
--   practice_statutory_schedule
--   practice_statutory_dependencies
--   practice_statutory_calendar_events

-- ─────────────────────────────────────────────────────────────────────────────
-- TABLE: practice_statutory_obligations
-- The recurring RULE ("what's due, how often") — not an individual due date.
-- Individual due occurrences live in practice_statutory_schedule.
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS practice_statutory_obligations (
    id                      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id               INTEGER NOT NULL,
    client_id                  INTEGER NOT NULL,   -- plain integer, no FK — practice_clients (Codebox 41 convention)

    obligation_type               TEXT NOT NULL CHECK (obligation_type IN (
                                      'annual_return', 'beneficial_ownership_review', 'director_register_review',
                                      'share_register_review', 'company_information_review', 'financial_year_end_review',
                                      'company_secretary_review', 'auditor_review', 'accounting_officer_review', 'custom'
                                  )),
    title                          TEXT NOT NULL,

    frequency                        TEXT NOT NULL CHECK (frequency IN (
                                         'one_off', 'monthly', 'quarterly', 'half_yearly', 'annual', 'every_x_months', 'manual'
                                     )),
    every_x_months                     INTEGER,   -- only meaningful when frequency = 'every_x_months'

    -- Deterministic, explainable due-date computation rule — never a vague
    -- free-text description. anchor decides which date the frequency counts
    -- from; fixed_month_day is used only when anchor = 'fixed_date'.
    -- Shape: { "anchor": "registration_date" | "financial_year_end" | "fixed_date" | "manual",
    --          "offset_days": 0, "fixed_month_day": "MM-DD" | null }
    due_rule                             JSONB NOT NULL DEFAULT '{"anchor": "manual", "offset_days": 0, "fixed_month_day": null}',

    warning_days                           INTEGER NOT NULL DEFAULT 30,   -- days before due_date to surface as "upcoming"
    grace_period_days                        INTEGER NOT NULL DEFAULT 0,   -- days after due_date still treated as "grace" before hard overdue

    mandatory                                  BOOLEAN NOT NULL DEFAULT true,
    is_active                                    BOOLEAN NOT NULL DEFAULT true,

    notes                                          TEXT,
    internal_notes                                   TEXT,
    settings                                           JSONB NOT NULL DEFAULT '{}',

    created_by                                           INTEGER,
    updated_by                                             INTEGER,
    created_at                                              TIMESTAMPTZ DEFAULT NOW(),
    updated_at                                                TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_pso_company_id  ON practice_statutory_obligations (company_id);
CREATE INDEX IF NOT EXISTS idx_pso_client_id    ON practice_statutory_obligations (client_id);
CREATE INDEX IF NOT EXISTS idx_pso_type         ON practice_statutory_obligations (company_id, obligation_type);
CREATE INDEX IF NOT EXISTS idx_pso_active       ON practice_statutory_obligations (company_id, is_active);

CREATE OR REPLACE FUNCTION fn_pso_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS tg_pso_updated_at ON practice_statutory_obligations;
CREATE TRIGGER tg_pso_updated_at
    BEFORE UPDATE ON practice_statutory_obligations
    FOR EACH ROW EXECUTE FUNCTION fn_pso_updated_at();

COMMENT ON TABLE practice_statutory_obligations IS
    'Codebox 67 — Recurring statutory obligation rules per client. due_rule is a structured, deterministic JSON recipe — never a guessed date.';

-- ─────────────────────────────────────────────────────────────────────────────
-- TABLE: practice_statutory_schedule
-- Individual due occurrences generated from an obligation's recurrence rule.
-- status here is the manager-set LIFECYCLE state only (pending/completed/
-- cancelled) — temporal categories (upcoming/due_today/overdue/future) and
-- dependency-based categories (blocked/waiting) are computed live by
-- buildStatutoryCalendar(), never stored, so they can never drift.
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS practice_statutory_schedule (
    id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id          INTEGER NOT NULL,
    client_id             INTEGER NOT NULL,   -- plain integer, no FK — practice_clients
    obligation_id           INTEGER NOT NULL,   -- plain integer, no FK — practice_statutory_obligations

    period_label               TEXT NOT NULL,   -- e.g. "2026 Annual Return", "Q1 2026 BO Review"
    due_date                      DATE NOT NULL,
    warning_date                   DATE,   -- cached: due_date - obligation.warning_days, recomputed on generation
    grace_end_date                   DATE,   -- cached: due_date + obligation.grace_period_days, recomputed on generation

    status                              TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'completed', 'cancelled')),

    linked_deadline_id                    INTEGER,   -- plain integer, no FK — practice_deadlines.id. Set by the resolve-or-create deadline sync helper. Never duplicated.

    completed_at                            TIMESTAMPTZ,
    completed_by                              INTEGER,

    notes                                       TEXT,
    metadata                                      JSONB NOT NULL DEFAULT '{}',

    created_by                                      INTEGER,
    updated_by                                        INTEGER,
    created_at                                         TIMESTAMPTZ DEFAULT NOW(),
    updated_at                                           TIMESTAMPTZ DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_pss_obligation_period
    ON practice_statutory_schedule (obligation_id, period_label);

CREATE INDEX IF NOT EXISTS idx_pss_company_id           ON practice_statutory_schedule (company_id);
CREATE INDEX IF NOT EXISTS idx_pss_client_id             ON practice_statutory_schedule (client_id);
CREATE INDEX IF NOT EXISTS idx_pss_obligation_id         ON practice_statutory_schedule (obligation_id);
CREATE INDEX IF NOT EXISTS idx_pss_due_date              ON practice_statutory_schedule (company_id, due_date);
CREATE INDEX IF NOT EXISTS idx_pss_status                ON practice_statutory_schedule (company_id, status);
CREATE INDEX IF NOT EXISTS idx_pss_linked_deadline_id    ON practice_statutory_schedule (linked_deadline_id) WHERE linked_deadline_id IS NOT NULL;

CREATE OR REPLACE FUNCTION fn_pss_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS tg_pss_updated_at ON practice_statutory_schedule;
CREATE TRIGGER tg_pss_updated_at
    BEFORE UPDATE ON practice_statutory_schedule
    FOR EACH ROW EXECUTE FUNCTION fn_pss_updated_at();

COMMENT ON TABLE practice_statutory_schedule IS
    'Codebox 67 — Individual due occurrences generated from a statutory obligation. linked_deadline_id points to an existing-or-created practice_deadlines row — this table never duplicates deadline management, it schedules and cross-references it.';

-- ─────────────────────────────────────────────────────────────────────────────
-- TABLE: practice_statutory_dependencies
-- Manager may override any dependency — see secretarial-calendar.js.
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS practice_statutory_dependencies (
    id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id          INTEGER NOT NULL,
    client_id             INTEGER NOT NULL,   -- plain integer, no FK — practice_clients
    schedule_id             INTEGER NOT NULL,   -- plain integer, no FK — practice_statutory_schedule (the entry that HAS this dependency)

    depends_on_type            TEXT NOT NULL CHECK (depends_on_type IN ('schedule_item', 'bo_review', 'evidence_complete', 'governance_complete', 'custom')),
    depends_on_schedule_id        INTEGER,   -- plain integer, no FK — practice_statutory_schedule. Used only when depends_on_type = 'schedule_item'.
    description                     TEXT,   -- e.g. "Annual Return depends on BO review complete"

    manager_override                  BOOLEAN NOT NULL DEFAULT false,
    override_reason                     TEXT,
    override_by                           INTEGER,
    override_at                             TIMESTAMPTZ,

    notes                                      TEXT,

    created_by                                   INTEGER,
    created_at                                     TIMESTAMPTZ DEFAULT NOW(),
    updated_at                                       TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_psd_company_id            ON practice_statutory_dependencies (company_id);
CREATE INDEX IF NOT EXISTS idx_psd_client_id              ON practice_statutory_dependencies (client_id);
CREATE INDEX IF NOT EXISTS idx_psd_schedule_id            ON practice_statutory_dependencies (schedule_id);
CREATE INDEX IF NOT EXISTS idx_psd_depends_on_schedule_id ON practice_statutory_dependencies (depends_on_schedule_id) WHERE depends_on_schedule_id IS NOT NULL;

CREATE OR REPLACE FUNCTION fn_psd_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS tg_psd_updated_at ON practice_statutory_dependencies;
CREATE TRIGGER tg_psd_updated_at
    BEFORE UPDATE ON practice_statutory_dependencies
    FOR EACH ROW EXECUTE FUNCTION fn_psd_updated_at();

COMMENT ON TABLE practice_statutory_dependencies IS
    'Codebox 67 — Dependency rules gating a schedule entry (e.g. Annual Return depends on BO review). is_satisfied is never stored — always computed live by buildStatutoryCalendar() so it can never drift. manager_override always short-circuits to satisfied.';

-- ─────────────────────────────────────────────────────────────────────────────
-- TABLE: practice_statutory_calendar_events  (append-only audit log)
-- Never updated. Never deleted.
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS practice_statutory_calendar_events (
    id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id          INTEGER NOT NULL,
    client_id             INTEGER,   -- plain integer, no FK — practice_clients (denormalized for fast per-client history queries)

    source_type             TEXT NOT NULL CHECK (source_type IN ('obligation', 'schedule', 'dependency')),
    source_id                 INTEGER NOT NULL,   -- plain integer, no FK (Codebox 41 convention)

    event_type                  TEXT NOT NULL CHECK (event_type IN (
                                    'obligation_created', 'obligation_updated', 'obligation_archived',
                                    'schedule_generated', 'schedule_updated', 'schedule_completed', 'schedule_cancelled',
                                    'dependency_created', 'dependency_overridden',
                                    'deadline_linked', 'deadline_created'
                                )),
    old_status                    TEXT,
    new_status                      TEXT,

    actor_user_id                      INTEGER,
    notes                                TEXT,
    metadata                              JSONB NOT NULL DEFAULT '{}',
    created_at                              TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_psce_company_id  ON practice_statutory_calendar_events (company_id);
CREATE INDEX IF NOT EXISTS idx_psce_source       ON practice_statutory_calendar_events (source_type, source_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_psce_client_id    ON practice_statutory_calendar_events (client_id) WHERE client_id IS NOT NULL;

COMMENT ON TABLE practice_statutory_calendar_events IS
    'Codebox 67 — Append-only log of statutory obligation/schedule/dependency activity. Never updated or deleted.';
