-- Migration 124: Secretarial Document Checklist + Governance Evidence Requests
-- Codebox 66 — Lorenco Practice Management
--
-- NUMBERING NOTE: The spec for this codebox requested "123_practice_secretarial_
-- evidence.sql", but migration 123 was already created AND APPLIED to Supabase
-- in this session as 123_practice_secretarial_calendar.sql (Codebox 67's
-- content was delivered out of order — see SESSION_HANDOFF_codebox_66_
-- secretarial_evidence.md for the full explanation). Renumbered to 124, the
-- next available slot, rather than overwrite an already-applied migration.
--
-- DO NOT BUILD: document storage, file uploads, an attachment system, a
-- document viewer, duplicate document requests, duplicate document tables.
-- practice_document_requests (migration 073) remains the SOLE owner of
-- documents. This migration creates an EVIDENCE LAYER on top of it —
-- what evidence is required, why, whether it's been received, whether it's
-- been verified — linking to existing document requests, never duplicating
-- them.
--
-- AUDIT (RULE A1 — see docs/new-app/66_secretarial_evidence.md Architect
-- Freedom #1-#2): confirmed practice_document_requests' exact columns
-- (id, company_id, client_id, request_title, document_category, request_status,
-- received_at, notes, etc. — no DB-level CHECK, enums are app-level in
-- document-requests.js) and confirmed it exports nothing beyond its router,
-- so integration here is via direct, read-only status queries and a
-- resolve-or-create insert helper — the same reuse pattern established for
-- practice_deadlines in Codebox 67. Also confirmed practice_bo_readiness_items
-- (Codebox 65) already IS a fully-formed evidence-style checklist for
-- Beneficial Ownership specifically — "BO readiness uses evidence completion,
-- no duplicate readiness logic" is satisfied by DELEGATING to it (see
-- secretarial-evidence.js's BO branch), never re-tracking BO evidence items
-- in the tables below.
--
-- Tables created (all IF NOT EXISTS — safe to re-run):
--   practice_secretarial_evidence_templates
--   practice_secretarial_evidence_checklists
--   practice_secretarial_evidence_items
--   practice_secretarial_evidence_events
--
-- Also extends practice_statutory_schedule's dependency table (migration 123,
-- Codebox 67) with a nullable link so 'evidence_complete' dependencies can be
-- resolved automatically instead of always requiring manager override — see
-- Architect Freedom #7. Purely additive (ADD COLUMN IF NOT EXISTS).

-- ─────────────────────────────────────────────────────────────────────────────
-- TABLE: practice_secretarial_evidence_templates
-- Company-level reusable definitions (not per-client) — "what evidence does a
-- Director Appointment typically need," defined once, applied to many clients.
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS practice_secretarial_evidence_templates (
    id                      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id               INTEGER NOT NULL,

    template_type               TEXT NOT NULL CHECK (template_type IN (
                                    'director_appointment', 'director_resignation', 'share_transfer',
                                    'company_name_change', 'registered_address_change', 'beneficial_ownership',
                                    'annual_return', 'resolution', 'minutes', 'trustee_appointment',
                                    'company_secretary', 'accounting_officer', 'auditor', 'financial_year_end', 'custom'
                                )),
    template_name                 TEXT NOT NULL,
    description                     TEXT,

    -- Structured, deterministic evidence definition — array of
    -- { evidence_type, item_name, required, verification_required, recommended_document_category }.
    -- Manager-editable persisted version of the CHECKLIST_DEFAULTS pattern
    -- established in Codebox 63 (there, a hardcoded JS constant; here, a real
    -- table so practices can tailor their own evidence requirements).
    required_evidence                 JSONB NOT NULL DEFAULT '[]',

    is_active                            BOOLEAN NOT NULL DEFAULT true,
    notes                                  TEXT,
    settings                                JSONB NOT NULL DEFAULT '{}',

    created_by                                INTEGER,
    updated_by                                  INTEGER,
    created_at                                   TIMESTAMPTZ DEFAULT NOW(),
    updated_at                                     TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_pset_company_id  ON practice_secretarial_evidence_templates (company_id);
CREATE INDEX IF NOT EXISTS idx_pset_type         ON practice_secretarial_evidence_templates (company_id, template_type);
CREATE INDEX IF NOT EXISTS idx_pset_active       ON practice_secretarial_evidence_templates (company_id, is_active);

CREATE OR REPLACE FUNCTION fn_pset_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS tg_pset_updated_at ON practice_secretarial_evidence_templates;
CREATE TRIGGER tg_pset_updated_at
    BEFORE UPDATE ON practice_secretarial_evidence_templates
    FOR EACH ROW EXECUTE FUNCTION fn_pset_updated_at();

COMMENT ON TABLE practice_secretarial_evidence_templates IS
    'Codebox 66 — Reusable evidence definitions per statutory process type. required_evidence is structured JSON, never a guessed list.';

-- ─────────────────────────────────────────────────────────────────────────────
-- TABLE: practice_secretarial_evidence_checklists
-- One checklist per process. For source_type = 'bo_verification', this row
-- exists for reference/linking only — its items are NOT duplicated here;
-- readiness is delegated live to practice_bo_readiness_items (Codebox 65)
-- via beneficial-ownership.js. See migration header + Architect Freedom #3.
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS practice_secretarial_evidence_checklists (
    id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id          INTEGER NOT NULL,
    client_id             INTEGER NOT NULL,   -- plain integer, no FK — practice_clients (Codebox 41 convention)

    source_type             TEXT NOT NULL CHECK (source_type IN (
                                'change_case', 'governance_resolution', 'governance_meeting',
                                'bo_verification', 'annual_return', 'manual'
                            )),
    source_id                 INTEGER,   -- plain integer, no FK. Nullable — 'manual' has no source record.
    template_id                 INTEGER,   -- plain integer, no FK — practice_secretarial_evidence_templates. Nullable.

    title                          TEXT NOT NULL,
    notes                            TEXT,
    internal_notes                     TEXT,
    settings                             JSONB NOT NULL DEFAULT '{}',

    created_by                             INTEGER,
    updated_by                               INTEGER,
    created_at                                TIMESTAMPTZ DEFAULT NOW(),
    updated_at                                  TIMESTAMPTZ DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_psec_source
    ON practice_secretarial_evidence_checklists (source_type, source_id)
    WHERE source_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_psec_company_id  ON practice_secretarial_evidence_checklists (company_id);
CREATE INDEX IF NOT EXISTS idx_psec_client_id    ON practice_secretarial_evidence_checklists (client_id);
CREATE INDEX IF NOT EXISTS idx_psec_source_type  ON practice_secretarial_evidence_checklists (company_id, source_type);

CREATE OR REPLACE FUNCTION fn_psec_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS tg_psec_updated_at ON practice_secretarial_evidence_checklists;
CREATE TRIGGER tg_psec_updated_at
    BEFORE UPDATE ON practice_secretarial_evidence_checklists
    FOR EACH ROW EXECUTE FUNCTION fn_psec_updated_at();

COMMENT ON TABLE practice_secretarial_evidence_checklists IS
    'Codebox 66 — One evidence checklist per process (change case, resolution, meeting, BO verification, annual return, or manual). checklist_status is never stored — always computed live from item statuses (or, for bo_verification, delegated to BO readiness).';

-- ─────────────────────────────────────────────────────────────────────────────
-- TABLE: practice_secretarial_evidence_items
-- Never populated for source_type = 'bo_verification' checklists — see above.
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS practice_secretarial_evidence_items (
    id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id          INTEGER NOT NULL,
    checklist_id           INTEGER NOT NULL,   -- plain integer, no FK — practice_secretarial_evidence_checklists

    evidence_type             TEXT NOT NULL,   -- free text, drawn from the template's required_evidence — no fixed enum (templates are the source of truth)
    item_name                   TEXT NOT NULL,
    required                      BOOLEAN NOT NULL DEFAULT true,
    verification_required           BOOLEAN NOT NULL DEFAULT false,

    status                             TEXT NOT NULL DEFAULT 'waiting' CHECK (status IN ('waiting', 'requested', 'received', 'verified', 'waived', 'blocked')),

    linked_document_request_id            INTEGER,   -- plain integer, no FK — practice_document_requests.id (migration 073). The reuse target — never a duplicate document table.
    reviewer_team_member_id                 INTEGER,   -- plain integer, no FK — practice_team_members
    verification_notes                        TEXT,

    notes                                       TEXT,

    created_by                                    INTEGER,
    updated_by                                      INTEGER,
    created_at                                       TIMESTAMPTZ DEFAULT NOW(),
    updated_at                                         TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_psei_company_id                  ON practice_secretarial_evidence_items (company_id);
CREATE INDEX IF NOT EXISTS idx_psei_checklist_id                 ON practice_secretarial_evidence_items (checklist_id);
CREATE INDEX IF NOT EXISTS idx_psei_status                        ON practice_secretarial_evidence_items (company_id, status);
CREATE INDEX IF NOT EXISTS idx_psei_linked_document_request_id     ON practice_secretarial_evidence_items (linked_document_request_id) WHERE linked_document_request_id IS NOT NULL;

CREATE OR REPLACE FUNCTION fn_psei_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS tg_psei_updated_at ON practice_secretarial_evidence_items;
CREATE TRIGGER tg_psei_updated_at
    BEFORE UPDATE ON practice_secretarial_evidence_items
    FOR EACH ROW EXECUTE FUNCTION fn_psei_updated_at();

COMMENT ON TABLE practice_secretarial_evidence_items IS
    'Codebox 66 — Individual evidence requirements within a checklist. linked_document_request_id points into the EXISTING practice_document_requests table (migration 073) — this table never stores or owns a document itself.';

-- ─────────────────────────────────────────────────────────────────────────────
-- TABLE: practice_secretarial_evidence_events  (append-only audit log)
-- Never updated. Never deleted.
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS practice_secretarial_evidence_events (
    id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id          INTEGER NOT NULL,
    client_id             INTEGER,   -- plain integer, no FK — practice_clients (denormalized for fast per-client history queries)

    source_type             TEXT NOT NULL CHECK (source_type IN ('template', 'checklist', 'item')),
    source_id                 INTEGER NOT NULL,   -- plain integer, no FK (Codebox 41 convention)

    event_type                  TEXT NOT NULL CHECK (event_type IN (
                                    'template_created', 'template_updated', 'template_archived',
                                    'checklist_generated', 'checklist_regenerated', 'checklist_updated',
                                    'item_created', 'item_updated', 'item_status_synced', 'item_verified', 'item_waived'
                                )),
    old_status                    TEXT,
    new_status                      TEXT,

    actor_user_id                      INTEGER,
    notes                                TEXT,
    metadata                              JSONB NOT NULL DEFAULT '{}',
    created_at                              TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_psee_company_id  ON practice_secretarial_evidence_events (company_id);
CREATE INDEX IF NOT EXISTS idx_psee_source       ON practice_secretarial_evidence_events (source_type, source_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_psee_client_id    ON practice_secretarial_evidence_events (client_id) WHERE client_id IS NOT NULL;

COMMENT ON TABLE practice_secretarial_evidence_events IS
    'Codebox 66 — Append-only log of evidence template/checklist/item activity. Never updated or deleted.';

-- ─────────────────────────────────────────────────────────────────────────────
-- Additive extension of Codebox 67's practice_statutory_dependencies (already
-- applied in Supabase as part of migration 123) so an 'evidence_complete'
-- dependency can point at a specific evidence checklist and be resolved
-- automatically, instead of always requiring a manager override. See
-- secretarial-calendar.js's updated _isDependencySatisfied().
-- ─────────────────────────────────────────────────────────────────────────────

ALTER TABLE practice_statutory_dependencies
    ADD COLUMN IF NOT EXISTS depends_on_checklist_id INTEGER;   -- plain integer, no FK — practice_secretarial_evidence_checklists. Used only when depends_on_type = 'evidence_complete'.

CREATE INDEX IF NOT EXISTS idx_psd_depends_on_checklist_id
    ON practice_statutory_dependencies (depends_on_checklist_id)
    WHERE depends_on_checklist_id IS NOT NULL;
