-- Migration 125: Practice Secretarial Entity Lifecycle Management
-- Codebox 68 — Lorenco Practice Management
--
-- NOT CIPC API. NOT automatic deregistration/restoration. NOT liquidation/
-- legal advice. NOT trust accounting. Manual entity lifecycle tracking and
-- control — future CIPC/API work must plug into this engine, not replace it.
--
-- AUDIT (RULE A1 — see docs/new-app/68_entity_lifecycle.md Architect Freedom
-- #1): confirmed practice_secretarial_profiles.company_status (migration 119)
-- already exists as a simple 6-value lifecycle-ish field (active/dormant/
-- deregistration_process/deregistered/in_liquidation/other), already
-- read/written by secretarial.js and secretarial-workflows.js's
-- company_status_change implementation. This migration does NOT touch that
-- column or table. current_lifecycle_status here is a richer, SEPARATE,
-- ADDITIONAL 14-value model with full transition/checklist/audit control —
-- the two fields serve different purposes and are never synchronised
-- automatically (see getEntityLifecycleProfile()'s secretarial_profile_summary,
-- which reads company_status as context, never as the same value).
--
-- Tables created (all IF NOT EXISTS — safe to re-run):
--   practice_entity_lifecycle_profiles
--   practice_entity_lifecycle_transitions
--   practice_entity_lifecycle_checklist_items
--   practice_entity_lifecycle_events

-- ─────────────────────────────────────────────────────────────────────────────
-- TABLE: practice_entity_lifecycle_profiles
-- One row per client — the entity's current lifecycle state.
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS practice_entity_lifecycle_profiles (
    id                      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id               INTEGER NOT NULL,
    client_id                  INTEGER NOT NULL,   -- plain integer, no FK — practice_clients (Codebox 41 convention)

    entity_category               TEXT NOT NULL DEFAULT 'company' CHECK (entity_category IN (
                                      'company', 'close_corporation', 'trust', 'non_profit', 'sole_proprietor', 'partnership', 'other'
                                  )),

    current_lifecycle_status        TEXT NOT NULL DEFAULT 'unknown' CHECK (current_lifecycle_status IN (
                                         'pre_incorporation', 'incorporated', 'active', 'trading', 'dormant', 'non_compliant',
                                         'deregistration_pending', 'deregistered', 'restoration_pending', 'restored',
                                         'liquidation_pending', 'liquidated', 'closed', 'unknown'
                                     )),
    lifecycle_status_reason            TEXT,
    status_effective_date                DATE,
    last_reviewed_at                       TIMESTAMPTZ,
    last_reviewed_by                         INTEGER,
    next_review_date                           DATE,

    trading_status                               TEXT NOT NULL DEFAULT 'unknown' CHECK (trading_status IN ('trading', 'not_trading', 'dormant', 'unknown')),
    compliance_status                              TEXT NOT NULL DEFAULT 'unknown' CHECK (compliance_status IN ('compliant', 'attention_required', 'non_compliant', 'unknown')),
    risk_status                                      TEXT NOT NULL DEFAULT 'unknown' CHECK (risk_status IN ('low', 'medium', 'high', 'critical', 'unknown')),

    notes                                               TEXT,
    internal_notes                                        TEXT,
    settings                                                JSONB NOT NULL DEFAULT '{}',

    created_by                                                INTEGER,
    updated_by                                                  INTEGER,
    created_at                                                   TIMESTAMPTZ DEFAULT NOW(),
    updated_at                                                     TIMESTAMPTZ DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_pelp_company_client
    ON practice_entity_lifecycle_profiles (company_id, client_id);

CREATE INDEX IF NOT EXISTS idx_pelp_company_id  ON practice_entity_lifecycle_profiles (company_id);
CREATE INDEX IF NOT EXISTS idx_pelp_status       ON practice_entity_lifecycle_profiles (company_id, current_lifecycle_status);

CREATE OR REPLACE FUNCTION fn_pelp_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS tg_pelp_updated_at ON practice_entity_lifecycle_profiles;
CREATE TRIGGER tg_pelp_updated_at
    BEFORE UPDATE ON practice_entity_lifecycle_profiles
    FOR EACH ROW EXECUTE FUNCTION fn_pelp_updated_at();

COMMENT ON TABLE practice_entity_lifecycle_profiles IS
    'Codebox 68 — One lifecycle profile per client. current_lifecycle_status is a richer, SEPARATE model from practice_secretarial_profiles.company_status (Codebox 62) — never synchronised automatically. Only ever changed via an implemented practice_entity_lifecycle_transitions row.';

-- ─────────────────────────────────────────────────────────────────────────────
-- TABLE: practice_entity_lifecycle_transitions
-- The control point — current_lifecycle_status only ever changes via a
-- transition reaching case_status = 'implemented'.
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS practice_entity_lifecycle_transitions (
    id                      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id               INTEGER NOT NULL,
    client_id                  INTEGER NOT NULL,   -- plain integer, no FK — practice_clients
    lifecycle_profile_id          INTEGER NOT NULL,   -- plain integer, no FK — practice_entity_lifecycle_profiles

    transition_type                  TEXT NOT NULL CHECK (transition_type IN (
                                         'incorporate', 'activate', 'commence_trading', 'mark_dormant', 'mark_non_compliant',
                                         'start_deregistration', 'confirm_deregistered', 'start_restoration', 'confirm_restored',
                                         'start_liquidation', 'confirm_liquidated', 'close_entity', 'reopen_entity', 'status_review', 'custom'
                                     )),
    old_status                          TEXT,
    new_status                            TEXT,

    transition_status                       TEXT NOT NULL DEFAULT 'draft' CHECK (transition_status IN (
                                                'draft', 'preparing', 'awaiting_evidence', 'ready_for_review',
                                                'approved', 'implemented', 'completed', 'rejected', 'cancelled'
                                            )),

    requested_by_name                          TEXT,
    requested_date                               DATE,
    effective_date                                 DATE,

    approved_by                                      INTEGER,
    approved_at                                        TIMESTAMPTZ,
    implemented_by                                       INTEGER,
    implemented_at                                         TIMESTAMPTZ,
    completed_by                                             INTEGER,
    completed_at                                               TIMESTAMPTZ,

    transition_summary                                           TEXT,
    reason                                                          TEXT,
    risk_notes                                                        TEXT,
    evidence_notes                                                      TEXT,
    rejection_reason                                                      TEXT,

    before_snapshot                                                         JSONB,
    after_snapshot                                                            JSONB,
    payload                                                                     JSONB NOT NULL DEFAULT '{}',
    settings                                                                      JSONB NOT NULL DEFAULT '{}',

    created_by                                                                     INTEGER,
    updated_by                                                                       INTEGER,
    created_at                                                                        TIMESTAMPTZ DEFAULT NOW(),
    updated_at                                                                          TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_pelt_company_id           ON practice_entity_lifecycle_transitions (company_id);
CREATE INDEX IF NOT EXISTS idx_pelt_client_id             ON practice_entity_lifecycle_transitions (client_id);
CREATE INDEX IF NOT EXISTS idx_pelt_lifecycle_profile_id  ON practice_entity_lifecycle_transitions (lifecycle_profile_id);
CREATE INDEX IF NOT EXISTS idx_pelt_transition_type       ON practice_entity_lifecycle_transitions (company_id, transition_type);
CREATE INDEX IF NOT EXISTS idx_pelt_transition_status     ON practice_entity_lifecycle_transitions (company_id, transition_status);
CREATE INDEX IF NOT EXISTS idx_pelt_effective_date        ON practice_entity_lifecycle_transitions (company_id, effective_date) WHERE effective_date IS NOT NULL;

CREATE OR REPLACE FUNCTION fn_pelt_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS tg_pelt_updated_at ON practice_entity_lifecycle_transitions;
CREATE TRIGGER tg_pelt_updated_at
    BEFORE UPDATE ON practice_entity_lifecycle_transitions
    FOR EACH ROW EXECUTE FUNCTION fn_pelt_updated_at();

COMMENT ON TABLE practice_entity_lifecycle_transitions IS
    'Codebox 68 — Controlled lifecycle stage-change cases. draft/preparing/awaiting_evidence/ready_for_review/approved/implemented/completed/rejected/cancelled. before_snapshot/after_snapshot capture the lifecycle profile at implementation for audit purposes — not a generated document.';

-- ─────────────────────────────────────────────────────────────────────────────
-- TABLE: practice_entity_lifecycle_checklist_items
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS practice_entity_lifecycle_checklist_items (
    id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id          INTEGER NOT NULL,
    transition_id          INTEGER NOT NULL,   -- plain integer, no FK — practice_entity_lifecycle_transitions

    item_name                TEXT NOT NULL,
    item_type                  TEXT NOT NULL CHECK (item_type IN (
                                  'evidence', 'approval', 'client_confirmation', 'statutory_check', 'tax_check',
                                  'creditor_check', 'cipc_step', 'governance_resolution', 'bo_check',
                                  'document_request', 'internal_review', 'custom'
                              )),

    required                    BOOLEAN NOT NULL DEFAULT true,
    completed                     BOOLEAN NOT NULL DEFAULT false,
    completed_at                    TIMESTAMPTZ,
    completed_by                     INTEGER,

    linked_document_request_id         INTEGER,   -- plain integer, no FK — practice_document_requests.id (migration 073). Reuse target — never a duplicate document table.

    notes                                 TEXT,
    sort_order                             INTEGER NOT NULL DEFAULT 0,

    created_at                               TIMESTAMPTZ DEFAULT NOW(),
    updated_at                                 TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_pelci_company_id      ON practice_entity_lifecycle_checklist_items (company_id);
CREATE INDEX IF NOT EXISTS idx_pelci_transition_id     ON practice_entity_lifecycle_checklist_items (transition_id, sort_order);

CREATE OR REPLACE FUNCTION fn_pelci_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS tg_pelci_updated_at ON practice_entity_lifecycle_checklist_items;
CREATE TRIGGER tg_pelci_updated_at
    BEFORE UPDATE ON practice_entity_lifecycle_checklist_items
    FOR EACH ROW EXECUTE FUNCTION fn_pelci_updated_at();

COMMENT ON TABLE practice_entity_lifecycle_checklist_items IS
    'Codebox 68 — Per-transition checklist. Generated from CHECKLIST_DEFAULTS per transition_type (see entity-lifecycle.js) or added manually. required items gate approval unless a manager override reason is recorded.';

-- ─────────────────────────────────────────────────────────────────────────────
-- TABLE: practice_entity_lifecycle_events  (append-only audit log)
-- Never updated. Never deleted. No lifecycle status change and no transition
-- completion without a matching event — enforced at the application layer.
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS practice_entity_lifecycle_events (
    id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id          INTEGER NOT NULL,
    client_id             INTEGER,   -- plain integer, no FK — practice_clients (denormalized for fast per-client history queries)

    source_type             TEXT NOT NULL CHECK (source_type IN ('lifecycle_profile', 'lifecycle_transition', 'checklist_item')),
    source_id                 INTEGER NOT NULL,   -- plain integer, no FK (Codebox 41 convention)

    event_type                  TEXT NOT NULL CHECK (event_type IN (
                                    'lifecycle_profile_created', 'lifecycle_profile_updated',
                                    'transition_created', 'transition_updated',
                                    'checklist_generated', 'checklist_item_updated',
                                    'transition_submitted_review', 'transition_approved', 'transition_rejected',
                                    'transition_implemented', 'transition_completed', 'transition_cancelled',
                                    'lifecycle_status_changed', 'lifecycle_reviewed'
                                )),
    old_status                    TEXT,
    new_status                      TEXT,

    actor_user_id                      INTEGER,
    notes                                TEXT,
    metadata                              JSONB NOT NULL DEFAULT '{}',
    created_at                              TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_pele_company_id  ON practice_entity_lifecycle_events (company_id);
CREATE INDEX IF NOT EXISTS idx_pele_source       ON practice_entity_lifecycle_events (source_type, source_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_pele_client_id    ON practice_entity_lifecycle_events (client_id) WHERE client_id IS NOT NULL;

COMMENT ON TABLE practice_entity_lifecycle_events IS
    'Codebox 68 — Append-only log of lifecycle profile/transition/checklist activity. Never updated or deleted.';
