-- Migration 126: Secretarial Register Integrity Audit + Statutory Data Quality Review
-- Codebox 69 — Lorenco Practice Management
--
-- NOT data correction. NOT automatic repair. NOT CIPC validation. NOT legal
-- advice. This module only detects, classifies, and reports issues across
-- the existing Secretarial suite (Registers, Workflows, Governance,
-- Beneficial Ownership, Evidence, Statutory Calendar, Entity Lifecycle).
-- Managers decide how to resolve findings — nothing here ever writes to any
-- table outside this migration's own three tables.
--
-- AUDIT (RULE A1 — see docs/new-app/69_secretarial_integrity.md): confirmed
-- the exact shape of every table this module reads from (migrations 119-125):
--   practice_secretarial_profiles, practice_company_directors,
--   practice_company_shareholders, practice_annual_returns (119)
--   practice_secretarial_change_cases (120)
--   practice_secretarial_resolutions, practice_secretarial_meetings,
--   practice_secretarial_decisions (121)
--   practice_beneficial_owners, practice_ownership_chains,
--   practice_bo_readiness_items (122)
--   practice_statutory_obligations, practice_statutory_schedule,
--   practice_statutory_dependencies (123)
--   practice_secretarial_evidence_templates, _checklists, _items (124)
--   practice_entity_lifecycle_profiles, _transitions (125)
--   practice_clients.registration_number (007), practice_taxpayer_profiles.
--   financial_year_end (075) — reused live, never duplicated.
-- This module reads all of the above but writes to none of them — it only
-- ever inserts into its own three tables below.
--
-- Tables created (all IF NOT EXISTS — safe to re-run):
--   practice_secretarial_integrity_runs
--   practice_secretarial_integrity_findings
--   practice_secretarial_integrity_events

-- ─────────────────────────────────────────────────────────────────────────────
-- TABLE: practice_secretarial_integrity_runs
-- One row per audit execution. Findings (below) belong to a run.
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS practice_secretarial_integrity_runs (
    id                      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id               INTEGER NOT NULL,

    run_type                     TEXT NOT NULL DEFAULT 'manual' CHECK (run_type IN (
                                     'manual', 'scheduled', 'pre_filing', 'pre_review', 'full_scan'
                                 )),

    scan_started_at                TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    scan_completed_at                TIMESTAMPTZ,

    overall_score                       INTEGER,   -- 0-100, null until scan_completed_at is set
    critical_count                        INTEGER NOT NULL DEFAULT 0,
    high_count                              INTEGER NOT NULL DEFAULT 0,
    medium_count                              INTEGER NOT NULL DEFAULT 0,
    low_count                                   INTEGER NOT NULL DEFAULT 0,

    passed                                        BOOLEAN,   -- null until completed; true only if zero critical/high findings

    notes                                           TEXT,

    created_by                                        INTEGER,
    created_at                                          TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_psir_company_id  ON practice_secretarial_integrity_runs (company_id);
CREATE INDEX IF NOT EXISTS idx_psir_run_type     ON practice_secretarial_integrity_runs (company_id, run_type);
CREATE INDEX IF NOT EXISTS idx_psir_started_at   ON practice_secretarial_integrity_runs (company_id, scan_started_at DESC);

COMMENT ON TABLE practice_secretarial_integrity_runs IS
    'Codebox 69 — One row per audit execution (runIntegrityAudit()). overall_score/severity counts are a snapshot of the findings this run created — a re-run always creates a NEW run row rather than mutating a prior one, so audit history is never lost.';

-- ─────────────────────────────────────────────────────────────────────────────
-- TABLE: practice_secretarial_integrity_findings
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS practice_secretarial_integrity_findings (
    id                      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id               INTEGER NOT NULL,
    client_id                  INTEGER,   -- plain integer, no FK — practice_clients. Nullable — a handful of checks are company-wide, not client-specific.
    run_id                        INTEGER NOT NULL,   -- plain integer, no FK — practice_secretarial_integrity_runs (Codebox 41 convention)

    finding_category                TEXT NOT NULL CHECK (finding_category IN (
                                        'register', 'director', 'shareholder', 'beneficial_owner', 'governance',
                                        'evidence', 'calendar', 'lifecycle', 'annual_return', 'general'
                                    )),
    finding_code                       TEXT NOT NULL,   -- stable machine-readable code, e.g. 'no_active_directors' — see VALIDATIONS in secretarial-integrity.js for the definitive list

    severity                              TEXT NOT NULL CHECK (severity IN ('critical', 'high', 'medium', 'low', 'info')),

    title                                    TEXT NOT NULL,
    description                               TEXT NOT NULL,
    recommended_action                          TEXT,

    source_module                                 TEXT,   -- e.g. 'secretarial', 'beneficial-ownership', 'entity-lifecycle' — which module's data this finding is about
    source_record_id                                INTEGER,   -- plain integer, no FK (Codebox 41 convention) — points into the table named by source_module/finding_code, informational only

    status                                            TEXT NOT NULL DEFAULT 'open' CHECK (status IN (
                                                          'open', 'acknowledged', 'resolved', 'accepted_risk', 'ignored'
                                                      )),
    reviewed_by                                         INTEGER,
    reviewed_at                                           TIMESTAMPTZ,

    notes                                                    TEXT,

    created_at                                                 TIMESTAMPTZ DEFAULT NOW(),
    updated_at                                                   TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_psif_company_id     ON practice_secretarial_integrity_findings (company_id);
CREATE INDEX IF NOT EXISTS idx_psif_client_id       ON practice_secretarial_integrity_findings (client_id) WHERE client_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_psif_run_id          ON practice_secretarial_integrity_findings (run_id);
CREATE INDEX IF NOT EXISTS idx_psif_category        ON practice_secretarial_integrity_findings (company_id, finding_category);
CREATE INDEX IF NOT EXISTS idx_psif_severity        ON practice_secretarial_integrity_findings (company_id, severity);
CREATE INDEX IF NOT EXISTS idx_psif_status          ON practice_secretarial_integrity_findings (company_id, status);
CREATE INDEX IF NOT EXISTS idx_psif_code            ON practice_secretarial_integrity_findings (company_id, finding_code);

CREATE OR REPLACE FUNCTION fn_psif_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS tg_psif_updated_at ON practice_secretarial_integrity_findings;
CREATE TRIGGER tg_psif_updated_at
    BEFORE UPDATE ON practice_secretarial_integrity_findings
    FOR EACH ROW EXECUTE FUNCTION fn_psif_updated_at();

COMMENT ON TABLE practice_secretarial_integrity_findings IS
    'Codebox 69 — Individual data-quality findings produced by a run. Detection and classification only — this table is never written to by anything other than runIntegrityAudit() (insert) and the manager review endpoints (status/notes update only). No other column is ever mutated after creation.';

-- ─────────────────────────────────────────────────────────────────────────────
-- TABLE: practice_secretarial_integrity_events  (append-only audit log)
-- Never updated. Never deleted. No run and no finding status change without a
-- matching event — enforced at the application layer in secretarial-integrity.js.
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS practice_secretarial_integrity_events (
    id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id          INTEGER NOT NULL,
    client_id             INTEGER,   -- plain integer, no FK — practice_clients (denormalized for fast per-client history queries)

    source_type             TEXT NOT NULL CHECK (source_type IN ('run', 'finding')),
    source_id                 INTEGER NOT NULL,   -- plain integer, no FK (Codebox 41 convention)

    event_type                  TEXT NOT NULL CHECK (event_type IN (
                                    'run_started', 'run_completed',
                                    'finding_created', 'finding_acknowledged', 'finding_resolved',
                                    'finding_accepted', 'finding_reopened'
                                )),
    old_status                    TEXT,
    new_status                      TEXT,

    actor_user_id                      INTEGER,
    notes                                 TEXT,
    metadata                              JSONB NOT NULL DEFAULT '{}',
    created_at                              TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_psie_company_id  ON practice_secretarial_integrity_events (company_id);
CREATE INDEX IF NOT EXISTS idx_psie_source       ON practice_secretarial_integrity_events (source_type, source_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_psie_client_id    ON practice_secretarial_integrity_events (client_id) WHERE client_id IS NOT NULL;

COMMENT ON TABLE practice_secretarial_integrity_events IS
    'Codebox 69 — Append-only log of run/finding activity. Never updated or deleted. No silent resolution — every finding status change is recorded here.';
