-- Migration 127: Practice Client Onboarding + Entity Formation Foundation
-- Codebox 70 — Lorenco Practice Management
--
-- NOT CIPC incorporation. NOT SARS registration. NOT banking integration.
-- NOT a client portal. This module prepares the Practice to perform those
-- activities later — it builds the internal onboarding workspace, tracks
-- progress, and initializes (or detects and links to) the Secretarial
-- suite's per-client records that already exist, without ever duplicating
-- or overwriting them.
--
-- AUDIT (RULE A1 — see docs/new-app/70_client_onboarding.md Architect
-- Freedom): confirmed practice_secretarial_profiles (119), practice_entity_
-- lifecycle_profiles (125), practice_client_success (118), practice_
-- secretarial_evidence_templates (124), practice_beneficial_owners/
-- practice_bo_readiness_items (122), practice_statutory_obligations (123),
-- practice_secretarial_integrity_findings (126), practice_risks (107),
-- practice_knowledge_links (104), and practice_taxpayer_profiles (075) all
-- already exist with the shapes this module's engine (buildOnboardingWorkspace())
-- reads from and safely initializes — see the router's own header for the
-- definitive list of which are TRUE initializers (idempotent create-if-
-- missing) vs. DETECTION-ONLY reads (never auto-created, because a sensible
-- value cannot be set without guessing — e.g. a Risk Register entry needs a
-- likelihood/impact rating only a human can judge).
--
-- Tables created (all IF NOT EXISTS — safe to re-run):
--   practice_onboarding_profiles
--   practice_onboarding_steps
--   practice_onboarding_checklists
--   practice_onboarding_events

-- ─────────────────────────────────────────────────────────────────────────────
-- TABLE: practice_onboarding_profiles
-- One row per client being onboarded.
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS practice_onboarding_profiles (
    id                      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id               INTEGER NOT NULL,
    client_id                  INTEGER NOT NULL,   -- plain integer, no FK — practice_clients (Codebox 41 convention)

    entity_type                  TEXT NOT NULL CHECK (entity_type IN (
                                     'pty_ltd', 'cc', 'trust', 'partnership', 'sole_proprietor', 'npc', 'other'
                                 )),

    onboarding_status               TEXT NOT NULL DEFAULT 'draft' CHECK (onboarding_status IN (
                                        'draft', 'information_collection', 'document_collection', 'secretarial_setup',
                                        'tax_setup', 'practice_setup', 'review', 'completed', 'cancelled'
                                    )),
    priority                          TEXT NOT NULL DEFAULT 'normal' CHECK (priority IN ('low', 'normal', 'high', 'urgent')),

    assigned_team_member_id             INTEGER,   -- plain integer, no FK — practice_team_members

    client_contact_name                   TEXT,
    client_contact_email                    TEXT,
    client_contact_phone                      TEXT,

    expected_go_live_date                       DATE,

    -- Always server-calculated from step/checklist completion — never
    -- accepted from the client, same discipline as entity-lifecycle's
    -- current_lifecycle_status and BO's effective_percentage.
    completion_percentage                         INTEGER NOT NULL DEFAULT 0 CHECK (completion_percentage BETWEEN 0 AND 100),

    risk_level                                       TEXT NOT NULL DEFAULT 'low' CHECK (risk_level IN ('low', 'medium', 'high', 'critical')),

    reviewed_by                                        INTEGER,
    reviewed_at                                          TIMESTAMPTZ,
    completed_at                                           TIMESTAMPTZ,
    cancelled_reason                                         TEXT,

    notes                                                      TEXT,
    internal_notes                                              TEXT,
    settings                                                      JSONB NOT NULL DEFAULT '{}',

    created_by                                                     INTEGER,
    updated_by                                                       INTEGER,
    created_at                                                        TIMESTAMPTZ DEFAULT NOW(),
    updated_at                                                         TIMESTAMPTZ DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_pop_company_client
    ON practice_onboarding_profiles (company_id, client_id);

CREATE INDEX IF NOT EXISTS idx_pop_company_id  ON practice_onboarding_profiles (company_id);
CREATE INDEX IF NOT EXISTS idx_pop_status       ON practice_onboarding_profiles (company_id, onboarding_status);
CREATE INDEX IF NOT EXISTS idx_pop_assigned     ON practice_onboarding_profiles (assigned_team_member_id) WHERE assigned_team_member_id IS NOT NULL;

CREATE OR REPLACE FUNCTION fn_pop_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS tg_pop_updated_at ON practice_onboarding_profiles;
CREATE TRIGGER tg_pop_updated_at
    BEFORE UPDATE ON practice_onboarding_profiles
    FOR EACH ROW EXECUTE FUNCTION fn_pop_updated_at();

COMMENT ON TABLE practice_onboarding_profiles IS
    'Codebox 70 — One onboarding workspace per client. entity_type drives the default checklist template and the initial company_type/entity_category set on the Secretarial/Entity Lifecycle profiles at THEIR creation only — never overwritten on an existing profile.';

-- ─────────────────────────────────────────────────────────────────────────────
-- TABLE: practice_onboarding_steps
-- Ordered, named progress steps — a manager-controlled workflow, not a
-- generic checklist (see practice_onboarding_checklists below for that).
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS practice_onboarding_steps (
    id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id          INTEGER NOT NULL,
    client_id             INTEGER NOT NULL,   -- plain integer, no FK — practice_clients (denormalized for fast per-client queries)
    profile_id              INTEGER NOT NULL,   -- plain integer, no FK — practice_onboarding_profiles

    step_name                  TEXT NOT NULL,
    status                       TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'in_progress', 'completed', 'skipped', 'blocked')),
    sort_order                    INTEGER NOT NULL DEFAULT 0,

    completed_by                    INTEGER,
    completed_at                      TIMESTAMPTZ,

    notes                                TEXT,

    created_at                            TIMESTAMPTZ DEFAULT NOW(),
    updated_at                              TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_pos_company_id  ON practice_onboarding_steps (company_id);
CREATE INDEX IF NOT EXISTS idx_pos_profile_id    ON practice_onboarding_steps (profile_id, sort_order);
CREATE INDEX IF NOT EXISTS idx_pos_status        ON practice_onboarding_steps (company_id, status);

CREATE OR REPLACE FUNCTION fn_pos_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS tg_pos_updated_at ON practice_onboarding_steps;
CREATE TRIGGER tg_pos_updated_at
    BEFORE UPDATE ON practice_onboarding_steps
    FOR EACH ROW EXECUTE FUNCTION fn_pos_updated_at();

COMMENT ON TABLE practice_onboarding_steps IS
    'Codebox 70 — The 13-step standard onboarding workflow (Client accepted through Go-live approved). Some steps auto-complete when buildOnboardingWorkspace() successfully initializes the corresponding module (Secretarial/Entity Lifecycle/BO); the rest are manager-completed manually.';

-- ─────────────────────────────────────────────────────────────────────────────
-- TABLE: practice_onboarding_checklists
-- Entity-type-specific document/information checklist. One row per item.
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS practice_onboarding_checklists (
    id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id          INTEGER NOT NULL,
    client_id             INTEGER NOT NULL,   -- plain integer, no FK — practice_clients
    profile_id              INTEGER NOT NULL,   -- plain integer, no FK — practice_onboarding_profiles

    item_name                  TEXT NOT NULL,
    item_type                    TEXT NOT NULL CHECK (item_type IN (
                                     'information', 'document', 'registration', 'secretarial', 'tax', 'practice', 'review', 'custom'
                                 )),

    required                       BOOLEAN NOT NULL DEFAULT true,
    completed                        BOOLEAN NOT NULL DEFAULT false,
    completed_at                       TIMESTAMPTZ,
    completed_by                         INTEGER,

    notes                                   TEXT,
    sort_order                               INTEGER NOT NULL DEFAULT 0,

    created_at                                 TIMESTAMPTZ DEFAULT NOW(),
    updated_at                                   TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_poc_company_id  ON practice_onboarding_checklists (company_id);
CREATE INDEX IF NOT EXISTS idx_poc_profile_id    ON practice_onboarding_checklists (profile_id, sort_order);

CREATE OR REPLACE FUNCTION fn_poc_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS tg_poc_updated_at ON practice_onboarding_checklists;
CREATE TRIGGER tg_poc_updated_at
    BEFORE UPDATE ON practice_onboarding_checklists
    FOR EACH ROW EXECUTE FUNCTION fn_poc_updated_at();

COMMENT ON TABLE practice_onboarding_checklists IS
    'Codebox 70 — Entity-type-specific onboarding checklist (one row per item). Generated from a deterministic per-entity-type template (see ONBOARDING_CHECKLIST_DEFAULTS in client-onboarding.js) or added manually. Manager may regenerate — regeneration only adds missing items, never removes or resets existing ones.';

-- ─────────────────────────────────────────────────────────────────────────────
-- TABLE: practice_onboarding_events  (append-only audit log)
-- Never updated. Never deleted. No status change and no silent
-- initialization without a matching event — enforced at the application
-- layer in client-onboarding.js.
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS practice_onboarding_events (
    id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id          INTEGER NOT NULL,
    client_id             INTEGER,   -- plain integer, no FK — practice_clients (denormalized for fast per-client history queries)

    source_type             TEXT NOT NULL CHECK (source_type IN ('profile', 'step', 'checklist_item')),
    source_id                 INTEGER NOT NULL,   -- plain integer, no FK (Codebox 41 convention)

    event_type                  TEXT NOT NULL CHECK (event_type IN (
                                    'profile_created', 'step_created', 'step_completed', 'checklist_generated',
                                    'status_changed', 'review_completed', 'onboarding_completed'
                                )),
    old_status                    TEXT,
    new_status                      TEXT,

    actor_user_id                      INTEGER,
    notes                                 TEXT,
    metadata                              JSONB NOT NULL DEFAULT '{}',
    created_at                              TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_poe_company_id  ON practice_onboarding_events (company_id);
CREATE INDEX IF NOT EXISTS idx_poe_source       ON practice_onboarding_events (source_type, source_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_poe_client_id    ON practice_onboarding_events (client_id) WHERE client_id IS NOT NULL;

COMMENT ON TABLE practice_onboarding_events IS
    'Codebox 70 — Append-only log of onboarding profile/step/checklist activity, including every module buildOnboardingWorkspace() initializes. Never updated or deleted. No silent initialization — every create-if-missing action writes an event.';
