-- Migration 129: Practice Engagement Scope Control + Work Authorization Gate
-- Codebox 72 — Lorenco Practice Management
--
-- NOT legal advice. NOT automatic engagement drafting. NOT billing
-- automation. NOT hard blocking of normal work. The system WARNS and
-- RECORDS when work appears outside an active engagement's scope — managers
-- and partners decide, always with an audited reason. No silent blocking,
-- ever: every authorization check either resolves clear or produces a
-- record a human can act on.
--
-- AUDIT (RULE A1 — see docs/new-app/72_work_authorization_scope_control.md):
-- confirmed no pre-existing "work authorization"/"scope control" tables.
-- Reuses practice_client_engagements (Codebox 15, enriched by Codebox 71's
-- migration 128: engagement_status, engagement_type, scope_inclusions,
-- scope_exclusions, risk_level) live via engagement-management.js's
-- getClientEngagementProfile() export — never duplicates engagement data.
--
-- Tables created (all IF NOT EXISTS — safe to re-run):
--   practice_work_authorizations
--   practice_work_authorization_events

-- ─────────────────────────────────────────────────────────────────────────────
-- TABLE: practice_work_authorizations
-- One row per (source record, work_type) checked. A duplicate check for the
-- same source+work_type reuses/updates the existing row rather than creating
-- a new one — see the unique guard below.
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS practice_work_authorizations (
    id                      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id               INTEGER NOT NULL,
    client_id                  INTEGER NOT NULL,   -- plain integer, no FK — practice_clients (Codebox 41 convention)

    -- What triggered this check — a task, a workflow-generation attempt, a
    -- manual check from the Work Authorization page, an onboarding readiness
    -- read, etc. Plain text/integer, no FK (Codebox 41 convention).
    source_module                TEXT NOT NULL,
    source_type                    TEXT NOT NULL,
    source_id                        INTEGER,

    work_type                          TEXT NOT NULL CHECK (work_type IN (
                                           'accounting', 'tax', 'payroll', 'secretarial', 'advisory', 'compliance',
                                           'bookkeeping', 'company_secretarial', 'management', 'billing', 'onboarding', 'custom'
                                       )),

    authorization_status                 TEXT NOT NULL DEFAULT 'clear' CHECK (authorization_status IN (
                                             'clear', 'warning', 'out_of_scope', 'override_requested',
                                             'override_approved', 'override_rejected', 'accepted_risk', 'cancelled'
                                         )),

    matched_engagement_id                   INTEGER,   -- plain integer, no FK — practice_client_engagements. Nullable.
    matched_engagement_status                 TEXT,    -- snapshot of engagement_status at check time, for audit — never re-read live after the fact

    scope_result                                TEXT NOT NULL CHECK (scope_result IN (
                                                    'in_scope', 'possible_gap', 'out_of_scope', 'no_active_engagement', 'unknown'
                                                )),
    risk_level                                    TEXT NOT NULL DEFAULT 'low' CHECK (risk_level IN ('low', 'medium', 'high', 'critical')),

    reason                                           TEXT,   -- deterministic, system-generated explanation of the scope_result
    override_reason                                    TEXT,   -- manager/partner-provided reason for overriding
    approved_by                                          INTEGER,
    approved_at                                            TIMESTAMPTZ,
    rejected_by                                              INTEGER,
    rejected_at                                                TIMESTAMPTZ,

    metadata                                                     JSONB NOT NULL DEFAULT '{}',

    created_at                                                     TIMESTAMPTZ DEFAULT NOW(),
    updated_at                                                       TIMESTAMPTZ DEFAULT NOW(),
    created_by                                                         INTEGER,
    updated_by                                                           INTEGER
);

CREATE INDEX IF NOT EXISTS idx_pwa_company_id            ON practice_work_authorizations (company_id);
CREATE INDEX IF NOT EXISTS idx_pwa_client_id              ON practice_work_authorizations (company_id, client_id);
CREATE INDEX IF NOT EXISTS idx_pwa_source_module          ON practice_work_authorizations (company_id, source_module);
CREATE INDEX IF NOT EXISTS idx_pwa_source_type            ON practice_work_authorizations (company_id, source_type);
CREATE INDEX IF NOT EXISTS idx_pwa_source_id              ON practice_work_authorizations (source_id) WHERE source_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_pwa_work_type              ON practice_work_authorizations (company_id, work_type);
CREATE INDEX IF NOT EXISTS idx_pwa_authorization_status   ON practice_work_authorizations (company_id, authorization_status);
CREATE INDEX IF NOT EXISTS idx_pwa_scope_result           ON practice_work_authorizations (company_id, scope_result);

-- Duplicate guard: a live (not cancelled/rejected) authorization already
-- exists for this exact (source, work_type) — re-checking updates it in
-- place rather than creating a second, competing record. Explicitly scoped
-- to exclude terminal-but-not-resolved statuses so a rejected override or a
-- cancelled check can always be re-attempted fresh.
CREATE UNIQUE INDEX IF NOT EXISTS uq_pwa_source_worktype_live
    ON practice_work_authorizations (company_id, source_module, source_type, source_id, work_type)
    WHERE authorization_status NOT IN ('cancelled', 'override_rejected');

CREATE OR REPLACE FUNCTION fn_pwa_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS tg_pwa_updated_at ON practice_work_authorizations;
CREATE TRIGGER tg_pwa_updated_at
    BEFORE UPDATE ON practice_work_authorizations
    FOR EACH ROW EXECUTE FUNCTION fn_pwa_updated_at();

COMMENT ON TABLE practice_work_authorizations IS
    'Codebox 72 — "Are we formally engaged to do this work?" One row per (source, work_type) checked against active engagement scope. Never blocks — authorization_status tracks the human decision (override/accepted risk) when scope_result is not in_scope.';

-- ─────────────────────────────────────────────────────────────────────────────
-- TABLE: practice_work_authorization_events  (append-only audit log)
-- Never updated. Never deleted. No status change without a matching event —
-- enforced at the application layer in work-authorization.js.
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS practice_work_authorization_events (
    id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id          INTEGER NOT NULL,
    authorization_id      INTEGER NOT NULL,   -- plain integer, no FK — practice_work_authorizations (Codebox 41 convention)

    event_type               TEXT NOT NULL CHECK (event_type IN (
                                 'authorization_checked', 'authorization_warning_created', 'override_requested',
                                 'override_approved', 'override_rejected', 'accepted_risk', 'authorization_cancelled'
                             )),
    old_status                  TEXT,
    new_status                    TEXT,

    actor_user_id                    INTEGER,
    notes                               TEXT,
    metadata                             JSONB NOT NULL DEFAULT '{}',
    created_at                             TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_pwae_company_id        ON practice_work_authorization_events (company_id);
CREATE INDEX IF NOT EXISTS idx_pwae_authorization_id   ON practice_work_authorization_events (company_id, authorization_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_pwae_created_at          ON practice_work_authorization_events (created_at DESC);

COMMENT ON TABLE practice_work_authorization_events IS
    'Codebox 72 — Append-only log of every work-authorization check, warning, override request/decision, and risk acceptance. Never updated or deleted.';
