-- Migration 130: Practice Client Profitability + Service Margin Foundation
-- Codebox 73 — Lorenco Practice Management
--
-- NOT accounting. NOT a general ledger. NOT invoicing automation. NOT
-- revenue recognition. Accounting remains the financial source of truth;
-- Billing/WIP (practice_billing_packs) remains the billing workflow source
-- of truth. This module only ANALYZES existing Time/Billing/Engagement data
-- to surface margin, realization, and leakage indicators — it never writes
-- to any of those tables.
--
-- ══════════════════════════════════════════════════════════════════════════
-- MANDATORY PRE-BUILD AUDIT — FULL FINDINGS
-- ══════════════════════════════════════════════════════════════════════════
-- No pre-existing profitability/margin table or router exists anywhere in
-- the codebase — confirmed by a dedicated schema-investigation pass. This is
-- a genuinely new feature area. Key facts that shaped the engine below:
--
--   practice_time_entries (007, extended 061/062) has: hours, billable,
--   rate, time_type, standard_rate, override_rate, effective_rate,
--   recoverable_value, billed_value, writeoff_value, billing_status
--   ('unbilled'|'pending_review'|'approved'|'rejected'|'billed'|'written_off'),
--   writeoff_reason, billing_pack_id, task_id. NO engagement_id column
--   directly — engagement linkage is only via task_id → practice_tasks.
--   engagement_id/service_id (added by migration 066, plain integers, no FK).
--
--   practice_billing_packs (062, extended 063/064) has period_start/end,
--   status ('draft'|'reviewed'|'approved'|'locked'|'cancelled', API-layer
--   only, no DB CHECK), and pack-level aggregate columns recoverable_value/
--   billable_value/writeoff_value (recomputed from practice_billing_pack_lines
--   by billing.js's own recalculatePack() — NEVER re-derived by this module;
--   this module only READS these stored aggregates).
--
--   practice_team_members has NO cost-rate/internal-rate column anywhere in
--   the schema. estimated_cost therefore has no live data source and is
--   ALWAYS 0 with a TEAM_COST_RATE_MISSING warning until such a column is
--   added in a future codebox — see the router's own header for the full
--   consequence of this (margin_percentage is structurally always 100% or
--   null while cost is unavailable; realization_percentage is the one
--   reliable signal in this pass).
--
--   practice_client_engagements has TWO parallel status columns: the
--   original `status` (065, 4 values, drives engagements.js's generate-
--   workflow gate) and `engagement_status` (128, 10 values, Codebox 71's
--   richer model). This module deliberately does NOT filter analysis by
--   either status — historical time/billing data for an ended or paused
--   engagement is still real, already-recorded work worth analyzing, so
--   profitability figures are never gated on "is this engagement currently
--   active." An engagement row is only used to resolve its client_id (a
--   direct, multi-tenant-verified lookup) and to display its own name/type.
--
-- Tables created (all IF NOT EXISTS — safe to re-run):
--   practice_profitability_snapshots
--   practice_profitability_reviews
--   practice_profitability_events

-- ─────────────────────────────────────────────────────────────────────────────
-- TABLE: practice_profitability_snapshots
-- A point-in-time, saved analysis result. calculateProfitability() can be
-- run ad-hoc (GET, no DB write) or saved as a snapshot (POST /snapshots) for
-- historical comparison and partner review — the snapshot is a frozen copy,
-- never recalculated in place.
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS practice_profitability_snapshots (
    id                      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id               INTEGER NOT NULL,
    client_id                  INTEGER,   -- plain integer, no FK — practice_clients (Codebox 41 convention). Nullable — practice-wide snapshots have none.
    engagement_id                 INTEGER,   -- plain integer, no FK — practice_client_engagements. Nullable.
    service_id                       INTEGER,   -- plain integer, no FK — practice_service_catalog. Nullable.

    snapshot_type                       TEXT NOT NULL CHECK (snapshot_type IN ('client', 'engagement', 'service', 'practice', 'manual')),

    period_start                           DATE NOT NULL,
    period_end                               DATE NOT NULL,
    period_key                                 TEXT,   -- e.g. "2026-06" for a monthly snapshot — informational grouping only, never authoritative

    profitability_status                          TEXT NOT NULL DEFAULT 'unknown' CHECK (profitability_status IN (
                                                      'profitable', 'watch', 'low_margin', 'unprofitable', 'unknown'
                                                  )),

    revenue_amount                                    NUMERIC(14, 2) NOT NULL DEFAULT 0,
    recoverable_value                                   NUMERIC(14, 2) NOT NULL DEFAULT 0,
    billed_value                                          NUMERIC(14, 2) NOT NULL DEFAULT 0,
    writeoff_value                                          NUMERIC(14, 2) NOT NULL DEFAULT 0,
    unbilled_value                                            NUMERIC(14, 2) NOT NULL DEFAULT 0,
    estimated_cost                                              NUMERIC(14, 2) NOT NULL DEFAULT 0,
    estimated_margin                                              NUMERIC(14, 2) NOT NULL DEFAULT 0,
    realization_percentage                                          NUMERIC(8, 2),
    margin_percentage                                                 NUMERIC(8, 2),

    hours_recorded                                                       NUMERIC(10, 2) NOT NULL DEFAULT 0,
    billable_hours                                                         NUMERIC(10, 2) NOT NULL DEFAULT 0,
    nonbillable_hours                                                        NUMERIC(10, 2) NOT NULL DEFAULT 0,

    -- Full engine output — source_breakdown, assumptions, and every input
    -- figure — preserved verbatim so a saved snapshot can always be audited
    -- against exactly what it was computed from, even if formulas change later.
    analysis_snapshot                                                          JSONB NOT NULL DEFAULT '{}',
    warnings                                                                     JSONB NOT NULL DEFAULT '[]',
    notes                                                                          TEXT,

    created_at                                                                      TIMESTAMPTZ DEFAULT NOW(),
    created_by                                                                        INTEGER
);

CREATE INDEX IF NOT EXISTS idx_pps_company_id     ON practice_profitability_snapshots (company_id);
CREATE INDEX IF NOT EXISTS idx_pps_client_id       ON practice_profitability_snapshots (client_id) WHERE client_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_pps_engagement_id   ON practice_profitability_snapshots (engagement_id) WHERE engagement_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_pps_service_id      ON practice_profitability_snapshots (service_id) WHERE service_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_pps_snapshot_type   ON practice_profitability_snapshots (company_id, snapshot_type);
CREATE INDEX IF NOT EXISTS idx_pps_period_start     ON practice_profitability_snapshots (company_id, period_start);
CREATE INDEX IF NOT EXISTS idx_pps_period_end        ON practice_profitability_snapshots (company_id, period_end);
CREATE INDEX IF NOT EXISTS idx_pps_period_key         ON practice_profitability_snapshots (company_id, period_key) WHERE period_key IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_pps_created_at          ON practice_profitability_snapshots (created_at DESC);

COMMENT ON TABLE practice_profitability_snapshots IS
    'Codebox 73 — A frozen, point-in-time profitability analysis result. Never recalculated in place — a new snapshot is always a new row, preserving full history for partner review and trend comparison.';

-- ─────────────────────────────────────────────────────────────────────────────
-- TABLE: practice_profitability_reviews
-- The partner decision layer over a snapshot (or a standalone client/
-- engagement concern raised without one).
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS practice_profitability_reviews (
    id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id          INTEGER NOT NULL,
    client_id             INTEGER,   -- plain integer, no FK — practice_clients. Nullable.
    engagement_id            INTEGER,   -- plain integer, no FK — practice_client_engagements. Nullable.
    snapshot_id                 INTEGER,   -- plain integer, no FK — practice_profitability_snapshots. Nullable — a review may be opened before any snapshot is saved.

    review_status                  TEXT NOT NULL DEFAULT 'draft' CHECK (review_status IN (
                                       'draft', 'under_review', 'reviewed', 'action_required', 'accepted', 'archived', 'cancelled'
                                   )),

    review_title                      TEXT NOT NULL,
    review_summary                      TEXT,
    partner_notes                         TEXT,
    recommended_action                       TEXT CHECK (recommended_action IS NULL OR recommended_action IN (
                                                 'no_action', 'reprice', 'rescope', 'improve_process', 'write_off_review',
                                                 'client_discussion', 'terminate_service', 'monitor', 'other'
                                             )),

    assigned_partner_id                          INTEGER,
    reviewed_by                                     INTEGER,
    reviewed_at                                        TIMESTAMPTZ,
    next_review_date                                     DATE,

    created_at                                              TIMESTAMPTZ DEFAULT NOW(),
    updated_at                                                TIMESTAMPTZ DEFAULT NOW(),
    created_by                                                  INTEGER,
    updated_by                                                    INTEGER
);

CREATE INDEX IF NOT EXISTS idx_ppr_company_id         ON practice_profitability_reviews (company_id);
CREATE INDEX IF NOT EXISTS idx_ppr_client_id           ON practice_profitability_reviews (client_id) WHERE client_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_ppr_engagement_id       ON practice_profitability_reviews (engagement_id) WHERE engagement_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_ppr_snapshot_id         ON practice_profitability_reviews (snapshot_id) WHERE snapshot_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_ppr_review_status       ON practice_profitability_reviews (company_id, review_status);
CREATE INDEX IF NOT EXISTS idx_ppr_assigned_partner    ON practice_profitability_reviews (assigned_partner_id) WHERE assigned_partner_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_ppr_next_review_date    ON practice_profitability_reviews (company_id, next_review_date) WHERE next_review_date IS NOT NULL;

CREATE OR REPLACE FUNCTION fn_ppr_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS tg_ppr_updated_at ON practice_profitability_reviews;
CREATE TRIGGER tg_ppr_updated_at
    BEFORE UPDATE ON practice_profitability_reviews
    FOR EACH ROW EXECUTE FUNCTION fn_ppr_updated_at();

COMMENT ON TABLE practice_profitability_reviews IS
    'Codebox 73 — Partner review workflow over a profitability concern. May reference a saved snapshot or stand alone. draft/under_review/reviewed/action_required/accepted/archived/cancelled.';

-- ─────────────────────────────────────────────────────────────────────────────
-- TABLE: practice_profitability_events  (append-only audit log)
-- Never updated. Never deleted. No snapshot creation and no review status
-- change without a matching event — enforced at the application layer in
-- profitability.js.
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS practice_profitability_events (
    id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id          INTEGER NOT NULL,

    source_type             TEXT NOT NULL CHECK (source_type IN ('snapshot', 'review')),
    source_id                 INTEGER NOT NULL,   -- plain integer, no FK (Codebox 41 convention)

    event_type                  TEXT NOT NULL CHECK (event_type IN (
                                    'profitability_snapshot_created', 'profitability_review_created', 'profitability_review_updated',
                                    'profitability_review_submitted', 'profitability_review_completed', 'profitability_review_action_required',
                                    'profitability_review_accepted', 'profitability_review_archived', 'profitability_review_cancelled'
                                )),
    old_status                    TEXT,
    new_status                      TEXT,

    actor_user_id                      INTEGER,
    notes                                 TEXT,
    metadata                               JSONB NOT NULL DEFAULT '{}',
    created_at                               TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_ppe_company_id  ON practice_profitability_events (company_id);
CREATE INDEX IF NOT EXISTS idx_ppe_source       ON practice_profitability_events (source_type, source_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_ppe_created_at    ON practice_profitability_events (created_at DESC);

COMMENT ON TABLE practice_profitability_events IS
    'Codebox 73 — Append-only log of every snapshot creation and review status change. Never updated or deleted.';
