-- Migration 131: Practice Pricing Review + Fee Adjustment Workflow
-- Codebox 74 — Lorenco Practice Management
--
-- NOT invoice modification. NOT accounting. NOT automatic billing update.
-- NOT engagement letter generation. NOT email. This module prepares and
-- GOVERNS pricing decisions only — actual fee/engagement changes happen
-- later, in a future codebox, only after this workflow reaches 'implemented'.
--
-- ══════════════════════════════════════════════════════════════════════════
-- MANDATORY PRE-BUILD AUDIT — FULL FINDINGS
-- ══════════════════════════════════════════════════════════════════════════
-- No pre-existing pricing-review table or router exists anywhere. Confirmed
-- reuse targets (never duplicated):
--
--   practice_client_engagements (065/128) — fee_amount, fee_basis,
--   billing_frequency, engagement_name, engagement_status, client_id,
--   partner_team_member_id, responsible_team_member_id. This migration
--   copies current_fee_basis/current_fee_amount onto the pricing review as
--   a POINT-IN-TIME SNAPSHOT (what the fee was when the review was opened)
--   — never a live foreign key the review "becomes stale" against; the
--   engagement's own live fields remain the single source of truth for
--   "what is the fee right now."
--
--   practice_profitability_reviews / practice_profitability_snapshots (130,
--   Codebox 73) — profitability_review_id links a pricing review to the
--   profitability concern that triggered it. Realization/margin/write-off
--   figures are read live from the linked snapshot at prepare-time, never
--   copied into a new duplicate column set on this table.
--
--   practice_client_success (118, Codebox 61) — read-only for the "commercial
--   review due" Client Success integration; never written to by this module.
--
-- Tables created (all IF NOT EXISTS — safe to re-run):
--   practice_pricing_reviews
--   practice_pricing_review_items
--   practice_pricing_events

-- ─────────────────────────────────────────────────────────────────────────────
-- TABLE: practice_pricing_reviews
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS practice_pricing_reviews (
    id                      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id               INTEGER NOT NULL,
    client_id                  INTEGER NOT NULL,   -- plain integer, no FK — practice_clients (Codebox 41 convention)
    engagement_id                 INTEGER,   -- plain integer, no FK — practice_client_engagements. Nullable — a review may concern the whole client relationship, not one engagement.
    profitability_review_id          INTEGER,   -- plain integer, no FK — practice_profitability_reviews (Codebox 73). Nullable.

    review_title                        TEXT NOT NULL,
    review_reason                          TEXT NOT NULL CHECK (review_reason IN (
                                               'profitability', 'scope_change', 'inflation', 'annual_review', 'client_growth',
                                               'service_growth', 'writeoffs', 'low_realization', 'manual', 'other'
                                           )),

    -- Point-in-time snapshot of the fee at the moment this review was
    -- opened — see migration header. current_fee_basis reuses the exact
    -- CHECK vocabulary already established on practice_client_engagements
    -- (migration 128) for consistency, not because this column is a live FK.
    current_fee_basis                        TEXT CHECK (current_fee_basis IS NULL OR current_fee_basis IN (
                                                 'fixed_monthly', 'fixed_annual', 'hourly', 'per_service', 'once_off',
                                                 'retainer', 'quote_based', 'no_charge', 'other'
                                             )),
    current_fee_amount                          NUMERIC(14, 2),
    proposed_fee_basis                             TEXT CHECK (proposed_fee_basis IS NULL OR proposed_fee_basis IN (
                                                       'fixed_monthly', 'fixed_annual', 'hourly', 'per_service', 'once_off',
                                                       'retainer', 'quote_based', 'no_charge', 'other'
                                                   )),
    proposed_fee_amount                               NUMERIC(14, 2),
    effective_date                                       DATE,

    pricing_status                                          TEXT NOT NULL DEFAULT 'draft' CHECK (pricing_status IN (
                                                                'draft', 'under_review', 'partner_review', 'approved',
                                                                'rejected', 'implemented', 'cancelled'
                                                            )),
    recommended_action                                          TEXT CHECK (recommended_action IS NULL OR recommended_action IN (
                                                                    'increase_fee', 'decrease_fee', 'change_fee_basis', 'change_scope',
                                                                    'split_services', 'merge_services', 'engagement_update', 'monitor', 'no_change'
                                                                )),

    partner_notes                                                  TEXT,
    client_discussion_notes                                          TEXT,
    approval_notes                                                     TEXT,
    internal_notes                                                       TEXT,
    rejection_reason                                                       TEXT,
    cancellation_reason                                                      TEXT,

    assigned_partner_id                                                        INTEGER,
    approved_by                                                                  INTEGER,
    approved_at                                                                    TIMESTAMPTZ,
    implemented_by                                                                   INTEGER,
    implemented_at                                                                     TIMESTAMPTZ,

    created_at                                                                          TIMESTAMPTZ DEFAULT NOW(),
    updated_at                                                                            TIMESTAMPTZ DEFAULT NOW(),
    created_by                                                                              INTEGER,
    updated_by                                                                                INTEGER
);

CREATE INDEX IF NOT EXISTS idx_ppcr_company_id            ON practice_pricing_reviews (company_id);
CREATE INDEX IF NOT EXISTS idx_ppcr_client_id              ON practice_pricing_reviews (company_id, client_id);
CREATE INDEX IF NOT EXISTS idx_ppcr_engagement_id          ON practice_pricing_reviews (engagement_id) WHERE engagement_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_ppcr_profitability_review   ON practice_pricing_reviews (profitability_review_id) WHERE profitability_review_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_ppcr_pricing_status         ON practice_pricing_reviews (company_id, pricing_status);
CREATE INDEX IF NOT EXISTS idx_ppcr_assigned_partner       ON practice_pricing_reviews (assigned_partner_id) WHERE assigned_partner_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_ppcr_effective_date         ON practice_pricing_reviews (company_id, effective_date) WHERE effective_date IS NOT NULL;

CREATE OR REPLACE FUNCTION fn_ppcr_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS tg_ppcr_updated_at ON practice_pricing_reviews;
CREATE TRIGGER tg_ppcr_updated_at
    BEFORE UPDATE ON practice_pricing_reviews
    FOR EACH ROW EXECUTE FUNCTION fn_ppcr_updated_at();

COMMENT ON TABLE practice_pricing_reviews IS
    'Codebox 74 — Pricing/fee-adjustment governance workflow. draft/under_review/partner_review/approved/rejected/implemented/cancelled. "implemented" means the commercial DECISION was accepted — it never itself changes practice_client_engagements. A future codebox may consume implemented reviews to actually update engagement fees.';

-- ─────────────────────────────────────────────────────────────────────────────
-- TABLE: practice_pricing_review_items
-- Supporting evidence attached to a review — never a commercial decision by
-- itself, just a documented fact (a low realization %, a write-off amount,
-- a scope-creep observation, etc.) a partner can weigh.
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS practice_pricing_review_items (
    id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id          INTEGER NOT NULL,
    pricing_review_id      INTEGER NOT NULL,   -- plain integer, no FK — practice_pricing_reviews (Codebox 41 convention)

    item_type                TEXT NOT NULL CHECK (item_type IN (
                                 'low_realization', 'high_writeoffs', 'scope_creep', 'time_increase',
                                 'new_services', 'additional_compliance', 'manual_justification', 'other'
                             )),
    title                       TEXT NOT NULL,
    description                   TEXT,
    supporting_value                NUMERIC(14, 2),   -- e.g. a percentage or amount backing the item — meaning depends on item_type, documented in `description`

    sort_order                         INTEGER NOT NULL DEFAULT 0,

    created_at                            TIMESTAMPTZ DEFAULT NOW(),
    updated_at                              TIMESTAMPTZ DEFAULT NOW(),
    created_by                                INTEGER
);

CREATE INDEX IF NOT EXISTS idx_ppri_company_id       ON practice_pricing_review_items (company_id);
CREATE INDEX IF NOT EXISTS idx_ppri_review_id         ON practice_pricing_review_items (pricing_review_id, sort_order);

CREATE OR REPLACE FUNCTION fn_ppri_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS tg_ppri_updated_at ON practice_pricing_review_items;
CREATE TRIGGER tg_ppri_updated_at
    BEFORE UPDATE ON practice_pricing_review_items
    FOR EACH ROW EXECUTE FUNCTION fn_ppri_updated_at();

COMMENT ON TABLE practice_pricing_review_items IS
    'Codebox 74 — Supporting evidence items attached to a pricing review. Purely documentary — never a fee calculation.';

-- ─────────────────────────────────────────────────────────────────────────────
-- TABLE: practice_pricing_events  (append-only audit log)
-- Never updated. Never deleted. No status change without a matching event —
-- enforced at the application layer in pricing-review.js.
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS practice_pricing_events (
    id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id          INTEGER NOT NULL,
    pricing_review_id     INTEGER NOT NULL,   -- plain integer, no FK — practice_pricing_reviews (Codebox 41 convention)

    event_type               TEXT NOT NULL CHECK (event_type IN (
                                 'review_created', 'review_updated', 'submitted', 'partner_review_started',
                                 'approved', 'rejected', 'implemented', 'cancelled'
                             )),
    old_status                  TEXT,
    new_status                    TEXT,

    actor_user_id                    INTEGER,
    notes                               TEXT,
    metadata                             JSONB NOT NULL DEFAULT '{}',
    created_at                             TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_ppev_company_id  ON practice_pricing_events (company_id);
CREATE INDEX IF NOT EXISTS idx_ppev_review_id    ON practice_pricing_events (company_id, pricing_review_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_ppev_created_at    ON practice_pricing_events (created_at DESC);

COMMENT ON TABLE practice_pricing_events IS
    'Codebox 74 — Append-only log of every pricing review lifecycle event, including every approval and implementation. Never updated or deleted.';
