-- Migration 132: Practice Partner Performance + Practice Scorecards
-- Codebox 75 — Lorenco Practice Management
--
-- NOT HR. NOT payroll performance. NOT employee ranking. NOT disciplinary
-- management. This is executive operational reporting — a management
-- scorecard system that AGGREGATES existing KPIs (Profitability, Quality,
-- Risk, Capacity, Client Success, Engagement Management, Learning, Planning,
-- Notifications). It never recalculates a metric differently than its
-- source module already does.
--
-- ══════════════════════════════════════════════════════════════════════════
-- MANDATORY PRE-BUILD AUDIT — FULL FINDINGS
-- ══════════════════════════════════════════════════════════════════════════
-- No pre-existing scorecard/performance table exists anywhere. Confirmed
-- reuse targets (every one read directly, never recalculated):
--
--   management-dashboard.js — computePracticeScore() already implements a
--   practice-wide deterministic weighted-penalty score (quality/compliance/
--   risk/capacity/tax) via getRules() thresholds. This module reuses the
--   exact same PENALTY FORMULAS (documented per-component below) but scopes
--   them to a specific team member's owned work instead of the whole
--   practice, since computePracticeScore() itself has no per-member scoping.
--
--   kpi-history.js — practice_kpi_snapshots establishes the
--   period_key/snapshot_type/status='active'|'archived' immutable-snapshot
--   pattern this migration mirrors for scorecards.
--
--   alert-rules.js getRules() — risk_high_min/risk_critical_min/
--   capacity_overloaded_ratio thresholds are reused via getRules(), never
--   re-hardcoded, so a threshold change in Alert Rules automatically flows
--   through to scorecards too.
--
--   Ownership columns confirmed by table (all plain integers, no FK —
--   Codebox 41 convention): practice_clients.responsible_team_member_id /
--   .reviewer_team_member_id / .partner_team_member_id (065/128),
--   practice_client_engagements.responsible_team_member_id /
--   .partner_team_member_id (065/128), practice_quality_reviews.
--   assigned_reviewer_team_member_id (048), practice_quality_findings.
--   responsible_team_member_id (048), practice_risks.owner_team_member_id
--   (049), practice_tasks.preparer_team_member_id (007/058),
--   practice_learning_plans.team_member_id (060), practice_notifications.
--   assigned_team_member_id (054).
--
--   capacity.js exports buildTeamCapacity(cid) — reused directly for the
--   capacity component (utilization_percentage/capacity_status per member),
--   never re-derived.
--
--   skills-matrix.js exports getCompetency(cid, teamMemberId) — reused
--   directly for the learning component's competency-gap count.
--
--   planning-board.js exports buildTeamItemPool(cid) — reused directly for
--   the planning component (overdue/critical work items per member).
--
--   No "team"/"department" linkage TABLE exists — practice_team_members has
--   a plain `department` TEXT column (Codebox 15) with no separate teams
--   table. "Team" scorecards therefore group by this existing department
--   string. A `team_key` column (nullable, holds the department value) is
--   added below beyond the spec's literal field list to make this concrete
--   and queryable — documented Architect Freedom addition.
--
-- Tables created (all IF NOT EXISTS — safe to re-run):
--   practice_partner_scorecards
--   practice_partner_scorecard_reviews
--   practice_partner_scorecard_events

-- ─────────────────────────────────────────────────────────────────────────────
-- TABLE: practice_partner_scorecards  (immutable once created — see Codebox 73
-- precedent: a scorecard snapshot's entire value is that it is never altered
-- after the fact. DELETE is disabled entirely at the application layer.)
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS practice_partner_scorecards (
    id                    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id             INTEGER NOT NULL,
    team_member_id            INTEGER,   -- plain integer, no FK — practice_team_members. NULL for 'team'/'practice' scorecards.
    scorecard_type               TEXT NOT NULL CHECK (scorecard_type IN ('partner', 'manager', 'team', 'practice')),
    team_key                        TEXT,   -- Architect Freedom addition — see migration header. Holds practice_team_members.department when scorecard_type = 'team'. NULL otherwise.

    period_start                       DATE NOT NULL,
    period_end                            DATE NOT NULL,
    period_key                               TEXT NOT NULL,   -- e.g. '2026-06' or '2026-Q2' — mirrors kpi-history.js's period_key convention for /trends and /compare.

    overall_score                               NUMERIC(5, 2),   -- NULL only if every component was unavailable (never fabricated).
    profitability_score                            NUMERIC(5, 2),
    quality_score                                     NUMERIC(5, 2),
    capacity_score                                       NUMERIC(5, 2),
    client_score                                            NUMERIC(5, 2),
    risk_score                                                 NUMERIC(5, 2),
    engagement_score                                              NUMERIC(5, 2),
    learning_score                                                   NUMERIC(5, 2),
    planning_score                                                      NUMERIC(5, 2),
    notification_score                                                     NUMERIC(5, 2),

    custom_scores                                                             JSONB NOT NULL DEFAULT '{}',   -- reserved for future component scores without a schema change
    warnings                                                                     JSONB NOT NULL DEFAULT '[]',   -- e.g. NO_OWNED_CLIENTS, TEAM_COST_RATE_MISSING (passed through from Profitability)
    snapshot                                                                        JSONB NOT NULL DEFAULT '{}',   -- full buildScorecard() output: per-component {source, formula, weight, confidence, raw_counts}

    created_at                                                                         TIMESTAMPTZ DEFAULT NOW(),
    created_by                                                                            INTEGER
);

CREATE INDEX IF NOT EXISTS idx_ppsc_company_id     ON practice_partner_scorecards (company_id);
CREATE INDEX IF NOT EXISTS idx_ppsc_team_member     ON practice_partner_scorecards (team_member_id) WHERE team_member_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_ppsc_type_period      ON practice_partner_scorecards (company_id, scorecard_type, period_key);
CREATE INDEX IF NOT EXISTS idx_ppsc_team_key          ON practice_partner_scorecards (team_key) WHERE team_key IS NOT NULL;

COMMENT ON TABLE practice_partner_scorecards IS
    'Codebox 75 — Immutable scorecard snapshots (partner/manager/team/practice). NOT HR, NOT ranking, NOT disciplinary. Aggregates existing KPI sources only — never recalculates a metric differently than its source module. DELETE disabled at the application layer (405), matching Profitability snapshots (Codebox 73).';

-- ─────────────────────────────────────────────────────────────────────────────
-- TABLE: practice_partner_scorecard_reviews
-- The executive review workflow layered on top of an immutable scorecard.
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS practice_partner_scorecard_reviews (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id           INTEGER NOT NULL,
    scorecard_id            INTEGER NOT NULL,   -- plain integer, no FK — practice_partner_scorecards (Codebox 41 convention)

    review_status               TEXT NOT NULL DEFAULT 'draft' CHECK (review_status IN (
                                    'draft', 'under_review', 'reviewed', 'accepted', 'action_required', 'archived', 'cancelled'
                                )),

    review_summary                    TEXT,
    strengths                            TEXT,
    improvement_areas                       TEXT,
    partner_notes                              TEXT,
    action_plan                                   TEXT,

    assigned_partner_id                              INTEGER,   -- plain integer, no FK — practice_team_members
    reviewed_by                                         INTEGER,
    reviewed_at                                            TIMESTAMPTZ,
    next_review_date                                          DATE,

    created_at                                                   TIMESTAMPTZ DEFAULT NOW(),
    updated_at                                                      TIMESTAMPTZ DEFAULT NOW(),
    created_by                                                         INTEGER,
    updated_by                                                            INTEGER
);

CREATE INDEX IF NOT EXISTS idx_ppsr_company_id    ON practice_partner_scorecard_reviews (company_id);
CREATE INDEX IF NOT EXISTS idx_ppsr_scorecard_id   ON practice_partner_scorecard_reviews (scorecard_id);
CREATE INDEX IF NOT EXISTS idx_ppsr_review_status   ON practice_partner_scorecard_reviews (company_id, review_status);
CREATE INDEX IF NOT EXISTS idx_ppsr_assigned_partner  ON practice_partner_scorecard_reviews (assigned_partner_id) WHERE assigned_partner_id IS NOT NULL;

CREATE OR REPLACE FUNCTION fn_ppsr_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS tg_ppsr_updated_at ON practice_partner_scorecard_reviews;
CREATE TRIGGER tg_ppsr_updated_at
    BEFORE UPDATE ON practice_partner_scorecard_reviews
    FOR EACH ROW EXECUTE FUNCTION fn_ppsr_updated_at();

COMMENT ON TABLE practice_partner_scorecard_reviews IS
    'Codebox 75 — Executive review workflow over an immutable scorecard snapshot. draft/under_review/reviewed/accepted/action_required/archived/cancelled.';

-- ─────────────────────────────────────────────────────────────────────────────
-- TABLE: practice_partner_scorecard_events  (append-only audit log)
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS practice_partner_scorecard_events (
    id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id          INTEGER NOT NULL,
    scorecard_id           INTEGER,   -- plain integer, no FK. Nullable so a 'scorecard_created' event and any later review event both fit this one log.
    review_id                 INTEGER,   -- plain integer, no FK — practice_partner_scorecard_reviews. NULL for scorecard-level events.

    event_type                   TEXT NOT NULL CHECK (event_type IN (
                                     'scorecard_created', 'review_created', 'review_updated', 'submitted',
                                     'review_completed', 'accepted', 'action_required', 'archived'
                                 )),
    old_status                      TEXT,
    new_status                         TEXT,

    actor_user_id                         INTEGER,
    notes                                     TEXT,
    metadata                                    JSONB NOT NULL DEFAULT '{}',
    created_at                                     TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_ppse_company_id  ON practice_partner_scorecard_events (company_id);
CREATE INDEX IF NOT EXISTS idx_ppse_scorecard_id ON practice_partner_scorecard_events (scorecard_id) WHERE scorecard_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_ppse_review_id     ON practice_partner_scorecard_events (review_id) WHERE review_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_ppse_created_at      ON practice_partner_scorecard_events (created_at DESC);

COMMENT ON TABLE practice_partner_scorecard_events IS
    'Codebox 75 — Append-only log of every scorecard/review lifecycle event. Never updated or deleted.';
