-- Migration 133: Practice Strategic Planning + Objectives Management
-- Codebox 76 — Lorenco Practice Management
--
-- NOT project management. NOT task management. NOT HR performance. This is
-- strategic practice leadership — annual objectives, quarterly priorities,
-- initiatives, and KPI links that reference (never duplicate) the KPI
-- engines already built in Codeboxes 50/51/61/73/74/75 and the Risk/QMS
-- registers. Tasks/workflows remain the operational execution layer.
--
-- ══════════════════════════════════════════════════════════════════════════
-- MANDATORY PRE-BUILD AUDIT — FULL FINDINGS
-- ══════════════════════════════════════════════════════════════════════════
-- No pre-existing strategic-plan/objective table exists anywhere. Confirmed
-- reuse targets (every one read directly via a small, explicit metric
-- registry in strategic-planning.js — never a duplicate KPI engine):
--
--   kpi-history.js exports METRIC_EXTRACTORS/METRIC_KEYS (Codebox 51) —
--   reused directly against the latest active practice_kpi_snapshots row.
--
--   management-dashboard.js exports computeSummary()/computePracticeScore()
--   (Codebox 50) — a small, explicit dot-path registry maps a handful of
--   known-safe metric_keys to fields on computeSummary()'s own return
--   shape. Only called when a manager explicitly views/refreshes a single
--   objective's KPI links (never in a bulk/company-wide scan).
--
--   capacity.js exports buildTeamCapacity() (Codebox 18/57), planning-board.js
--   exports buildTeamItemPool() (Codebox 56), alert-rules.js exports
--   getRules() (Codebox 53) — all reused directly, same pattern established
--   in partner-scorecards.js (Codebox 75).
--
--   practice_partner_scorecards (132, Codebox 75), practice_profitability_snapshots
--   (130, Codebox 73), practice_client_success (118, Codebox 61),
--   practice_risks (Codebox 49), practice_quality_reviews/findings
--   (Codebox 48) are read directly (cheap, count-only queries) for their
--   respective kpi_source registries — never recalculated differently.
--
-- Tables created (all IF NOT EXISTS — safe to re-run):
--   practice_strategic_plans
--   practice_strategic_objectives
--   practice_strategic_initiatives
--   practice_strategic_kpi_links
--   practice_strategic_reviews
--   practice_strategic_events

-- ─────────────────────────────────────────────────────────────────────────────
-- TABLE: practice_strategic_plans
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS practice_strategic_plans (
    id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id          INTEGER NOT NULL,

    plan_name              TEXT NOT NULL,
    plan_year                 INTEGER NOT NULL,
    period_start                 DATE NOT NULL,
    period_end                      DATE NOT NULL,

    plan_status                        TEXT NOT NULL DEFAULT 'draft' CHECK (plan_status IN (
                                           'draft', 'active', 'under_review', 'completed', 'archived', 'cancelled'
                                       )),

    vision_statement                       TEXT,
    strategic_theme                           TEXT,
    executive_summary                            TEXT,
    partner_notes                                   TEXT,
    cancellation_reason                                TEXT,   -- Architect Freedom addition — required by DELETE (soft-cancel), same "reason required" convention as every other consequential action this session.
    settings                                              JSONB NOT NULL DEFAULT '{}',

    created_at                                               TIMESTAMPTZ DEFAULT NOW(),
    updated_at                                                  TIMESTAMPTZ DEFAULT NOW(),
    created_by                                                     INTEGER,
    updated_by                                                        INTEGER
);

CREATE INDEX IF NOT EXISTS idx_psp_company_id  ON practice_strategic_plans (company_id);
CREATE INDEX IF NOT EXISTS idx_psp_status       ON practice_strategic_plans (company_id, plan_status);
CREATE INDEX IF NOT EXISTS idx_psp_year          ON practice_strategic_plans (company_id, plan_year);

CREATE OR REPLACE FUNCTION fn_psp_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS tg_psp_updated_at ON practice_strategic_plans;
CREATE TRIGGER tg_psp_updated_at
    BEFORE UPDATE ON practice_strategic_plans
    FOR EACH ROW EXECUTE FUNCTION fn_psp_updated_at();

COMMENT ON TABLE practice_strategic_plans IS
    'Codebox 76 — Annual/period strategic plan. draft/active/under_review/completed/archived/cancelled. Objectives, initiatives, and reviews all reference a plan.';

-- ─────────────────────────────────────────────────────────────────────────────
-- TABLE: practice_strategic_objectives
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS practice_strategic_objectives (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id           INTEGER NOT NULL,
    plan_id                 INTEGER NOT NULL,   -- plain integer, no FK — practice_strategic_plans (Codebox 41 convention)

    objective_title            TEXT NOT NULL,
    objective_description         TEXT,

    objective_area                   TEXT NOT NULL CHECK (objective_area IN (
                                         'growth', 'profitability', 'quality', 'client_success', 'capacity',
                                         'team_development', 'risk', 'compliance', 'secretarial', 'tax',
                                         'operational_excellence', 'technology', 'other'
                                     )),

    objective_status                    TEXT NOT NULL DEFAULT 'not_started' CHECK (objective_status IN (
                                            'not_started', 'in_progress', 'on_track', 'at_risk', 'off_track',
                                            'achieved', 'deferred', 'cancelled'
                                        )),
    priority                                TEXT NOT NULL DEFAULT 'medium' CHECK (priority IN ('low', 'medium', 'high', 'critical')),

    owner_team_member_id                       INTEGER,   -- plain integer, no FK — practice_team_members. Nullable.
    target_date                                   DATE,
    progress_percentage                              NUMERIC(5, 2) NOT NULL DEFAULT 0,   -- manual fallback — see strategic-planning.js's progress logic; overridden by computed initiative/KPI progress wherever that data exists (never silently persisted over manual entry).

    success_measure                                     TEXT,
    current_position                                       TEXT,
    target_position                                           TEXT,

    notes                                                        TEXT,
    internal_notes                                                  TEXT,
    settings                                                           JSONB NOT NULL DEFAULT '{}',

    created_at                                                            TIMESTAMPTZ DEFAULT NOW(),
    updated_at                                                               TIMESTAMPTZ DEFAULT NOW(),
    created_by                                                                  INTEGER,
    updated_by                                                                     INTEGER
);

CREATE INDEX IF NOT EXISTS idx_pso_company_id  ON practice_strategic_objectives (company_id);
CREATE INDEX IF NOT EXISTS idx_pso_plan_id      ON practice_strategic_objectives (plan_id);
CREATE INDEX IF NOT EXISTS idx_pso_status        ON practice_strategic_objectives (company_id, objective_status);
CREATE INDEX IF NOT EXISTS idx_pso_owner          ON practice_strategic_objectives (owner_team_member_id) WHERE owner_team_member_id IS NOT NULL;

CREATE OR REPLACE FUNCTION fn_pso_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS tg_pso_updated_at ON practice_strategic_objectives;
CREATE TRIGGER tg_pso_updated_at
    BEFORE UPDATE ON practice_strategic_objectives
    FOR EACH ROW EXECUTE FUNCTION fn_pso_updated_at();

COMMENT ON TABLE practice_strategic_objectives IS
    'Codebox 76 — A strategic objective within a plan. progress_percentage is the manual fallback; strategic-planning.js computes a live progress figure from linked initiatives/KPIs wherever that data exists, returned alongside (never silently overwriting) this stored value.';

-- ─────────────────────────────────────────────────────────────────────────────
-- TABLE: practice_strategic_initiatives
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS practice_strategic_initiatives (
    id                   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id            INTEGER NOT NULL,
    objective_id             INTEGER NOT NULL,   -- plain integer, no FK — practice_strategic_objectives (Codebox 41 convention)

    initiative_title            TEXT NOT NULL,
    initiative_description         TEXT,

    initiative_status                 TEXT NOT NULL DEFAULT 'not_started' CHECK (initiative_status IN (
                                          'not_started', 'in_progress', 'blocked', 'completed', 'deferred', 'cancelled'
                                      )),

    owner_team_member_id                 INTEGER,   -- plain integer, no FK — practice_team_members. Nullable.
    start_date                              DATE,
    due_date                                   DATE,
    completed_at                                  TIMESTAMPTZ,
    progress_percentage                              NUMERIC(5, 2) NOT NULL DEFAULT 0,

    blocker_notes                                       TEXT,
    next_action                                            TEXT,
    notes                                                     TEXT,
    settings                                                    JSONB NOT NULL DEFAULT '{}',

    created_at                                                     TIMESTAMPTZ DEFAULT NOW(),
    updated_at                                                        TIMESTAMPTZ DEFAULT NOW(),
    created_by                                                           INTEGER,
    updated_by                                                              INTEGER
);

CREATE INDEX IF NOT EXISTS idx_psi_company_id  ON practice_strategic_initiatives (company_id);
CREATE INDEX IF NOT EXISTS idx_psi_objective_id ON practice_strategic_initiatives (objective_id);
CREATE INDEX IF NOT EXISTS idx_psi_status        ON practice_strategic_initiatives (company_id, initiative_status);
CREATE INDEX IF NOT EXISTS idx_psi_owner          ON practice_strategic_initiatives (owner_team_member_id) WHERE owner_team_member_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_psi_due_date        ON practice_strategic_initiatives (company_id, due_date) WHERE due_date IS NOT NULL;

CREATE OR REPLACE FUNCTION fn_psi_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS tg_psi_updated_at ON practice_strategic_initiatives;
CREATE TRIGGER tg_psi_updated_at
    BEFORE UPDATE ON practice_strategic_initiatives
    FOR EACH ROW EXECUTE FUNCTION fn_psi_updated_at();

COMMENT ON TABLE practice_strategic_initiatives IS
    'Codebox 76 — A concrete initiative under a strategic objective. Not a task — this is the strategic execution layer; operational tasks/workflows remain in practice_tasks.';

-- ─────────────────────────────────────────────────────────────────────────────
-- TABLE: practice_strategic_kpi_links
-- References to existing KPI sources. Never a duplicate KPI engine.
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS practice_strategic_kpi_links (
    id                    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id             INTEGER NOT NULL,
    objective_id              INTEGER NOT NULL,   -- plain integer, no FK — practice_strategic_objectives (Codebox 41 convention)

    kpi_source                   TEXT NOT NULL CHECK (kpi_source IN (
                                     'management_dashboard', 'kpi_history', 'partner_scorecard', 'profitability',
                                     'client_success', 'risk', 'qms', 'planning', 'capacity', 'tax', 'secretarial', 'custom'
                                 )),
    metric_key                       TEXT NOT NULL,
    metric_label                        TEXT NOT NULL,

    baseline_value                          NUMERIC(14, 2),
    target_value                               NUMERIC(14, 2),
    current_value                                 NUMERIC(14, 2),

    direction                                        TEXT NOT NULL CHECK (direction IN ('increase', 'decrease', 'maintain', 'threshold')),
    weight                                               NUMERIC(8, 2) NOT NULL DEFAULT 1,

    -- Architect Freedom addition — not in the spec's literal field list, but
    -- required by the spec's own "KPI LINK LOGIC" section ("If unsafe: mark
    -- confidence = manual"). 'auto' = last refreshed from a known-safe
    -- source/metric_key registry match; 'manual' = user-entered/unmatched.
    confidence                                              TEXT NOT NULL DEFAULT 'manual' CHECK (confidence IN ('auto', 'manual')),

    last_measured_at                                            TIMESTAMPTZ,
    notes                                                           TEXT,
    settings                                                           JSONB NOT NULL DEFAULT '{}',

    created_at                                                            TIMESTAMPTZ DEFAULT NOW(),
    updated_at                                                               TIMESTAMPTZ DEFAULT NOW(),
    created_by                                                                  INTEGER,
    updated_by                                                                     INTEGER
);

CREATE INDEX IF NOT EXISTS idx_pskl_company_id  ON practice_strategic_kpi_links (company_id);
CREATE INDEX IF NOT EXISTS idx_pskl_objective_id ON practice_strategic_kpi_links (objective_id);
CREATE INDEX IF NOT EXISTS idx_pskl_source        ON practice_strategic_kpi_links (company_id, kpi_source);

CREATE OR REPLACE FUNCTION fn_pskl_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS tg_pskl_updated_at ON practice_strategic_kpi_links;
CREATE TRIGGER tg_pskl_updated_at
    BEFORE UPDATE ON practice_strategic_kpi_links
    FOR EACH ROW EXECUTE FUNCTION fn_pskl_updated_at();

COMMENT ON TABLE practice_strategic_kpi_links IS
    'Codebox 76 — A reference to an existing KPI source/metric. Never a duplicate KPI engine — current_value is either safely auto-refreshed from a known source (confidence=auto) or manually maintained (confidence=manual).';

-- ─────────────────────────────────────────────────────────────────────────────
-- TABLE: practice_strategic_reviews
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS practice_strategic_reviews (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id           INTEGER NOT NULL,
    plan_id                 INTEGER NOT NULL,   -- plain integer, no FK — practice_strategic_plans (Codebox 41 convention)

    review_title                TEXT NOT NULL,
    review_period_start            DATE,
    review_period_end                 DATE,

    review_status                        TEXT NOT NULL DEFAULT 'draft' CHECK (review_status IN (
                                             'draft', 'under_review', 'reviewed', 'action_required', 'completed', 'cancelled'
                                         )),

    overall_progress                         NUMERIC(5, 2),
    review_summary                              TEXT,
    wins                                            TEXT,
    concerns                                          TEXT,
    decisions                                            TEXT,
    action_items                                            TEXT,
    partner_notes                                              TEXT,
    cancellation_reason                                           TEXT,   -- Architect Freedom addition — required by DELETE (soft-cancel).

    reviewed_by                                                      INTEGER,
    reviewed_at                                                         TIMESTAMPTZ,
    next_review_date                                                       DATE,

    created_at                                                                TIMESTAMPTZ DEFAULT NOW(),
    updated_at                                                                   TIMESTAMPTZ DEFAULT NOW(),
    created_by                                                                      INTEGER,
    updated_by                                                                         INTEGER
);

CREATE INDEX IF NOT EXISTS idx_psr_company_id  ON practice_strategic_reviews (company_id);
CREATE INDEX IF NOT EXISTS idx_psr_plan_id      ON practice_strategic_reviews (plan_id);
CREATE INDEX IF NOT EXISTS idx_psr_status        ON practice_strategic_reviews (company_id, review_status);
CREATE INDEX IF NOT EXISTS idx_psr_next_review    ON practice_strategic_reviews (company_id, next_review_date) WHERE next_review_date IS NOT NULL;

CREATE OR REPLACE FUNCTION fn_psr_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS tg_psr_updated_at ON practice_strategic_reviews;
CREATE TRIGGER tg_psr_updated_at
    BEFORE UPDATE ON practice_strategic_reviews
    FOR EACH ROW EXECUTE FUNCTION fn_psr_updated_at();

COMMENT ON TABLE practice_strategic_reviews IS
    'Codebox 76 — Executive review of a strategic plan''s progress over a period. draft/under_review/reviewed/action_required/completed/cancelled.';

-- ─────────────────────────────────────────────────────────────────────────────
-- TABLE: practice_strategic_events  (append-only audit log)
-- One shared log for the whole module — nullable reference columns let a
-- single append-only table cover plan/objective/initiative/kpi_link/review
-- level events without five near-identical tables.
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS practice_strategic_events (
    id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id          INTEGER NOT NULL,

    plan_id                INTEGER,   -- plain integer, no FK. Nullable.
    objective_id              INTEGER,   -- plain integer, no FK. Nullable.
    initiative_id                INTEGER,   -- plain integer, no FK. Nullable.
    kpi_link_id                     INTEGER,   -- plain integer, no FK. Nullable.
    review_id                          INTEGER,   -- plain integer, no FK. Nullable.

    event_type                            TEXT NOT NULL CHECK (event_type IN (
                                              'plan_created', 'plan_updated', 'plan_activated', 'plan_completed', 'plan_archived', 'plan_cancelled',
                                              'objective_created', 'objective_updated', 'objective_status_changed', 'objective_cancelled',
                                              'initiative_created', 'initiative_updated', 'initiative_status_changed', 'initiative_cancelled',
                                              'kpi_link_created', 'kpi_link_updated', 'kpi_link_refreshed', 'kpi_link_cancelled',
                                              'review_created', 'review_updated', 'review_completed', 'review_action_required', 'review_cancelled'
                                          )),
    old_status                               TEXT,
    new_status                                  TEXT,

    actor_user_id                                  INTEGER,
    notes                                              TEXT,
    metadata                                              JSONB NOT NULL DEFAULT '{}',
    created_at                                               TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_pse_company_id  ON practice_strategic_events (company_id);
CREATE INDEX IF NOT EXISTS idx_pse_plan_id      ON practice_strategic_events (plan_id) WHERE plan_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_pse_objective_id  ON practice_strategic_events (objective_id) WHERE objective_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_pse_initiative_id  ON practice_strategic_events (initiative_id) WHERE initiative_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_pse_kpi_link_id      ON practice_strategic_events (kpi_link_id) WHERE kpi_link_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_pse_review_id          ON practice_strategic_events (review_id) WHERE review_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_pse_created_at          ON practice_strategic_events (created_at DESC);

COMMENT ON TABLE practice_strategic_events IS
    'Codebox 76 — Append-only log of every strategic plan/objective/initiative/KPI-link/review lifecycle event. Never updated or deleted. Note: plan_cancelled, objective_cancelled, initiative_cancelled, and kpi_link_cancelled extend the spec''s literal event list to cover this module''s soft-cancel DELETE endpoints — every status change must have a matching event, including cancellation.';

-- Note on event_type list: the spec's literal list of 17 event types did not
-- include plan_cancelled/objective_cancelled/initiative_cancelled/
-- kpi_link_cancelled, but this module's DELETE endpoints soft-cancel rather
-- than hard-delete (matching the reason-required, event-logged convention
-- used everywhere else this session) — those 4 extra event types were added
-- so "no strategic status change without event" (per the spec's own AUDIT
-- section) holds for cancellation too. Documented Architect Freedom addition.
