-- Migration 134: Practice Executive Reporting + Board Pack Foundation
-- Codebox 77 — Lorenco Practice Management
--
-- NOT Business Intelligence. NOT Power BI. NOT AI reporting. NOT financial
-- statement reporting. An executive management reporting layer built from
-- existing Practice data — the place that answers "what decisions do we
-- need to make today?" instead of "where is the information?"
--
-- ══════════════════════════════════════════════════════════════════════════
-- MANDATORY PRE-BUILD AUDIT — FULL FINDINGS
-- ══════════════════════════════════════════════════════════════════════════
-- No pre-existing executive-report/board-pack table exists anywhere.
-- Confirmed reuse targets (every one read directly by
-- executive-reporting.js's buildExecutiveReport() — never a duplicate KPI
-- engine):
--
--   management-dashboard.js exports computeSummary()/computePracticeScore()/
--   computeAlerts()/computePartnerReview()/computeExecutiveFeed() (Codebox
--   50) — this is the backbone of the report snapshot, exactly as
--   partner-review-packs.js (Codebox 52) already established. risk-register.js
--   and quality-management.js (Codeboxes 48/49) export NO compute function at
--   all, so risk/QMS figures are reused via computeSummary().risk/.qms only —
--   never re-queried independently.
--
--   partner-scorecards.js exports buildScorecard() (Codebox 75) — called once
--   with scorecardType='practice' for the board pack's live practice-level
--   score (read-only reuse, per spec's own "Partner Scorecards: Read-only
--   reuse" instruction).
--
--   profitability.js exports calculateProfitability() (Codebox 73) and
--   pricing-review.js exports buildPricingReview() (Codebox 74) — the former
--   is reused directly for a period-scoped practice-wide figure; the latter
--   has no company-wide aggregate signature (it is per-client/per-engagement),
--   so pricing-review figures are reused via computeSummary().pricing_review
--   instead of looping buildPricingReview() per client.
--
--   capacity.js exports buildTeamCapacity() (Codebox 18/57) and
--   planning-board.js exports buildTeamItemPool() (Codebox 56) — both reused
--   directly for the board pack's Capacity and Planning sections (neither
--   appears in computeSummary(), so this is their first reuse in a report
--   context, not a duplication of anything).
--
--   kpi-history.js exports METRIC_EXTRACTORS/METRIC_KEYS/direction/deltaPct
--   (Codebox 51) — reused for the KPI Trends section against the nearest
--   active practice_kpi_snapshots row at/before each period boundary, the
--   exact same pattern partner-review-packs.js already uses. No second KPI
--   diffing engine was written.
--
--   secretarial-calendar.js exports buildStatutoryCalendar() and
--   secretarial-evidence.js exports getEvidenceSummary() (Codeboxes 66/67) —
--   both already folded into computeSummary()'s statutory_compliance/
--   evidence_readiness/secretarial_integrity blocks, reused from there rather
--   than re-invoked a second time in the same report build.
--
--   notifications.js and learning-centre.js export no company-wide summary
--   function (notify() and calculateLearningProgress()/getDevelopmentBadge()
--   are per-notification/per-plan). Their board-pack sections are therefore
--   plain count-only queries against practice_notifications/
--   practice_learning_plans — counts only, never re-deriving either module's
--   internal scoring formulas.
--
-- Tables created (all IF NOT EXISTS — safe to re-run):
--   practice_executive_reports
--   practice_executive_report_sections
--   practice_executive_decisions
--   practice_executive_action_register
--   practice_executive_events

-- ─────────────────────────────────────────────────────────────────────────────
-- TABLE: practice_executive_reports
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS practice_executive_reports (
    id                    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id            INTEGER NOT NULL,

    report_title          TEXT NOT NULL,
    report_type           TEXT NOT NULL CHECK (report_type IN (
                               'monthly', 'quarterly', 'annual', 'board', 'management', 'custom'
                           )),

    period_start          DATE NOT NULL,
    period_end            DATE NOT NULL,
    period_key            TEXT,

    report_status         TEXT NOT NULL DEFAULT 'draft' CHECK (report_status IN (
                               'draft', 'generated', 'under_review', 'approved', 'published', 'archived', 'cancelled'
                           )),

    executive_summary        TEXT,
    practice_health_summary     TEXT,
    key_wins                      TEXT,
    key_concerns                     TEXT,
    key_decisions                       TEXT,
    recommendations                        TEXT,
    cancellation_reason                       TEXT,   -- Architect Freedom addition — required by DELETE (soft-cancel), same "reason required" convention as every other consequential action this session.

    -- The frozen board-pack snapshot — the single source of truth for
    -- report-data/report-html/report-pdf. Never recalculated after
    -- generation; buildExecutiveReport() is called again only via an
    -- explicit regenerate action, which overwrites this column deliberately.
    report_snapshot           JSONB NOT NULL DEFAULT '{}',
    settings                     JSONB NOT NULL DEFAULT '{}',

    generated_by                   INTEGER,   -- plain integer, no FK — users.id
    generated_at                      TIMESTAMPTZ,
    approved_by                          INTEGER,   -- plain integer, no FK — users.id
    approved_at                             TIMESTAMPTZ,
    published_by                               INTEGER,   -- plain integer, no FK — users.id
    published_at                                  TIMESTAMPTZ,

    created_at                                       TIMESTAMPTZ DEFAULT NOW(),
    updated_at                                           TIMESTAMPTZ DEFAULT NOW(),
    created_by                                              INTEGER,
    updated_by                                                 INTEGER
);

CREATE INDEX IF NOT EXISTS idx_per_company_id  ON practice_executive_reports (company_id);
CREATE INDEX IF NOT EXISTS idx_per_status       ON practice_executive_reports (company_id, report_status);
CREATE INDEX IF NOT EXISTS idx_per_type          ON practice_executive_reports (company_id, report_type);
CREATE INDEX IF NOT EXISTS idx_per_period         ON practice_executive_reports (company_id, period_start, period_end);

CREATE OR REPLACE FUNCTION fn_per_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS tg_per_updated_at ON practice_executive_reports;
CREATE TRIGGER tg_per_updated_at
    BEFORE UPDATE ON practice_executive_reports
    FOR EACH ROW EXECUTE FUNCTION fn_per_updated_at();

COMMENT ON TABLE practice_executive_reports IS
    'Codebox 77 — Executive board pack for a reporting period. draft/generated/under_review/approved/published/archived/cancelled. report_snapshot is frozen at generation time and never silently recalculated.';

-- ─────────────────────────────────────────────────────────────────────────────
-- TABLE: practice_executive_report_sections
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS practice_executive_report_sections (
    id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id          INTEGER NOT NULL,
    report_id              INTEGER NOT NULL,   -- plain integer, no FK — practice_executive_reports (Codebox 41 convention)

    section_key                TEXT NOT NULL CHECK (section_key IN (
                                   'executive_summary', 'practice_health', 'strategy', 'kpis', 'partner_scorecards',
                                   'profitability', 'pricing', 'client_success', 'capacity', 'planning', 'risk',
                                   'quality', 'secretarial', 'notifications', 'learning', 'recommendations',
                                   'decisions', 'actions'
                               )),
    section_title                  TEXT NOT NULL,
    section_order                     INTEGER NOT NULL DEFAULT 0,

    section_status                       TEXT NOT NULL DEFAULT 'included' CHECK (section_status IN (
                                             'included', 'hidden', 'manual'
                                         )),

    -- Frozen at generation time for every engine-sourced section
    -- (section_status <> 'manual'); NULL for a manual section a partner adds
    -- freeform. Never recalculated except by a full report regenerate.
    section_snapshot                        JSONB,
    notes                                       TEXT,

    created_at                                     TIMESTAMPTZ DEFAULT NOW(),
    updated_at                                        TIMESTAMPTZ DEFAULT NOW(),
    created_by                                           INTEGER,
    updated_by                                              INTEGER
);

CREATE INDEX IF NOT EXISTS idx_pers_company_id  ON practice_executive_report_sections (company_id);
CREATE INDEX IF NOT EXISTS idx_pers_report_id     ON practice_executive_report_sections (report_id);
CREATE INDEX IF NOT EXISTS idx_pers_order          ON practice_executive_report_sections (report_id, section_order);

-- One row per section per report — generation is idempotent per section_key,
-- never silently duplicating rows on regenerate (upsert on this constraint).
CREATE UNIQUE INDEX IF NOT EXISTS uq_pers_report_section
    ON practice_executive_report_sections (report_id, section_key);

CREATE OR REPLACE FUNCTION fn_pers_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS tg_pers_updated_at ON practice_executive_report_sections;
CREATE TRIGGER tg_pers_updated_at
    BEFORE UPDATE ON practice_executive_report_sections
    FOR EACH ROW EXECUTE FUNCTION fn_pers_updated_at();

COMMENT ON TABLE practice_executive_report_sections IS
    'Codebox 77 — One reusable section within an executive report. included/hidden/manual. section_snapshot is frozen per engine-sourced section; manual sections carry no snapshot and are partner-authored via notes.';

-- ─────────────────────────────────────────────────────────────────────────────
-- TABLE: practice_executive_decisions
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS practice_executive_decisions (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id           INTEGER NOT NULL,
    report_id               INTEGER NOT NULL,   -- plain integer, no FK — practice_executive_reports (Codebox 41 convention)

    decision_title              TEXT NOT NULL,
    decision_description            TEXT,

    decision_category                  TEXT NOT NULL CHECK (decision_category IN (
                                           'strategy', 'pricing', 'risk', 'quality', 'capacity', 'people',
                                           'technology', 'client', 'secretarial', 'other'
                                       )),
    decision_status                        TEXT NOT NULL DEFAULT 'proposed' CHECK (decision_status IN (
                                               'proposed', 'approved', 'deferred', 'rejected', 'implemented', 'cancelled'
                                           )),

    owner_team_member_id                       INTEGER,   -- plain integer, no FK — practice_team_members. Nullable.
    due_date                                       DATE,
    completed_at                                      TIMESTAMPTZ,

    notes                                                 TEXT,
    cancellation_reason                                      TEXT,   -- Architect Freedom addition — required by DELETE (soft-cancel).

    created_at                                                  TIMESTAMPTZ DEFAULT NOW(),
    updated_at                                                      TIMESTAMPTZ DEFAULT NOW(),
    created_by                                                         INTEGER,
    updated_by                                                            INTEGER
);

CREATE INDEX IF NOT EXISTS idx_ped_company_id  ON practice_executive_decisions (company_id);
CREATE INDEX IF NOT EXISTS idx_ped_report_id     ON practice_executive_decisions (report_id);
CREATE INDEX IF NOT EXISTS idx_ped_status         ON practice_executive_decisions (company_id, decision_status);
CREATE INDEX IF NOT EXISTS idx_ped_category         ON practice_executive_decisions (company_id, decision_category);
CREATE INDEX IF NOT EXISTS idx_ped_owner              ON practice_executive_decisions (owner_team_member_id) WHERE owner_team_member_id IS NOT NULL;

CREATE OR REPLACE FUNCTION fn_ped_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS tg_ped_updated_at ON practice_executive_decisions;
CREATE TRIGGER tg_ped_updated_at
    BEFORE UPDATE ON practice_executive_decisions
    FOR EACH ROW EXECUTE FUNCTION fn_ped_updated_at();

COMMENT ON TABLE practice_executive_decisions IS
    'Codebox 77 — A board/executive decision attached to a report forever. This is an executive decision register only — it does NOT create practice_tasks or workflow items. proposed/approved/deferred/rejected/implemented/cancelled.';

-- ─────────────────────────────────────────────────────────────────────────────
-- TABLE: practice_executive_action_register
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS practice_executive_action_register (
    id                   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id            INTEGER NOT NULL,
    report_id                INTEGER NOT NULL,   -- plain integer, no FK — practice_executive_reports (Codebox 41 convention)
    decision_id                  INTEGER,            -- plain integer, no FK — practice_executive_decisions. Nullable — an action need not trace to a specific decision.

    action_title                     TEXT NOT NULL,
    action_description                  TEXT,

    owner_team_member_id                    INTEGER,   -- plain integer, no FK — practice_team_members. Nullable.
    priority                                    TEXT NOT NULL DEFAULT 'medium' CHECK (priority IN ('low', 'medium', 'high', 'critical')),
    status                                          TEXT NOT NULL DEFAULT 'open' CHECK (status IN (
                                                        'open', 'in_progress', 'waiting', 'completed', 'cancelled'
                                                    )),

    due_date                                             DATE,
    completed_at                                            TIMESTAMPTZ,

    notes                                                       TEXT,
    cancellation_reason                                            TEXT,   -- Architect Freedom addition — required by DELETE (soft-cancel).

    created_at                                                        TIMESTAMPTZ DEFAULT NOW(),
    updated_at                                                            TIMESTAMPTZ DEFAULT NOW(),
    created_by                                                               INTEGER,
    updated_by                                                                  INTEGER
);

CREATE INDEX IF NOT EXISTS idx_pear_company_id  ON practice_executive_action_register (company_id);
CREATE INDEX IF NOT EXISTS idx_pear_report_id     ON practice_executive_action_register (report_id);
CREATE INDEX IF NOT EXISTS idx_pear_decision_id     ON practice_executive_action_register (decision_id) WHERE decision_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_pear_status            ON practice_executive_action_register (company_id, status);
CREATE INDEX IF NOT EXISTS idx_pear_owner                ON practice_executive_action_register (owner_team_member_id) WHERE owner_team_member_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_pear_due_date               ON practice_executive_action_register (company_id, due_date) WHERE due_date IS NOT NULL;

CREATE OR REPLACE FUNCTION fn_pear_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS tg_pear_updated_at ON practice_executive_action_register;
CREATE TRIGGER tg_pear_updated_at
    BEFORE UPDATE ON practice_executive_action_register
    FOR EACH ROW EXECUTE FUNCTION fn_pear_updated_at();

COMMENT ON TABLE practice_executive_action_register IS
    'Codebox 77 — Lightweight management follow-up item, optionally linked to a decision. Does NOT replace Task Management (practice_tasks) — a future integration may reference these, this module never creates a practice_task from one.';

-- ─────────────────────────────────────────────────────────────────────────────
-- TABLE: practice_executive_events  (append-only audit log)
-- One shared log for the whole module — nullable reference columns let a
-- single append-only table cover report/decision/action level events
-- without three near-identical tables (same convention as Codebox 76's
-- practice_strategic_events).
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS practice_executive_events (
    id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id          INTEGER NOT NULL,

    report_id              INTEGER,   -- plain integer, no FK. Nullable.
    decision_id               INTEGER,   -- plain integer, no FK. Nullable.
    action_id                    INTEGER,   -- plain integer, no FK. Nullable.

    event_type                       TEXT NOT NULL CHECK (event_type IN (
                                         'report_created', 'report_generated', 'report_updated', 'report_reviewed',
                                         'report_approved', 'report_published', 'report_archived', 'report_cancelled',
                                         'decision_created', 'decision_updated', 'decision_completed', 'decision_cancelled',
                                         'action_created', 'action_updated', 'action_completed', 'action_cancelled'
                                     )),
    old_status                          TEXT,
    new_status                             TEXT,

    actor_user_id                             INTEGER,
    notes                                         TEXT,
    metadata                                        JSONB NOT NULL DEFAULT '{}',
    created_at                                         TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_pee_company_id  ON practice_executive_events (company_id);
CREATE INDEX IF NOT EXISTS idx_pee_report_id     ON practice_executive_events (report_id) WHERE report_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_pee_decision_id     ON practice_executive_events (decision_id) WHERE decision_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_pee_action_id          ON practice_executive_events (action_id) WHERE action_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_pee_created_at            ON practice_executive_events (created_at DESC);

COMMENT ON TABLE practice_executive_events IS
    'Codebox 77 — Append-only log of every executive report/decision/action lifecycle event. Never updated or deleted. Note: report_cancelled/decision_cancelled/action_cancelled and decision_updated/action_updated extend the spec''s literal 12-event list to cover this module''s soft-cancel DELETE endpoints and plain field edits — every status change must have a matching event, including cancellation and edits, same convention as Codebox 76.';
