-- Migration 135: Practice Automation Foundation + Workflow Orchestration
-- Codebox 78 — Lorenco Practice Management
--
-- NOT AI. NOT autonomous decision making. NOT cron-heavy background
-- processing. NOT workflow replacement. NOT task engine replacement. NOT
-- external integration automation. A deterministic, manager-controlled,
-- fully auditable internal automation layer — manual test-run and run-now
-- only in this codebox; automatic module-to-module triggering is NOT wired
-- yet (see automation.js header for the explicit scope line).
--
-- ══════════════════════════════════════════════════════════════════════════
-- MANDATORY PRE-BUILD AUDIT — FULL FINDINGS
-- ══════════════════════════════════════════════════════════════════════════
-- No pre-existing automation-rule/run table exists anywhere. Confirmed reuse
-- targets — every one called by automation.js's action engine, never
-- reimplemented:
--
--   notifications.js exports notify() (Codebox 54) — the ONLY path the
--   create_notification action uses to write a row into
--   practice_notifications. Automation never inserts into that table
--   directly, so notify()'s own dedup/assignment-resolution logic is never
--   duplicated.
--
--   reminders.js has no exported creation function, but its own POST /
--   route's insert shape (practice_reminders: reminder_type, source_type,
--   source_id, assigned_team_member_id, title, message, severity, due_date,
--   metadata) is safe and stable — reused directly by the create_reminder
--   action via the identical column set, never a new reminder-scoring or
--   dedup concept.
--
--   executive-reporting.js (Codebox 77) owns practice_executive_action_register
--   — report_id is NOT NULL on that table by Codebox 77's own design, so the
--   create_executive_action action REQUIRES a resolvable report_id in the
--   trigger context and fails safely (a clear error, no fallback guess) when
--   one isn't available. No practice_task is ever created by this module.
--
--   practice_secretarial_workflows (change cases, Codebox 63),
--   practice_secretarial_integrity_findings (Codebox 69),
--   practice_onboarding_profiles (Codebox 70), practice_risks (Codebox 49),
--   practice_quality_findings (Codebox 48), practice_pricing_reviews
--   (Codebox 74) are ALL read-only trigger-context sources for manual
--   test/run calls in this codebox — none of their own write paths, status
--   machines, or scoring are touched or duplicated. This codebox does not
--   modify any of those modules to auto-fire triggers; see automation.js's
--   own header for why that wiring is explicitly out of scope here.
--
--   lib/team-access.js (this session's canonical helper) gates every
--   mutating route — no new authorization logic was written.
--
-- Tables created (all IF NOT EXISTS — safe to re-run):
--   practice_automation_rules
--   practice_automation_runs
--   practice_automation_run_steps
--   practice_automation_events

-- ─────────────────────────────────────────────────────────────────────────────
-- TABLE: practice_automation_rules
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS practice_automation_rules (
    id                    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id            INTEGER NOT NULL,

    rule_name             TEXT NOT NULL,
    rule_key              TEXT NOT NULL,

    rule_status           TEXT NOT NULL DEFAULT 'draft' CHECK (rule_status IN (
                               'draft', 'active', 'paused', 'disabled', 'archived', 'cancelled'
                           )),

    trigger_type          TEXT NOT NULL CHECK (trigger_type IN (
                               'manual', 'notification_created', 'task_completed', 'workflow_completed',
                               'pricing_review_approved', 'engagement_renewal_due', 'executive_report_published',
                               'executive_action_created', 'strategic_review_completed',
                               'secretarial_change_implemented', 'secretarial_integrity_critical',
                               'onboarding_completed', 'risk_created', 'qms_finding_created', 'custom'
                           )),

    rule_category         TEXT NOT NULL CHECK (rule_category IN (
                               'notifications', 'reminders', 'executive', 'strategy', 'pricing', 'engagement',
                               'secretarial', 'qms', 'risk', 'onboarding', 'planning', 'custom'
                           )),

    description           TEXT,

    -- Deterministic condition/action definitions — see automation.js's
    -- condition/action engines. Never dynamic code, never eval, never
    -- arbitrary JavaScript.
    conditions            JSONB NOT NULL DEFAULT '[]',
    actions               JSONB NOT NULL DEFAULT '[]',

    safety_level          TEXT NOT NULL DEFAULT 'low' CHECK (safety_level IN ('low', 'medium', 'high', 'critical')),
    requires_approval     BOOLEAN NOT NULL DEFAULT FALSE,
    approved_by           INTEGER,
    approved_at           TIMESTAMPTZ,
    approval_notes        TEXT,

    last_run_at           TIMESTAMPTZ,
    next_review_date      DATE,

    -- Optional custom idempotency template (e.g.
    -- "{company_id}:{rule_id}:{trigger_type}:{source_type}:{source_id}") —
    -- when null, the engine's default template (identical shape) is used.
    idempotency_key_template TEXT,

    cancellation_reason   TEXT,   -- Architect Freedom addition — required by DELETE (soft-cancel), same "reason required" convention as every other consequential action this session.
    settings              JSONB NOT NULL DEFAULT '{}',

    created_at            TIMESTAMPTZ DEFAULT NOW(),
    updated_at            TIMESTAMPTZ DEFAULT NOW(),
    created_by            INTEGER,
    updated_by            INTEGER
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_par_company_rule_key ON practice_automation_rules (company_id, rule_key);
CREATE INDEX IF NOT EXISTS idx_par_company_id ON practice_automation_rules (company_id);
CREATE INDEX IF NOT EXISTS idx_par_status ON practice_automation_rules (company_id, rule_status);
CREATE INDEX IF NOT EXISTS idx_par_trigger ON practice_automation_rules (company_id, trigger_type);
CREATE INDEX IF NOT EXISTS idx_par_category ON practice_automation_rules (company_id, rule_category);

CREATE OR REPLACE FUNCTION fn_par_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS tg_par_updated_at ON practice_automation_rules;
CREATE TRIGGER tg_par_updated_at
    BEFORE UPDATE ON practice_automation_rules
    FOR EACH ROW EXECUTE FUNCTION fn_par_updated_at();

COMMENT ON TABLE practice_automation_rules IS
    'Codebox 78 — A deterministic automation rule: trigger + conditions + actions. draft/active/paused/disabled/archived/cancelled. high/critical safety_level rules require approval before activation.';

-- ─────────────────────────────────────────────────────────────────────────────
-- TABLE: practice_automation_runs
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS practice_automation_runs (
    id                   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id           INTEGER NOT NULL,
    rule_id              INTEGER,   -- plain integer, no FK — practice_automation_rules (Codebox 41 convention). Nullable only in principle; every route always supplies one.

    run_status           TEXT NOT NULL DEFAULT 'running' CHECK (run_status IN (
                              'dry_run', 'running', 'completed', 'completed_with_warnings', 'failed', 'cancelled', 'skipped'
                          )),

    trigger_type         TEXT NOT NULL,
    trigger_source_type  TEXT,
    trigger_source_id    INTEGER,

    dry_run              BOOLEAN NOT NULL DEFAULT TRUE,

    started_at           TIMESTAMPTZ DEFAULT NOW(),
    completed_at          TIMESTAMPTZ,

    result_summary        TEXT,
    warnings              JSONB NOT NULL DEFAULT '[]',
    errors                 JSONB NOT NULL DEFAULT '[]',
    input_snapshot          JSONB NOT NULL DEFAULT '{}',
    output_snapshot          JSONB NOT NULL DEFAULT '{}',

    -- Null for every dry_run (dry-runs never consume idempotency, per spec).
    idempotency_key           TEXT,

    created_by                   INTEGER,
    created_at                      TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_pauto_run_company_id ON practice_automation_runs (company_id);
CREATE INDEX IF NOT EXISTS idx_pauto_run_rule_id ON practice_automation_runs (rule_id) WHERE rule_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_pauto_run_status ON practice_automation_runs (company_id, run_status);
CREATE INDEX IF NOT EXISTS idx_pauto_run_trigger ON practice_automation_runs (company_id, trigger_type);
CREATE INDEX IF NOT EXISTS idx_pauto_run_created_at ON practice_automation_runs (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_pauto_run_idempotency ON practice_automation_runs (company_id, idempotency_key) WHERE idempotency_key IS NOT NULL;

COMMENT ON TABLE practice_automation_runs IS
    'Codebox 78 — One execution record per test-run or run-now, dry or live. idempotency_key is null for every dry-run; a completed live run''s key blocks a duplicate live execution for the same trigger occurrence.';

-- ─────────────────────────────────────────────────────────────────────────────
-- TABLE: practice_automation_run_steps
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS practice_automation_run_steps (
    id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id         INTEGER NOT NULL,
    run_id             INTEGER NOT NULL,   -- plain integer, no FK — practice_automation_runs (Codebox 41 convention)

    step_order         INTEGER NOT NULL DEFAULT 0,
    step_type          TEXT NOT NULL CHECK (step_type IN (
                           'condition', 'action', 'safety_check', 'idempotency_check', 'output'
                       )),

    step_name          TEXT NOT NULL,
    step_status        TEXT NOT NULL DEFAULT 'pending' CHECK (step_status IN (
                           'pending', 'passed', 'skipped', 'completed', 'failed', 'warning'
                       )),

    input              JSONB NOT NULL DEFAULT '{}',
    output             JSONB NOT NULL DEFAULT '{}',
    error_message      TEXT,
    created_at         TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_pars_company_id ON practice_automation_run_steps (company_id);
CREATE INDEX IF NOT EXISTS idx_pars_run_id ON practice_automation_run_steps (run_id);
CREATE INDEX IF NOT EXISTS idx_pars_order ON practice_automation_run_steps (run_id, step_order);

COMMENT ON TABLE practice_automation_run_steps IS
    'Codebox 78 — One row per condition/action/safety-check/idempotency-check/output step within a run. Every action step traces to exactly one row here — "no action without run step" per the spec''s own audit requirement.';

-- ─────────────────────────────────────────────────────────────────────────────
-- TABLE: practice_automation_events  (append-only audit log)
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS practice_automation_events (
    id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id         INTEGER NOT NULL,

    rule_id            INTEGER,   -- plain integer, no FK. Nullable.
    run_id             INTEGER,   -- plain integer, no FK. Nullable.

    event_type         TEXT NOT NULL CHECK (event_type IN (
                           'rule_created', 'rule_updated', 'rule_activated', 'rule_paused', 'rule_disabled',
                           'rule_approved', 'rule_archived', 'rule_cancelled',
                           'run_started', 'run_completed', 'run_failed', 'run_cancelled', 'dry_run_completed',
                           'action_executed', 'action_skipped'
                       )),
    old_status         TEXT,
    new_status         TEXT,

    actor_user_id      INTEGER,
    notes              TEXT,
    metadata           JSONB NOT NULL DEFAULT '{}',
    created_at         TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_pae_company_id ON practice_automation_events (company_id);
CREATE INDEX IF NOT EXISTS idx_pae_rule_id ON practice_automation_events (rule_id) WHERE rule_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_pae_run_id ON practice_automation_events (run_id) WHERE run_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_pae_created_at ON practice_automation_events (created_at DESC);

COMMENT ON TABLE practice_automation_events IS
    'Codebox 78 — Append-only log of every rule lifecycle change and every run''s lifecycle. Never updated or deleted. Note: rule_cancelled extends the spec''s literal event list to cover this module''s soft-cancel DELETE endpoint, same convention as Codeboxes 76/77.';
