-- Migration 136: Practice Operational Health Centre + System Readiness Monitor
-- Codebox 79 — Lorenco Practice Management
--
-- NOT AI. NOT a new business module. A read-only monitor that audits every
-- other Practice module for module health, configuration validity,
-- migration readiness, automation health, role-link integrity, stale data,
-- and broken cross-module references — then produces a deterministic
-- production-readiness score and a pilot-readiness checklist. Manager-
-- controlled, run-on-demand only (no cron).
--
-- ══════════════════════════════════════════════════════════════════════════
-- MANDATORY PRE-BUILD AUDIT — FULL FINDINGS
-- ══════════════════════════════════════════════════════════════════════════
-- No pre-existing health-check/readiness table exists anywhere. This module
-- reads dozens of existing tables directly (deliberately — that IS its job,
-- unlike every prior codebox which reused compute FUNCTIONS) but never
-- re-derives another module's own business logic/scoring:
--
--   alert-rules.js exports getRules() (Codebox 53) — reused directly for the
--   configuration-health check (confirms the central rules engine resolves
--   without throwing for this company; never re-implements rule resolution).
--
--   secretarial.js exports getOrInitProfile() (Codebox 62) — reused directly
--   for the "practice profile exists" configuration check.
--
--   lib/team-access.js's getMyTeamMember() self-heal logic (this session's
--   root-cause fix) is the DIRECT origin of the role-link-integrity check
--   below — this migration/module formalizes permanent, visible monitoring
--   for the exact class of bug (practice_team_members.user_id left NULL)
--   that caused the 2026-07-05 Planning Board access incident. The health
--   check is READ-ONLY (it reports counts and candidate matches); it never
--   writes a fix itself — self-healing still only happens the moment the
--   affected person next logs in and hits any manager-gated route, exactly
--   as lib/team-access.js already does.
--
--   practice_kpi_snapshots (Codebox 51), practice_automation_rules/runs
--   (Codebox 78), practice_executive_reports (Codebox 77), practice_reminders,
--   practice_notifications (Codebox 54) are read directly for staleness/
--   integration checks that no existing module currently tracks — this is
--   the first place these thresholds are centralized, not a duplicate of
--   anything.
--
--   Migration-readiness is checked by probing actual live table existence
--   via the application's own Supabase client at request time (never a
--   filesystem/migration-file count) — the audit surfaced that this app's
--   migrations are split across two directories (accounting-ecosystem/
--   database/migrations/ for early ecosystem-wide + foundational practice
--   tables 054-056, and accounting-ecosystem/backend/config/migrations/ for
--   every Codebox from 46 [057] onward) with independently-numbered,
--   overlapping filenames. A file-count check would be misleading; a live
--   table-existence probe is accurate regardless of which directory created
--   the table. Documented as a follow-up note, not fixed here (out of scope
--   — reorganizing migration directories is a separate, much riskier task).
--
-- Tables created (all IF NOT EXISTS — safe to re-run):
--   practice_health_check_runs
--   practice_health_check_events

-- ─────────────────────────────────────────────────────────────────────────────
-- TABLE: practice_health_check_runs
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS practice_health_check_runs (
    id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id         INTEGER NOT NULL,

    run_status         TEXT NOT NULL DEFAULT 'running' CHECK (run_status IN ('running', 'completed', 'failed')),
    overall_status     TEXT CHECK (overall_status IN ('healthy', 'warning', 'critical')),
    overall_score      NUMERIC(5, 2),

    -- Per-category score/status breakdown (modules, configuration,
    -- migrations, automation, role_links, stale_data, integrations) — see
    -- operational-health.js's computeOperationalHealth() for the exact
    -- deterministic weighting formula, documented there (not duplicated here).
    category_results   JSONB NOT NULL DEFAULT '{}',

    -- Flat list of individual findings: [{ category, severity, code, message, detail }]
    findings           JSONB NOT NULL DEFAULT '[]',

    -- Fixed pilot-readiness checklist result: [{ key, label, passed, detail }]
    checklist          JSONB NOT NULL DEFAULT '[]',

    started_at         TIMESTAMPTZ DEFAULT NOW(),
    completed_at       TIMESTAMPTZ,

    created_by         INTEGER,
    created_at         TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_phcr_company_id ON practice_health_check_runs (company_id);
CREATE INDEX IF NOT EXISTS idx_phcr_status ON practice_health_check_runs (company_id, run_status);
CREATE INDEX IF NOT EXISTS idx_phcr_created_at ON practice_health_check_runs (created_at DESC);

COMMENT ON TABLE practice_health_check_runs IS
    'Codebox 79 — One snapshot per health-check run (manager-initiated, never scheduled). category_results/findings/checklist are frozen at run time; re-run to refresh.';

-- ─────────────────────────────────────────────────────────────────────────────
-- TABLE: practice_health_check_events  (append-only audit log)
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS practice_health_check_events (
    id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id         INTEGER NOT NULL,
    run_id             INTEGER,   -- plain integer, no FK — practice_health_check_runs. Nullable.

    event_type         TEXT NOT NULL CHECK (event_type IN (
                           'health_check_started', 'health_check_completed', 'health_check_failed'
                       )),

    actor_user_id      INTEGER,
    notes              TEXT,
    metadata           JSONB NOT NULL DEFAULT '{}',
    created_at         TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_phce_company_id ON practice_health_check_events (company_id);
CREATE INDEX IF NOT EXISTS idx_phce_run_id ON practice_health_check_events (run_id) WHERE run_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_phce_created_at ON practice_health_check_events (created_at DESC);

COMMENT ON TABLE practice_health_check_events IS
    'Codebox 79 — Append-only log of every health-check run''s lifecycle. Never updated or deleted.';
