-- Migration 137: Practice Pilot Launch Readiness + Navigation/UX Consolidation
-- Codebox 80 — Lorenco Practice Management
--
-- NOT a new business module. A consolidation and launch-readiness layer —
-- the final codebox (±80 total) before pilot testing begins. Reduces every
-- prior codebox's own health/quality signal into one Go/No-Go decision,
-- plus a manager-editable launch checklist and known-issues register.
--
-- ══════════════════════════════════════════════════════════════════════════
-- MANDATORY PRE-BUILD AUDIT — FULL FINDINGS
-- ══════════════════════════════════════════════════════════════════════════
-- No pre-existing readiness/checklist/known-issue table exists anywhere.
-- Confirmed reuse targets — computePilotReadiness() reads these directly,
-- never re-derives their scoring:
--
--   operational-health.js exports computeOperationalHealth() (Codebox 79) —
--   this module does NOT call it fresh. Per the spec's own instruction
--   ("Use: Operational Health latest run... Do not invent health data"),
--   pilot-readiness.js reads the latest STORED practice_health_check_runs
--   row only. If none exists, readiness_status is forced to at least
--   'needs_attention' and a warning code OPERATIONAL_HEALTH_NOT_RUN is
--   raised — exactly as specified, never a fabricated score.
--
--   practice_automation_runs (Codebox 78) is read directly (same
--   count-only pattern management-dashboard.js and operational-health.js
--   both already use) for recent failed-run counts — never re-derives
--   automation.js's own run-status logic.
--
--   lib/team-access.js's role concept is reused, not reimplemented: this
--   migration adds no new role/permission table, and the one new frontend-
--   facing endpoint this codebox adds (GET /api/practice/team/me) calls
--   teamAccess.getMyTeamMember()/isManager() directly — it exists only so
--   the frontend can safely INFER whether to show manager-level nav
--   groups; the backend remains the sole authorization boundary
--   unchanged (every existing manager-gated route is untouched).
--
--   Navigation consolidation (layout.js) is a pure frontend/JS change —
--   no new table backs it; navigation_summary on a readiness run is a
--   static, honest description of the shipped grouped-nav structure
--   (group count, page count), not a runtime health probe, since
--   navigation structure is code, not queryable data.
--
-- Tables created (all IF NOT EXISTS — safe to re-run):
--   practice_pilot_readiness_runs
--   practice_pilot_checklist_items
--   practice_pilot_known_issues
--   practice_pilot_events

-- ─────────────────────────────────────────────────────────────────────────────
-- TABLE: practice_pilot_readiness_runs
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS practice_pilot_readiness_runs (
    id                        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id                INTEGER NOT NULL,

    run_name                  TEXT NOT NULL,
    run_type                  TEXT NOT NULL CHECK (run_type IN (
                                  'internal_test', 'pilot_test', 'pre_launch', 'go_no_go', 'post_fix_review'
                              )),

    readiness_status          TEXT NOT NULL DEFAULT 'not_ready' CHECK (readiness_status IN (
                                  'not_ready', 'needs_attention', 'pilot_ready', 'launch_ready', 'blocked'
                              )),

    overall_score             NUMERIC(5, 2),
    critical_blockers         INTEGER NOT NULL DEFAULT 0,
    high_issues               INTEGER NOT NULL DEFAULT 0,
    medium_issues             INTEGER NOT NULL DEFAULT 0,
    low_issues                INTEGER NOT NULL DEFAULT 0,

    operational_health_run_id INTEGER,   -- plain integer, no FK — practice_health_check_runs (Codebox 41 convention). Nullable — a run may find none exists yet.

    module_matrix             JSONB NOT NULL DEFAULT '{}',
    smoke_test_summary        JSONB NOT NULL DEFAULT '{}',
    navigation_summary        JSONB NOT NULL DEFAULT '{}',
    known_issue_summary       JSONB NOT NULL DEFAULT '{}',
    readiness_snapshot        JSONB NOT NULL DEFAULT '{}',

    decision                  TEXT NOT NULL DEFAULT 'no_decision' CHECK (decision IN ('no_decision', 'go', 'no_go', 'conditional_go')),
    decision_notes            TEXT,
    decided_by                INTEGER,
    decided_at                TIMESTAMPTZ,

    created_at                TIMESTAMPTZ DEFAULT NOW(),
    created_by                INTEGER
);

CREATE INDEX IF NOT EXISTS idx_pprr_company_id ON practice_pilot_readiness_runs (company_id);
CREATE INDEX IF NOT EXISTS idx_pprr_status ON practice_pilot_readiness_runs (company_id, readiness_status);
CREATE INDEX IF NOT EXISTS idx_pprr_created_at ON practice_pilot_readiness_runs (created_at DESC);

COMMENT ON TABLE practice_pilot_readiness_runs IS
    'Codebox 80 — One snapshot per readiness run. Reads the latest Operational Health run + automation/role-link/known-issue/checklist state at run time; never invents health data.';

-- ─────────────────────────────────────────────────────────────────────────────
-- TABLE: practice_pilot_checklist_items
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS practice_pilot_checklist_items (
    id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id         INTEGER NOT NULL,

    check_category     TEXT NOT NULL CHECK (check_category IN (
                           'navigation', 'access_control', 'core_operations', 'clients', 'planning',
                           'secretarial', 'tax', 'engagement', 'reporting', 'automation', 'health',
                           'data', 'security', 'documentation', 'pilot_admin', 'custom'
                       )),

    check_title        TEXT NOT NULL,
    check_description  TEXT,

    check_status       TEXT NOT NULL DEFAULT 'not_started' CHECK (check_status IN (
                           'not_started', 'passed', 'failed', 'warning', 'not_applicable', 'deferred'
                       )),
    severity           TEXT NOT NULL DEFAULT 'medium' CHECK (severity IN ('critical', 'high', 'medium', 'low', 'info')),

    linked_module      TEXT,
    linked_url         TEXT,
    owner_team_member_id INTEGER,   -- plain integer, no FK — practice_team_members. Nullable.
    due_date           DATE,

    evidence_notes     TEXT,
    resolution_notes   TEXT,
    sort_order         INTEGER NOT NULL DEFAULT 0,
    is_default         BOOLEAN NOT NULL DEFAULT FALSE,

    created_at         TIMESTAMPTZ DEFAULT NOW(),
    updated_at         TIMESTAMPTZ DEFAULT NOW(),
    created_by         INTEGER,
    updated_by         INTEGER
);

CREATE INDEX IF NOT EXISTS idx_ppci_company_id ON practice_pilot_checklist_items (company_id);
CREATE INDEX IF NOT EXISTS idx_ppci_status ON practice_pilot_checklist_items (company_id, check_status);
CREATE INDEX IF NOT EXISTS idx_ppci_category ON practice_pilot_checklist_items (company_id, check_category);
CREATE INDEX IF NOT EXISTS idx_ppci_sort ON practice_pilot_checklist_items (company_id, sort_order);

CREATE OR REPLACE FUNCTION fn_ppci_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS tg_ppci_updated_at ON practice_pilot_checklist_items;
CREATE TRIGGER tg_ppci_updated_at
    BEFORE UPDATE ON practice_pilot_checklist_items
    FOR EACH ROW EXECUTE FUNCTION fn_ppci_updated_at();

COMMENT ON TABLE practice_pilot_checklist_items IS
    'Codebox 80 — Manager-editable launch checklist, seeded with 15 default smoke-test items covering login/access/core pages/reporting/automation/health/navigation. is_default marks seeded rows so re-seeding never duplicates them.';

-- ─────────────────────────────────────────────────────────────────────────────
-- TABLE: practice_pilot_known_issues
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS practice_pilot_known_issues (
    id                     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id             INTEGER NOT NULL,

    issue_title            TEXT NOT NULL,
    issue_description      TEXT,
    issue_category         TEXT NOT NULL CHECK (issue_category IN (
                               'bug', 'ux', 'performance', 'data', 'security', 'access',
                               'navigation', 'integration', 'documentation', 'other'
                           )),

    severity               TEXT NOT NULL DEFAULT 'medium' CHECK (severity IN ('critical', 'high', 'medium', 'low')),
    issue_status           TEXT NOT NULL DEFAULT 'open' CHECK (issue_status IN (
                               'open', 'in_progress', 'resolved', 'accepted_risk', 'deferred', 'cancelled'
                           )),

    affected_module        TEXT,
    affected_url           TEXT,
    reproduction_steps     TEXT,
    expected_result        TEXT,
    actual_result           TEXT,
    workaround             TEXT,
    resolution_notes       TEXT,

    reported_by            INTEGER,
    assigned_team_member_id INTEGER,   -- plain integer, no FK — practice_team_members. Nullable.
    resolved_by            INTEGER,
    resolved_at            TIMESTAMPTZ,

    created_at             TIMESTAMPTZ DEFAULT NOW(),
    updated_at             TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_ppki_company_id ON practice_pilot_known_issues (company_id);
CREATE INDEX IF NOT EXISTS idx_ppki_status ON practice_pilot_known_issues (company_id, issue_status);
CREATE INDEX IF NOT EXISTS idx_ppki_severity ON practice_pilot_known_issues (company_id, severity);
CREATE INDEX IF NOT EXISTS idx_ppki_category ON practice_pilot_known_issues (company_id, issue_category);

CREATE OR REPLACE FUNCTION fn_ppki_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS tg_ppki_updated_at ON practice_pilot_known_issues;
CREATE TRIGGER tg_ppki_updated_at
    BEFORE UPDATE ON practice_pilot_known_issues
    FOR EACH ROW EXECUTE FUNCTION fn_ppki_updated_at();

COMMENT ON TABLE practice_pilot_known_issues IS
    'Codebox 80 — Known-issues register for pilot launch. A critical severity issue in the security/access category forces readiness_status to blocked regardless of overall score.';

-- ─────────────────────────────────────────────────────────────────────────────
-- TABLE: practice_pilot_events  (append-only audit log)
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS practice_pilot_events (
    id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id         INTEGER NOT NULL,

    readiness_run_id   INTEGER,   -- plain integer, no FK. Nullable.
    checklist_item_id  INTEGER,   -- plain integer, no FK. Nullable.
    known_issue_id     INTEGER,   -- plain integer, no FK. Nullable.

    event_type         TEXT NOT NULL CHECK (event_type IN (
                           'readiness_run_created', 'readiness_run_completed', 'checklist_seeded',
                           'checklist_item_updated', 'known_issue_created', 'known_issue_updated',
                           'known_issue_resolved', 'go_decision_recorded', 'navigation_refactor_completed',
                           'smoke_test_recorded'
                       )),
    old_status         TEXT,
    new_status         TEXT,

    actor_user_id      INTEGER,
    notes              TEXT,
    metadata           JSONB NOT NULL DEFAULT '{}',
    created_at         TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_ppe_company_id ON practice_pilot_events (company_id);
CREATE INDEX IF NOT EXISTS idx_ppe_run_id ON practice_pilot_events (readiness_run_id) WHERE readiness_run_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_ppe_checklist_id ON practice_pilot_events (checklist_item_id) WHERE checklist_item_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_ppe_issue_id ON practice_pilot_events (known_issue_id) WHERE known_issue_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_ppe_created_at ON practice_pilot_events (created_at DESC);

COMMENT ON TABLE practice_pilot_events IS
    'Codebox 80 — Append-only log of every readiness run, checklist change, known-issue change, and Go/No-Go decision. Never updated or deleted.';
