-- =============================================================================
-- Migration 153: Create the Sales Order tables (Stockton — Codebox 09)
-- =============================================================================
-- Run in Supabase SQL Editor.
--
-- Problem: the Stockton breadth audit (2026-08-27) found that
-- routes/sales-orders.js and services/salesOrderService.js (572 lines of
-- complete, coherent lifecycle logic — draft → confirmed → allocated →
-- partially_fulfilled → fulfilled, with reservation and stock-movement
-- integration) reference sales_orders / sales_order_lines /
-- sales_order_status_history — none of which exist in the database at all
-- (confirmed live via PGRST205 "table not found"). The feature's
-- application code was fully built but its tables were never created —
-- every endpoint has always thrown. User confirmed (2026-08-27): build the
-- tables now to match the already-written code, rather than leave the
-- feature dormant.
--
-- Schema below is reverse-engineered directly from every field the service
-- code actually reads/writes — not a fresh design. line_total on
-- sales_order_lines is a generated column (quantity_ordered * unit_price):
-- the existing createSalesOrder() code computes a line total in memory but
-- never persists it, yet getSalesOrder()'s select expects a line_total
-- column — making it GENERATED fixes that latent gap for free, with no
-- code change needed.
-- =============================================================================

CREATE TABLE IF NOT EXISTS sales_orders (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id        INTEGER NOT NULL,
  so_number         TEXT NOT NULL,
  customer_name     TEXT NOT NULL,
  customer_email    TEXT,
  customer_phone    TEXT,
  customer_ref      TEXT,
  required_date     DATE,
  delivery_address  TEXT,
  currency_code     TEXT NOT NULL DEFAULT 'ZAR',
  notes             TEXT,
  so_status         TEXT NOT NULL DEFAULT 'draft',
  total_amount      NUMERIC(14,4) NOT NULL DEFAULT 0,
  created_by        INTEGER,
  confirmed_by      INTEGER,
  cancelled_by      INTEGER,
  cancelled_at      TIMESTAMPTZ,
  fulfilled_at      TIMESTAMPTZ,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_sales_orders_company_id ON sales_orders(company_id);
CREATE INDEX IF NOT EXISTS idx_sales_orders_so_status ON sales_orders(so_status);

CREATE TABLE IF NOT EXISTS sales_order_lines (
  id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id          INTEGER NOT NULL,
  so_id               BIGINT NOT NULL REFERENCES sales_orders(id),
  item_id             INTEGER REFERENCES inventory_items(id),
  line_number         INTEGER,
  quantity_ordered    NUMERIC(14,4) NOT NULL DEFAULT 0,
  quantity_allocated  NUMERIC(14,4) NOT NULL DEFAULT 0,
  quantity_fulfilled  NUMERIC(14,4) NOT NULL DEFAULT 0,
  unit_price          NUMERIC(14,4) NOT NULL DEFAULT 0,
  line_total          NUMERIC(14,4) GENERATED ALWAYS AS (quantity_ordered * unit_price) STORED,
  required_date       DATE,
  notes               TEXT,
  reservation_id      BIGINT REFERENCES stock_reservations(id),
  created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_sales_order_lines_so_id ON sales_order_lines(so_id);
CREATE INDEX IF NOT EXISTS idx_sales_order_lines_item_id ON sales_order_lines(item_id);
CREATE INDEX IF NOT EXISTS idx_sales_order_lines_company_id ON sales_order_lines(company_id);

CREATE TABLE IF NOT EXISTS sales_order_status_history (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id    INTEGER NOT NULL,
  so_id         BIGINT NOT NULL REFERENCES sales_orders(id),
  from_status   TEXT,
  to_status     TEXT NOT NULL,
  changed_by    INTEGER,
  notes         TEXT,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_sales_order_status_history_so_id ON sales_order_status_history(so_id);

-- ─── Verification ─────────────────────────────────────────────────────────────
SELECT table_name, column_name, data_type
FROM information_schema.columns
WHERE table_name IN ('sales_orders', 'sales_order_lines', 'sales_order_status_history')
ORDER BY table_name, ordinal_position;
